### ISSUE TITLE
Make it easy to get the OperationMetadata from Operation

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#1001]
__Use case:__
When using the `operations` api, getting the metadata about what operation is being reported on (e.g. is this a Chunk move outut jo) from the client is cumbersome.

The way it is accomplished as of the time of writing is a function such as [this](https://github.com/influxdata/influxdb_iox/blob/3fe1b8c5b73338c225ef9fba827f4df807612dd8/tests/end_to_end_cases/operations_api.rs#L6) (not part of the influxdb_iox_client crate):

```
fn get_operation_metadata(metadata: Option<Any>) -> OperationMetadata {
    assert!(metadata.is_some());
    let metadata = metadata.unwrap();
    assert!(protobuf_type_url_eq(&metadata.type_url, OPERATION_METADATA));
    prost::Message::decode(metadata.value).expect("failed to decode metadata")
}
```

__Proposal:__
Add some way that is part of the `influxdb_iox_client` crate to extract the `OperationMetadata` from the return value of the `operations::client::Client` functions

__Desired behaviour:__
Describe what you want.

__Alternatives considered:__
Maybe return a wrapper over the generated `Operation` type that has an accessor

```rust
struct Operation {
  inner: influxdb_iox_client::operations::generated_types::Operation
}

impl Operation { 
...
  pub fn metadata(&self) -> OperationMetadata {
    //  do the prost dance here
  }
```

**Comment by alamb** [comment]
@tustvold  FYI

**Comment by alamb** [comment]
Something else that would be helpful is getting the operation id back in the same form the client wants it in

Namely avoiding stuff like this
```
    let operation_id = operation.name.parse().expect("not an integer");
```

(b/c the client gives you back an `Option` which has a `name` but then the IOx client wants an `usize` id)

**Comment by NGA-TRAN** [comment]
Start working on this
