### ISSUE TITLE
Ensure partially loaded read buffer chunks are not visible to queries

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#1006]
As described on https://github.com/influxdata/influxdb_iox/pull/1002#issuecomment-801013840

The implementation of `move-chunk` in #1002 has the same issue as identified by @e-dard and @NGA-TRAN -- namely that as a chunk is being loaded from mutable buffer to read buffer it will become "queryable" in the read buffer prior to it being fully loaded.

__Steps to reproduce:__
close a chunk with the CLI command from #1002

__Expected behaviour:__
The read buffer chunk will only appear in queries after it has been completely loaded

__Actual behaviour:__
as soon as the first row group is loaded, the read buffer chunk will be used instead of the mutable buffer chunk

**Comment by tustvold** [comment]
The simplest solution for this would be to swap the query precedence to use the mutable buffer chunk in preference to the read buffer chunk if one exists. There may be a better way though
