### ISSUE TITLE
Cloud Authentication

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#1009]
We intend to support object storage in AWS, GCP and Azure. Each of these have different ways of providing the necessary credentials to the application, we should support the most common.

They generally follow a theme:

* Static credentials - the simplest form, but generally discouraged for all the normal reasons static credentials are discouraged
* Metadata Credentials - credentials obtained by talking to a special metadata API. This is typically problematic in multi-tenanted environments, such as kubernetes, as these credentials are instance level not pod (workload) level. Some environments mask the metadata API using something like [kube2iam](https://github.com/jtblin/kube2iam) but such solutions are not ideal
* Federated Auth - provide federated authentication mapping Kubernetes Service Accounts to some cloud provider concept. This is the best solution when it is available, but not everyone does this

## Rusoto (AWS)

* Static IAM credentials - provided as environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`
* [Credentials obtained from the metadata API](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html)
* [Service Account Linked Roles](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) - the recommended way to provide IAM access within EKS (AWS' managed kubernetes offering)

This will involve creating a custom rusoto chain provider that tries each of these in turn, falling back on the next one on failure. 

NB: Unlike the default rusoto chain provider this should **not** just swallow errors. It should also include the [WebIdentityProvider](https://docs.rs/rusoto_sts/0.46.0/rusoto_sts/struct.WebIdentityProvider.html#method.from_k8s_env) for the Service Account Linked Roles functionality.

## Cloud Storage (GCP)

* [Static Google Service Account Credentials](https://cloud.google.com/docs/authentication/production) - these are typically provided as a JSON file with the path provided as an environment variable
* [Instance Service Account Credentials](https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances) - credentials provided by querying a metadata endpoint
* [Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) - federated authentication from Kubernetes Service Account to Google Service Account

I am not entirely sure what, if any of this is already supported, but we should make sure we support all 3.

## Azure Blob Storage

_What is below is tentative - I have no prior experience with Azure_

* [Static Credentials](https://docs.microsoft.com/en-us/rest/api/storageservices/authorize-with-shared-key)
* [Instance Metadata](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token)

I'm not sure that Azure has a federated authentication story for kubernetes, at least I can't find anything. I've asked the SRE team

**Comment by primeroz** [comment]
We do not really support static credentials on any platform so we should really only look in kubernetes identity in all providers

> I'm not sure that Azure has a federated authentication story for kubernetes, at least I can't find anything. I've asked the SRE team

AKS supports it through `pod identity` in `standard mode` https://docs.microsoft.com/en-us/azure/aks/use-azure-ad-pod-identity

we already use it on `IDPE` and other workloads , it generally requires some cloud configuration ( like all other providers ) and the creation of 2 resources 

* aadpodidentity 
* aadpodbinding
in the namespace of the workload and some labeling of the workload itself
