### ISSUE TITLE
Logs and Tracing

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#1012]
IOx and a number of libraries it depends on make use of [tokio-tracing](https://docs.rs/tracing/0.1.25/tracing/). This allows adding instrumentation of spans and events within the application.

A single global Subscriber can be registered which determines at runtime which instrumentation sites should be enabled, and is notified when they occur.

Having a single-global subscriber is limiting, and the trait is non-trivial to implement, so [tracing-subscriber](https://docs.rs/tracing-subscriber/0.2.17/tracing_subscriber/) provides a way to compose multiple Layers together into a single subscriber. 

We use this to add the following layers:

* An [OpenTelemetry layer](https://docs.rs/tracing-opentelemetry/0.11.0/tracing_opentelemetry/struct.OpenTelemetryLayer.html) that sinks to Jaeger
* An [EnvFilter](https://docs.rs/tracing-subscriber/0.2.17/tracing_subscriber/filter/struct.EnvFilter.html) that enables/disables log sites based on the RUST_LOG environment variable
* A [fmt::Layer](https://docs.rs/tracing-subscriber/0.2.17/tracing_subscriber/fmt/struct.Layer.html) that prints tracing events, along with their parent spans, to stdout

Unfortunately the filtering performed by `EnvFilter` is global to the entire stack of Layers, and this presents an issue as we don't want to log to stdout all the same things we send to jaeger. This is a recognized [issue](https://github.com/tokio-rs/tracing/issues/302) but there doesn't appear to be an official solution to this yet. Progress towards an official solution appears to have [stalled](https://github.com/tokio-rs/tracing/pull/508).

In the short-term we will likely need to create a custom Layer that composes the OpenTelemetry layer, and EnvFilter+fmt::Layer such that the superset of relevant callsites are enabled, but that each only sees the relevant subset of events/spans. When a better solution exists upstream we can switch to that

Note: The terminology used here is pre-0.2 tokio tracing, 0.2 renames a number of these [concepts](https://github.com/tokio-rs/tracing/pull/1015), but has [yet to be released](https://github.com/tokio-rs/tracing/issues/922)

FYI: @jacobmarble

**Comment by alamb** [comment]
@tustvold  also found  https://github.com/tokio-rs/tracing/issues/597#issuecomment-765863450 which hints at a possible way to accomplish this goal

**Comment by tustvold** [comment]
I couldn't get it to work...

**Comment by jacobmarble** [comment]
I think I understand [the per-layer filtering issue](https://github.com/tokio-rs/tracing/issues/302). I haven't seen severity labels or severity filtering in tracing before. Seems like we should use them to be idiomatic, but my preference for deployment will be to not filter by severity, whether they fix the issue or not.

**Comment by alamb** [comment]
FYI @tustvold and @jacobmarble -- check out the example from @kehlert  in https://github.com/tokio-rs/tracing/issues/597#issuecomment-814507031

**Comment by jacobmarble** [comment]
Having worked for a couple of weeks on this issue, I now understand this issue a lot better. In particular:
> Unfortunately the filtering performed by EnvFilter is global to the entire stack of Layers, and this presents an issue as we don't want to log to stdout all the same things we send to jaeger.

Multiple issues have been raised, some already mentioned here. Here's one list:
- [subscriber: Per-layer filtering ](https://github.com/tokio-rs/tracing/issues/302)
- [How can I have multiple fmt writers with different level? ](https://github.com/tokio-rs/tracing/issues/597)
- [Subscriber/layer tree](https://github.com/tokio-rs/tracing/issues/1348)
- [Multiple ownership of tracing_subscriber::Registry not possible](https://github.com/tokio-rs/tracing/issues/1356)
