### ISSUE TITLE
IOx system tables for system visibility

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#1013]
> "you wouldn't drive blindfolded (wouldn't you right?)"

@mkmik 

# Background:
As we roll out IOx to our internal systems and put it under increasing load, we need a way to observe its state so we can monitor how the rollout is going, and observe if IOx is performing as designed. 

As we implement features such as automatic chunk movement and multi-node clusters, we also need the ability to observe what is happening in our IOx cluster.

See the additional rationale and usecases on https://github.com/influxdata/influxdb_iox/issues/946 

# Goal +  Non goals
This project's goals are:
* A way to query the basic state of an IOx server (chunks, partitions, tables, etc) via SQL
* create  the infrastructure to add access to additional information easily in the future
* Ensure that access to the same data is  available via the management API and stays in sync

The project will not:
* A full featured visibility story, or SQL information_schema support (see below)
* Any way to *change* the system state via SQL (e.g. nothing like `ALTER PARTITION MOVE OUT`)

# Proposed User Visible Behavior:

## New system tables

We will add several new iox specific "IOx system tables" and the mechanics to create and populate them

```
iox_databases
iox_partitions
iox_tables
iox_chunks
iox_system_tables; # list of system tables
```

Here is an example of querying from `iox_chunks` (Note this is  schemas as the management API):
```
SELECT * from iox_chunks;
+----------+---------------------+----+-------------------+----------------+
| database | partition_key       | id | storage           | estimated_bytes|
+----------+---------------------+----+-------------------+----------------+
| my_db    | 2021-03-01 12:00:00 | 0  | OpenMutableBuffer | 1023           |
| my_db    | 2021-03-01 12:00:00 | 1  | ReadBuffer        | 3423           |
| my_db    | 2021-03-01 13:00:00 | 0  | OpenMutableBuffer | 1023           |
+----------+---------------------+----+-------------------+----------------+
```

## Cross Database / Server Wide Information

All queries in IOx are scoped to a particular database, but some system tables (such as `iox_datbases`) would contain information that is server wide. To allow access to server wide information,  we will introduce a special `sys` database.

It will *not* be possible to load data into the `sys` database (writes will be rejected). However, queries to system tables in `sys` will show information for all databases. For example, in the `sys` database we can see

```
SELECT * from iox_chunks;
+----------+---------------------+----+-------------------+----------------+
| database | partition_key       | id | storage           | estimated_bytes|
+----------+---------------------+----+-------------------+----------------+
| my_db    | 2021-03-01 12:00:00 | 0  | OpenMutableBuffer | 1023           |
| my_db    | 2021-03-01 12:00:00 | 1  | ReadBuffer        | 3423           |
| my_db    | 2021-03-01 13:00:00 | 0  | OpenMutableBuffer | 1023           |
| other_db | 2021-03-03 13:00:00 | 1  | OpenMutableBuffer | 4322           |
| other_db | 2021-03-01 13:00:00 | 0  | Parquet           | 7777           |
+----------+---------------------+----+-------------------+----------------+
```

We will control access to the `sys` database using the same coarse grained permissions (aka are you a super user or not?) that we plan to limit access to the management API.

## No `information_schema` support

We will not add SQL `information_schema` support at this time. If/when we want to add information_schema support, I suggest this belongs in the DataFusion layer (based on the existing `TableProvider` interface).

# Frequently Asked Questions

## Why not use "metrics" (ala Open Telemetry)
A: Both standard open-telemetry style metrics as well as system tables will likely be required

Metrics capture mostly numerical information at a point in time (# queries, etc). With appropriate summarization, they can  provide insight into certain parts of the state of the  database (e.g. "how many chunks does this database have now").

However with metrics, it is harder in to provide non numerical information such as what are the types of the columns in this database. Calculating things such as "how much memory is consumed by a particular tables in this database" might require such fine grained metrics to be exposed that it becomes prohibitive.

System tables allow the state to be visualized at the point in time a query is issued, and they can be combined / filtered / aggregated using SQL.

## Why not SQL `information_schema`?

The ISO SQL standard has an "information_schema" schema ([some details here](https://docs.microsoft.com/en-us/sql/relational-databases/system-information-schema-views/system-information-schema-views-transact-sql?view=sql-server-ver15
)] that defines a standard set of views that ca be used to list tables / columns in a database.

For example, if IOx supported `information_schema`, you could list all the tables in IOx using a query such as the following:

```
SELECT * from information_schema.TABLES
+---------------+--------------+------------+------------+
| table_catalog | table_schema | table_name | table_type |
+---------------+--------------+------------+------------+
| my_db         |              | cpu        | BASE TABLE |
| my_db         |              | memory     | BASE TABLE |
| other_db      |              | usage      | BASE TABLE |
+---------------+--------------+------------+------------+
```

Note that `information_schema` only has standard SQL object types (tables, views, etc). It does not have any way to access database specific things like "chunks"

## Why the names `sys` and the `iox_` prefix?

Other mainstream databases have the system table concept, for the reasons described in this document.
* Postgres (calls them "system catalogs") uses the `pg_` prefix on such tables
* SQL Server uses the `sys` prefix on such tables
* Oracle doesn't use a name prefix, but instead puts them all in a schema called `'sys'`

Thus the `iox_` prefix was picked to mirror `pg_` and the `sys` name was picked to be similar to oracle's sys prefix.

## Will the schema of the system tables change over time, in a compatible way?
Initially, IOx will offer no backwards compatibility guarantees of the schema until the system has stabilized and we have some users. At some point, we will likely start managing changes to these schemas more carefully (only adding new columns, but not removing or changing types, for example) but not initially. 

We plan to have tests in place (e.g. `select * from iox_chunks` ) that would need to be updated if someone changed the struct.

# Implementation Thoughts
We will implement the `iox_*` tables as "virtual" tables on top of the same Rust stucts in `data_types`

This means that we will serialize those structs to `RecordBatch`es via a custom `serde` dataformat implementation, and then feed those `RecordBatch`es to DataFusion.

Since we will use the same structs for management API / CLI as well as the virtual tables as we add new fields to a the management API objects / CLI response the same column will appear in the virtual tables as well.

Note: 
And in the future if we wanted to “freeze” the schema of the system tables while changing the data_types implementation, we can always introduced a new set of structs at that time to back the system tables.

**Comment by mkmik** [comment]
Should we reserve the `iox_` prefix for database names, so that in future we can add more such tables?

**Comment by alamb** [comment]
> Will we strictly reserve the iox_ prefix (i.e. forbid users from creating them)?

Yes I think that would be a good idea

**Comment by e-dard** [comment]
I don't have much to add beyond saying that this seems like pretty reasonable thing to do. It would be good to see all of this information available in a more consumable format for other services (e.g., JSON), so that might be worth thinking about during implementation.

**Comment by alamb** [comment]
>  more consumable format for other services (e.g., JSON), so that might be worth thinking about during implementation.

@e-dard  since IOx already has the ability to format SQL results as JSON (or CSV) by exposing this information as tables we get those format support "for free"

**Comment by tustvold** [comment]
How would this handle nested types? Would it flatten them somehow?

**Comment by alamb** [comment]
> How would this handle nested types? Would it flatten them somehow?

@tustvold  Yes. In general this approach won't handle arbitrary rust data types -- it will only handle things that have an obvious flattened mapping to a row of data

**Comment by NGA-TRAN** [comment]
I am debating between iox_ prefix or not. iox_ prefix will help explicitly tell users that they are querying a system table and we do not need to reserve keywords like databases, tables, partitions, chunks, ... However, as always, long names are not what everyone wants  and that our specific components/design names such as partitions, chunks, ... should be reserved as keywords.

**Comment by mkmik** [comment]
The problem with reserved keywords is that you never know what components/concepts we'll have in the future. Reserving a prefix (or some other pattern) is a common way to be forward compatible

**Comment by alamb** [comment]
So there is now a PR out (thanks @returnString 👋 ) that adds the schema namespaces to DataFusion -  https://github.com/apache/arrow/pull/9762. Using that feature, we could actually make system tables in their own schema

for example:
```
select * from system.iox_chunks;
```

or 
```
select * from iox_system.chunks
```

@mkmik  or @NGA-TRAN  -- any thoughts?

**Comment by mkmik** [comment]
that sounds much better! I guess we shouldn't prefix `iox` on every table, so if we have to put `iox` somewhere let's put it in the schema name

**Comment by NGA-TRAN** [comment]
Agree with Marko. I like system.chunks. If we happen to change iox name, we do not have to worry about it here

**Comment by alamb** [comment]
@tustvold  -- Here is my proprotype `serde` based serializer that can make `RecordBatch`es
[virtual_tables.zip](https://github.com/influxdata/influxdb_iox/files/6204972/virtual_tables.zip)

**Comment by alamb** [comment]
@tustvold  has very nicely offered to take this over for me
