### ISSUE TITLE
Add a catalog to manage chunk lifecycle in a coherent way

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#1016]
# Background:
As we start implementing Chunk movement between different storage types in (mutable buffer, read buffer, etc) tracking the state of the Chunk becomes important, as described in the [mini spec](https://docs.google.com/document/d/1uxpDk29UelqNzD2u-cDNn-CtkSxBvnjdsobCwGIonBs/edit?pli=1#heading=h.6i9jyvdxz4iv) and #153 and #154.

The [mini spec] calls for Chunk states of "open", "closing", "closed", "moving" and "moved".  The implementation in #944 proposes to store that state on the chunks in the `mutable_buffer`. This is non ideal for at least the following reasons:
1. It is not clear how we will get the state of chunks that don't start in the mutable buffer (e.g. if they were loaded from parquet)
2. It requires potentially consulting several structures( mutable buffer, read buffer, and object store) to understand a chunk's state

# Goal / Definition of Done:
Have a single structure that is responsible for managing the lifetime of chunks, and be the single source of truth about the state of any chunk in a database. Among other benefits, we also expect that bugs #1006 and #1008, which are due to race conditions when chunks are changing state, will be fixed.

# Proposal (enter the Catalog!)

We propose to add a new struct, named the `Catalog` that is responsible for tracking the state of each Chunk in a `Db`. Initially the `Catalog` will not have any be persisted state (it will be entirely stored in memory and recreated on startup) but over time it will become the primary interface for storing the lifecycle of a chunk (e.g. the location of chunks in memory, etc).

The `Catalog` itself will maintain the state about if 'the chunk is open' or if 'the chunk is moving' etc as well as manage a list of chunks for the db to operate on. The actual storage of chunk data would continue to actually be the mutable buffer and read_buffer respectively.

# Non responsibility

The Catalog itself will not have any logic for actually moving data around or enforcing valid state transitions. Rather that will be handled by logic at a higher level (in `Db` most likely). However the state of those operations will be stored in the catalog.

The sequence of steps to close a chunk might look like:

* Server::close_chunk() is invoked
** The chunk mover logic consults the current state of the chunk in the catalog, and ensures the chunk is in 'open' state.
** The chunk mover updates the chunk state to "closing" in the catalog and the close-chunk operation proceeds
** The data is now loaded into the read buffer
** During this time any query that comes in will be directed to use the copy of the chunk in the mutable buffer
** Once the load into the read buffer is complete, the chunk mover changes the state to 'closed' and any subsequent queries will use the read buffer chunk
** the chunk is now dropped from the mutable buffer.

**Comment by tustvold** [comment]
LGTM!

> The chunk mover logic consults the current state of the chunk in the catalog, and ensures the chunk is in 'open' state.
> The chunk mover updates the chunk state to "closing" in the catalog and the close-chunk operation proceeds

Should probably state that these two operations need to be one atomic operation. This is another major motivation for having a single "coordination" point to handle what chunk is in what state, across potentially multiple backing stores

**Comment by NGA-TRAN** [comment]
LGTM. I like we store the state in catalog for all easy automatic and manual chunk actives and monitoring

**Comment by NGA-TRAN** [comment]
I am not sure I am supposed to close this with my comments. Let me know the procedure if it is different

**Comment by alamb** [comment]
@NGA-TRAN  I would recommend we leave the issue open until we have merged a PR with code -- and that can close the issue

**Comment by NGA-TRAN** [comment]
Ah, I though this is just a design :)

**Comment by alamb** [comment]
Resolved in https://github.com/influxdata/influxdb_iox/pull/1043
