### ISSUE TITLE
Reduce the duplication of   "database -> partition -> Chunk" mapping

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#1042]
__Use case:__

This is a refactoring / restructuring the code exercise

while working on the catalog https://github.com/influxdata/influxdb_iox/issues/1016 , @tustvold  pointed out (see comments here https://github.com/influxdata/influxdb_iox/pull/1033#issuecomment-804258703) that IOx now has three very similar hierarchies of Databases which have a map of partitions which have a map of Chunks.

Specifically, they are:
* Mutable buffer ([source link](https://github.com/influxdata/influxdb_iox/blob/9817dbef2f2b24edd72a3f1152b85afdcc18a5fe/mutable_buffer/src/database.rs#L68))
* Read buffer; ([source link](https://github.com/influxdata/influxdb_iox/blob/9817dbef2f2b24edd72a3f1152b85afdcc18a5fe/read_buffer/src/lib.rs#L78)
* Catalog: see https://github.com/influxdata/influxdb_iox/pull/1039
(and it is likely we will need something similar for parquet files on object store)

The problem is that these maps all need to remain in sync for correctness. 

__Proposal:__
The proposal is to change the mutable buffer and read buffer to only deal with Chunks, and have some other database own the list of those chunks (perhaps the `Db` struct, perhaps the Catalog itself)

**Comment by pauldix** [comment]
Hmmm, the hierarchy of Database -> Partition -> Chunk is important for how the data is compacted and reorganized. I'm not sure I get how you'd update MB, RB or OBJ to not have that inherent in them. The Chunk is really just an underlying optimization for how the DB deals with data movement or writing data to a partition that has been cold for writes (i.e. it has been converted into a read-only format in the form of RB or OBJ).

How MB, RB, and OBJ deal with chunks within a partition is specific to each underlying implementation. My thought is that the only thing they share in common is the metadata (schema, summary) and some methods for querying them. The methods for operating on them would be different for each system.

So I'd expect traits for partitions and chunks for getting their metadata, summaries and queries but with different implemeting structs in each system (RB, MB, OBJ).

**Comment by alamb** [comment]
> How MB, RB, and OBJ deal with chunks within a partition is specific to each underlying implementation. My thought is that the only thing they share in common is the metadata (schema, summary) and some methods for querying them. The methods for operating on them would be different for each system.

Yes this makes sense -- thank you @pauldix 

I think the `PartitionChunk` trait is very similar to what you are describing https://github.com/influxdata/influxdb_iox/blob/6e1795fda04ce3c58fe86836cc7e196a8f4bce4c/query/src/lib.rs#L58 

The point if this ticket is that the (actual object) `Partition`  in the MB and `Partition` in the RB are redundant -- the actual `Chunk` is definitely different. So the hierarchy could be traced in the `Db` struct rather than in both RB and MB

**Comment by alamb** [comment]
I have been experimenting with some approaches to this change this afternoon my biggest challenge is to figure out how to avoid a "rewrite the world" type PR

Another issue I have hit is related to locking -- the mutable buffer has locks at the partition level, but (currently) the DB has a single giant catalog lock.

In order to prevent situations like "starting to move a chunk that has active writes to it" I need a way to lock the partitions individually (e.g. I probably need a read lock on each partition as well). I will continue to whack away at and see if I can find some way to make progess

**Comment by NGA-TRAN** [comment]
> In order to prevent situations like "starting to move a chunk that has active writes to it" I need a way to lock the partitions individually (e.g. I probably need a read lock on each partition as well). I will continue to whack away at and see if I can find some way to make progess

I am not sure I get this. We only move chunks that are closed. How will we hit this situtation?

**Comment by alamb** [comment]
> I am not sure I get this. We only move chunks that are closed. How will we hit this situtation?

I was observing that once a write has been "planed" (aka directed to a specific `mutable_bufer::chunk::Chunk`) nothing prevents the chunk from being marked as "closed" and begin copying to RB only to have the write then actually execute against the "closed" chunk

This is because the MB chunk is protected by a different set of locks than the Catalog chunk

**Comment by tustvold** [comment]
I think this can be considered complete now
