### ISSUE TITLE
Use proper jsonpb encoding for our protos

### ISSUE THREAD

**Issue by mkmik** [influxdata/influxdb_iox#1075]
Our CLI needs to be able to accept configuration as JSON and render configuration as JSON.

Protobufs technically have an official JSON encoding rule called `jsonpb` but prost doesn't
offer native support for it yet.

The feature may land upstream (See https://github.com/danburkert/prost/issues/75, https://github.com/danburkert/prost/pull/255, https://github.com/danburkert/prost/issues/277, https://github.com/danburkert/prost/pull/336); we may help and/or we may find some workarounds until it does.

In #1069 we started by just adding `serde` derives, but there are still major divergences from `jsonpb`:

- [ ] Enums are rendered numerically (jsonpb renders as string but accepts both string or number)
- [ ] Fields with default values are emitted (jsonpb omits a field if its value is `0`, `""`, `[]`, `null`)
- [ ] Well Known Types (such as `Any` and `Duration`) may have specific json renderings.

**Comment by jacobmarble** [comment]
@mkmik please update this issue. Can it be closed now?

**Comment by mkmik** [comment]
there may be some things missing (like encoding of well known types such as Any) but now that responsibility has moved to the https://github.com/influxdata/pbjson repo (e.g. https://github.com/influxdata/pbjson/issues/2) so I think we can close this one
