### ISSUE TITLE
Write RB chunks to parquet files 

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#1081]
__Use case:__
This is the first task of #808 that will write closed MB chunks to parquet. This work only provide functions to write to parquet, it does not include when to write and what are the state of the chunks while writing to parquet which will be described in a separated ticket.

__Proposal:__

Implement a new function named `load_chunk_to_object_store` that write a specified chunk to parquet files, each file represents  a table of the chunk. All the rows of that table will be grouped in one row-group in the parquet file.

This function will be done similarly to [`load_chunk_to_read_buffer` ](https://github.com/influxdata/influxdb_iox/blob/a51b1008a2fc9129cad90961f6720782b07a5e20/server/src/db.rs#L302) to get chunk data and convert it to RecordBatches and then and use [Arrow's write function ](https://github.com/apache/arrow/blob/1b9280f8d77b014f931325bce3f8023d03d72029/rust/parquet/src/arrow/arrow_writer.rs#L83) to write it to a specified path in parquet format

__Current behaviour:__
Describe what currently happens.

__Desired behaviour:__
Describe what you want.

__Alternatives considered:__
Describe other solutions or features you considered.

**Comment by alamb** [comment]
As @mkmik  keeps reminding me, there is some version of this code in snapshot.rs: https://github.com/influxdata/influxdb_iox/blob/7154dfd5f61232076a3336479ee98870bdc602c2/server/src/snapshot.rs

But that needs to be hooked into the rest of the `Db` structures

**Comment by NGA-TRAN** [comment]
After 5 different PRs, all pieces of this work are put together!
