### ISSUE TITLE
Evaluate different summary statistic data types (histogram)

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#11]
We should support a summary statistic for rolled up data. Rather than storing min, max, sum, count, and different percentiles, we might look into having a single series rollup into a single summary statistic that can get serialized and deserialized and used depending on what kind of value a query is asking for.

Here's what I can think of to evaluate:
* t-digest
* HDRHistogram
* DDSketch

**Comment by jacobmarble** [comment]
@pauldix can this be closed? Or, can you clarify the meaning of the original comment?

**Comment by pauldix** [comment]
Ah, this was to add a histogram type (like int64, float64, etc.). But I think this can be closed for the time being as this referenced a single series, which isn't really applicable in the current model.
