### ISSUE TITLE
Track Db Memory Footprint

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#1100]
Currently to determine the memory footprint of a Db it is necessary to enumerate all chunks in the catalog, acquire read locks on them and get their size. This is unfortunate, makes it impossible to efficiently implement a hard per-Db memory limit, and complicates observability.

As all writes, loads, etc... are coordinated via the Db struct I think it should be possible to track this on the Db, assuming the read buffer doesn't perform internal compaction (@e-dard ?)

**Comment by e-dard** [comment]
The Read Buffer does not changes the size of a chunk currently you could memoize all of them on the Db struct.

However once we add deletes that won't be true any more.

**Comment by alamb** [comment]
I like the idea of memozing the chunk statistics, FWIW

As a specific implementation suggestion, perhaps we could change https://github.com/influxdata/influxdb_iox/blob/839fe514a26173eefd65582a28524b6f4a031b43/server/src/db/chunk.rs#L191 to return `Arc<TableSummary>`
