### ISSUE TITLE
Possible memory leak on query

### ISSUE THREAD

**Issue by mkmik** [influxdata/influxdb_iox#1135]
Sudden increases of memory usage temporally correlate with manually issued queries I ran in the context of troubleshooting #1132 and #1133:

![image](https://user-images.githubusercontent.com/52673/113787020-934b1200-973a-11eb-9eaf-d60b639a3b1b.png)

Each query causes a transfer of about 22 Mb of record batches passed in a arrow flight "data_body" response,
which seems to be in the right order of magnitude of the leaked data (e.g. around 00:30 GMT+2 I issued around 10 queries and the memory usage spiked by ~300 Mb)

**Comment by alamb** [comment]
I wonder if this is also related to https://github.com/influxdata/influxdb_iox/issues/635 (which means we are effectively copying the entire dataset at least twice) on every query

**Comment by mkmik** [comment]
now that we have #1142 we see this is not a memory leak but it was just glibc's malloc not being able or willing to reduce the size of the process heap.

The amount of memory usage is still worrying, but it's not a leak; see #635
