### ISSUE TITLE
Build IOx with rust stable rather than a nightly build  (apache arrow needs rust nightly-2020-04-22)

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#115]
This issue tracks figuring out how to build apache arrow using rust `stable` rather than the  `nightly-2020-04-22`  toolchain.  The reason to do this is so that IOx itself could also be built using rust stable. 

@carols10cents  and @shepmaster  had previously  looked at the [Rust Arrow implementation](https://github.com/apache/arrow/blob/master/rust/arrow/) and think that nightly is used because it uses `packed_simd` and SIMD is still nightly-only https://github.com/apache/arrow/blob/master/rust/arrow/README.md#simd-single-instruction-multiple-data

it does look like arrow can have a feature that can be enabled/disabled for SIMD support, so theoretically it could work (but just be slower) on stable: https://github.com/apache/arrow/blob/a70b4a06f3cf657f08f80cee83b61f8799828539/rust/arrow/Cargo.toml#L48-L56

Here is a link to more details in slack:
https://influxdata.slack.com/archives/CRK9M8L5Q/p1589984277329600

**Comment by GregBowyer** [comment]
Fwiw I think the only place its actually used is in `parquet` the related file format of arrow (I was able to compile arrow itself with stable)

**Comment by alamb** [comment]
@GregBowyer  I think you are correct that parquet is the last remaining user of rust nightly -- and there is work in the arrow project to remove the need for nightly rust so hopefully we'll be able to get this done 🤞

**Comment by GregBowyer** [comment]
I only know this because I am taking a personal swing at removing specialization from parquet right now

**Comment by GregBowyer** [comment]
I have a PR for people to scream at and not like here https://github.com/apache/arrow/pull/8698

This pulls out specialization and thus renders the crate build-able with stable
