### ISSUE TITLE
feat: implement logical clock and refactor Write Buffer

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#1157]
The Write Buffer must be refactored for the new flatbuffers structure. It should take an `Entry` and produce a `SequencedEntry` with a logical clock value and the writer ID.

Segment should be refactored to have an array of `SequencedEntry`, writer id, min clock value, max clock value and consistency_high_water (the clock value of the last consistency check). It should be moved into `entry.fbs` or a new `segment.fbs` in the same location.

Finally, the Write Buffer should keep a logical clock that can be incremented or updated to a new value (if passed value is > the current one). The [clock is the same one detailed here](https://docs.google.com/document/d/1wVGOCMjLlDM0QvKotbqmGGwe0V_4yaJurPXM7c4-Tw8/edit#heading=h.pxl1pb6eg5le).

**Comment by pauldix** [comment]
This PR removed the old WAL Segment persistence. Might be useful to pull the code out of here when refactoring to bring the persistence back in: https://github.com/influxdata/influxdb_iox/pull/1181

**Comment by tustvold** [comment]
I believe this can be closed now?

**Comment by carols10cents** [comment]
I think you're right!
