### ISSUE TITLE
Object store persistence

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#1163]
# Definition of Done:
1. Data is written to parquet files on object store based on data lifecycle rules
2. Data that has been written to object store should be able to be queried
3. When the iox process is restarted, any previously written parquet files are available

# Open question:
1. Will we query parquet files directly or first load them into the read buffer
2. Do we need to persist a serialized catalog for v1 or can we just list objectstore files
3.

**Comment by alamb** [comment]
All the items in this epic are done and we have object store persistence, so marking as complete

**Comment by crepererum** [comment]
@alamb did you re-open this ticket on purpose?

**Comment by alamb** [comment]
@crepererum  I did not -- maybe it was something related to dragging stuff around in ZenHub. Sorry for the noise
