### ISSUE TITLE
Label influxdb_client PRs

### ISSUE THREAD

**Issue by aakashhemadri** [influxdata/influxdb_iox#1202]
I would like to filter PRs/Issues based on the influxdb_client label for reference, If someone could mark the below PRs it would be helpful

PR:
https://github.com/influxdata/influxdb_iox/pull/249
https://github.com/influxdata/influxdb_iox/pull/253
https://github.com/influxdata/influxdb_iox/pull/260
https://github.com/influxdata/influxdb_iox/pull/273
https://github.com/influxdata/influxdb_iox/pull/770
https://github.com/influxdata/influxdb_iox/pull/996
https://github.com/influxdata/influxdb_iox/pull/998
https://github.com/influxdata/influxdb_iox/pull/1070
https://github.com/influxdata/influxdb_iox/pull/1076
https://github.com/influxdata/influxdb_iox/pull/1093
https://github.com/influxdata/influxdb_iox/pull/1172

Issues:
https://github.com/influxdata/influxdb_iox/issues/1028
https://github.com/influxdata/influxdb_iox/issues/1176

I might have missed a few PR's, So do feel free to add them :)

**Comment by alamb** [comment]
Done @aakashhemadri  -- let me know if you need any more

**Comment by alamb** [comment]
https://github.com/influxdata/influxdb_iox/labels/influxdb_client

**Comment by aakashhemadri** [comment]
Thanks! @alamb
