### ISSUE TITLE
Remove line protocol gRPC write service 

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#1204]
__Use case:__
we want to encourage users to avoid sending IOx line protocol (which takes a lot of CPU to parse and validate) as much as possible. The gRPC write service introduced in https://github.com/influxdata/influxdb_iox/pull/939 added support to send line protocol formatted data via gRPC. @pauldix  notes this is not desired long term.  

Note we need to keep the /api/v2/write http api endpoint for backwards compatibility.

__Proposal:__
Once the native write protocol (flatbuffers based) is implemented, remove the write service that takes line protocol. Note that there should still be a way via the CLI to write line protocol data into IOx but it should do the lineprotocol --> flatbuffers conversion at the client. 

__Current behaviour:__
gRPC API takes line protocol formatted data

__Desired behaviour:__
gRPC API does not take line protocol formatted data

__Alternatives considered:__
Describe other solutions or features you considered.

**Comment by jacobmarble** [comment]
@crepererum does

**Comment by crepererum** [comment]
It's not done yet though.

**Comment by tustvold** [comment]
Closed by #3044
