### ISSUE TITLE
Use Arrow StringDictionary for tag columns

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#1220]
For tag values, and possibly all string values in general, dictionary encoding can have significant benefits to both in-memory size and query performance. It is theorized that the loss of dictionary encoding is the cause of the performance regression created by #1179.

This issue tracks adding the necessary plumbing within IOx to support this, and potentially any necessary arrow/Datafusion work.

A previous attempt at this can be found in #328 

Also relates to #334

**Comment by alamb** [comment]
@tustvold  the plan is to use string dictionary encoding for only tags, correct?

**Comment by tustvold** [comment]
@alamb Yes this ticket just tracks using them for tags
