### ISSUE TITLE
memory on IOx is growing without bounds

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#1225]
We deployed a new image to IOx on tools cluster

__Expected behaviour:__
Memory usage should hit a peak and stay stable as the life cycle rules roll data over. Specifically I expect to see about 1GB maximum of data in the `844910ece80be8bc_infra` database

__Actual behaviour:__
Memory usage seems to be going monotonically upwards. The `844910ece80be8bc_infra` has more than 16GB

![image (2)](https://user-images.githubusercontent.com/490673/114884798-0eb06180-9dd4-11eb-9744-908c1a1faee0.png)

When I examined the data layout for the server I can see the `844910ece80be8bc_infra` database consuimg ~ 16GB

```
> -- Total estimated storage size by database
select database_name, storage, count(*) as num_chunks, sum(estimated_bytes)/1024/1024 as estimated_mb
from chunks
group by database_name, storage
order by estimated_mb desc;

+-----------------------------------+---------------------+------------+--------------+
| database_name                     | storage             | num_chunks | estimated_mb |
+-----------------------------------+---------------------+------------+--------------+
| 844910ece80be8bc_infra            | ReadBuffer          | 2408       | 16223        |
| 844910ece80be8bc_apps             | ReadBuffer          | 65         | 494          |
| 844910ece80be8bc_7be09b71c487d5d3 | ReadBuffer          | 133        | 454          |
| 844910ece80be8bc_istio            | ReadBuffer          | 13         | 129          |
| 844910ece80be8bc_7be09b71c487d5d3 | ClosedMutableBuffer | 11         | 110          |
| 7f4b06e9112d7bc8_system%5Fusage   | ReadBuffer          | 29         | 60           |
| 844910ece80be8bc_5403ba1b2193d41f | ReadBuffer          | 17         | 46           |
| InfluxData_%5Ftasks               | ReadBuffer          | 3          | 32           |
| 844910ece80be8bc_apps             | ClosedMutableBuffer | 3          | 30           |
| 7f4b06e9112d7bc8_system%5Fusage   | ClosedMutableBuffer | 2          | 20           |
| 844910ece80be8bc_eaec8df57a81a1e9 | ReadBuffer          | 3          | 13           |
| 844910ece80be8bc_05d1e95653672000 | ReadBuffer          | 3          | 13           |
...
```

The lifecycle rules (obtained via `./scripts/edit_db_rules localhost:1234 844910ece80be8bc_infra`) for the `844910ece80be8bc_infra` database say it should stop dropping data when it hits a 1GB threshold

```
{
  "rules": {
    "name": "844910ece80be8bc_infra",
    "partitionTemplate": {
      "parts": [
        {
          "time": "%Y-%m-%d %H:00:00"
        }
      ]
    },
    "lifecycleRules": {
      "mutableLingerSeconds": 5,
      "mutableSizeThreshold": "10485760",
      "bufferSizeSoft": "1000000000",
      "bufferSizeHard": "1000000000",
      "sortOrder": {
        "order": "ORDER_ASC",
        "createdAtTime": {
        
        }
      }
    }
  }
}
```

**Comment by alamb** [comment]
We theorize this may be related to the changes in lifecycle policy in https://github.com/influxdata/influxdb_iox/pull/1174

**Comment by alamb** [comment]
@crepererum  says: My current guess is that we have the persist flag set to false and the "drop unpersisted" set to false as well. The handling around that was changed by my PR.

In the config above neither flag is set, so they both default to false

**Comment by crepererum** [comment]
Suspicion confirmed by flipping `persist` to `true`. Let's keep this issue open until we have fixed the defaults.
