### ISSUE TITLE
add db_name to all log messages in lifecycle.rs

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#1227]
__Use case:__
When looking at the logs, I can see lots of chunk movement, but there is no way from the logs to know what database is writing and thus I can't filter for what my database of interest is doing

![Screen Shot 2021-04-15 at 11 46 30 AM](https://user-images.githubusercontent.com/490673/114898979-98fec280-9de0-11eb-98bc-8b59cfa6d823.png)

__Proposal:__
Add `db_name=<name>` field to each log message

__Current behaviour:__
no db_name is logged

__Desired behaviour:__
db name is logged

__Alternatives considered:__
Describe other solutions or features you considered.

**Comment by tustvold** [comment]
Theoretically this should be being added as part of the fields on the span... I wonder if our custom log formatting is causing issues :thinking:

**Comment by alamb** [comment]
When I was last poking around at the tracing libraries, what I found was that the the fields on the currently active span are not also included with each message. So in theory it is probably possible to match each message with its encompassing span and then find the db_name from that.

My (new) thinking is to add, (what else?) a system table to track chunk movements in #1315

**Comment by tustvold** [comment]
I think this has been done
