### ISSUE TITLE
Make chunks per-table

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#1256]
Defining chunks as collections of tables has a number of issues:

* They are the atomic unit of data movement, but throughput is not evenly distributed across tables. This leads to tables with very few rows being moved to the RUB/Parquet on account of large sibling tables
* Table management, predicate pushdown, etc... logic duplicated in MUB, RUB and Parquet
* MUB chunk snapshots may snapshot tables the query isn't interested in - this could be fixed with better predicate pushdown but easier to just filter entire chunks within catalog

Currently the catalog stores partitions containing chunks, the catalog should instead be changed to store partitions containing tables which contain chunks. The corresponding table logic should then be removed from the chunk implementations.

**Comment by e-dard** [comment]
I discussed this with @tustvold and @crepererum and as an initial step proposed that we made changes to limit the number of tables to one per chunk, but in a way that didn't change the existing contract with the execution engines.

This has the advantage of allowing us to provide out the notion that limiting chunks to single tables will let us hold smaller chunks in the MUB for longer and limit the number of small tables being pushed to the RB. But it will also mean we don't have to change any execution engine code initially.
