### ISSUE TITLE
Move "inner" chunk implementations to "exactly one table"

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#1295]
As an engineer, I except the inner chunk implementations to follow the high-level chunk states, therefore I want them to track "exactly one table".

This requires #1296 to be implemented!

# ACs
- All inner table multiplexers like https://github.com/influxdata/influxdb_iox/blob/2a6eed97c684cf30d7d6121ab814ae7bab7c5442/mutable_buffer/src/chunk.rs#L74-L75 are gone.
- All `has_table` methods are gone.

**Comment by alamb** [comment]
@e-dard  is cleaning up the "multiple tables in a chunk" still on your radar for the RUB?

**Comment by e-dard** [comment]
@crepererum I have done this on the RUB, can this issue be closed or is there more to do on the Parquet side?

**Comment by crepererum** [comment]
parquet is done, thanks!

**Comment by alamb** [comment]
🎉
