### ISSUE TITLE
Register used bytes for Parquet chunks

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#1311]
__Use case:__
While testing Query Parquet for #1082, I discovered that not all bytes of parquet catalog info is registered. This ticket is to do it. 

__Proposal:__
Will follow what have registered for MB and RB to do the same for ParquetFile

__Current behaviour:__
Only a small part of the bytes are registered

__Desired behaviour:__
Fully registered all Parquet bytes used in memory

**Comment by alamb** [comment]
@NGA-TRAN  should the reported parquet size be the size of parquet on "disk" (aka size of bytes in object store / local volume) or do you really mean "in memory")?

**Comment by NGA-TRAN** [comment]
@alamb if I understand correctly, we try to register what we use in memory. Hence, this is to register bytes in memory of this [chunk](https://github.com/influxdata/influxdb_iox/blob/0a835436acdf6c4f010c0eb9f66b849d831c38e8/parquet_file/src/chunk.rs) and [table](https://github.com/influxdata/influxdb_iox/blob/0a835436acdf6c4f010c0eb9f66b849d831c38e8/parquet_file/src/table.rs). I think someone just did this recently and not yet do it for parquet_file
