### ISSUE TITLE
Background task to delete Object Store files of dropped chunks

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#1313]
__Use case:__
Currently, when a chunk is dropped, we do not remove its corresponding file in object store. This should be done.

__Proposal:__
Store the dropped chunks that have corresponding files in object store somewhere in the catalog and have an background task to go and remove them.

__Current behaviour:__
It seems the object store files are scheduled deleted from AWS outside IOx. @alamb: correct me if I am wrong.

__Desired behaviour:__
Have an IOx background task to remove them

__Alternatives considered:__

**Comment by alamb** [comment]
@NGA-TRAN I don't think anything is currently cleaning up object store files, unless @mkmik  or @tustvold  or @e-dard  knows differently -- there is some way to set a policy to delete S3 objects that get too old but I don't think we have set it.

I was tracking the growth of stuff on S3 internally with https://github.com/influxdata/conductor/issues/254

**Comment by crepererum** [comment]
What do you mean by "dropped" chunks? Currently we "drop" chunks if we run out of memory on a writer (soft buffer limit) but I think that doesn't justify to remove parquet files from the object store.

**Comment by e-dard** [comment]
In Influxdata parlance dropping durable data after some period of time is usually referred to as the Retention Policy. I think what we are after here is an initial Retention Policy for IOx

**Comment by NGA-TRAN** [comment]
@crepererum This ticket is to remove left over parquet files of chunks that were already dropped permanently. The experience is we do not want to wait for parquet files to be deleted before declaring the delete transaction completed.

@e-dard : Yes, this is a part of the Retention Policy for IOx. I think before we start doing this, we have to decide what the retention policy looks like

**Comment by NGA-TRAN** [comment]
Send this to @crepererum as he will have a write-up about the new state machine setup that includes this work

**Comment by crepererum** [comment]
Fair. I think this is very similar to what we wanna do for the catalog (i.e. prune/delete parquet files that are no longer referenced). Would you agree that this is technically the same? In that case, I would just "steal" this issue here and move it over the #1375 epic. Sure at a later point we could also do "eager deletions" for permanently deleted chunks (e.g. via some API call), but I think just doing it via the catalog-driven pruning (which we need anyway to clean up after node crashes w/ incomplete transactions) is "good enough" for now.

**Comment by NGA-TRAN** [comment]
Yes, sounds good to move it under #1375
