### ISSUE TITLE
Unload chunks from memory (RB) but keep them in Object Store

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#1314]
__Use case:__
Since we let an IOx database to operate on a specified limited memory size, we need to unload chunks from RB when the DB's  memory reach a certain size. 

__Proposal:__
  . Create an unload_chunk similar to this [drop_chunk](https://github.com/influxdata/influxdb_iox/blob/0a835436acdf6c4f010c0eb9f66b849d831c38e8/server/src/db.rs#L434) but do not drop it from the catalog and only remove the RB chunk.
 . Design and implement functions to make the unload happen.

__Current behaviour:__
We do not have unload chunk from RB but keep it in OS yet

__Desired behaviour:__
Support unload chunks from RB functionality

__Alternatives considered:__

**Comment by NGA-TRAN** [comment]
This ticket is for implementing unload_chunk function only. When it is invoked, the chunk's status will be moved to **ChunkState::ObjectSToreOnly**. When this is available, we will have a different ticket to hook it into our life cycle

@alamb : this is related to [#1315](https://github.com/influxdata/influxdb_iox/issues/1315) because it ads a new state. Let me know if it sounds good to you

**Comment by NGA-TRAN** [comment]
Without thinking about compacting, the states can looks like this

```
┌────────────────────┐               
│        Open        │               
│                    │               
└────────────────────┘               
           │                         
           ▼                         
┌────────────────────┐               
│      Closing       │               
│                    │               
└────────────────────┘               
           │                         
           ▼                         
┌────────────────────┐               
│       Moving       │               
│                    │               
└────────────────────┘               
           │                         
           ▼                         
┌────────────────────┐               
│       Moved        │               
│                    │◀─             
└────────────────────┘  │            
           │                         
           ▼            │            
┌────────────────────┐               
│WritingToObjectStore│  │            
│                    │               
└────────────────────┘              
           │                         
           ▼            │  
┌────────────────────┐       
│     WrittenTo      │    ◀─   
│    ObjectStore     │      |
└────────────────────┘|
           │                         | Move hot 
           ▼                       | data back
 ┌────────────────────┐| in RUB
  ObjectStoreOnly   │  │ 
│        │      
└────────────────────┘ |                
                        |                      
                        │            
           └ ─ ─ ─ ─ ─ ─             
```

**Comment by alamb** [comment]
@NGA-TRAN  I think this picture makes sense. @influxdata/iox-conductor  any other thoughts?

**Comment by alamb** [comment]
@pauldix 's mentioned elsewhere 

> Here are the states I imagine:
* Open (in MUB)
* Closing (in MUB but still accepting writes for rows in its key space)
* Moving (still in MUB, but building a RUB chunk to swap with)
* Closed (in RUB)
* WritingToObjectStore (in RUB and being written)
* ObjectStoreAndRUB (exists in both OS and RUB)
* ObjectStore (just in the OS)
* Retrieving (in the OS and hydrating to the RUB) -> ends in ObjectStoreAndRUB
* Cached (in OS and local filesystem)
* Hydrating (loading from local filesystem to RUB)
* Getting (in OS and caching to local filesystem)
* CachedAndHydrated (in OS, RUB, and local filesystem)

> For now I would skip the cache related states, but I can see them being useful once we want to query against Parquet files directly without hydrating them into the RUB. (edited)

**Comment by crepererum** [comment]
So if we leave out the "cached" parts of Pauls suggestion, then I think we end up at the graph @NGA-TRAN  is proposing - assuming that "move hot data back in RUB" is a state. Or to bring that in line with the rest of the graph:

```text
┌────────────────────┐       
│     WrittenTo      │◀────┐
│    ObjectStore     │      │
└────────────────────┘      │
           │             ┌────────────────────┐
           ▼             │   RetrievingFrom   │
┌────────────────────┐   │   ObjectStore      │
|    ObjectStoreOnly │   └────────────────────┘
│                    |      │
└────────────────────┘      │               
           │                │                    
           │                │                    
           └────────────────┘
```

**Comment by NGA-TRAN** [comment]
Totally aree @crepererum
