### ISSUE TITLE
Expose chunk lifecycle chunk movement as a system table

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#1315]
__Use case:__
As we explore IOx underload and contemplate ways we may want to modify the the life cycle rules, it will be important to understand what operations have been performed by the mover so that we can tweak the rules accordingly

__Proposal:__
Add `system.chunk_mover` system table that has the following columns:
* Time of operation
* Name of operation
* Description of operation
* partition_id
* chunk_id
* Other info that might be interesting (like object store path??)

**Comment by alamb** [comment]
This is also perhaps related to #1287

**Comment by tustvold** [comment]
I wonder if this transition information should be tracked at the chunk level, that way we'd get the plumbing largely for free, and potentially also get persistence?

**Comment by alamb** [comment]
@tustvold  are you thinking "track chunk state transitions" like
* partition_id
* chunk_id
* time of transition
* Current state
* New state
* other information

**Comment by tustvold** [comment]
I meant make it an inherent part of the representation of a chunk in the catalog, as opposed to a separate system that tracks the chunk mover specifically. After all there are multiple things that can cause a given transition.

A simple implementation would be to just store a time_moved_to_rub optional timestamp on the chunk or something...

**Comment by crepererum** [comment]
I'm with @tustvold on the point that data lineage information should be part of the chunk, not yet another tracker. This would also allow us to store parts of it in parquet files which will be gold for future debugging sessions.

**Comment by alamb** [comment]
Got it -- makes sense @tustvold  and @crepererum  -- good ideas. 

I will need to think about how to model the lifecycle of a chunk in order to do this. Right now we have a single lifecycle

```
┌────────────────────┐
│        Open        │
│                    │
└────────────────────┘
           │          
           ▼          
┌────────────────────┐
│      Closing       │
│                    │
└────────────────────┘
           │          
           ▼          
┌────────────────────┐
│       Moving       │
│                    │
└────────────────────┘
           │          
           ▼          
┌────────────────────┐
│       Moved        │
│                    │
└────────────────────┘
           │          
           ▼          
┌────────────────────┐
│WritingToObjectStore│
│                    │
└────────────────────┘
           │          
           ▼          
┌────────────────────┐
│     WrittenTo      │
│    ObjectStore     │
└────────────────────┘
```

But I wonder how to store such provenance information of the state machine starts having cycles like

```
┌────────────────────┐               
│        Open        │               
│                    │               
└────────────────────┘               
           │                         
           ▼                         
┌────────────────────┐               
│      Closing       │               
│                    │               
└────────────────────┘               
           │                         
           ▼                         
┌────────────────────┐               
│       Moving       │               
│                    │               
└────────────────────┘               
           │                         
           ▼                         
┌────────────────────┐               
│       Moved        │               
│                    │◀─             
└────────────────────┘  │            
           │                         
           ▼            │            
┌────────────────────┐               
│WritingToObjectStore│  │            
│                    │               
└────────────────────┘  │            
           │                         
           ▼            │  Will this 
┌────────────────────┐      type of  
│     WrittenTo      │  │ transition 
│    ObjectStore     │      ever be  
└────────────────────┘  │  possible? 
           │                         
                        │            
           └ ─ ─ ─ ─ ─ ─             
```

I will think about it

**Comment by crepererum** [comment]
For the diagrams above: the question is also if `WrittenToObjectStore` is one or multiple states. For example, could we load "hot" parquet files back into RAM for efficiency in the future?

**Comment by alamb** [comment]
FYI @NGA-TRAN

**Comment by NGA-TRAN** [comment]
I like the idea about moving hot data back to RUB

**Comment by NGA-TRAN** [comment]
The ticket #1314 will add another state  ObjectStoreOnly. We might want to include it in the design of this

**Comment by alamb** [comment]
We have added `lifecycle_action` to each chunk in `system.chunks` -- I think that is good enough for now along with the system.operations table
