### ISSUE TITLE
Use Rustls

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#1354]
[Rustls](https://github.com/ctz/rustls) is a Rust implementation of SSL. This has a number of advantages:

* It's faster and uses less memory than OpenSSL
* Doesn't require libssl as a runtime dependency <sup>1</sup>
* Doesn't rely on OpenSSL <sup>2</sup>

_1. Some people might argue that cryptography libraries should be dynamically linked, but I think that ship sailed with docker (pun somewhat intended)_
_2. This is sort of misleading, rustls depends on ring, which has implementations borrowed from Google's BoringSSL, which itself derives code from OpenSSL :turtle:_

Most crates already have options to switch to using rustls, but it is possible that some of the more esoteric dependencies don't. Last time I looked the azure cloud SDK didn't have support, but in almost all cases it is simply a case of plumbing feature flags through correctly - and so should be a fairly straightforward PR to upstream

**Comment by jacobmarble** [comment]
@carols10cents maybe this switch from a C dependency to a Rust dependency would improve build times?

**Comment by carols10cents** [comment]
mkm is working on doing this in conductor over here: https://github.com/influxdata/conductor/pull/848

**Comment by domodwyer** [comment]
One compatibility concern to be aware of is that rustls does not currently respect [iPAddress SANs](https://github.com/briansmith/webpki/issues/54) in certificates, preventing TLS connections to IP addresses. You'd like to think everyone uses DNS, but :shrug:
