### ISSUE TITLE
Catalog Lock Contention Metrics

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#1355]
The catalog contains a number of RwLocks that are used to mediate access to the chunks within a database.

Critically writes to the MUB take place under the catalog chunk's write lock, and snapshots take place under the catalog chunk's read lock. Neither of these operations are necessarily very fast, and therefore there is a high chance of lock contention, particularly as for high-throughput tables there are likely multiple concurrent writes to the same table and therefore potentially the same chunk.

As these locks are not async (which is probably still correct) lock contention can potentially starve out tokio worker threads, which would be bad. 

We should get some metrics on how much time is spent waiting to acquire read and write locks. This could take the form of two AtomicUsize for each lock, storing the number of milliseconds spent waiting to acquire the lock as read and write respectively. These could then be exposed as monotonic gauges to prometheus, or something similar.

**Comment by alamb** [comment]
This is a good idea -- I think it may be worth gathering this as part of the "handle tools write workload" epic

**Comment by e-dard** [comment]
This makes sense to do but it pains me that we have to write code to do it rather than being able to simply take a blocking profile of the program :-)

**Comment by tustvold** [comment]
> simply take a blocking profile of the program

They are OS-level locks, so would show up in a standard perf profile, however, the advantage to instrumenting would be that we could have the metrics all the time :grinning:
