### ISSUE TITLE
Read Buffer RowGroup Compaction

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#1360]
Below is the formulation for the compaction lifecycle as envisaged at the time of writing - this may be subject to change:

* Data for a single table arrives in a mutable buffer chunk
* It accumulates until some policy causes it to be moved to the read buffer
* At this point there is a read buffer chunk with a single row group
* This process repeats until there are multiple read buffer chunks each containing a single row group
* At some point a compaction policy decides to compact _k_ of these chunks into a single new chunk
* The resulting chunk should contain a single, sorted row group

This ticket covers the work to perform this _k_ way merge, it doesn't cover any additional work to plumb in the chunk state machine, compaction policy, etc...

Doing this efficiently may relate to, it would be reasonable imo to only support compacting chunks with the same sort order - https://github.com/influxdata/influxdb_iox/issues/1357 https://github.com/influxdata/influxdb_iox/issues/1359

@e-dard probably has more ideas of what this should look like. Currently RowGroup is private to the read buffer crate, which may influence how this is implemented

**Comment by alamb** [comment]
Another interesting thought might be to "compact" chunks in the read buffer by simply appending their row groups together. Then we could have a "merge" operation that would merge the row groups.... 🤔
