### ISSUE TITLE
Compaction State Machine

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#1361]
As described on https://github.com/influxdata/influxdb_iox/issues/1360 compaction introduces new states to the chunk state machine.

Once compaction starts we need to change the chunk state so that it indicates that a compaction is in-progress.

In addition compaction will normally (if not solely) take place on chunks that have already been persisted to parquet, i.e. are in the `ObjectStoreAndRUB` state. As such we only want to remove the source chunks once the new compacted chunk also exist in the `ObjectStoreAndRUB`. A simple way to achieve this would be to add the compacted chunk to the catalog in this state, i.e. compact + persist and then swap into catalog - but the process should be defined and the necessary plumbing implemented

**Comment by alamb** [comment]
It is also not 100% clear to me that a "compacting" state in the catalog is ideal (because it doesn't affect what you can do with a chunk from a query perspective). 

Though it may affect lifecycle decisions, perhaps, which would argue for encoding explicitly as a state in the catalog. 🤔

**Comment by pauldix** [comment]
I expect in-memory compactions to be very frequent. Not sure that's something we'd even want to bother having in the catalog. I'd skip having the transitionary states in the catalog (e.g. loading, hydrating, compacting, moving (mub to rub))

**Comment by NGA-TRAN** [comment]
@alamb and @pauldix I agree we do not need to keep a new state of compacting in the catalog but after a compacting is done, we must update the catalog to replace all small compacted chunks with the newly created one.

@tustvold  If you want to have some history such as when/how many times compacting happens or compacting happened but failed, I think logging is good enough. System table can also be used if needed to query log files for that info.

**Comment by alamb** [comment]
As we were discussing in #1397 it seems like we will need some way to track the lifecycle actions currently underway (e.g. compactions, moving to RB, etc ) but those actions shouldn't be persisted to the "catalog" (though maybe they would live on the same in-memory structure). 

Persisting in-progress actions would likely be problematic because when the process was restarted all those actions, by definition, are no longer in progress 🤣  So they would have to be cleared anyways.
