### ISSUE TITLE
Enable parquet compression for catalog-managed files

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#1372]
__Use case:__
As a IOx user, I expect max performance at minimal cost (or at least someone good inbetween), therefore IOx should parquets "general purpose compression" (GZIP, ZSTD, ...)

__Proposal:__
Short summary of the feature.

__Current behaviour:__
Compression is not set:

https://github.com/influxdata/influxdb_iox/blob/98be7e8b0017f11d8d441597cfb3b231f082e8f1/parquet_file/src/storage.rs#L191

so props are `None` which will lead to this default:

https://github.com/apache/arrow-rs/blob/ed00e4d4a160cd5182bfafb81fee2240ec005014/parquet/src/file/properties.rs#L60

__Desired behaviour:__
Compression should either use some IOx-specific default or should be configurable.

__Alternatives considered:__
None.

**Comment by alamb** [comment]
Closed in https://github.com/influxdata/influxdb_iox/pull/2218
