### ISSUE TITLE
Map In-Memory Parquet Chunks <-> Parquet

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#1379]
Map all parts required to represent an parquet chunk in-memory to the written parquet files at back, so that parquet files are "self-contained" (i.e. inspecting an parquet file and its path should be sufficient to restore the in-memory information).

# Background
This requires handling of at least the schema and statistics. This might require additional file-level parquet metadata for information that cannot be expressed in vanilla parquet.

**Comment by NGA-TRAN** [comment]
Yeah, we will need to add a bit in a few files/modules under [parquet_file crate](https://github.com/influxdata/influxdb_iox/tree/main/parquet_file) for all info needed but our today catalog's ParquetFileChunk has already mapped to its parquet file under the crate.
