### ISSUE TITLE
feat: Add a local filesystem based object store

### ISSUE THREAD

**Issue by carols10cents** [influxdata/influxdb_iox#139]
In addition to the S3, GCS, and in-memory stores in the delorean_object_store crate. See https://github.com/influxdata/delorean/pull/134 and https://github.com/influxdata/delorean/pull/116 for info and inspiration.

**Comment by alamb** [comment]
@carols10cents  I think this ticket is finished -- shall we close it?

e.g. 
https://github.com/influxdata/influxdb_iox/blob/master/object_store/src/lib.rs#L494

**Comment by carols10cents** [comment]
Agreed!
