### ISSUE TITLE
Hook unload_read_buffer into the life cycle

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#1400]
When #1314 is done, this ticket is to hook that unload_read_buffer function into our life cycle

**Comment by alamb** [comment]
It is probably worth thinking about how loading and unloading will play with the other lifecycle operations as well

**Comment by NGA-TRAN** [comment]
The proposed life cycle that includes 1 more state and a reload back to RUB

┌────────────────────┐                    
│        Open        │                    
│                    │                    
└────────────────────┘                    
           │                              
           ▼                              
┌────────────────────┐                    
│      Closed        │                    
│                    │                    
└────────────────────┘                    
           │                              
           ▼                              
┌────────────────────┐                    
│       Moving       │                    
│                    │                    
└────────────────────┘                    
           │                              
           ▼                              
┌────────────────────┐                    
│       Moved        │                    
│                    │                    
└────────────────────┘                    
           │                              
           ▼                              
┌────────────────────┐                    
│WritingToObjectStore│                    
│                    │                    
└────────────────────┘                    
           │                              
           ▼                              
┌────────────────────┐                    
│     WrittenTo      │    ◀─              
│    ObjectStore     │      |             
└────────────────────┘      |             
           │                | Reload hot  
           ▼                | data back   
┌────────────────────┐      | in RUB      
|    ObjectStoreOnly │      │             
│                    |      |             
└────────────────────┘      |             
               |            │             
                ------------

**Comment by alamb** [comment]
@NGA-TRAN  I am not sure where the `ObjectStoreAndLocalDisk` fits in this picture. 

I think @tustvold  has some plans sketched in https://github.com/influxdata/influxdb_iox/pull/1397 (which I liked) to split the information on "ephemeral actions we are doing to the Chunk" and the "state that we will save to the catalog"

```
   ┌────────────────────┐    
   │        Open        │    
   │   (only in MUB)    │    
   └────────────────────┘    
              │              
              ▼              
   ┌────────────────────┐    
   │      Closing       │    
   │   (only in MUB)    │    
   └────────────────────┘    
              │              
              │              
              ▼              
   ┌────────────────────┐    
   │       Closed       │    
   │  (RUB and/or MUB)  │    
   └────────────────────┘    
              │              
              │              
              ▼              
┌───────────────────────────┐
│         Persisted         │
│ (ObjectStore and/or RUB)  │
└───────────────────────────┘
```

And then we would have a separate state machine or flags or something that would track stuff like "is being loaded to RUB" or "is cached in a local file", etc. 

🤔  may be worth a thought

**Comment by crepererum** [comment]
In the above graph: can you persist from an MUB directly? Otherwise I definitely like the hierarchical idea (= collapse all sub-states into a single node if the behave in an identical manner) since it makes reasoning about states a lot easier.

**Comment by alamb** [comment]
> can you persist from an MUB directly

There is no theoretical reason preventing persisting directly from the MUB (anything that can create RecordBatches can be written to parquet). 

Given it would likely be much less data / smaller than what we could persist from the RUB the code today assumes data will have been written to RUB first.

**Comment by NGA-TRAN** [comment]
@alamb I like the design that keep only Open, Closed and Persisted and then separate state for cached Bac in RUB or Local Disk. I think @tustvold 's state includes only 3 states:

                                                                                                                                                  
                                                                                                                                                  
                                                                                                                                                  
                                                                                                                                                  
                                                                                                                                                  
                                                                                                                                                  
                  ┌──────────────────────────────┐                                                                                                
                  │             Open             │                                                                                                
                  │        (Only in MUB)         │                                                                                                
                  └──────────────────────────────┘                                                                                                
                                  │                                                                                                               
                                  ▼                                                                                                               
                  ┌──────────────────────────────┐                                                                                                
                  │            Closed            │                                                                                                
                  │     (RUB and maybe MUB)      │                                                                                                
                  └──────────────────────────────┘                                                                                                
                                  │                                                                                                              ─
                                  ▼                                          .                                                                    
                  ┌──────────────────────────────┐                          ( )                                                                   
                  │          *ersisted           │                           '                                                                    
                  │ (Object Store and maybe RUB) │                                                                                                
                  └──────────────────────────────┘

**Comment by NGA-TRAN** [comment]
@crepererum Send this ticket your way as you plan to include it in your current PR
