### ISSUE TITLE
Notify conductor about catalog forks

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#1401]
As discussed in #1386 , we may wanna inform Conductor in some way about the fact that the transaction layer detecting a fork (= two instances with the same ServerID writing into the same catalog).

# ACs
- decide on some way to inform conductor, e.g. via push (direct callback to conductor) or push (flagging the IOx node which will then later be discovered by conductor)
- implement the IOx side
- create a story for (or implement) the conductor side

**Comment by pauldix** [comment]
Not relevant to NG (new) catalog.
