### ISSUE TITLE
test: Larger data sets and streaming with object stores

### ISSUE THREAD

**Issue by carols10cents** [influxdata/influxdb_iox#141]
From [this comment](https://github.com/influxdata/delorean/pull/134/files#r438684986):

> Given all the apis above work with async streams too, I wonder how well the 'data was sent / came back in multiple chunks' case is tested.
>
>In particular I was thinking about these cases:
>
>-    Input data stream: data in this function seems to be sent in a single chunk via stream_data below. I wonder if breaking it into two pieces ("arbitrary", "data") might add some additional coverage.
>
>-    Data comes back in multiple chunks -- this will be hard to test without sending a significant number of bytes to AWS I suspect, which is likely not appropriate for unit tests.
>
>-    The state machine for streaming list https://github.com/influxdata/delorean/pull/134/files#diff-e062a137534b1fbd6b7bfdd7d4dd9b75R282. I don't have a great idea of how to test that as it depends on AWS but I have written code before that works great in the small data (aka dev environments) but then had challenges in real situations where the data is larger and there were lurking bugs we couldn't cover it with tests that only appeared sporadically
>
>I am not sure what to suggest here (I would probably suggest using the simpler, though less efficient initial implementation if we can't come up with some way to test the more efficient streaming implementation, but I realize that in some way that is the opposite of what @pauldix suggested)

**Comment by jacobmarble** [comment]
@carols10cents can this be closed?

**Comment by carols10cents** [comment]
Yes, I think this will come up if/when it turns out to be important.
