### ISSUE TITLE
feat: API endpoint to prevent writing to the Object Store

### ISSUE THREAD

**Issue by domodwyer** [influxdata/influxdb_iox#1426]
__Use case:__
Minimise server ID and therefore catalog txn log conflicts

__Proposal:__
Conductor will request an IOx node stop writing to the object store before
indirectly killing the instance - the time between requesting the instance be
terminated and it _actually stopping_ is outside of our control and may not be
directly observable.

In order to minimise the likelihood of two IOx instances using the same server
ID at the same time, Conductor will (or a variation of):

1. Send a "stop writing to the object store" request to the IOx node (this feature request)
2. Wait for an ACK
3. Request instance termination
4. Immediately provision a new instance using the same server ID

This process allows Conductor to provision a new instance immediately and
definitively know it is safe to reuse the server ID.

__Current behaviour:__
A node may write to the object store at any point

__Desired behaviour:__
Object store write permission controllable by an external actor (Conductor)

**Comment by pauldix** [comment]
Not relevant to NG (new) catalog.
