### ISSUE TITLE
feat: read-only instance mode

### ISSUE THREAD

**Issue by domodwyer** [influxdata/influxdb_iox#1427]
__Use case:__
Safely pre-load data before serving traffic

__Proposal:__
Allow a node to pre-load data before serving traffic (described below), and
allow read-only access from remote "satellite" IOx query servers that are
capable of querying data from object storage (such as a local instance on your
laptop)

In order for a hot-swap upgrade to take place, an new IOx instance must be
started and pre-loaded with data before decommissioning the node it is
replacing. During this time, there will be two instances of IOx configured with
the same server ID:

1. Request to upgrade from v1 to v2 is received by Conductor 
2. A new IOx instance is provisioned for the existing `ServerID: 1` instance
3. The new instance is instructed to pull data from the object store to pre-warm caches  
4. The old instance is terminated (see #1426)
5. The new instance is immediately configured to be `read-only: false` and it begins serving traffic

It is critical that only one instance be permitted to write to the object store
at any time.

__Current behaviour:__
Once a node is configured with a server ID, it is free to replicate / write to object store using the identifier.

__Desired behaviour:__
A node can be configured to not perform any externally visible action using the configured server ID.

__Alternatives considered:__
Only route traffic after the old node has stopped without using an explicit
read-only flag: this will work for the upgrade process described above, but
hinges on no other entity requesting a write operation during the pre-loading
phase (which is improbable but certainly possible). 

It is a dangerous configuration long term on a local laptop for the "satellite 
query server" use case.

**Comment by pauldix** [comment]
Only one other thing I'd like to note because it might impact how the code is organized. I want to be able to start an IOx server with a collection of writers IDs and have it able to download the catalogs and query across all of that data. So I want to be able to attach to many writer IDs in read-only mode, not just "my" id.
