### ISSUE TITLE
Cross-Request Aggregation

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#1473]
Currently the write path for line-protocol is as follows:

* Entire string payload is parsed into ParsedLine<_>
* The list of ParsedLine<_> are aggregated into flatbuffer Entry's per-shard
* These Entry's are then sent where they need to go

This means that every Entry originates from a single write. This means any of the following leads to very small Entry payloads:

* IOx is receiving small write payloads
* IOx is configured with a large number of shards
* IOx is writing to something that mandates further sharding/partitioning (e.g. Kafka / Kinesis)

This has a severely detrimental impact on throughput should it occur.

An alternative approach would be to parse the data into lines of line protocol, and put these into per-destination queues. When a given queue reaches a certain size threshold, or a timeout expires, the contained data would be parceled up and written out. I have previously written an implementation of this concept [here](https://github.com/tustvold/rust-playground/blob/master/lib/stream/src/batch.rs).

In order to avoid interfering with the ongoing work on the write buffer, the proposed write-path would be as follows:

* Parse lines to some owning data structure
* Group the lines based on their destination shard
* For each shard group
    * If the destination shard is a remote IOx node - compute Entry and continue as before
    * If the destination shard is the local IOx node - compute Entry and continue as before (might be changed by #1472)
    * If the destination shard is not an IOx node - dump lines onto queue

Effectively this would allow non IOx shards to experiment with doing cross-request aggregation, and in future may allow us to do the same for IOx shards if we so wished

**Comment by alamb** [comment]
I wonder how "when to acknowledge the write" would work in this situation? Would the write be held until the batch was written?

I also wonder about error handling. Say if we batched up three writes from different writers; When we decided to process the batch, the first succeeds, the middle one fails, what would we do with the third write? Would we try it anyways?

**Comment by tustvold** [comment]
> I wonder how "when to acknowledge the write" would work in this situation? Would the write be held until the batch was written?

Yes. There are many ways to implement this, the most basic being a oneshot, a more sophisticated version using a Notified would also be possible.

> I also wonder about error handling. Say if we batched up three writes from different writers; When we decided to process the batch, the first succeeds, the middle one fails, what would we do with the third write? Would we try it anyways?

We have the same issue with sharding already, I understand that partial failures are permissible

> Until we observe this being a significant problem in our traces / metrics, I would personally put this into the "it might be premature optimization" category, but I may not have the whole story

Being able to do this is a requirement for writing to kafka or kinesis, which I'm working on as hobby project, as the writes have to be split on the full tagset for load distribution across the brokers/shards, but then you need to perform batching to get any reasonable amount of throughput per Kafka partition / Kinesis shard.

**Comment by tustvold** [comment]
> I wonder if you could batch prior to the write -- so rather than batching the actual write, buffer stuff from kinesis / kafka prior to sending it down the write path?

I'm not sure I follow? What is the write path you are referring to here?

**Comment by alamb** [comment]
Thank you -- this description of what you are thinking now makes sense to me. I would phrase it as "making it easier to add new ways to get data in to and get data out of the ingest path. 👍

**Comment by mkmik** [comment]
If N writes get grouped into one larger batch, the three original requests must block until the batch is acknowledged and we'll return an error to all N clients if the downstream batch write fails

**Comment by jacobmarble** [comment]
@tustvold is this issue still valid?

**Comment by crepererum** [comment]
I think so.

**Comment by tustvold** [comment]
@jacobmarble Some of the content is somewhat out-dated by the work under #2724 and friends, but the core proposal to decouple the batching within the write buffer from how the user decides to batch data is likely still important. The experiments by Francesco and @mkmik showed that Kafka is sensitive to message size, and so having the ability to control this may become relevant

**Comment by tustvold** [comment]
This has now been implemented using the functionality added to rskafka
