### ISSUE TITLE
Cache parquet files in object store into local disk

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#1491]
__Use case:__
Memory is usually used for MUB and RUB to store ingesting and the most recent data. In situation when not-too-recent data that is only available in object store is queried a lot but we do not have enough memory to bring them back in, we want those files are cached in local disk to increase the reading performance

__Proposal:__
Introducing a new state: ObjectStoreAndLocalDisk
TBD: where this new state in our life cycle

__Context__
Here is a document about file system assumptions that we wrote up at some point https://docs.google.com/document/d/1Gd0cjyNGb08CjStr0Y4Pm8_2NNbNa80UVZqn0VuxFGg/edit

**Comment by NGA-TRAN** [comment]
Send this to @crepererum as he will have a write-up about the new state machine setup that includes this work

**Comment by alamb** [comment]
I talked to @crepererum  this morning and I am going to give this a shot next. I plan to write up a doc and circulate it first

**Comment by alamb** [comment]
I took the content in this ticket and updated to reflect the current state of the system in https://github.com/influxdata/idpe/issues/17839 so I think this issue is now superceded. Closing.
