### ISSUE TITLE
test: chunk::tests::test_snapshot fails

### ISSUE THREAD

**Issue by domodwyer** [influxdata/influxdb_iox#1496]
Running `cargo test --all-features --workspace --lib --bins --examples --tests` on main (d98d66e7186441645442439cc33ec9fa92b8bb1f) fails:

```
---- chunk::tests::test_snapshot stdout ----
thread 'chunk::tests::test_snapshot' panicked at 'assertion failed: `(left == right)`
  left: `0x7ff5fe305500`,
 right: `0x7ff5fe306890`', mutable_buffer/src/chunk.rs:336:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    chunk::tests::test_snapshot
```

This failure seems to be deterministic (4/4 tests). 

Running macOS 11.3.1 with `rustc 1.51.0 (2fd73fabe 2021-03-23)`

**Comment by carols10cents** [comment]
The [assertion that's failing](https://github.com/influxdata/influxdb_iox/blob/d98d66e7186441645442439cc33ec9fa92b8bb1f/mutable_buffer/src/chunk.rs#L336) is checking that 2 `Arc`s returned from `chunk.snapshot()` are the same.

[There are 2 versions of `chunk.snapshot()`](https://github.com/influxdata/influxdb_iox/blob/d98d66e7186441645442439cc33ec9fa92b8bb1f/mutable_buffer/src/chunk.rs#L134-L152) that behave differently whether the `nocache` feature is on or off.

[The `nocache` feature is off by default](https://github.com/influxdata/influxdb_iox/blob/d98d66e7186441645442439cc33ec9fa92b8bb1f/mutable_buffer/Cargo.toml#L36-L39), but you're running `cargo test --all-features`. The `nocache` version of the function is always returning `Arc::new`.

I'm not sure if this test is expected to pass whether `nocache` is on or off (which would mean the code has a bug) or if this test is only expected to pass when `nocache` is off (which would mean this test should have `#[cfg(not(feature = "nocache"))]` on it.

**Comment by carols10cents** [comment]
Relevant commits:

- [Addition of snapshot caching and this test](https://github.com/influxdata/influxdb_iox/commit/55a77914b1dfd9ff4ff61093f4eaa5b082029db1)
- [Addition of the `nocache` feature](https://github.com/influxdata/influxdb_iox/commit/1cf3ab39781a2e3340dc81a76eb9ee37dd6640ce)

cc @tustvold

**Comment by tustvold** [comment]
Aah, we should probably disable the test when nocache is enabled. It's a test that caching is working correctly, so if caching is disabled it's going to fail 😂

Will fix, thanks @carols10cents for identifying
