### ISSUE TITLE
Preserved Catalog: do NOT parse paths

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#1506]
As of #1482 we decode writer ID, db name, table name, partition key, and chunk ID from the file paths. We should instead include them in the catalog as well as in the parquet file metadata (for #1376 ). The catalog should pass all this information to the `CatalogState` implementation, so the latter one should have no need to assume any path semantics.

# ACs:

- `CatalogState` implementation does not need to look at the path (it's just an opaque pointer)
- `Storage::parse_location` is gone
- the preserved catalog already does the conversion from "dirs and filename" to the store-native path (so the `CatalogState` does not need to do that)
- The path of the parquet file can be changed (with appropriate catalog pointer updates) and the contents will still be acceptable.

**Comment by crepererum** [comment]
Keep #1507 in mind while implementing this!

**Comment by alamb** [comment]
I suggest an acceptance criteria of "The path of the parquet file can be changed (with appropriate catalog pointer updates) and the contents will still be acceptable"
