### ISSUE TITLE
Separate persistences state from different types of caching in chunk lifecycle state machine

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#1513]
# Chunk Lifecycle -- State Machine Simplification
This proposes a simplification of our chunk state machine while allowing powerful future extensions.

## Stages
There shall be the following stages:

- **Open:** A chunk can receive new data. It is not persisted
- **Frozen:** A chunk cannot receive new data. It is not persisted
- **Persisted:** A chunk cannot receive new data. It is persisted.

Note that the stage say nothing about the representation of data (e.g. _frozen_ can be represented using the `MutableBuffer` as well as the `ReadBuffer`) or caching (e.g. _persisted_ can be in object store only, on local disk, in memory using a `ReadBuffer`, ...). Also note there is no "can receive data, is persisted" state.

## Stage Transitions
A chunk is in exactly one stage. The stage transition is:

```text
open => frozen => persisted
```

The _persisted_ state is the only one that can be recovered on node startup (from the persisted catalog). A chunk can be _in-transit_ when there is a job that moves it from the stage to the next. There can only be a single job per chunk. The chunk stage is considered unchanged as long as the job is running and is atomatically changed when the job finishes.

## Chunk Representation
Within a single stage a chunk can have multiple representations. E.g. (up for future extension!):

- **Open:** `MutableBuffer`, optionally on top:
  -  query caching
- **Frozen:** One of:
  - `MutableBuffer`
  - `ReadBuffer`
- **Persisted:** There is at least the pointer to the blob store. Additionally there might be:
  - `ReadBuffer` (in-memory cache)
  - local on-disk parquet file

Note that the chunk representation does nothing to the stage transitions, e.g. a chunk can move from _frozen_ to _persisted_ no matter if it is represented via a `MutableBuffer` or `ReadBuffer`.

## Representation Changes
Representations (within the same stage) can change using caching and memory optimization rules, e.g.:

- A _frozen_ chunk should likely be moved from `MutableBuffer` to `ReadBuffer` rather swiftly.
- A _persisted_ that after node startup is only available via object store might be cached on local disk, then using a `ReadBuffer` and after memory pressure builds up and the chunk is not queried often the `ReadBuffer` might be dropped again.

When a representation change happens, a job will be created. Similar to the stage transitions, the change is considered done when the job is finished. An representation change blocks a stage transition (for technically simplicity, this restriction might be lifted in the future).

## Intra-stage Lifecycle Rules
There is at least one lifecycle rule (= soft buffer limit) that interacts with multiple stages at the same time. These rules should not look at the chunk representation but should rather use high-level interfaces. For the soft buffer limit, this can look like this:

```rust
/// !!! This is unfinished pseudo-code to illustrate the design idea !!!

trait Chunk {
    /// Checks if there is some job running (either stage transition or representation change)
    fn has_active_job() -> bool;

    /// Reports RAM usage in bytes.
    fn ram_size() -> usize;

    /// Drop cached data, subsequent queries might be slower.
    ///
    /// Returns `true` if a job was started that will result in changed chunk representation.
    fn drop_cache() -> bool;

    /// Drop data permanently. Cannot be recovered.
    ///
    /// Returns `true` if a job was started that will result in changed chunk representation.
    fn drop_data() -> bool;
}

fn lifecycle_step() {
    let mut usage = tracked_ram_usage();

    if usage <= limit {
        // nothing to do
        return;
    }

    for chunk in chunks.iter_reversed_query_lru() {
        // get lock to modify the chunk so there is no race-condition in job handling
        let chunk  = chunk.writer();

        if chunk.has_active_job() {
            // cannot touch that chunk at the moment
            continue;
        }

        let candidate_size = chunk.ram_size();
        if chunk.drop_cache() {
            // assume we can free that memory
            usage -= candidate_size;
        }

        if usage <= limit {
            // good enough for now
            return;
        }
    }

   // cannot free enough memory be clearing caches => start dropping data

    for chunk in chunks.iter_in_revered_age() {
        // get lock to modify the chunk so there is no race-condition in job handling
        let chunk  = chunk.writer();

        if chunk.has_active_job() {
            // cannot touch that chunk at the moment
            continue;
        }

        let candidate_size = chunk.ram_size();
        if chunk.drop_data() {
            // assume we can free that memory
            usage -= candidate_size;
        }

        if usage <= limit {
            // good enough for now
            return;
        }
    }
}
```

**Comment by crepererum** [comment]
Opinion? @tustvold @NGA-TRAN @alamb

**Comment by tustvold** [comment]
LGTM :+1:

**Comment by NGA-TRAN** [comment]
> Note that the chunk representation does nothing to the stage transitions, e.g. a chunk can move from frozen to persisted no matter if it is represented via a MutableBuffer or ReadBuffer.

In theory this is correct but for simplification and optimization, I think we should only persist RUB chunk

**Comment by NGA-TRAN** [comment]
The pseudo code looks good but I think it will be more complicated when you start implementing it. I think we might need to think about caching policy (e.g last recent read) because we want to cache data before user actually need it

**Comment by crepererum** [comment]
> The pseudo code looks good but I think it will be more complicated when you start implementing it. I think we might need to think about caching policy (e.g last recent read) because we want to cache data before user actually need it

:+1: I imagine we have some other life-cycle "background loop" that looks at usage statistics and starts "load into cache" jobs.

**Comment by alamb** [comment]
Overall this sounds like exactly what we talked about -- thank you @crepererum  for writing it up. My feeling is that we will one place where lifecycle rules are implemented (rather than one that handles persistence and one that handles caching) but I think that is an implementation decision we can let be guided by the code

To summarize I also think this is ready to code up 👍
