### ISSUE TITLE
Improve Catalog::size performance (probably by caching) 

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#1561]
__Use case:__
Make IOx more cpu efficient by not doing redundant work. 

I noticed while looking at a flamegraph that a non trivial amount of time (10% of the overall time) goes to calculating `ChunkSize` for read buffer and mutable buffer chunks: 
![Screen Shot 2021-05-26 at 11 45 10 AM](https://user-images.githubusercontent.com/490673/119690782-fd696480-be17-11eb-9983-57160762786c.png)

Looking at the stack you can see the LifeCycle manager is getting the size of a chunk frequently but that call is doing non trivial work. 

Given the read buffer is immutable, we should not have to calculate this each time. 

I was looking at the flamegraph (thanks @mkmik !) from our internal systems,  by forwarding 8080 to localhost 1235 and then visiting  http://localhost:1235/debug/pprof/profile?seconds=30

Open [profile_iox_30s.xml.zip](https://github.com/influxdata/influxdb_iox/files/6547999/profile_iox_30s.xml.zip) in the browser and check out `profile_iox_30s.xml?x=360&y=1317`

__Proposal:__
Cache chunk stats (size, rows) in catalog Chunk

__Current behaviour:__
Calculated on demand

__Desired behaviour:__
Calculated only when needed

__Alternatives considered:__
Could cache elsewhere

**Comment by tustvold** [comment]
This is already cached on the local GaugeValue - it could theoretically just fetch it with `GaugeValue::get_local`

**Comment by alamb** [comment]
@e-dard  rightly asked "how much CPU was being used" -- and the answer appears to be between 1 and 2 CPU cores:

![Screen Shot 2021-05-26 at 12 08 58 PM](https://user-images.githubusercontent.com/490673/119694387-2d663700-be1b-11eb-865c-1a8f24507445.png)

**Comment by e-dard** [comment]
@alamb I don't think this is using much CPU but I can fix it up as part of the refactor to make a chunk per single-table.

**Comment by alamb** [comment]
@e-dard  note it applies to the MutableBuffer chunk too (not just ReadBuffer). So it might make sense cache the calculation at a higher level than the ReadBuffer (aka in the catalog)

**Comment by tustvold** [comment]
I should maybe mention that the lifecycle manager doesn't actually need to call this method anymore - this dates from before the GaugeValue's were hooked up. It should be able to just use the totals

**Comment by alamb** [comment]
What I would really love to see is this kind of information pulled from `ChunkStats` or `TableStats` and then those particular structures cached on the Chunk.

**Comment by mkmik** [comment]
![image](https://user-images.githubusercontent.com/52673/120302219-f639cf00-c2cd-11eb-8abc-ec3f1840132a.png)

now most of the time is spent doing something useful like loading data in the read buffer, etc

Closed by #1586
