### ISSUE TITLE
Complete parquet statistics extraction

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#1576]
This is mostly a reminder for myself to get [this branch](https://github.com/influxdata/influxdb_iox/tree/crepererum/more_parquet_stats_work) merged. It was mostly blocked on upstream bugs that are now fixed. While doing so also investigate why the unique count seems to be never set as discussed [here](https://github.com/influxdata/influxdb_iox/pull/1568#discussion_r641326066).

**Comment by nevi-me** [comment]
> While doing so also investigate why the unique count seems to be never set as discussed [here](https://github.com/influxdata/influxdb_iox/pull/1568#discussion_r641326066).

@crepererum this might not be unique to just Rust, as I think most implementations never write the unique count (at least pyarrow doesn't, and I can't recall seeing it from pyspark)

**Comment by crepererum** [comment]
@nevi-me thanks for the insight. I'll see if I find the time then to at least have this optionally written by the Rust implementation (since it requires additional computation during Parquet write).

**Comment by alamb** [comment]
If you plan to work on distinct count, I think another common problem is with columns of high cardinality (aka large number of distinct counts) as you can consume large amounts of RAM if you use something like a HashSet -- often times it may be good to cap the size of this set and bail out of too many distinct values are seen

**Comment by crepererum** [comment]
@alamb Unique count moved to #1712 since that's currently not a prio.
