### ISSUE TITLE
Incorrect results with integer predicate on floating point column

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#1603]
__Steps to reproduce:__
Note this test case is on the [alamb/read_with_predicate_failure](https://github.com/influxdata/influxdb_iox/tree/alamb/read_with_predicate_failure)  branch

Load Input line protocol (first two rows in 1 chunk, last row in a different RB chunk)
```
cpu bar=1 10
cpu bar=2 20
cpu bar=3 10
```

__Expected behaviour:__

```sql
select * from cpu where bar < 3
```
IOx returns the correct answer
```
"+-----+-------------------------------+",
"| bar | time                          |",
"+-----+-------------------------------+",
"| 1   | 1970-01-01 00:00:00.000000010 |",
"| 2   | 1970-01-01 00:00:00.000000020 |",
"+-----+-------------------------------+",
```

__Actual behaviour:__

IOx returns the wrong answer (no rows):
```
recom
"++",
"++",
```

__Note__

Note that when the constant is expressed as `3.0` the query results are correct:

```
select * from cpu where bar < 3.0
```

```
"+-----+-------------------------------+",
"| bar | time                          |",
"+-----+-------------------------------+",
"| 1   | 1970-01-01 00:00:00.000000010 |",
"| 2   | 1970-01-01 00:00:00.000000020 |",
"+-----+-------------------------------+",
```

**Comment by alamb** [comment]
@e-dard  notes that this may be due to trying to compare floats / integers directly in the read buffer  --  no values pass the predicate because currently floats and integers are not comparable in the read buffer

some options are:
1. add support for that type of comparison in the read buffer 
2. validate expressions against a schema at a higher level and not push down expressions that aren’t going to work.

**Comment by e-dard** [comment]
I have some thoughts about how I want to add support for comparing floats to integers in the Read Buffer but I don't think I will be able to get to that until next week. If you want to fix this in the mean time then one option would be to check predicates against Chunk schemas and only push down expressions that have exactly the same type as the column.

**Comment by alamb** [comment]
Thanks @e-dard  -- I likely also won't get to this this week. Given https://github.com/influxdata/influxdb_iox/pull/1612 this may not as high a priority (generating a unsupported error is much less bad in my opinion than generating wrong answers)

**Comment by alamb** [comment]
I am pretty sure #2631  doesn't fix this issue and github got over zealous reading the comment
