### ISSUE TITLE
UUIDv4 in parquet file names

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#1623]
# Abstract
Include an UUIDv4 in our parquet file names.

# Reasoning
Currently object store cleanups need to hold catalog transaction locks during IO operations. This cannot be avoid due to
the following issue: Imagine there was a once a server that wrote a chunk for a table. Then the catalog was wiped, or
the transaction that should have added the file in question to the catalog was aborted (e.g. due to a crash). Now a new
IOx node (same serverID, same table, same chunk) should write this data again:

| Step | Thread 1 (write chunk to OS)    | Thread 2 (cleanup)                        |
| ---- | ------------------------------- | ----------------------------------------- |
| 1    |                                 | scan store, descovers file                |
| 2    |                                 | get transaction lock                      |
| 3    |                                 | scans catalog, marks file as unreferenced |
| 4    |                                 | release transaction lock                  |
| 5    | get transaction lock            |                                           |
| 6    | overwrite existing file         |                                           |
| 7    |                                 | deletes file                              |
| 8    | adds (now gone) file to catalog |                                           |
| 9    | release transaction lock        |                                           |

If we would have UUIDs as part of the file naming, then the file from the old IOx instance (discovered in step 1 and
marked as unreferenced in step 3) would be a different one than the file written by the new IOx instance (written in
step 6, added to the catalog in step 8).

# Prior Art
- our catalog uses UUIDs for transaction and checkpoint files
- IIRC other catalog solutions also encourage UUIDs for payload files

**Comment by mkmik** [comment]
sounds reasonable to me.

what are the downsides?

**Comment by crepererum** [comment]
> what are the downsides?

Longer filenames, but I think that's OK.

**Comment by alamb** [comment]
Ah, i see -- thank you @crepererum  the clear description of the problem. This is a tricky situation indeed. 

The only downside I can see to this solution is that the file names get larger and thus are
1. harder to deal with without scripts
2. get closer to the object store path length limits

Another potential solution might be for the cleanup script to "register" the set of files it was going to delete with the catalog which could then delay / prevent any new transaction that would write to one of the registered files.

Just adding a UUID to the file name to avoid conflicts sounds like a simpler solution to me, however; Given this situation is (hopefully) very rare going for simpler is better in my opinion

**Comment by NGA-TRAN** [comment]
This is a great early discovery and this happened to Vertica.

**Comment by pauldix** [comment]
What is the current filename? Given the updates that @tustvold and I are making to the lifecycle, I'm wondering if we even need chunk IDs to be increasing ints. They could just be UUIDs. The metadata in the Parquet file and the Catalog will contain the information about what the min & max sequence number is for the data contained in the file.

**Comment by alamb** [comment]
Chunk ids as UUID would be 👍  in my mind

**Comment by tustvold** [comment]
Chunks may have overlapping min/max sequence numbers, we favour creating chunks with non-overlapping time ranges at the expense of this. Sequence numbers alone therefore cannot establish an unambiguous ordering of persisted chunks.

That being said the unambiguous ordering doesn't have to be established by chunk IDs, provided there is some monotonic number somewhere in the metadata or path name.

**Comment by alamb** [comment]
Metadata sounds like a good idea to me
