### ISSUE TITLE
bug: chunks are removed from parquet when memory budget is full

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#1674]
Otherwise known as the case of the mysteriously disappearing parquet files 🕵️ 

__Steps to reproduce:__
Configure a database thusly (as our internal `istio` databases is):
```
{
  "rules": {
    "name": "844910ece80be8bc_64881f0f8fd1653c",
    "partitionTemplate": {
      "parts": [
        {
          "time": "%Y-%m-%d %H:00:00"
        }
      ]
    },
    "lifecycleRules": {
      "mutableLingerSeconds": 30,
      "mutableMinimumAgeSeconds": 0,
      "mutableSizeThreshold": "10485760",
      "bufferSizeSoft": "1073741824",
      "bufferSizeHard": "2147483648",
      "sortOrder": {
        "order": "ORDER_ASC",
        "createdAtTime": {
        
        }
      },
      "dropNonPersisted": true,
      "immutable": false,
      "persist": true,
      "workerBackoffMillis": "100"
    },
    "workerCleanupAvgSleep": "500s",
    "writeBufferConnectionString": ""
  }
}
```

Note:
```
      "persist": true,
```

__Expected behaviour:__
Chunks are moved to object storage,  removed from memory when the memory budget is full, but  left on object storage

__Actual behaviour:__
Chunks are moved to object storage, and then promptly removed from both memory **and** object storage

You can see this by looking at the steady state of this database:

```
844910ece80be8bc_64881f0f8fd1653c>      select table_name, storage, sum(estimated_bytes) as total_bytes, sum(row_count) as total_rows, count(*) as num_chunks from system.chunks where table_name = 'istio_request_bytes' group by table_name, storage order by num_chunks desc limit 10;
+---------------------+--------------------------+-------------+------------+------------+
| table_name          | storage                  | total_bytes | total_rows | num_chunks |
+---------------------+--------------------------+-------------+------------+------------+
| istio_request_bytes | ReadBufferAndObjectStore | 66566510    | 716663     | 23         |
| istio_request_bytes | OpenMutableBuffer        | 9194164     | 29330      | 1          |
| istio_request_bytes | ReadBuffer               | 3078436     | 33310      | 1          |
+---------------------+--------------------------+-------------+------------+------------+
```

Note there are no chunks in the `ObjectStoreOnly` state

**Comment by alamb** [comment]
I believe the issue is in [`lifecycle.rs`](https://github.com/influxdata/influxdb_iox/blob/47c7c38131c37253051853a9b20e5b68ac0786b1/server/src/db/lifecycle.rs#L232) where it uses "drop" rather than "clear from memory"

**Comment by crepererum** [comment]
> I believe the issue is in lifecycle.rs where it uses "drop" rather than "clear from memory"

That sounds about right. Side note: `drop` is currently not wired up into the persisted catalog, i.e. it will likely delete the parquet file (which it actually shouldn't) but will not inform the persisted catalog that the file was removed. We should probably fix this soonish.
