### ISSUE TITLE
Collect key columns from different chunks if they are different

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#1682]
# Rationale
As part of #600, Deduplicate data at read time, we need to primary key to deduplicate the data of input chunks. However, each chunk may contain data different columns even the key columns. Hence, the function chunk.summary().primary_key_columns() return only keys of that chunk. We need to get all unique key columns from all chunks. After full key set is collected, it need to integrated in this[ key_summaries code ](https://github.com/influxdata/influxdb_iox/blob/1c7b13f0a5b2d583cc613800313af219ce05f357/query/src/provider.rs#L491)

Update on 2021/06/11: As discovered in #1703, all the column info from all chunks is already merged into [self.arrow_schema()](https://github.com/influxdata/influxdb_iox/blob/1c7b13f0a5b2d583cc613800313af219ce05f357/query/src/provider.rs#L241) so I think the work needed for this ticket is very minimal and, likely,resue the results from #1683

**Comment by alamb** [comment]
I think this and #1683  are so closely related it does not make sense to track them individually, so closing this one and will update #1683
