### ISSUE TITLE
Add all key columns of input chunks down to the scan node

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#1683]
# Rationale 
Currently, our scan node only reads columns that are needed by the query. As part of #600 to deduplicate data during read time, we need to read data of all key columns of all input chunks. Make sure thi[s scan_schema](https://github.com/influxdata/influxdb_iox/blob/1c7b13f0a5b2d583cc613800313af219ce05f357/query/src/provider.rs#L241) includes all those key columns

Update on 2021/06/11: As discovered in #1703, all the column info from all chunks is already merged into [self.arrow_schema()](https://github.com/influxdata/influxdb_iox/blob/1c7b13f0a5b2d583cc613800313af219ce05f357/query/src/provider.rs#L241) so I think the work needed for this ticket is, likely, inside this function [project_schema](https://github.com/influxdata/influxdb_iox/blob/1c7b13f0a5b2d583cc613800313af219ce05f357/query/src/util.rs#L33) ,  we also add key columns in the return list.

**Comment by alamb** [comment]
The basic problem is when chunks contain different subsets of the tag columns but need to be deduplicated

```
       ┌────────────────────────┐
       │SortPreservingMergeExec │
       └────────────────────────┘
                    ▲
                    │
                    │
       ┌────────────────────────┐
       │       UnionExec        │
       └────────────────────────┘
                    ▲           ◀ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─
                    │                                      │
         ┌──────────┴──────────┐
         │                     │                           │
         │                     │                 The  issue if these
┌────────────────┐    ┌────────────────┐        outputs don't have the
│    SortExec    │    │    SortExec    │             same schema
│   (optional)   │    │   (optional)   │
└────────────────┘    └────────────────┘
         ▲                     ▲
         │                     │
         │                     │
┌────────────────┐    ┌─────────────────┐
│    Chunk 1     │    │     Chunk 2     │
│  (tag1, tag2)  │    │  (tag1, tag3)   │
└────────────────┘    └─────────────────┘
```

My basic plan is:

```
       ┌────────────────────────┐
       │SortPreservingMergeExec │
       └────────────────────────┘
                    ▲
                    │
       ┌────────────────────────┐
       │       UnionExec        │
       └────────────────────────┘
                    ▲
         ┌──────────┴──────────┐
         │                     │
┌ ─ ─ ─ ─ ─ ─ ─ ─     ┌ ─ ─ ─ ─ ─ ─ ─ ─
  SchemaAdapter  │      SchemaAdapter  │
│  (adds nulls        │  (adds nulls       ◀ ─ ─ ─ ─ ─ ─ ─ ┐
    for tag3)    │        for tag2)    │
└ ─ ─ ─ ─ ─ ─ ─ ─     └ ─ ─ ─ ─ ─ ─ ─ ─                    │
         ▲                     ▲
         │                     │                           │
         │                     │
┌────────────────┐    ┌────────────────┐         Add in adapter nodes
│    SortExec    │    │    SortExec    │         to fixup the schema
│   (optional)   │    │   (optional)   │
└────────────────┘    └────────────────┘
         ▲                     ▲
         │                     │
         │                     │
┌────────────────┐    ┌─────────────────┐
│    Chunk 1     │    │     Chunk 2     │
│  (tag1, tag2)  │    │  (tag1, tag3)   │
└────────────────┘    └─────────────────┘
```

In order to implement this plan, I plan a sequence of PRs as follows:

- [ ] Always use `Schema` rather than `ArrowSchema` in planner
- [ ] Implement deduplication detection in terms of `Schema` rather than `TableSummary` (so I can reuse merging logic)
- [ ] Create a SchemaAdapter physical plan node for use in planning
- [ ] Insert SchemaAdapter physical plan nodes into scan plans when needed, and update tests
