### ISSUE TITLE
Better Panic Handling

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#1694]
Spawned out of a series of discussions with @alamb around the current pain points of error handling in IOx.

Within Rust there are two major mechanisms for bailing out if something has gone wrong, [Result](https://doc.rust-lang.org/std/result/) and panic. 

This is often portrayed as a binary choice, but perhaps it is more reasonable to consider them complementary techniques. For one thing you cannot not use panic, it's baked into the language.

I'm personally a fan of the distinction drawn up [here](https://blog.rust-lang.org/2016/05/26/Rust-1.9.html#controlled-unwinding) - `Result` is for predictable error scenarios that are expected in standard operation, normally due to bad user input, whereas panic is indicative of a bug. Or to put it another way, Result is for control flow and panic for debug.

# Pain Points

Currently within IOx we tend to avoid panic and favour error enumerations, and this causes some pain points

## Impossible Code Paths

It is fairly common to come across error propagation code that could never be encountered in the absence of a bug. 

For example, the catalog chunk has an error enumeration for when its state doesn't match what was expected for the given transition. However, the callers always check the state, perform the necessary work to convert the data, and then call the method to transition the state. If this function ever returned an error it would be a bug. There is therefore limited value gained from making this function fallible, over just documenting the invariant and panicking if is violated.

Other similar examples might be encountering an error building an arrow schema for a chunk, or creating a record batch from a set of columns, neither of which should be possible by construction.

## Error Agnostic Code Paths

A number of code paths within IOx are what I'm going to call error agnostic, that is, they have no mechanism to recover from an erroneous situation, and will just print any encountered error to stderr and return. 

Most background tasks fall into this category - if say a compaction job fails, not only is this almost certainly a bug, but all that is going to happen is it is going to get logged to stderr. 

I'd imagine query execution to also likely fall into this category, if the query encounters an IO error reading a parquet file, or encounters some invalid dictionary index, it is just going to abort and return this error to the user. Having additional plumbing to represent all the possible failure scenarios as separate enumerations, only to just serialize them blindly, is not adding a great deal

## Error Cardinality

One of the great strengths of the Result pattern is to be able to concisely express the expected fallibility of an API. This makes it easy for callers to determine what error scenarios they may need to handle. However, doing this effectively involves keeping the number of variants low, which is at odds with providing the maximum amount of context of where the particular error was encountered. The style guide in fact actively encourages favouring the latter, resulting in large error enumerations that in many cases do little more than build up a stacktrace manually.

# Proposal

The proposal is to improve the support for using panic within IOx, to not only allow it to be used for unexpected error scenarios within IOx, but also improve the situation where something external like DataFusion panics.

## Panic Hook

I think we may already have this, but we should verify it is setup correctly. It should do the following:

* Log a tokio-tracing `error!`
* Print the backtrace

The separate tokio-tracing log is to print context provided by any enclosing [spans](https://docs.rs/tracing/0.1.26/tracing/#spans). For example, these might encode the name of the database, HTTP request id, etc... As these are controlled by the standard tokio-tracing verbosity and filtering plumbing, the detail can be dynamically increased whilst debugging an issue, at the cost of a performance hit.

## User Response

Currently if a request causes a panic, the connection/stream is just dropped, resulting in errors like the below in the client

```
Error getting database: Unexpected server error: The operation was cancelled: h2 protocol error: protocol error: stream no longer needed
```

Ideally we would like the panic message to be sent back to the client as an error. Aside from giving better user UX, this would also aid finding the corresponding logs.

There might be better approaches, but the simplest mechanism to handle this would be to spawn panic-able code to a tokio task, and inspect the returned [JoinError](https://docs.rs/tokio/1.6.1/tokio/task/struct.JoinError.html#method.try_into_panic). 

## Panic Propagation

Related to the above, but spawning a `tokio::task` and never inspecting its `JoinHandle` can cause you to miss an error. In some cases this will still result in an error sent to a client, but if say you spawn a task that writes to a stream and that task panics, you may just think the stream has finished and return truncated data to the client. To be clear, this is a bug whether we use panics within IOx, but is worth highlighting.

## Inconsistent State

If an atomic operation on shared mutable state panics, it may leave this data in an inconsistent intermediate state. 

To give an example:

```
let foo = Mutex::new((0,0));

{
    let mut locked = foo.lock();
    locked.0 += 1;
    maybe_panic();
    locked.1 += 1;
}

```

After this it would be possible to observe the two different values in the mutex, despite them always being mutated under a lock as a supposedly single atomic operation.

Mutexes in the standard library have a concept called poisoning where subsequent locks acquisitions are prevented if they have observed a panic. This is a valid, but very pessimistic approach - `parking_lot` locks and locks in other languages with stack unwinding (C++, Go, Java, etc...) accept the risk.

There are a couple of reasons I'm inclined to think this is fine:

1. `Result` doesn't really solve this problem, without additional code to back out the change. The below code is "wrong"

```
{
    let mut locked = foo.lock();
    locked.0 += 1;
    fallible()?;
    locked.1 += 1;
}
```

2. We can and should minimize the amount of work that takes place under write locks by using Arc, upgrade-able locks, etc...
3. Safe code should still be [exception safe](https://doc.rust-lang.org/nomicon/exception-safety.html) anyway

**Comment by crepererum** [comment]
Overall I very much welcome your observation. A couple of notes:

> Most background tasks fall into this category - if say a compaction job fails, not only is this almost certainly a bug, but all that is going to happen is it is going to get logged to stderr.

I would be a bit more careful here. There are errors that are predicable (e.g. IO errors) but for which we still don't have a good way to react immediately (we can still retry the background task, log the error and increase some error counter metric for visibility).

> If an atomic operation on shared mutable state panics, it may leave this data in an inconsistent intermediate state.

Only if you either:

- [catch the panic](https://doc.rust-lang.org/std/panic/fn.catch_unwind.html) (which IMHO we must never do)
- use the broken state during unwinding (i.e. in `Drop`, directly or indirectly)

> There are a couple of reasons I'm inclined to think this is fine...

Then the question is: what to do? IMHO, there are the following ways:

- static analysis (didn't research the options so far)
- humans during code/PR review
- tests (e.g. test the error cases as well, including that the data structure is usable after failing)

> Error Cardinality

I also think that the big catch-them-all error structs at the top of every module are wrong. They mix error cases that usually have nothing to do with each other. E.g. creating a DB and persisting to OS have very different error cases, but `Server` still only has a single fused error type for these. This makes handling and reporting harder. On top, we often just bubble errors w/o adding any important information. E.g.:

```rust
fn do_io(...) -> Result<()> {...}

fn create_db() -> Result<()> {
    ...
    do_io(...)?;   // we should add more data here!
    ...
}
```

**Comment by alamb** [comment]
This is how I read your analysis and proposal (sorry for the brutal summarization):

# Problem:
1. Today when `panic!` occurs (due to a bug in IOx or DF or whatever), IOx often does not return the equivalent of 500 / something went wrong to the client, it just stops doing whatever it was doing.
2. In code which returns `Result`  it is often not clear what errors (if any) are expected to occur in normal operation.

# Proposal:
1. Improve `panic` handling so that the client gets a better indication that something internal went wrong
2. Be more liberal with `panic` / `unwrap` etc for conditions that can only occur due to a bug rather than large Error enumerations

If this is a correct (if incomplete) summary I am all onboard 👍

**Comment by tustvold** [comment]
@alamb Pretty much, but I wanted to provide a bit more context :grin: 

There is a 3rd item to the proposal though, which is that we don't expect panic to bring down the process and we accept that this makes writing exception-safe code more important than if say panic always triggers abort (which it currently doesn't).

**Comment by crepererum** [comment]
> >  catch the panic (which IMHO we must never do)
>
> But this is precisely what I'm suggesting doing - not treating panics as fatal abort the entire process errors. And instead catching and logging them?

I'm against it for two reasons:

1. catching panics doesn't always work, see https://doc.rust-lang.org/std/panic/fn.catch_unwind.html#notes Most notably panic while panic (e.g. due to `Drop`) will always lead to an abort and cannot be caught. So this whole thing gives you a false sense of security.
2. programming in a generic panic/unwind-safe way is WAY harder than being error-safe. The beauty of Rusts result handling is that you can -- in contrast to C++ -- see every failure point just by looking at functions. That gives every programmer and reviewer a way to see where a function might just exit (either by `return` or by `?`) and check invariants quickly (e.g. that states are not partially modified). With `panic` this is not possible, since literally everything you do can panic, and even things you don't do (e.g. `Drop` which is a somewhat hidden operation). That makes unwind-safe programming a nightmare and has already led to many bugs in std.
3. In contrast to errors, panics are really hard to inspect and react. There is a difference between a slight bug that you might wanna catch and ignore or a "oh my god my memory allocator is on fire".

**Comment by crepererum** [comment]
However: all of the above points would be OKish / acceptable if we only wanna use `catch_unwind` to send 500 errors to every client and then quit as quickly as possible. However since I think (I however might be wrong here) that panic will also ruin tokio, you won't have any way to react to it because ... well, how? Writing to sockets directly?

**Comment by tustvold** [comment]
> However: all of the above points would be OKish / acceptable if we only wanna use catch_unwind to send 500 errors to every client and then quit as quickly as possible. However since I think (I however might be wrong here) that panic will also ruin tokio, you won't have any way to react to it because ... well, how? Writing to sockets directly?

Tokio by default adds catch_unwind to all worker pools, what I describe and am suggesting is the tokio model of panic handling. Namely if a panic occurs, log it, notify anyone who has joined the task that panicked, and carry on as before

**Comment by crepererum** [comment]
> Tokio by default adds catch_unwind to all worker pools, ...

Well, then I'm OK with notifying clients and exit. I'm still against carrying on server operations for the reasons illustrated above.

**Comment by alamb** [comment]
FWIW here is an example of what happens today (a `panic` inside of DataFusion): https://github.com/influxdata/influxdb_iox/issues/1768

The user gets an "internal error" and then we see the panic message in the logs, but the system remains up. This seems like a reasonable behavior

**Comment by tustvold** [comment]
Closing as #4686 implemented this
