### ISSUE TITLE
Roundtrip "unique count" through parquet metadata.

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#1712]
See #1576 for some info. In short: our stats have a "unique count" field which we currently recover from the parquet metadata. However the parquet field is currently always set to `None`, because the upstream writer doesn't calculate / write it. Two ways to implement that upstream:

- implement distinct counting in the parquet writer. Note however that this can be really costly for high-cardinality columns, so that should probably on be done on-demand (opt-in by API user)
- add a way to pass a pre-calculated unique count to the writer API (IOx already knows that count in many cases, so there's technically no need to recalculate it).

**Comment by alamb** [comment]
I believe this is OG specific and thus no longer relevant so closing

**Comment by crepererum** [comment]
Technically not, we might need something like this for NG as well. However I think the agreement is that "unique count" is not a useful metric and that we probably need cardinality estimation that can be folded (like a hyperloglog). So let's close this issue and come up with a proper requirement and design when we need it (and double-check what the arrow/parquet community is doing by then).
