### ISSUE TITLE
Catalog Transaction Bundling

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#1737]
# Abstract
Bundle catalog transaction from multiple table-partitions.

# Status Quo
We had the following design constraints for the persisted catalog:

- KISS (which would at least to a certain extend prohibit catalog history forks/branches)
- have a catalog per DB (not per table, because there can be that many)
- catalog can be rebuild (as best as possible) from parquet files
- apart from "parquet file written" house other information like "schema changed"

This leads to the fat that the persisted catalog is a single linear history. Furthermore a file can only be written while holding the transaction lock because we want to encode transaction information (like timestamp, revision, UUID) into the parquet file. This obviously somewhat limits the write throughput.

The new lifecycle policy will create reasonable large parquet files per table-partition, so we can treat every table-partition as one write-stream. However each of these write streams creates transactions on it's one:

```text
+-----------------+   ........................................................
|    table 1      |   .                   transaction lock                   .
|                 |   .                                                      .
| [ partition 1 ]-|-----[ start transaction ]--[ write parquet ]--[ commit ] .
|                 |   .                                                      .
| [ partition 2 ]-|-----[ start transaction ]--[ write parquet ]--[ commit ] .
+-----------------+   .                                                      .
                      .                                                      .
+-----------------+   .                                                      .
|    table 2      |   .                                                      .
|                 |   .                                                      .
| [ partition 1 ]-|-----[ start transaction ]--[ write parquet ]--[ commit ] .
+-----------------+   ........................................................
```

Apart from limiting the entire per-DB write throughput this also means that we create many transaction (basically one per parquet file, even though the persisted catalog supports multiple actions per transaction).

# Proposal
Instead of having a write stream per table-partition, have a single per DB write stream:

```text
+-----------------+                               ...............................................................
|    table 1      |                               .                      transaction lock                       .
|                 |                               .                                                             .
| [ partition 1 ]-|---[ persitable chunk(s) ]--+-----[ start transaction ]--+--[ write parquet ]--+--[ commit ] .
|                 |                            |  .                         |                     |             .
| [ partition 2 ]-|---[ persitable chunk(s) ]--+  .                         +--[ write parquet ]--+             .
+-----------------+                            |  .                         .                     .             .
                                               |  .                         .                     .             .
+-----------------+                            |  .                                                             .
|    table 2      |                            |  .                                                             .
|                 |                            |  ...............................................................
| [ partition 1 ]-|---[ persitable chunk(s) ]--+  
+-----------------+   
```

Note that the actual writing of the parquet files can be done in parallel. Apart from limiting the performance impact of the linear persisted history, this also results in larger transactions and therefore a significant reduction in transaction counts and persisted catalog size.

# References
This is the outcome of a discussion w/ @tustvold. Also somehow based on a comment from @mkmik noticing the fact that "single file per transaction" might have some room for improvement.

**Comment by pauldix** [comment]
Not relevant to NG (new) catalog.
