### ISSUE TITLE
Turn off deduplication for queries that do not need it

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#1763]
__Use case:__
When we enabled query deduplication in https://github.com/influxdata/influxdb_iox/pull/1762/ we did not yet have chunk merging that could merge + deduplicate chunks together and thus we want for the conservative "every chunk has potential overlaps internally". 

https://github.com/influxdata/influxdb_iox/pull/1762/commits/7babd26eb7b0b5aba0e6255fc273296f23fa3000#diff-8cde814c4cd929f1b942f17dfdb1cf9bc99021c0852e9a0cdc68edd365bd7e9eR214

__Proposal:__
When we do complete merging such that the open mutable buffer chunks are the only ones that can have internal dupes, we should update `DbChunk::may_contain_pk_duplicates` to reflect that

__Current behaviour:__
All chunks are deduplicated

**Comment by pauldix** [comment]
We'll also need split working (with the persistence windows) so that chunks that move from RUB to persisting/persisted don't overlap. Otherwise each RUB chunk will overlap with the next one.

**Comment by alamb** [comment]
This is blocked on https://github.com/influxdata/influxdb_iox/issues/1855 as well (as a bunch of tests call MOVE to setup the scenarios and MOVE doesn't deduplicate yet)
