### ISSUE TITLE
Flaky test end_to_end_cases::persistence::test_full_lifecycle

### ISSUE THREAD

**Issue by mkmik** [influxdata/influxdb_iox#1809]
```
thread 'end_to_end_cases::persistence::test_full_lifecycle' panicked at 'Could not find chunk in desired state ObjectStoreOnly within 10s. Chunks were: [

```

https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/7336/workflows/2164744f-5d5c-436f-a0e5-3f7d0d6edd6c/jobs/33423

**Comment by mkmik** [comment]
Happened again https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/7370/workflows/b301ac3f-1234-4b06-91e7-3928a6ad1dbf/jobs/33730

**Comment by alamb** [comment]
Closing this as it is old -- note we have a new instance of test flake in https://github.com/influxdata/influxdb_iox/issues/4437 but the symptoms appear to be different
