### ISSUE TITLE
panic during ingestion: sequence.number > n.max

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#1817]
We see the following `panic`s occurring during ingest after the latest deployment

```
level=error msg="thread \'tokio-runtime-worker\' panicked at \'assertion failed: sequence.number > n.max\', mutable_buffer/src/persistence_windows.rs:234:17" target="panic_logging" location="panic_logging/src/lib.rs:110" time=1624875128145767206
thread 'tokio-runtime-worker' panicked at 'assertion failed: sequence.number > n.max', mutable_buffer/src/persistence_windows.rs:234:17
thread 'tokio-runtime-worker' panicked at 'assertion failed: sequence.number > n.max', mutable_buffer/src/persistence_windows.rs:234:17
level=error msg="thread \'tokio-runtime-worker\' panicked at \'assertion failed: sequence.number > n.max\', mutable_buffer/src/persistence_windows.rs:234:17" target="panic_logging" location="panic_logging/src/lib.rs:110" time=1624875128168575512
level=error msg="thread \'tokio-runtime-worker\' panicked at \'assertion failed: sequence.number > n.max\', mutable_buffer/src/persistence_windows.rs:234:17" target="panic_logging" location="panic_logging/src/lib.rs:110" time=1624875128215106458
thread 'tokio-runtime-worker' panicked at 'assertion failed: sequence.number > n.max', mutable_buffer/src/persistence_windows.rs:234:17
level=error msg="thread \'tokio-runtime-worker\' panicked at \'assertion failed: sequence.number > n.max\', mutable_buffer/src/persistence_windows.rs:234:17" target="panic_logging" location="panic_logging/src/lib.rs:110" time=1624875128241538761
```

__Environment info:__

Not sure if it was introduced with https://github.com/influxdata/k8s-idpe/pull/3684. We could check graylog to see but I imagine @tustvold  or @mkmik might have seen it already if was already present in the deployment. It was probably introduced with https://github.com/influxdata/influxdb_iox/pull/1801

**Comment by alamb** [comment]
Here is my working theory (not yet verified)

Note the partition lock is acquired immediately before writing into a partition, and released thereafter (aka it is not held for the entire batch):
Theory:  we get two writes each with data for two partitions, A and B
Write 1 arrives first, given sequence number 1 (A1, B1)
Write 2 arrives, given sequence number 2 (A2, B2)

Now the inserts go something like:

```
Task1: Inserts A1
Task1: waits for lock for B
Task2: Inserts A2
Task2: Inserts B2
Task1: Tries to insert into A1 (and gets a failure because that is earlier than 2)
```

**Comment by tustvold** [comment]
I'd just remove the use of the system clock for local writes, and just set the min timestamps, as I'm not sure it is meaningful to store sequence numbers without anything to recover from.

When consuming from a sequenced buffer, e.g. Kafka, provided the consumer consumes synchronously in order we won't run into this issue.

**Comment by alamb** [comment]
Thanks @tustvold  — I am going to see if I can confirm the theory by provoking the same error and then will proceed by attempting to remove the system clock for local writes (perhaps after talking with @pauldix)

**Comment by alamb** [comment]
Yes, I can reproduce the error. If I add some random sleeps between processing writes thusly:

```diff
diff --git a/server/src/db.rs b/server/src/db.rs
index b14b8a46..c6e520e4 100644
--- a/server/src/db.rs
+++ b/server/src/db.rs
@@ -950,6 +950,12 @@ impl Db {
 
         if let Some(partitioned_writes) = sequenced_entry.partition_writes() {
             for write in partitioned_writes {
+                let avg_sleep_secs = 2.0;
+                let dist = Poisson::new(avg_sleep_secs).expect("parameter should be positive and finite");
+                let duration = Duration::from_secs_f32(dist.sample(&mut rand::thread_rng()));
+                info!(?duration, "sleeping during sequenced write");
+                std::thread::sleep(duration);
+
                 let partition_key = write.key();
                 for table_batch in write.table_batches() {
                     let row_count = table_batch.row_count();
```

And then send 5 writes in parallel:
```shell
./target/debug/influxdb_iox database write my_db tests/fixtures/lineproto/metrics.lp&
./target/debug/influxdb_iox database write my_db tests/fixtures/lineproto/metrics.lp&
./target/debug/influxdb_iox database write my_db tests/fixtures/lineproto/metrics.lp&
./target/debug/influxdb_iox database write my_db tests/fixtures/lineproto/metrics.lp&
./target/debug/influxdb_iox database write my_db tests/fixtures/lineproto/metrics.lp&
```

Several of the writes see the panic

```
Jun 28 07:17:39.242 ERROR panic_logging: thread 'tokio-runtime-worker' panicked at 'assertion failed: sequence.number > n.max', mutable_buffer/src/persistence_windows.rs:235:17
```

So I now have a way to verify any fix I do make...

**Comment by alamb** [comment]
The write code seems to be setup to ensure that all writes contain a sequence number -- so skipping sequence entries when not from kafka might get us a temporary workaround but still leaves the question of how to handle writes when we implement a IOx specific write buffer.

So an alternate would be to create a "WriteSequencer" that accepts `SequenceEntry`s, possibly out of order, and lets them go in order (and rejects any write that arrives too late...)

**Comment by alamb** [comment]
Fixed in https://github.com/influxdata/influxdb_iox/pull/1826
