### ISSUE TITLE
Optimize DeduplicateNode and avoid calling `concat_batches` unless needed

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#1828]
__Use case:__
Part of https://github.com/influxdata/influxdb_iox/issues/1822 we are seeing massive dictionaries in IOx due to the behavior of `concat_batches`

As an interim solution until we improve `concat_batches` we can reduce the number of times it is called

__Proposal:__
Change the Deduplicator  node in IOx to produce the exact same record batches that went in, unless there is actual overlap (now it keeps the last partition key and concatenates it) which should cut down on the number of times we call `concat_batches`

__Current behaviour:__
See #1822

**Comment by NGA-TRAN** [comment]
Talk with @alamb and assign this to myself
