### ISSUE TITLE
Can not run SQL queries while under heavy insert load

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#1851]
__Steps to reproduce:__
Put the IOx cluster under heavy inseret load (running merge plans) to point its CPU is saturated. 

Now, try to run a `SHOW TABLES` command:
```
> use 844910ece80be8bc_3c0bd4c89186ca89;
You are now in remote mode, querying database 844910ece80be8bc_3c0bd4c89186ca89
844910ece80be8bc_3c0bd4c89186ca89> show tables;
Error running remote query: status: Cancelled, message: "Timeout expired", details: [], metadata: MetadataMap { headers: {} }
844910ece80be8bc_3c0bd4c89186ca89>
```

__Expected behaviour:__
Expected behavior is that the query will return results

__Actual behaviour:__
Query timed out

What I think is happening is that since the user query is running on the same execution pool with the reorganization query plans that are merging data, it simply is starved

__Proposal__:
Until we have a proper resource manager / queue system, make (yet another) execution pool for data reorganization queries so that we try to run them in parallel.

**Comment by mkmik** [comment]
a new execution pool sounds a reasonable solution until we have a proper resource manager
