### ISSUE TITLE
When chunks are "moved" they are not deduplicated prior to insertion to RUB

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#1855]
__Steps to reproduce:__
Found while working on https://github.com/influxdata/influxdb_iox/issues/1763

Move a chunk (via api call) from MUB to ReadBuffer

Note this is likely not affecting tools directly because the automated lifecycle policy doesn't call move (it only calls compact)

__Expected behaviour:__
The data will be deduplicated prior to insertion into the ReadBuffer

__Actual behaviour:__
Data is not deduplicated

The code in https://github.com/influxdata/influxdb_iox/blob/main/server/src/db.rs#L441 does sort (but does not deduplicate the code) 

It does call 
```
sort_record_batch(batch).expect("failed to sort");
```
manually

This is I think an artifact of adding the compact action after the move action

**Comment by tustvold** [comment]
We should probably just remove the concept of a "move" and replace it with a "compact" API call

**Comment by alamb** [comment]
My high level plan will be:
1.  have compact and move call the same code (they just differ in the calculation of what chunks to include)
2. Add coverage of compact to `query_tests`
3. File a follow on ticket for removing the concept of MOVE entirely
