### ISSUE TITLE
Refactor MUB lifecycle rules

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#1878]
MUB chunks no longer closed based on size. The close based on row count thresholds.

* Remove the `mutable_size_threshold`.
* I believe `mutable_minimum_age_seconds` is also no longer needed/applicable
* `mutable_linger_seconds` is also probably superseded by `persist_age_threshold_seconds`, but what they do is slightly different.

Thoughts @tustvold?

**Comment by alamb** [comment]
`mutable_size_threshold` is not hooked up anywhere -- I will remove it
