### ISSUE TITLE
Improve compaction performance  

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#1885]
# Problem
We have found in tools, ion-query-3000, on July 1 2021 that the compaction is extremely CPU expensive and slow. [This document ](https://docs.google.com/document/d/1xn1zxxDNZ6ufjZK-texoaBjj5dP5irfbuk2WoWXgWxQ/edit#) has described the details of the problems and some solutions.

In short, here are 2 main issues:
1. Compaction needs to scan data and the IOx's `chunk scan` is expensive and also CPU bound due to the needs of chunk sorting (done in `SortExec` operator and takes around 20% of scan time)  and chunk merging (done in `SortPreservingMergeExec` and takes about 77%was of scan time) during deduplication inside the scan.
2. We keep compacting already compacted RUB data with new MUB which means our compacted RUB gets larger and larger and we redundantly repeat running the expensive data scan.

# Solutions
We will focus on improving 3 largest isuues:
1. Teach IOx about the chunk sortedness to avoid resorting them. #1886
2. `SortPreservingMergeExec` is known not optimal and should be improved. https://github.com/influxdata/influxdb_iox/issues/1983
3. Avoid compacting chunks that is already compacted. The current idea is, during compacting,  split RUB into 2 RUBs: a large one that is not overlapped with MUB and a small one that is potentially overlapped with MUB. Next round of compacting only needs to compact the small one with the new MUB. #1887
4. Replace scan_and_sort plan that puts together 2 steps scan and then sort with one one step sorted_scan #1889 
5. Added on July 19 after analyzing the results of  items (1) and (2) above: [Use opposite sort order to compute ranges during deduplication #2051](https://github.com/influxdata/influxdb_iox/issues/2051)
6. Verify and Improve if Chunk Resorting happen during scan #2035

Note that the work in #1 and #2 will help improve scan performance which will also critical for query performance.

**Comment by e-dard** [comment]
I have filed https://github.com/influxdata/influxdb_iox/issues/1983 to track the work I'm doing for the second issue on this list.

**Comment by NGA-TRAN** [comment]
Reopen as it was closed by accident

**Comment by NGA-TRAN** [comment]
Close this as all of its subtasks are done. Yay!
