### ISSUE TITLE
Chunks not closed when partitions rolled over

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb_iox#1906]
When a partition is no longer open (has rolled over), I would expect all open chunks in the partition to become closed. This is useful for two reasons:

1. They can be come RUB chunks for better compression/query perf.
2. They can be dropped from IOx if necessary due to lifecycle rules.

Right now we are seeing a situation where old partitions still contains open chunks. For example this query:

```
⇒  ./target/debug/influxdb_iox --host http://localhost:1234 database query my_db "SELECT COUNT(*), partition_key, storage FROM system.chunks GROUP BY partition_key, storage"
+-----------------+---------------------+-------------------+
| COUNT(UInt8(1)) | partition_key       | storage           |
+-----------------+---------------------+-------------------+
| 106             | 2021-07-06 22:00:00 | OpenMutableBuffer |
| 418             | 2021-07-07 05:00:00 | OpenMutableBuffer |
| 416             | 2021-07-07 06:00:00 | OpenMutableBuffer |
| 418             | 2021-07-07 02:00:00 | OpenMutableBuffer |
| 419             | 2021-07-07 03:00:00 | OpenMutableBuffer |
| 6               | 2021-07-06 21:00:00 | OpenMutableBuffer |
| 9               | 2021-07-06 20:00:00 | OpenMutableBuffer |
| 417             | 2021-07-07 01:00:00 | OpenMutableBuffer |
| 419             | 2021-07-07 04:00:00 | OpenMutableBuffer |
| 1               | 1754-08-30 22:00:00 | OpenMutableBuffer |
| 416             | 2021-07-06 23:00:00 | OpenMutableBuffer |
| 416             | 2021-07-07 00:00:00 | OpenMutableBuffer |
```

This was ran just after `10:00` on the `7th` so these partitions are old.

### Expected Behaviour

Once partitions have rolled over they should close out the open chunks so that they can be dropped if necessary.

### Actual Behaviour

They appear to hand around taking up memory and cannot be dropped by the lifecycle rules because they're still open.

**Comment by mkmik** [comment]
Fixed for good in #1909 

Temporary workaroudn in influxdata/k8s-idpe#3777 until #1909 lands in prod
