### ISSUE TITLE
Management API: Add a way to drop chunks

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#1918]
__Use case:__
1. As an operator, in crisis operations when something is not going well, I want to be able to purge Chunks that are causing problems
2. As a developer, I want to be able to setup an end to end integration test and check the state is exactly as I desire

__Proposal:__
Add a "drop chunk" Management API which removes the chunk from MUB, RUB, and/or object store

Normally, API should error if the `drop_unpersisted` flag in db rules is set to false

However, it should have a `--force` mode of operation in which case the chunks will be dropped regardless of the setting of `drop_unpersisted`

**Comment by tustvold** [comment]
I believe this has been replaced by DropPartition added by https://github.com/influxdata/influxdb_iox/pull/2310
