### ISSUE TITLE
Management API: Implement the “Drop partition“

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#1920]
__Use case:__
As an operator or user of IOx I want to be able to purge data from the system when it is no longer needed in a speedy way

__Proposal:__

Add a "Drop Partition" API and CLI. This will drop the partition and all chunks associated with that partition from MUB, RUB, ObjectStore and catalog.

**Comment by alamb** [comment]
@tustvold  and I just had a good brainstorm about this. The biggest challenge with DROP PARTITION will be ensuring that any outstanding lifecycle actions (e.g. that are creating chunks in a partition to be dropped) are torn down / cleaned up correctly

**Comment by crepererum** [comment]
IIRC we're currently NOT dropping these chunks for the preserved catalog if they're already persisted, so that needs some wiring as well.

**Comment by crepererum** [comment]
Done by #2310.
