### ISSUE TITLE
Compaction race condition loses data

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#1938]
The policy checker will attempt to compact an open MUB chunk if it is over the row count threshold or it hasn't received a write in some period of time. This is the desired behavior, however, when the compaction runs, every chunk is [snapshotted](https://github.com/influxdata/influxdb_iox/blob/main/server/src/db/lifecycle/compact.rs#L57), then compacted together and then dropped after the RUB chunk is created.

If writes come in while the compaction process is happening, the MUB chunk will get written to without it being part of the snapshot. Once the compaction completes, the MUB chunk will be dropped, losing any writes that weren't in the snapshot.

Partition should have a function to take the open MUB chunk, close it out with a snapshot representation (and lose everything else), and then leave the MUB as None. If writes come in while the compaction is running, a new MUB chunk will get created. Once the compaction is done, this snapshot will get dropped in favor of the new RUB chunk that contains its data.

I need to figure out a way to produce a test that shows this bug. Right now I've found it through a hunch that it existed and a combination of sleep and println commands, an end-to-end test and eyeballing the output.

**Comment by alamb** [comment]
> Partition should have a function to take the open MUB chunk, close it out with a snapshot representation (and lose everything else), and then leave the MUB as None. If writes come in while the compaction is running, a new MUB chunk will get created. 


@pauldix The way `Chunk::set_moving` accomplishes this is `freezing` the chunk (so that all new writes go to a new chunk).

If you add the following code to `Chunk::set_compacting` https://github.com/influxdata/influxdb_iox/blob/main/server/src/db/catalog/chunk.rs#L593
```
        if matches!(self.stage, ChunkStage::Open { .. }) {
            self.freeze()?;
        }
```
(aka to "freeze" open chunks when they are start compacting), does it fix your reproducer?

**Comment by pauldix** [comment]
@alamb yeah, the fix is trivial. The test to reproduce and verify it... I need to think about.

**Comment by alamb** [comment]
> , the fix is trivial. The test to reproduce and verify it... I need to think about.
so true
