### ISSUE TITLE
Panics captured by logging layer lose message

### ISSUE THREAD

**Issue by mkmik** [influxdata/influxdb_iox#1953]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behaviour.

1. Cause a panic, e.g. noticed when sending very large http requests to `/api/v2/write` 

__Expected behaviour:__

```
level=error msg="thread 'tokio-runtime-worker' panicked at 'Should have been able to read the next chunk: hyper::Error(Body, Custom { kind: UnexpectedEof, error: IncompleteBody })', src/influxdb_ioxd/http.rs:427:27" 
```

__Actual behaviour:__

```
level=error msg="thread 'tokio-runtime-worker' panicked at 'UNKNOWN', src/influxdb_ioxd/http.rs:427:27" span=1657324937750249551 target="panic_logging" location="panic_logging/src/lib.rs:110" time=1626093262739824399
```

__Logs__

The stderr stream shows the original message:

```
thread 'tokio-runtime-worker' panicked at 'Should have been able to read the next chunk: hyper::Error(Body, Custom { kind: UnexpectedEof, error: IncompleteBody })', src/influxdb_ioxd/http.rs:427:27
```

**Comment by alamb** [comment]
Interestingly, there is a test for catching the context here https://github.com/influxdata/influxdb_iox/blob/99093b18fb7f60b0229705c5fce79c42f86657a5/src/influxdb_ioxd/rpc/storage/service.rs#L1892-L1896

I tried locally (on a mac) and I got messages both in debug and release mode

**Comment by mkmik** [comment]
To make the thing even more mysterious, the logs contain some examples where the message is correctly preserved in the logfmt body; so whatever is going on, it happens only in some cases (the best kind of bugs)

**Comment by carols10cents** [comment]
Preserving what I put in chat: one possible cause of this is calling `panic!` with something other than a `String` or `&str`. It doesn't look like we're doing this in our code.

`cargo build -vvv` shows warnings from your dependencies, so I ran `RUSTFLAGS="-W non_fmt_panic" cargo build -vvv`.

This spot in the `proc-macro-error` crate is the only candidate I found: https://gitlab.com/CreepySkeleton/proc-macro-error/-/blob/master/src/lib.rs#L472

The `proc-macro-error::AbortNow` type is private, so we can't just try downcasting to that, but we could fork `proc-macro-error` and change that call to `panic` and see if that's it?

**Comment by alamb** [comment]
Here is a reproducer 🎉  (aka use a formatted message in `panic` rather than a single string)

```diff
diff --git a/influxdb_iox/src/influxdb_ioxd/rpc/testing.rs b/influxdb_iox/src/influxdb_ioxd/rpc/testing.rs
index a4885a5f..bc691186 100644
--- a/influxdb_iox/src/influxdb_ioxd/rpc/testing.rs
+++ b/influxdb_iox/src/influxdb_ioxd/rpc/testing.rs
@@ -12,8 +12,12 @@ impl IOxTesting for IOxTestingService {
         _req: tonic::Request<TestErrorRequest>,
     ) -> Result<tonic::Response<TestErrorResponse>, tonic::Status> {
         warn!("Got a test_error request. About to panic");
-        panic!("This is a test panic");
+        // Purposely do not use a static string (so that the panic
+        // code has to deal with aribtrary payloads). See
+        // https://github.com/influxdata/influxdb_iox/issues/1953
+        panic!("This {}", "is a test panic");
     }
+
 }
 
 pub fn make_server() -> IOxTestingServer<impl IOxTesting> {

```
