### ISSUE TITLE
Reported size of parquet chunks in system.chunks incorrect

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#1960]
__Steps to reproduce:__
Persist some data o object storage locally using IOx

__Expected behaviour:__
The size of parquet data reported in system.chunks should be the same as the on disk parquet size

__Actual behaviour:__
The reported size of parquet data is way off of the actual parquet size

```sql
test_db>   select * from system.chunks;
+----+---------------------+------------+-----------------+------------------+-----------------+-----------+----------------------------+----------------------------+-------------+
| id | partition_key       | table_name | storage         | lifecycle_action | estimated_bytes | row_count | time_of_first_write        | time_of_last_write         | time_closed |
+----+---------------------+------------+-----------------+------------------+-----------------+-----------+----------------------------+----------------------------+-------------+
| 14 | 2021-07-12 13:00:00 | m0         | ObjectStoreOnly |                  | 1433            | 4240001   | 2021-07-12 13:50:08.102974 | 2021-07-12 13:50:08.102974 |             |
| 15 | 2021-07-12 13:00:00 | m0         | ObjectStoreOnly |                  | 1432            | 2680001   | 2021-07-12 13:52:28.672506 | 2021-07-12 13:52:28.672506 |             |
+----+---------------------+------------+-----------------+------------------+-----------------+-----------+----------------------------+----------------------------+-------------+
```

The actual on disk size is 63M and 40M respectively:
```shell
alamb@ip-192-168-0-133:~/Software/influxdb_iox$ du -s -h ~/.influxdb_iox/42/test_db/data/m0/2021-07-12\ 13\:00\:00/*
 63M	/Users/alamb/.influxdb_iox/42/test_db/data/m0/2021-07-12 13:00:00/14.9786e1f1-ed90-43d7-a2d6-4f9d1582e813.parquet
 40M	/Users/alamb/.influxdb_iox/42/test_db/data/m0/2021-07-12 13:00:00/15.684a3997-d7a4-4d37-8012-a3b7385591ba.parquet
```

Note that we need to ensure the object store size for a chunk is not included in the "buffer size" limit calculations

**Comment by crepererum** [comment]
Not sure this is a bug. The `estimated_bytes` currently estimates the in-memory usage and for "object store only" this is correct. I also think that the in-mem size is indeed an important measure. I think for the object store size we should introduce another column.

Also note that the preserved catalog currently does NOT track file sizes, so either this requires some additions there as well or we would need to live with more expensive `HEAD` operations for each and every chunk.

**Comment by alamb** [comment]
@crepererum  -- your explanation makes sense. 

Perhaps we could have separate columns for `memory_bytes` and `object_store_bytes` to make that distinction clear

As it is now reporting the in-memory catalog size for parquet chunks I think is misleading.
