### ISSUE TITLE
query-3003 spending large amount of CPU in lifecycle manager

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#1962]
This may be working as expected, but needs some investigation to confirm

__Steps to reproduce:__

Port forward to query-3003 (the database on tools that is setup to persist things)
```shell
kubectl -n iox port-forward svc/iox-query-3003  1234:8082 1235:8080
```
Get a profile at http://localhost:1235/debug/pprof/profile?seconds=30

__Expected behaviour:__
The profile should mostly contain  "useful" work such as ingesting data or reorganizing / compacting

__Actual behaviour:__

Even though query-3003 is using around 2 CPU cores according to the [monitor301](https://us-west1-1.gcp.cloud2.influxdata.com/orgs/2f5ec5d98a8d6526/dashboards/075d53e0068a1000?lower=now%28%29%20-%205m) dashboard, it appears to be spending most of that time in the lifecycle policy manager itself:

Here is a screen shot of the CPU usage showing around 2 CPU cores of work:
<img width="716" alt="Screen Shot 2021-07-12 at 9 59 33 AM" src="https://user-images.githubusercontent.com/490673/125310288-70fbfe00-e300-11eb-9ea5-0b6b14977fb0.png">

Here is a screenshot of the profile showing large amounts of time in check_for_work
<img width="1792" alt="Screen Shot 2021-07-12 at 10 54 15 AM" src="https://user-images.githubusercontent.com/490673/125310338-7c4f2980-e300-11eb-968a-6bfe1e6fed80.png">

Here is the  profile data (can open in chrome): [query-3003-2021-07-12.zip](https://github.com/influxdata/influxdb_iox/files/6802370/query-3003-2021-07-12.zip)

**Comment by alamb** [comment]
So I think this is simply related to the sheer number of partitions and chunks that are in the `istio` database and the fact that the background task is polling them continuously

There are 88 partitions and 47468 chunks in total. 

```sql
844910ece80be8bc_64881f0f8fd1653c> select count(distinct partition_key) from system.chunks;
+-------------------------------+
| COUNT(DISTINCT partition_key) |
+-------------------------------+
| 88                            |
+-------------------------------+

Returned 1 row in 104.705144ms
844910ece80be8bc_64881f0f8fd1653c> select count(*) from system.chunks;
+-----------------+
| COUNT(UInt8(1)) |
+-----------------+
| 47468           |
+-----------------+
```

Since the background task runs every 100ms, it is effectively in a non stop loop checking for work

```json
{
  "rules": {
    "name": "844910ece80be8bc_64881f0f8fd1653c",
    "partitionTemplate": {
      "parts": [
        {
          "time": "%Y-%m-%d %H:00:00"
        }
      ]
    },
    "lifecycleRules": {
      "mutableLingerSeconds": 0,
      "bufferSizeSoft": "1073741824",
      "bufferSizeHard": "2147483648",
      "dropNonPersisted": true,
      "immutable": false,
      "persist": true,
      "workerBackoffMillis": "100",
      "catalogTransactionsUntilCheckpoint": "100",
      "lateArriveWindowSeconds": 300,
      "persistRowThreshold": "1000000",
      "persistAgeThresholdSeconds": 1800
    },
    "workerCleanupAvgSleep": "500s"
  }
}
```

**Comment by alamb** [comment]
Next up for this ticket I will deploy a new version to tools and re-review performance profiling after https://github.com/influxdata/influxdb_iox/pull/1973 is in

**Comment by alamb** [comment]
I reviewed the the profile after we deployed https://github.com/influxdata/influxdb_iox/pull/1973, and it does looks like the CPU usage has decreased:

![Screen Shot 2021-07-13 at 8 08 12 AM](https://user-images.githubusercontent.com/490673/125450338-4bf162da-9368-4278-8b97-cba1fe410e79.png)

Looking at the profile, the `check_for_work` function is now using around 50% of the CPU, and half of that is in `maybe_cleanup_failed` which is checking every every chunk of every partition all the time.

![Screen Shot 2021-07-13 at 8 09 39 AM](https://user-images.githubusercontent.com/490673/125450350-2f7985ad-519b-42fa-868f-ef51d7d09da7.png)

**Comment by alamb** [comment]
One final experiment:

When I did change the backoff for the check_for_work in the istio db,

```json
{
  "rules": {
    ...
    "lifecycleRules": {
      "workerBackoffMillis": "10000",  <-- change from 100 to 10000
      ...
    },
  }
}
```

Then the percentage of time spent in `check_for_work` drops to more like 20%.

**Comment by alamb** [comment]
Thus, I conclude that the heavy CPU use for lifecycle policy evaluation is due to the large number of chunks in this database and the per-chunk overhead becomes significant. This matches the observations that reducing the number of chunks checked in #1973 decreased CPU usage as well as CPU usage decreasing when I cranked up the value of `workerBackoffMillis`.

There are several things that we could do to optimize this if we wanted:
1. Change from a busy loop / poll model to an "event" triggered model (aka only check the policy when data has been written into the partition)
2. Improve the locking / lifecycle lock accounting to remove the need for `maybe_cleanup_failed`

However, given where we are in the IOx project this doesn't feel like a top priority now

So my recommendation is:
1. Remember / file a ticket for "edge" / "event" triggered lifecycle policy rather than a poll policy
3. Call this "working good enough" for the time being and not spend any more time optimizing this unless we need to squeeze more CPU out of the Istio database.

**Comment by pauldix** [comment]
I did add one issue related to having an event trigger compaction with #1877 (compact when writing to the MUB and it crosses the threshold. An evented model sounds good to me, but agree that this can be shelved for now as it's "good enough".

**Comment by tustvold** [comment]
Agreed. FWIW we could easily move lifecycle recovery to be RAII based and eliminate that 50% of the profile. Perhaps as part of making a CatalogTransaction abstraction
