### ISSUE TITLE
Chunk Ordering

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#1963]
## Problem

When resolving duplicates, deletes and upserts, etc... it is necessary to establish an unambiguous ordering of which came later.

In single instance mode this order is established by the order data is written to the open chunk in the partition.

In multiple instance mode, there is a requirement for all replicas to agree on the same order. For this reason an ordering broker, such as Kafka, provides a total ordering (it is assumed potentially overlapping writes are not spread across Kafka partitions). Data is then written to the open chunk in this order.

Currently the assumption made by the catalog/query is that the chunk IDs establish an ordering of writes, with later chunks having higher chunk IDs. With the introduction of compaction and split-based persistence this is no longer the case:

```
Chunk 0: Open
---
Chunk 0: Frozen
Chunk 1: Open
---
Chunk 0: Compacting
Chunk 1: Open
---
Chunk 1: Open
Chunk 2: Compacted Chunk 0
```

```
Chunk 0: Open
---
Chunk 0: Frozen
Chunk 1: Open
---
Chunk 0: Compacting
Chunk 1: Open
---
Chunk 0: RUB
Chunk 1: Open
---
Chunk 0: Split for persist
Chunk 1: Frozen
---
Chunk 1: Frozen
Chunk 2: (Split from 0) Persisting
Chunk 3: RUB
```

## Proposal

* Associate an integer generation with each chunk
* Each new open chunk within a partition is assigned a generation greater than any previous chunk in the partition
* When compacting/splitting, etc... the new chunk(s) should have the minimum generation of the input chunk(s)
* When deduplicating order chunks based on their generation
* Compaction/persistence must not skip over generations, i.e. cannot compact chunks with generations 1 and 5 if there is an unpersisted chunk with generation 3

This relies on the property that compaction and persistence must deduplicate, and it is therefore sufficient that they preserve the order of their inputs w.r.t to the chunks in the partition not included in the operation.

**Comment by alamb** [comment]
@tustvold  I suggest calling this concept 'chunk_age' or `chunk_order` as it seems to be different than traditional logarithmic compaction schemes (or generational garbage collectors). The difference is that across all chunks within a partition, any particular "generation number" only appears once.

> When compacting/splitting, etc... the new chunk(s) should have the minimum generation of the input chunk(s)

I was going to asl if this should be  the 'maximum' generation of the input chunks, but after thinking some more, I don't think it matters what number is picked as the system will ensure chunks never have duplicated  'generation' numbers anyways

**Comment by tustvold** [comment]
>  I suggest calling this concept 'chunk_age' or chunk_order as it seems to be different than traditional logarithmic compaction schemes

Good idea, I like `chunk_order`

> The difference is that across all chunks within a partition, any particular "generation number" only appears once.

The split part of persist will create two non-overlapping chunks with the same "generation number". This doesn't matter as by definition they can't overlap, but thought I'd mention

**Comment by alamb** [comment]
> The split part of persist will create two non-overlapping chunks with the same "generation number". This doesn't matter as by definition they can't overlap, but thought I'd mention

That is a good point 👍

**Comment by tustvold** [comment]
This also extends through to persistence, as whilst the catalog transactions establish an ordering of chunk creation, this is not preserved on catalog checkpoint
