### ISSUE TITLE
Panic when client closes connection

### ISSUE THREAD

**Issue by mkmik** [influxdata/influxdb_iox#1965]
currently when the client closes the connection prematurely we panic:

```
thread 'tokio-runtime-worker' panicked at 'Should have been able to read the next chunk: hyper::Error(Body, Custom { kind: UnexpectedEof, error: IncompleteBody })', src/influxdb_ioxd/http.rs:427:27
```

we should not panic but log and/or track in metrics.

**Comment by alamb** [comment]
I have some time now while query-3003 gets back up to speed, so I'll take a crack at this
