### ISSUE TITLE
Possible flaky test

### ISSUE THREAD

**Issue by mkmik** [influxdata/influxdb_iox#1994]
https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/8022/workflows/d8731792-c075-4873-a337-5c1240678651/jobs/40039

```
failures:
    end_to_end_cases::persistence::test_full_lifecycle
    end_to_end_cases::read_cli::test
```

**Comment by alamb** [comment]
The `    end_to_end_cases::read_cli::test` failure appears due to a difference in ordering . I will look into this more carefully this afternoon
