### ISSUE TITLE
Refactor: Use `tracing` crate rather than `log` 

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#200]
Inspired from https://github.com/influxdata/delorean/pull/197#issue-441436563

Goal is to have a unified tracing system / unified pattern for people to follow. After #197 we will have a mix of `log` and `tracing`. The goal is to standardize on `tracing` given we are going to have an asynchronous server (or two!)

**Comment by Horki** [comment]
@alamb is this still active?
I couldn't find any usage of `log` crate on the current main branch

**Comment by alamb** [comment]
@Horki  -- you are correct -- this is already complete -- likely completed in 1004854403f680cc8e2d2becc5bb09418b41ce86 and #388 - closing it down

**Comment by alamb** [comment]
Thanks for the catch!
