### ISSUE TITLE
PersistenceWindows System Table

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#2030]
The state of data to be persisted is tracked on a partition-level in a PersistenceWindows. Not only is this used to drive persistence, but also provides insight into the data that is arriving to a given partition.

In particular, each partition maintains a number of non-overlapping windows. Each of these describe metadata for the writes that arrived in that time interval, as determined by Wall clock:

* The min and max sequence numbers for each sequencer id
* The min and max row timestamps
* An over-estimate of the number of rows (because of duplicates and/or partial persists)

It would be beneficial not only for debugging persistence, but also investigating the distribution of ingested data, to expose this data as a system table

**Comment by alamb** [comment]
This would be a great one!
