### ISSUE TITLE
Refactor: Create a catalog transaction type for acquiring and releasing catalog locks

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#2047]
__Use case:__
IOx uses several different kinds of locks that may be held that relate to its handling of persisted (catalog) data:
1. CatalogLocks (on Partititions and Chunks)
2. Locks on the Persistet catalog  (e.g. [`TransactionHandle`](https://github.com/influxdata/influxdb_iox/blob/0c86d1dccfcde7fffff46705a3a3ec15cc6d6cf3/parquet_file/src/catalog.rs#L973-L979)
2. [`FlushHandle`](https://github.com/influxdata/influxdb_iox/blob/d71f38f27c41cfb0039d3d7d4ba305cbbc1f1506/persistence_windows/src/persistence_windows.rs#L64) (locks on persist windows)
3. the [`ChunkLifecycleAction`](https://github.com/influxdata/influxdb_iox/blob/00b89cd751fa43203855a095086ae255ff149dda/server/src/db/catalog/chunk.rs#L190) mark on Chunks
4. a [`cleanup_lock`](https://github.com/influxdata/influxdb_iox/blob/main/server/src/db.rs#L262) for controlling parquet file cleanup

Operations such as writing new data into IOx, or running lifecycle actions require some subset of these types of locks at various times. This leads to several challenges;

1. **Deadlocks**: The order in which to take the locks to prevent deadlock is (currently) implicit and unchecked, which produces intermittent deadlocks under load such as https://github.com/influxdata/influxdb_iox/issues/2045
2. **Manual Cleanup**: Due to some things which can't / shouldn't be held across `await`  points, there is manual cleanup lock like [`maybe_cleanup_failed`](https://github.com/influxdata/influxdb_iox/blob/00b89cd751fa43203855a095086ae255ff149dda/lifecycle/src/policy.rs#L428) which is both wasteful from a CPU perspective (see https://github.com/influxdata/influxdb_iox/issues/1962#issuecomment-879063198) but also I suspect a source of lurking bugs
1. **Cognitive Overhead** : Figuring out which locks are needed and in what order to acquire them for a desired operation is non trivial (especially as crates like `lifecycle` abstract them away behind traits)
2. **Visibility**: When some operation is waiting on locks / handles from another, there is currently no way to see what operation is holding the locks nor how long they have been waiting

__Proposal:__
The high level idea is to make a `CatalogTransaction` RAII object that encapsulates working with these locks. Here are some examples of how this might work:

```rust
let txn = db.new_transaction();
txn.lock_partition(partition_key);
txn.lock_chunk(partition_key, chunk_id);
...
std::mem::drop(txn); // <-- also drops the partition and chunk locks
```

```rust
let txn = db.new_transaction();
txn.lock_chunk(partition, chunk_id1); // <-- also acquires partition lock
txn.lock_chunk(partition, chunk_id0); // <-- errors because chunks not locked in id order
```

# multi-step "transactions":
Success:
```rust
let txn = db.new_transaction();
txn.lock_partition(partition_key);
txn.lock_chunk(partition_key, chunk_id);
txn.mark_chunk_lifecycle(chunk_id, Persisting);
let timestamp = txn.lock_persistence_window(); 
... do persistence ...
txn.remove_chunk(chunk_id); // <-- doesn't yet change catalog
txn.commit(); // <-- updates catalog, releases all locks, removes marks, etc

Failures:
```rust
let txn = db.new_transaction();
txn.lock_partition(partition_key);
txn.lock_chunk(partition_key, chunk_id);
txn.mark_chunk_lifecycle(chunk_id, Persisting);
let timestamp = txn.lock_persistence_window(); 
... do persistence ...
txn.remove_chunk(chunk_id); // <-- doesn't yet change catalog
txn.rollback();  <-- arranges for lifecycle marks to be removed, lifecycle action removed
```

__Current behaviour:__
See rationale. There are many individual things that can be locked and mechanisms to lock them

__Desired behaviour:__
A single structure that manages all the potential locks that can be acquired for access to a database's state that internally ensures consistency

**Comment by tustvold** [comment]
Agree entirely with this, I have already at various points had a play with implementing such a thing. A couple of thoughts:

* We likely want to preserve the RWLock semantics, i.e. read, write, upgradeable_read - it'd be a shame if read-only operations need to acquire exclusive locks
* I think it might be easier if, when acquiring multiple chunk locks, the user provides a filter, and leaves the transaction to ensure correct ordering, as opposed to manually registering chunks. We could also have both APIs
* A common use case is to acquire a partition read lock, and then iterate through each chunk in turn evaluating something - this should be simpler than repeated `lock_chunk` and `remove_chunk` calls
* There will need to be an explicit `drop_locks` or `into_send` call that returns a different type, as anything that could hold a parking_lot guard will not be `Send` and therefore cannot be held across an `await`
* I'm not sure when `remove_chunk` would be useful separated from `mark_chunk_lifecycle`
* The "manual cleanup" isn't actually to do with `Send` - it was implemented that way to allow for failure backoff. FWIW now that we have RAII-based failure tracking - #2031 there is an easy optimization to remove the loop

**Comment by alamb** [comment]
@tustvold  makes sense

> I’m a little bit wary of combining in the PersistenceWindow and PreservedCatalog

The reason I was suggesting something like that is that without it you still seem subject to deadlocks if you acquire them in different orders compared to each other and the other catalog locks. But we could always start with catalog locks and move more stuff in if needed

**Comment by tustvold** [comment]
> The reason I was suggesting something like that is that without it you still seem subject to deadlocks if you acquire them in different orders compared to each other and the other catalog locks. But we could always start with catalog locks and move more stuff in if needed

The PersistenceWindows lock cannot be acquired incorrectly w.r.t to the catalog locking, the borrow checker ensures that. The PreservedCatalog is more complex, but if I understand correctly it cannot be used incorrect w.r.t the in-memory catalog only other users of the PreservedCatalog. To me that suggests the PreservedCatalog needs a higher-level abstraction of its own, much like the in-memory catalog, but I'm not sure they should be the same thing...

**Comment by tustvold** [comment]
As discussed on https://github.com/influxdata/influxdb_iox/pull/3560 this should also handle the logic for determining that a consistent chunk order slice has been selected, and what the final order should be

**Comment by pauldix** [comment]
Not relevant to NG (new) catalog.
