### ISSUE TITLE
Clean up metrics API

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#2076]
The `metrics` crate is a bit of an API mess at the moment:

- **clone:** For some metrics types `Clone` is implemented, for others it isn't
- **labels by ref / by value:** Some constructors take `&[KeyValue]`, others `Vec<KeyValue>`
- **drop:** While counters can be dropped w/o consequence, gauges reset their value on drop
- **`u64`/`usize`:** Some metrics accept `usize` as a value, others `u64`
- **labels:** make it easier to reason about the final labels (see [this comment](https://github.com/influxdata/influxdb_iox/pull/2077#discussion_r673847959))

**Comment by e-dard** [comment]
FWIW I am not a fan of gauges being decremented when objects are dropped. I find it surprising, and I don't like surprising :-) 

I'm happy for gauges to decrement on drop but I think it would be explicitly done via a `Drop` implementation in the code that is being instrumented.

**Comment by tustvold** [comment]
The reason for gauges decrementing on drop is conceptually they are an observation of the current state (they're actually an aggregation of a number of observations). If the value no longer exists to be observed I would expect the value to no longer include it. This is the key thing that distinguishes gauges from a counter, one is an observation of the current state, the other an accumulation of past states. If you leave the drop to be manual you then end up with orphaned metrics, which imo is even more confusing...

Otherwise I agree entirely with the points raised. Personally I'd like to stabilise on `&[(&str, &str)]` as the KeyValue API is obtuse, but I seem to remember at the time this was non-trivial for whatever reason

**Comment by e-dard** [comment]
@tustvold I completely agree on the semantics of gauges, merely that from a software engineering perspective I (and I'm sure future committers) will find it confusing that metrics have to be explicitly created and wired in etc, yet some of them (some gauges) are _implicitly_ decremented when objects are dropped. That's my only point really.

**Comment by tustvold** [comment]
> (some gauges)

It should be all gauges? Both Gauge and GaugeValue should decrement on drop?

**Comment by e-dard** [comment]
> It should be all gauges? Both Gauge and GaugeValue should decrement on drop? If not that's a bug...
what about gauges that are tracking something orthogonal to the lifetime of the object doing the tracking? For example a gauge that tracks the last time something was processed. If the processor (that's managing the gauge metric) drops I wouldn't expect the value of the gauge to change. 

Perhaps I'm still misunderstanding the design :-)

**Comment by tustvold** [comment]
> tracks the last time something was processed

The design of `metric::Gauge` is to allow reporting an aggregated total, across a number of discrete components. Specifically it was designed with memory reporting in mind. With this use-case in mind, having observations outlive the lifetime of the thing they are observing doesn't seem to make sense to me - you specifically don't want the lifetime of the observer and the observed to be disconnected.

Ignoring drop-semantics for a second, the example you give, however, won't work well with `metric::Gauge` as timestamps can't be aggregated. However, `metric::Gauge` is just an abstraction on top of the ValueObserver API, which I suspect would work well for this specific use. It is already being used for lock tracking, and there is plumbing on top of the OTEL functionality to make it less painful to use.

Perhaps it is a case of renaming `metric::Gauge` to be something else?

**Comment by e-dard** [comment]
> Perhaps it is a case of renaming metric::Gauge to be something else, so that it is clear what it is and isn't meant to be used for?

I suspect that could be a good idea. To me, and I think many other folks, a prometheus gauge is simply a floating point value that can be incremented, decremented and arbitrarily set. It is generally used for anything that exposes a point-in-time instrument value.

Perhaps we should have an abstraction in our metrics crate for that concept and something different for the specific ones we're using for accumulated totals.

**Comment by crepererum** [comment]
Seems we're having two usecases here:

- **sums:** things like total chunk mem usage per type
- **others:** things like write buffer lag

For the first one "subtract on drop" makes totally sense while for the second case it doesn't. Maybe we can just have a parameter for `Gauge` that controls that behavior?
