### ISSUE TITLE
Compaction Panic Stalls Lifecycle

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#2091]
It was observed that a database suffering from #2090 would cease to perform any further compactions. This would suggest that the background worker loop aborted.

There are a couple of takeaways from this:

* The main loop should print a prominent error and exit if the server loop exits (it already does, but it should be an error not info)
* The server background loop should monitor the loops of its databases to make sure they haven't exited - it should print an error and try to restart it if so
* The Db background loop should spawn potentially panic-ing work, to reduce the risk of it bringing down the loop

**Comment by alamb** [comment]
@tustvold 

which look are you referring to when you say, "main loop?" is it this one?  https://github.com/influxdata/influxdb_iox/blob/8f6ca07657a9ebd1911345c0acd64b8391202264/server/src/db.rs#L723-L793

I wonder if we did "The Db background loop should spawn potentially panic-ing work, to reduce the risk of it bringing down the loop" (aka ran the entire db background loop in a task) perhaps we don't even need the server level background monitoring loop?

**Comment by tustvold** [comment]
Going to pick this one up as we're seeing the same symptom with #2124

**Comment by alamb** [comment]
Thank you @tustvold
