### ISSUE TITLE
Dynamic CPU detection using significant CPU time

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb_iox#2094]
I noticed in a Flame graph:

![Screenshot 2021-07-22 at 16 04 53](https://user-images.githubusercontent.com/501993/126662505-999e788a-186a-453a-bc62-dc32eb8d7ad5.png)

That CPU detection is for some reason taking up about 25% of CPU time. This is happening when a roaring bitmap is calculating its cardinality. 

I think that we might be able to solve this by ensuring that we are building for targeted architecture. Then I would imagine that this dynamic architecture detection would not need to happen.

Alternatively it could be a defect in `croaring` or `croaring-rs` (I am surprised it shows up given how infrequently it will be being called).

**Comment by alamb** [comment]
that is very surprising indeed

**Comment by shepmaster** [comment]
[We are 18 days too late](https://github.com/RoaringBitmap/CRoaring/commit/6403d44cbea549b31c16266d57cf9a42aac320b6).

They mistakenly called `dynamic_croaring_detect_supported_architectures` (uncached) instead of calling `croaring_detect_supported_architectures` (cached).

Now we need to get the Rust wrapper to upgrade. I can work on submitting a PR to them.

**Comment by shepmaster** [comment]
Opened https://github.com/saulius/croaring-rs/pull/72

**Comment by shepmaster** [comment]
For our purposes, we can also hardcode a CPU type by setting `ROARING_ARCH` at build time:

```
    if let Ok(target_arch) = env::var("ROARING_ARCH") {
        build.flag_if_supported(&format!("-march={}", target_arch));
    }
```

**Comment by carols10cents** [comment]
[`ROARING_ARCH` is being set for `perf_image` builds](https://github.com/influxdata/influxdb_iox/blob/844a025c7cb5835880e1ad365238591366c59de4/.circleci/config.yml#L250), was this flamegraph from a development build, @e-dard ?

**Comment by e-dard** [comment]
> [`ROARING_ARCH` is being set for `perf_image` builds](https://github.com/influxdata/influxdb_iox/blob/844a025c7cb5835880e1ad365238591366c59de4/.circleci/config.yml#L250), was this flamegraph from a development build, @e-dard ?

No it's prod

**Comment by carols10cents** [comment]
Prod created from a perf_image job? So that env var isn't working? Or are prod jobs created some other way? I forget what's happening now.

**Comment by e-dard** [comment]
@carols10cents I'm not sure exactly what the situation is regarding builds, just that this issue is happening in the production deployment of IOx on Tools

**Comment by carols10cents** [comment]
Edd reported in chat that this doesn't seem to be fixed :(

**Comment by e-dard** [comment]
This seems to be fixed now as far as I can tell.
