### ISSUE TITLE
a problem with flux query using InfluxDB 2.0 API

### ISSUE THREAD

**Issue by atingchen** [influxdata/influxdb_iox#2137]
__Steps to reproduce:__

According to Get started, start the server and import the data, try to use the Influx2.0 API to query the data。
```
func main() {
	// Create client
	client := influxdb2.NewClient("http://localhost:8080", "")
	// Get query client
	queryAPI := client.QueryAPI("company")
	// Get QueryTableResult
	result, err := queryAPI.Query(context.Background(),
		`from(bucket:"sensors")|> range(start: -1h) |> filter(fn: (r) => r._measurement == "cpu")`)
	if err == nil {
		// Iterate over query response
		for result.Next() {
			// Notice when group key has changed
			if result.TableChanged() {
				fmt.Printf("table: %s\n", result.TableMetadata().String())
			}
			// Access data
			fmt.Printf("value: %v\n", result.Record().Value())
		}
		// Check for an error
		if result.Err() != nil {
			fmt.Printf("query parsing error: %s\n", result.Err().Error())
		}
	} else {
		panic(err)
	}

	client.Close()

}

```

__Expected behaviour:__
I just want to get data.

__Actual behaviour:__
panic: 404 Not Found: Not Found

**Comment by alamb** [comment]
Thanks for the report @atingchen -- at the moment IOx doesn't support querying via Flux directly -- it supports the V2 API write API as well as its own SQL read interface and the internal "storage gRPC" interface that flux uses. 

However, it doesn't include the entire flux interpreter yet, which must be hosted in a separate process. 

We have not yet done the integration / written the documentation on how to use Flux with IOx -- we will eventually but it is not our current top priority

**Comment by atingchen** [comment]
> Thanks for the report @atingchen -- at the moment IOx doesn't support querying via Flux directly -- it supports the V2 API write API as well as its own SQL read interface and the internal "storage gRPC" interface that flux uses.
> 
> However, it doesn't include the entire flux interpreter yet, which must be hosted in a separate process.
> 
> We have not yet done the integration / written the documentation on how to use Flux with IOx -- we will eventually but it is not our current top priority


Thank you for your reply. Does SQL currently support using regular expressions to query data?
I found that there is a regex.rs file in the source code, but I did not find a test using regular expressions in query_test/sql.rs.
I tried to use `SELECT * from cpu where host =~ /.*/`, but an error occurred: `SQL(ParserError("Expected an expression:, found: ~"))`
I read the comment`(equivalent to col ~= /pattern/)` in the regex.rs file , so I tried to use `SELECT * from cpu where host ~= /.*/`  but an error occurred: source : SQL(ParserError("Expected end of statement, found: ~"))
what should I do?

**Comment by alamb** [comment]
Hi @atingchen  - IOx uses the [DataFusion](https://github.com/apache/arrow-datafusion) SQL engine -- so it supports regular expressions using the `LIKE` clause

So for example, something like this should workL

```sql
SELECT * from cpu where host LIKE '%suffix';
```

It doesn't yet support operators like `~` to do regular expression matching

**Comment by alamb** [comment]
FYI I have filed https://github.com/apache/arrow-datafusion/issues/795 upstream to track adding this feature to DataFusion

Thank you

**Comment by atingchen** [comment]
@alamb thanks !

**Comment by atingchen** [comment]
I have to come to bother you again,
I followed your opinion and used `LIKE` to query data, but I encountered a new problem——"Error planning sql query Error preparing query Error during planning:'Dictionary(Int32, Utf8) LIKE Utf8' can't be evaluated because there isn't a common type to coerce the types to"

**Comment by alamb** [comment]
No worries @atingchen  -- thank you for testing.  I did some investigation and I can reproduce your problem and tracked it down to the underlying datafusion crate: https://github.com/apache/arrow-datafusion/issues/815

I did find a nasty workaround , which is to cast the column to `varchar` first:

```sql
SELECT cpu from cpu where cast (host as varchar) LIKE 'Andrews-MBP%';
``` 

Which is pretty nasty but does work

**Comment by atingchen** [comment]
Thanks @alamb

**Comment by alamb** [comment]
I am closing this ticket and we'll track the request in https://github.com/apache/arrow-datafusion/issues/815 👍  Thanks again for your help @atingchen
