### ISSUE TITLE
Re-enable row group pruning in parquet file reading

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#2163]
__Use case:__
We "solved" https://github.com/influxdata/influxdb_iox/issues/2153 by disabling parquet predicate pushdown (due to https://github.com/apache/arrow-rs/issues/641). 

Disabling parquet predicate pushdown is probably ok given all parquet files we make have a single row group.

__Proposal:__
Re-enable pushdown of predicates into parquet scans. This will be important if we ever generate parquet files with multiple row groups or if datafusion gets smarter about using these pushed down predicates (i.e. does more than row group pruning)

__Desired behaviour:__
Back out the changes in XXXX

**Comment by crepererum** [comment]
Outdated. I believe this was indirectly fixed by #3291.
