### ISSUE TITLE
Log server startup failures as INFO level or higher

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#2174]
__Use case:__
@NGA-TRAN  and I were looking at an internal system that appeared not to be doing anything. When we looked at the logs 
[query-3000-logs.zip](https://github.com/influxdata/influxdb_iox/files/6923475/query-3000-logs.zip) there were no error messages or warnings, instead the server appeared to startup and then just do nothing.

@crepererum subsequently figured out that replay had failed, using the management API:

```
./scripts/grpcurl -plaintext localhost:1234 influxdata.iox.management.v1.ManagementService.GetServerStatus
{
  "serverStatus": {
    "initialized": true,
    "databaseStatuses": [
      ...
      {
        "dbName": "844910ece80be8bc_3c0bd4c89186ca89",
        "error": {
          "message": "cannot load catalog: Cannot build replay plan: Minimum sequence number in partition checkpoint (3262041) is lower than database-wide number (132258769) for partition http_api_request_duration_seconds:2021-07-30 16:00:00 and sequencer
0"
        },
        "state": "DATABASE_STATE_RULES_LOADED"
      },
      ...
    ]
  }
}
```

And then could fix the issue by wiping the catalog:
```
$ cargo run -- --host http://localhost:1234 database catalog wipe 844910ece80be8bc_3c0bd4c89186ca89 --force
{
  "id": 0,
  "total_count": 1,
  "pending_count": 1,
  "success_count": 0,
  "error_count": 0,
  "cancelled_count": 0,
  "dropped_count": 0,
  "wall_time": {
    "secs": 0,
    "nanos": 0
  },
  "cpu_time": {
    "secs": 0,
    "nanos": 0
  },
  "job": {
    "WipePreservedCatalog": {
      "db_name": "844910ece80be8bc_3c0bd4c89186ca89"
    }
  },
  "status": "Running"
}
```

```
$ cargo run -- --host http://localhost:1234 operation get 0
{
  "id": 0,
  "total_count": 1,
  "pending_count": 0,
  "success_count": 1,
  "error_count": 0,
  "cancelled_count": 0,
  "dropped_count": 0,
  "wall_time": {
    "secs": 118,
    "nanos": 717874438
  },
  "cpu_time": {
    "secs": 0,
    "nanos": 911702990
  },
  "job": {
    "WipePreservedCatalog": {
      "db_name": "844910ece80be8bc_3c0bd4c89186ca89"
    }
  },
  "status": "Success"
}
```

__Proposal:__
Ensure that any error during replay is logged as `ERROR` 

This ticket is related to but doesn't appear to be the the same, as https://github.com/influxdata/influxdb_iox/issues/2146 and https://github.com/influxdata/influxdb_iox/issues/2162

__Current behaviour:__
Error happens and there is no mention in the log

__Desired behaviour:__
Operator should be able to understand the system state by looking at log messages

**Comment by crepererum** [comment]
Log should probably be placed here:

https://github.com/influxdata/influxdb_iox/blob/ffb36cd50c66a702e46893ca729881ea20483c17/server/src/init.rs#L173
