### ISSUE TITLE
Create a new persisted replica/server_id with data that no longer in the sequencer / kafka (aka foreign catalog, catalog seeding)

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#2177]
__Use case:__
Given 
1. One or more a IOx nodes that are reading from a sequencer (for example a Kafka stream) and thus are "replicas" of each other
2. persisting to object storage
3. The sequencer no longer has some of the data that has been persisted to object storage (for example due to retention or some other notion)

The desire is to add one or more new IOx nodes that are replicas, meaning they provide query access to all the same historical data and are themselves persisting the data.

Reasons for adding new replicas for doing this might be:
1. Add an additional read server to increase query capacity
2. Increase the database replication factor for improved durability (e.g. go from 1 to 2 replicas)
3. Restore desired replication factor if existing server id is corrupted / unavailable for some reason
4. (new) Not decrease the number of active write replicas  while deploying a new version of IOx  (start a new replica with new software version while keeping the existing replicas running existing version)

Since the existing Replay code can only recovers data that is in the sequencer (not data that only exists on object store) we will need additional functionality

For example:
```
                                                                                                      
                                      Database Checkpoint                                             
                                         min sequence                                                 
                                               │                                                      
    Input Stream                               └────────┐                                             
   from Sequencer                                       ▼                                             
               ┌ ─ ─┌ ─ ─             ┌────┬────┬────┬────┬────┬────┬────┬────┬────┐                  
                Data│Data│  ...       │Data│Data│Data│Data│Data│Data│Data│Data│Data│                  
               └ ─ ─└ ─ ─             └────┴────┴────┴────┴────┴────┴────┴────┴────┘                  
                0   1      ...         100   101  102  103  104  105  106  107  108   Sequence Number 
                                                                           ▲                          
                                                           ┌───────────────┘                          
                                                           │                    Position of           
   ╔══════════════╗                                        │                     next read            
   ║ ┌─────────┐  ║                           ┌────────────────────────┐                              
   ║ │ Parquet │  ║                           │                        │                              
   ║ │  file   │  ║                           │      influxdb_iox      │                              
   ║ └─────────┘  ║                           │                        │                              
   ║     ...      ║                           └────────────────────────┘                              
   ║ ┌─────────┐  ║                                                                                   
   ║ │ Parquet │  ║                                                                                   
   ║ │  file   │  ║                                                                                   
   ║ └─────────┘  ║                                                                                   
   ║              ║                                                                                   
   ║ Object Store ║                                                                                   
   ╚══════════════╝                                                                                   
```
                                                                                                
All data with sequence number between 0 and 103 is persisted to object storage

The sequencer (e.g. Kafka) only retains data with sequence number 100 and greater (sequence numbers 0 to 99 are no longer available)                                       

If we want to add a new persisting replica of database, it will somehow have to recover / know about the data that is already in the object store
 
__Proposal:__
Add some way to add a new persisting replica that can query using all previously persisted data. This may take the form of "seeding" one catalog with another. Somehow the files in object store need to be copied or somehow marked so that they are not accidentally garbage collected by the server that wrote them, etc. 

__Current behaviour:__
creating an insync replica after data has been removed from the ~object store~ sequencer (e.g. kafka)  is not possible today

**Comment by alamb** [comment]
FYI @tustvold @crepererum @pauldix

**Comment by tustvold** [comment]
>  creating an insync replica after data has been removed from object store is not possible today

Should this read "creating an insync repliaca after data has been removed from the **write buffer** is not possible today"?

**Comment by alamb** [comment]
> Should this read "creating an insync replica after data has been removed from the write buffer is not possible today"?

Good call @tustvold . Fixed. I changed the description to say "sequencer (e.g. kafka)" rather than "write buffer" as I think that is more technically accurate, but I will admit to not fully understanding how write buffer and sequencers are connected

**Comment by pauldix** [comment]
Not relevant to NG (new) catalog.
