### ISSUE TITLE
DB went down with replay error when hitting a likely datafusion bug

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#2185]
It seems a Datafusion bug while execute a query lead to IOx replay error

__Steps to reproduce:__
Run the following query in DB `844910ece80be8bc_3c0bd4c89186ca89`

```
SELECT Row_number() 
         OVER ( 
           partition BY Date_trunc('minute', time), bucket_id, partition_id 
           ORDER BY time DESC)    AS rn, 
       gauge, 
       Date_trunc('minute', time) AS time_bucket, 
       env 
FROM   storage_usage_bucket_cardinality 
WHERE  Cast(time AS BIGINT) > Cast(Now() AS BIGINT) - 5 * 60 * 1000000000 
       AND time <= Now(); 
```

We will see the following Datafusion internal error:
`Error running remote query: status: Internal, message: "Internal error reading points from database 844910ece80be8bc_3c0bd4c89186ca89: Internal error executing plan: Arrow error: External error: Arrow error: External error: Arrow error: External error: Execution error: Internal error: Unsupported data type in hasher. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Tue, 03 Aug 2021 18:55:08 GMT"} }`
Data Ticket: https://github.com/apache/arrow-datafusion/issues/821

Then `844910ece80be8bc_3c0bd4c89186ca89` also goes down with following error:

```
./scripts/grpcurl -plaintext localhost:1234 influxdata.iox.management.v1.ManagementService.GetServerStatus
.....
{
        "dbName": "844910ece80be8bc_3c0bd4c89186ca89",
        "error": {
          "message": "cannot load catalog: Cannot build replay plan: Minimum sequence number in partition checkpoint (123964015) is lower than database-wide number (183235313) for partition http_api_request_duration_seconds:2021-08-02 08:00:00 and sequencer 0"
        },
        "state": "DATABASE_STATE_RULES_LOADED"
      },
....
```

Update: the DF fusion bug and the replay error may not be related. After I wiped the catalog and ran the query again, I hit the same DF bug but the DB is still up running.

**Comment by alamb** [comment]
@NGA-TRAN  did you restart this database or did it restart by itself?

**Comment by alamb** [comment]
FYI @crepererum  @tustvold

**Comment by NGA-TRAN** [comment]
@alamb I have to wipe the catalog using this command:
cargo run -- --host http://localhost:1234 database catalog wipe 844910ece80be8bc_3c0bd4c89186ca89 --force
