### ISSUE TITLE
Simplify Server/Database Startup

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#2186]
**Problem:**

Over the last weeks we've seen a large number of issues related to the current server and database startup/shutdown logic contained within server, and the structure of the server crate in general:

* https://github.com/influxdata/influxdb_iox/issues/2146
* https://github.com/influxdata/influxdb_iox/issues/2162
* https://github.com/influxdata/influxdb_iox/issues/2174
* https://github.com/influxdata/influxdb_iox/issues/2091
* https://github.com/influxdata/influxdb_iox/issues/2134
* https://github.com/influxdata/influxdb_iox/issues/2139
* https://github.com/influxdata/influxdb_iox/issues/2065
* https://github.com/influxdata/influxdb_iox/issues/2053
* https://github.com/influxdata/influxdb_iox/issues/1990
* https://github.com/influxdata/influxdb_iox/pull/2168

Additionally there are the following problems which currently lack filed issues:

* A database cannot be shutdown, which blocks adding database deletion
* The status of a database's startup is only externally visible once it finishes initialization or errors
* There is a large amount of highly coupled code across lib.rs, init.rs, config.rs that is non-trivial to understand
* The separation of responsibilities between `Server` and `Db` is unclear

**Proposal:**

The full proposal can be found [here](https://docs.google.com/document/d/1sSRODNDcqQ0jncMZGK43zpD5RmvZIXCT_yyoiUfCx-I/edit?usp=sharing) but the major changes are:

* Create a `Database` abstraction that contains the subsystems necessary to implement a single `DatabaseRules`
* `Database` handles its startup/shutdown state machine, and background loop
* `Db` becomes an instance-local, queryable, possibly persisted, and possibly mutable data store
* `LifecyclePolicy`, `WriteBuffer`, etc... is pulled out of `Db` onto `Database`
* `Server` stores a collection of `Database`, and has no involvement in their initialization process
* A `/initialized` HTTP endpoint is added that returns 200 when the `Server` and all `Database` are initialized - for use as a kubernetes startup probe
* The `Server` and `Database` startup state machines remain largely the same, but the error states are explicit, with explicit operator initiated recovery transitions

**Potential Future Improvements**

* Separate `Db` into its own crate
* Ability to delete databases - https://github.com/influxdata/influxdb_iox/issues/1881
* Ability to shutdown databases with an API call

**Comment by alamb** [comment]
Maybe a better name for `Db` is `Store` or `DataStore`

**Comment by tustvold** [comment]
Closing as the major work for this has been completed
