### ISSUE TITLE
User should be able to group by all tags (GROUP BY *)

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#2188]
Our SQL dialect should have an easy way for a user to specify that they want to `GROUP BY` all the tags in a table. Users frequently don't know all of the tags that exist ahead of time and it's a very common thing for them to want to group by all tags so we should make it easy rather than forcing them to go look up the tags and write them out individually. In InfluxQL this looked like this:

```
SELECT *
FROM foo
GROUP BY *
```

I'm not sure what the easiest way to add an extension to Datafusion to do this. Maybe it's a UDF? 

```sql
SELECT *
FROM foo
GROUP BY tags('foo')

-- or maybe simpler
SELECT *
FROM foo
GROUP BY tags()

-- or would this even parse?
SELECT *
FROM foo
GROUP BY foo.tags()
```

I think I'm hesitant to do it as a new keyword. Mainly because I don't think we want to modify the SQL parser.

**Comment by alamb** [comment]
The way I would do this is as a rewrite pass prior to datafusion

So like
```
IOx Flavored SQL --> (parse into SQL AST) --> (do rewrite) --> (new SQL AST) --> pass to existing DataFusion planner
```

At the moment, there is no DataFusion extension mechanism I know of for adding a SQL rewrite phase, but I bet that people would welcome that extension (as they will have similar usecases to IOx wanting to support some flavor of SQL and then translating it into DataFusion supported SQL)

We could also do it ourselves (more quickly but likely with potential bugs)  in IOx by directly using `sqlparser` to parse the SQL, do the rewrite and then turn it back into a SQL string)

**Comment by alamb** [comment]
> I think I'm hesitant to do it as a new keyword. Mainly because I don't think we want to modify the SQL parser.

I agree avoiding the need to modify the sql parser would be ideal

**Comment by NGA-TRAN** [comment]
Sine we might support join in the future, I like the syntax  `tag(table1, table5)`

```
SELECT ...
FROM foo, bar, ...
GROUP BY tags(foo, bar)
```

Since this is IOx specific, I think the solution @alamb's suggestion is great
 > in IOx by directly using sqlparser to parse the SQL, do the rewrite and then turn it back into a SQL string

**Comment by alamb** [comment]
FYI here is a datafusion issue that describes the desire for an extension mechanism: https://github.com/apache/arrow-datafusion/issues/533

**Comment by alamb** [comment]
Given that `GROUP BY *` is an InfluxQL syntax and @stuartcarnie  is implementing proper InfluxQL support via https://github.com/orgs/influxdata/projects/92 (e.g. #5424 and #5412 ) I am not sure adding `GROUP BY *` support to SQL is something we still want to do

**Comment by alamb** [comment]
@e-dard  no longer works on this project, so unassigning him from this ticket :)

**Comment by alamb** [comment]
I can't think of any workaround using SQL for `GROUP BY *` 

## Option 1: no support, user has to rely on schema metadata
You can use the schema metadata to find all tag field names (see https://github.com/influxdata/influxdb_iox/issues/5659 for support and workaround) 

With the iox specific schema information (e.g. which columns are tags) a user can explicitly list which tag to group on

## Option 2:  implement a SQL rewrite 
Solution sketch: Implement a custom SQL rewrite in IOx before we passed the query to DataFusion that would expand `GROUP BY *` to `GROUP BY tag1, tag2, ...`

- [ ] Changes to sql-parser to support `GROUP BY *` (via a custom dialect)
- [ ] Implement generic SQL rewrite pass
- [ ] Implement specific GROUP BY rewrite

A prototype of this approach can be seen here: https://github.com/influxdata/influxdb_iox/pull/5438

Estimated time (for @alamb ): 1-2 weeks

**Comment by alamb** [comment]
I believe that this usecase is initially going to be handled by @stuartcarnie  as part of native InfluxQL support in IOx, so closing this ticket for now
