### ISSUE TITLE
Make compiling opentelementry-* depedencies optional

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#2192]
__Use case:__
During normal development of IOx as a developer I want faster compile / link times so I can iterate on changes and be more productive. The more crates IOx depends on the longer each iteration cycle takes

The `opentelemetry-*` set of crates adds many useful features (like sending metrics to jaeger and open telemetry collectors) that are important for production use but are not used during the course of normal development. These crates have many additional dependencies (e.g. they all use tonic/prost) and some are using different versions - e.g. in https://github.com/influxdata/influxdb_iox/pull/2172

Also, the plan is for our internal system, `conductor` to use IOx’s observability crates (trogging, observability_deps, metrics) so making it easy to choose to include support for opentelemetry or not will be helpful

__Proposal:__
Follow the model for the object store functionality where AWS / S3 / Azure support is not enabled by default but must be compiled in via a feature flag. 

THe proposal is to  feature gate as many of the “opentelemetry” crates as possible under a new `opentelemetry` feature in both IOx and the dependent crates and this

The `opentelemetry` feature flag would default to false, but we would enable it for production builds

Without `opentelemtry`  enabled, only logging to stderr would be supported. Any attempt to use other open telemetry features will result in an error telling the user that IOx needs to be recompiled with the `opentelemetry` feature 

I will try and consolidate stuff in the observability / trogging / metrics crate (edited) 

__Current behaviour:__
Compile open telemetry all the time

__Desired behaviour:__
Only compile the opentelemetry crates when we want to use them

__Alternatives considered:__
Describe other solutions or features you considered.

**Comment by tustvold** [comment]
>  logging to stderr

Why not stdout? It would be nice to keep tokio-tracing in debug builds, as I use its filtering frequently, but just strip out the jaeger/otel stuff?

> like sending metrics to jaeger and open telemetry collectors

Definitely supportive of this - would be good to keep prometheus support though. For one thing the tests need it, but also because it is a useful tool for local development (it's like a more detailed system table), and should be a very lightweight dependency.

**Comment by alamb** [comment]
> Why not stdout? It would be nice to keep tokio-tracing in debug builds, as I use its filtering frequently, but just strip out the jaeger/otel stuff?

Yes, I should have said "keep doing the same thing as we do to day when `LOGGING_LEVEL` is set or `-v` / `-vv` are passed on the command line

**Comment by tustvold** [comment]
> @tustvold how do you configure / enable logging during development?

A combination of `LOG_FILTER` and `RUST_LOG`. The former seems to influence the server binary, and the latter tests. I'm not sure why they are different.

**Comment by tustvold** [comment]
The combination of the new tracing plumbing and the new metrics abstraction achieves this
