### ISSUE TITLE
Dropping Unpersisted Data Extends Replay Indefinitely

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#2207]
As data is ingested it is recorded in the PersitenceWindows data structure for a partition. This is entirely separate from the representation of this data in chunks.

When data is written to object storage, the corresponding window is flushed from the PersistenceWindows and a PartitionCheckpoint written to object storage.

If the trailing edge of a partition is dropped before it can be persisted, this causes a problem, as the PersistenceWindows contains writes that no longer actually exist in memory. We can't just flush them from the PersistenceWindows as doing so would create a situation where future DatabaseCheckpoints would be inconsistent with the last persisted PartitionCheckpoint for this partition (which still thinks there are writes to be persisted). 

However, not doing so will prevent the min seqno in the generated DatabaseCheckpoints from ever advancing past the min seqnos in the PersistenceWindows for this partition. As the DatabaseCheckpoints are the range in which replay occurs, this is problematic.

**Comment by crepererum** [comment]
Dropping unpersisted chunks when persistince is on is no longer possible as of #2295.
