### ISSUE TITLE
Dropping Unpersisted Data Causes Persistence Panic

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#2208]
Dropping unpersisted data can cause the PersistenceWindows to think it has writes that it doesn't, which in turn can trigger the lifecycle to try to persist data that it doesn't have. In an extreme case, this will cause a panic as it tries to persist an empty list of  chunks.

It should be able to detect the scenario where there are no chunks with a timestamp range that overlaps with that being persisted and generate an error at "plan" time. Properly recovering from this error will likely require the ability to generate a PartitionCheckpoint without a parquet file, in order to allow dropping the data from the PersistenceWindows

Relates to #2207

**Comment by crepererum** [comment]
Dropping unpersisted chunks when persistence is on is no longer possible as of #2295.
