### ISSUE TITLE
Delete Persisted Chunks

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#2210]
Currently nothing truncates the catalog's transaction history, and parquet files are only deleted once they are no longer referenced by the transaction history. This means it is currently impossible to delete data without deleting the entire catalog.

It should be possible to:

* Automatically prune the transaction history to some time period, after which "time-travel" is not possible
* Delete data now, e.g. to comply with GDPR

**Comment by crepererum** [comment]
> * Automatically prune the transaction history to some time period, after which "time-travel" is not possible

Done as a combination of #1554 and #2524.

**Comment by NGA-TRAN** [comment]
> Delete data now, e.g. to comply with GDPR

Since the `delete`  is available to do the soft delete and the `compact_object_store_chunks` and `compact_object_store_partition` available to do hard delete, this task is doable today. Let us close this ticket.
