### ISSUE TITLE
Replay Restore Fully Persisted Sequencer

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#2215]
It is assumed that consecutive PartitionCheckpoints are monotonically increasing that is:

* Later PartitionCheckpoints have the same or larger min/max seqno for each sequencer id than previous
* Later PartitionCheckpoints have the same or more sequencer ids than previous

This last point is currently not necessarily the case. Consider a scenario with two sequencer ids 0 and 1, and a partition that is fully persisted in sequencer id 0. On replay only writes from sequencer id 1 will be replayed to the partition. If the partition continues to not receive writes from sequencer id 0, it may persist a PartitionCheckpoint having never "seen" a write from sequencer id 0.

At the end of replay, all persistence windows should be "seeded" with the maximum values from their PartitionCheckpoint to ensure that future checkpoints are consistent. (NB: The DatabaseCheckpoint might contain sequencer ids that have never written to this partition, and so it must be the PartitionCheckpoint that is used)

**Comment by crepererum** [comment]
I agree. The seeding can be done at the end of replay (as you describe) or during catalog loading (aka before replay, from the persisted data).
