### ISSUE TITLE
feat:  multi-core line protocol conversion

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#225]
When running a command such as `delorean convert input.lp output` at the moment only a single CPU core is used; The goal of this ticket is to improve the speed of the conversion process by using multiple cores (and the pattern described in #223)

**Comment by jacobmarble** [comment]
@alamb #223 was closed a long time ago. Can this also be closed?

**Comment by alamb** [comment]
I don't think this is tracking any specific feature on the horizon -- we can revisit if/when we do bulk ingest fro historical data
