### ISSUE TITLE
Investigate why there is a big gap between memory allocation (jemalloc active) and actual chunk memory

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#2252]
__Steps to reproduce:__
The Memory Usage chart in [IOx Metrics dashboard](https://us-west1-1.gcp.cloud2.influxdata.com/orgs/2f5ec5d98a8d6526/dashboards/07f20d557feae000?lower=now%28%29%20-%203h) shows a big gap between memory allocation (jemalloc active) and memory used to store chunk.  

This is an example:
![Screen Shot 2021-08-10 at 10 10 29 AM](https://user-images.githubusercontent.com/20850014/128928957-46963689-f437-4628-8f91-2458c461902f.png)
In general, we observe that stats.allocated (the memory allocated by calling malloc and friends, from rust and C code) is ~twice as big as the memory reported by catalog_chunks_mem_usage_bytes

__Expected behaviour:__
The gap should be very small

__Actual behaviour:__
Since the gap is large, we think either we do not capture all the memory needed to store our chunk data (and all related such as statistics, dictionaries)  or our memory consumption during data life cycle is too much or some other mystery. 

The current plan is to use [heappy ](https://github.com/mkmik/heappy) to see what have been allocated to  investigate this.

Related ticket:

1. [Track total memory allocation used by DataFusion plans](https://github.com/apache/arrow-datafusion/issues/898)

**Comment by NGA-TRAN** [comment]
#2279  has integrate heappy to collect allocation profiles

**Comment by NGA-TRAN** [comment]
After collect several 150-second-profiles, here are the functions that take good amount and percentage of memory allocation.
1. `collect_rub` : between 20% (~150MB) and 30% (over 300MB). The read_buffer's `upset_table` and read_buffer's `record_batch_to_row_groups` are the two in that function that we may want to focus.
2. read_buffer's `read_filter` (or `materialized_rows`) gos up to 13% (~180MB)
3. Data deduplication that include these 3 main functions, SortPreservingMergeStream's `build_record_batch`, RecordBatchDeduplicator's `compute_ranges` and RecordBatchDeduplicator's `output_ranges`, fluctuates a lot from under 4% ( ~50MB) to 35% (~500MB).
4. `rd_kafka_transport_io_event` (mostly `rd_buff_alloc_segment` and `rd_kafka_msgset_reader_decompress`) goes up to ~31% (~30-MB). 
5. `stream_in_sequence_entries` goes up to over 40% (~527MB)
6. `persist_chunks` (or more specific parquet_file's `write_to_object_store` goes up to 13% (~130MB)

**Comment by mkmik** [comment]
Ok we have two problems:

1. The kafka ingest path appears to have a memory leak (or some kind of unbounded memory bloat) (link to ticket?)
2. We're using roughly 2x memory than reported by the chunk size estimate.

![image](https://user-images.githubusercontent.com/52673/130066321-c7ea02a8-8a1b-4943-b7de-0f5394f9b26f.png)

**Comment by mkmik** [comment]
this tick from now on only focuses on the systemic discrepancy between chunk sizes and used memory. The kafka memory leak issue is tracked in #2353

**Comment by mkmik** [comment]
We paused routing to query-3003 for over 1h now: 

![image](https://user-images.githubusercontent.com/52673/130080085-35ec2493-991e-4500-932e-5114e3576eab.png)


CPU usage has flattened out. We occasionally see some little CPU spikes and an accompanying memory usage spike:

![image](https://user-images.githubusercontent.com/52673/130080356-0c0a4b8a-3ea1-4c1b-9baa-12593a206b6d.png)

I assume that the wiggles in the memory usage prior the pause correspond to active memory used to perform whatever work was happening (gRPC ingestion, compactions, sorts etc), while the straight line at 40G captures actual memory that is associated with the chunks.

Two possibilities come to mind:

1. Our estimation is wrong; we're reporting that the chunks are 20G but in reality they are 40G
2. We don't drop some extra copy of the data that each chunk contains, perhaps some hydrated record batches that we keep attached to a chunk (directly or indirectly somehow), which gets cleared only when the next one gets used on this chunk (hence the size stays bounded)

**Comment by mkmik** [comment]
```
OBSERVER> select storage,sum(memory_bytes) as memory_bytes  from chunks group by storage;
+--------------------------+--------------+
| storage                  | memory_bytes |
+--------------------------+--------------+
| ObjectStoreOnly          | 152671040    |
| ReadBufferAndObjectStore | 21105089757  |
+--------------------------+--------------+

```

**Comment by mkmik** [comment]
I manually unloaded these chunks:

```
| influxql_query_log                                                    | 112  | 2021-08-19 12:00:00 | ReadBufferAndObjectStore | 194462677    |
| influxql_query_log                                                    | 72   | 2021-08-19 10:00:00 | ReadBufferAndObjectStore | 247946676    |
| influxql_query_log                                                    | 76   | 2021-08-19 12:00:00 | ReadBufferAndObjectStore | 265828533    |
| influxql_query_log                                                    | 138  | 2021-08-19 10:00:00 | ReadBufferAndObjectStore | 268888579    |
| influxql_query_log                                                    | 148  | 2021-08-19 09:00:00 | ReadBufferAndObjectStore | 278795412    |
| influxql_query_log                                                    | 160  | 2021-08-19 11:00:00 | ReadBufferAndObjectStore | 299825425    |
| influxql_query_log                                                    | 88   | 2021-08-19 11:00:00 | ReadBufferAndObjectStore | 304941440    |
+-----------------------------------------------------------------------+------+---------------------+--------------------------+--------------+
```

total reported in-memory usage for those unloaded chunks is `1.86 GB` (power of 10)

**Comment by mkmik** [comment]
The memory usage dropped by `2.35 GB`

**Comment by mkmik** [comment]
The total chunk size metric accurately reported a drop of 1.86 GB (like the system tables said)

**Comment by mkmik** [comment]
I added another dashboard that shows the ratio of total chunk vs total allocated memory


![image](https://user-images.githubusercontent.com/52673/130232878-2fe8244e-a709-4bdd-a28c-6f2e24292bba.png)

**Comment by mkmik** [comment]
CC: @e-dard, @crepererum 

We noticed that the problem got worse with a big table with high cardinality data, possibly having to do with dictionary encoding.

However, dictionary encoding is only used when the number of distinct values in a row group is above a certain threshold (currently `TEMP_CARDINALITY_DICTIONARY_ENCODING_LIMIT: usize = 100_000;`)

Our staging environment doesn't report any `DICT` value in the `read_buffer_column_total` metric, and yet exhibits this "gap".

Furthermore, I tried to run a smaller test locally where I forced the dictionary encoding (with `TEMP_CARDINALITY_DICTIONARY_ENCODING_LIMIT: usize = 10;`)

I wrote 2.8 million points with a load test tool (`bin/inch -bucket bucket -org org -host "http://localhost:8080" -v -c 10  -t 2,20,200,20000 -p 1`), in a local database configured with very small limits and a per-minute partition. See the full config with:

```json
{
  "rules": {
    "name": "org_bucket",
    "partitionTemplate": {
      "parts": [
        {
          "time": "%Y-%m-%d %H:%M:00"
        }
      ]
    },
    "lifecycleRules": {
      "bufferSizeSoft": "52428800",
      "bufferSizeHard": "104857600",
      "immutable": false,
      "persist": true,
      "workerBackoffMillis": "1000",
      "catalogTransactionsUntilCheckpoint": "100",
      "lateArriveWindowSeconds": 5,
      "persistRowThreshold": "100",
      "persistAgeThresholdSeconds": 15,
      "mubRowThreshold": "1000",
      "parquetCacheLimit": "0",
      "maxActiveCompactionsCpuFraction": 1
    },
    "workerCleanupAvgSleep": "500s"
  }
}
```

I stopped writing after 2.8 M rows and waited 20m until the lifecycle manager settled on:

```
; ./target/debug/influxdb_iox database query org_bucket "select table_name,id,partition_key, storage,sum(memory_bytes) as memory_bytes  from system.chunks group by table_name,id,partition_key, storage order by memory_bytes;"
+------------+-----+---------------------+--------------------------+--------------+
| table_name | id  | partition_key       | storage                  | memory_bytes |
+------------+-----+---------------------+--------------------------+--------------+
| m0         | 120 | 2021-08-23 22:56:00 | ObjectStoreOnly          | 1500         |
| m0         | 122 | 2021-08-23 22:56:00 | ObjectStoreOnly          | 1503         |
| m0         | 110 | 2021-08-23 22:57:00 | ObjectStoreOnly          | 1504         |
| m0         | 218 | 2021-08-23 22:57:00 | ReadBufferAndObjectStore | 2549051      |
| m0         | 217 | 2021-08-23 22:57:00 | ReadBufferAndObjectStore | 30062658     |
+------------+-----+---------------------+--------------------------+--------------+
```

Then I unloaded the 30MB chunk with:

```bash
curl -s 'localhost:8080/metrics' | grep jemalloc >/tmp/jemalloc.before
curl -s 'localhost:8080/metrics' | grep catalog_chunks_mem_usage_bytes >/tmp/catalog_chunks_mem_usage_bytes.before

./target/debug/influxdb_iox database partition unload-chunk org_bucket "2021-08-23 22:57:00" "m0" 217

curl -s 'localhost:8080/metrics' | grep jemalloc >/tmp/jemalloc.after
curl -s 'localhost:8080/metrics' | grep catalog_chunks_mem_usage_bytes >/tmp/catalog_chunks_mem_usage_bytes.after
```

Then I computed the differences between the before/after values in the jemalloc and catalog_chunks_mem_usage_bytes metrics

```
# jemalloc diff: 30692832
# chunk    diff: 30061154
```

The disagreement is 631678 bytes, which is ~2% of the chunk size.

**Comment by crepererum** [comment]
`TEMP_CARDINALITY_DICTIONARY_ENCODING_LIMIT` is a very good catch, I'll try to use that for another Massif profiling run.

**Comment by mkmik** [comment]
I tried to reproduce the problem locally by creating rub chunks manually and also loading a known bad rub chunk from parquet file directly.

basically I was doing:

```rust
    let chunk = read_chunk();

    let heap_profiler_guard = heappy::HeapProfilerGuard::new(1).unwrap();
    std::mem::drop(chunk);
    let report = heap_profiler_guard.report();
```

I initially didn't notice anything odd, e.g.:

```
rows: 17_393_771
chunk size: 195_049_367 
total freed bytes: 185_073_351
```

But then I measured the reported total used memory by jemalloc, with:

```rust
    let mem_before = allocated();
    std::mem::drop(chunk);
    let mem_after = allocated();
```

And here we see the discrepancy again:

```
289_608_720
```

Heappy measured `185_073_351`  and heappy hooks into every call to `free` and `realloc`.

So if jemalloc is reporting that we're now using less allocated memory (this doesn't count metadata or other pools) it means we're not seeing all allocations.

I'll try again with valgrind on linux now that I can reproduce this locally

**Comment by mkmik** [comment]
A chunk size 198931427:

Once the chunk is dropped, total bytes freed (measured by calls `free` and `realloc` asking `malloc_usable_size`): 192085864

It appears that now the RUB is overestimating.

For the record: this graph shows where the freed memory comes from:

![image](https://user-images.githubusercontent.com/52673/130796670-584a7d8e-4cd6-4217-8ff2-542b7b31b3b3.png)

**Comment by mkmik** [comment]
of there was a bug in heappy's stack-collapsing and we were missing some free.

I manually tracked all calls to malloc/free/realloc... and new numbers are pretty much on par with jemalloc:

```
chunk size: 94707133
hook freed mem: 117853008 (ratio: 1.2443942105184411)
jemalloc freed mem: 117314968 (ratio: 1.2387131178387587)
hook and jemalloc ratio: 1.0045862860398171
```

**Comment by mkmik** [comment]
I ran a simple test program with valgrind:

```rust
use rurub::read_chunk;

fn main() {
    std::thread::sleep(std::time::Duration::from_secs(5));
    println!("reading chunk");
    let chunk = read_chunk("./chunk2.parquet");
    println!("chunk size: {}", chunk.size());

    std::thread::sleep(std::time::Duration::from_secs(10));
    std::mem::drop(chunk);
    std::thread::sleep(std::time::Duration::from_secs(10));
}
```

The output was:

```
chunk size: 94707133
```

The heap profile:

![image](https://user-images.githubusercontent.com/52673/132363709-01010c54-a8de-4514-ace1-cf6f8d834914.png)



I drilled a bit in the biggest snapshot to see where the memory is spent.


47.6 | readbuffer upsert table to_vec |   |  
-- | -- | -- | --
15.8 | readbuffer encoding string rle |   |  
4.6 | readbuffer encoding ID rle |   |  
0.16 | random stuff |   |  
7.4 | readbuffer rowid encoding string rle |   |  
3.3 | readbuffer string rle |   |  
1 | readbuffer scalar u32 rle |   |  
7.7 | croaring run_container_grow ... string rle |   |  
0.58 | random stuff |   |  
5.4 | croaring bitmap_create .. string rle |   |  
2.9 | croaring realloc array .. string rle (push additional) |   |  
2.2 | to_vec some map+fold iterators ... StringEncoding |   |  
2.1 | croaring ... string rle |   |  
0.4 | stuff below massif threshold |   |  
0.38 | random stuff |   |  
0.36 | other randomg stuff |   |  
0.36 | other random stuff |   |  
0.182 | other minor croaring stuff |   |  
0.181 | other minor stuff |   |  
  |   |   |  
  |   |   |  
  |   |   |  
  |   |   |  
  |   |   |  
  |   |   |  
  |   |   |  
  | reported | unaccounted |  
107587043 | 94707133 | 12879910 |  
102.60 MiB | 90.32 MiB| 12.28 MiB |  

About 12MiB there are missing in the estimate. It's not immediately evident which call site(s) is the major culprit; could be a combination of multiple small things.

One thing we could do is to return a more detailed size break down from the chunk and not just the summed up "size". For example we could then compare if the estimated croaring bitmap size matches the measured one etc.

**Comment by crepererum** [comment]
@mkmik you can control the pruning behavior of Massif using `--threshold=` (values in percentage, `1.0` being the default). I had some success lowering that value to `0.1`, but I think everything below that is really just natural noise.

**Comment by mkmik** [comment]
Just to be clear: the 102MB captured by massif match what I measure with manually hooking malloc calls with heappy.

The "missing" 12MiB are the difference between that number and what our IOx code reports as the size of a chunk

**Comment by alamb** [comment]
Given the initial investigation seems to have been wrapped i, I am claiming this ticket done (enough) and closing it down. Please reopen if that is not correct
