### ISSUE TITLE
IOx Tracing

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#2273]
It should be possible to use distributed tracing (e.g. Jaeger) to observe IOx.

This has at least two pieces:
1. Respect the incling request headers to connect spans made in IOx to the overall trace id
2. For Query execution, add visibility into which operators spend what time.

For query execution visibility, we hope to see something like the following in our Jaeger instance:
<img width="689" alt="Screen Shot 2021-08-12 at 11 14 33 AM" src="https://user-images.githubusercontent.com/490673/129233137-0f08660b-2aeb-4f00-bb1c-8573da4a7ec7.png">

More details [here](https://docs.google.com/document/d/1oCWaiEAGPHpAFXagh3sBsu3PjshwfwEgn-qrBSGvg5A/edit?usp=sharing)

**Comment by alamb** [comment]
I think this one is done now -- @tustvold  let me know if that is not correct.

**Comment by tustvold** [comment]
Making a note of https://github.com/influxdata/influxdb_iox/issues/2549 and https://github.com/influxdata/influxdb_iox/issues/2367 which track further work in this space
