### ISSUE TITLE
test_server_shutdown fails consistently on laptop environment 

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#2275]
__Steps to reproduce:__
 RUST_BACKTRACE=1 cargo test influxdb_ioxd::tests::test_server_shutdown
    Finished test [unoptimized + debuginfo] target(s) in 1.02s
     Running unittests (target/debug/deps/influxdb_iox-9aed9678acc1540c)

running 2 tests
test influxdb_ioxd::tests::test_server_shutdown_uninit ... ok
test influxdb_ioxd::tests::test_server_shutdown ... FAILED

failures:

---- influxdb_ioxd::tests::test_server_shutdown stdout ----
thread 'influxdb_ioxd::tests::test_server_shutdown' panicked at 'serve shouldn't finish', src/influxdb_ioxd.rs:666:30
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:541:12
   1: influxdb_iox::influxdb_ioxd::tests::test_server_shutdown::{{closure}}
             at ./src/influxdb_ioxd.rs:666:30
   2: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/future/mod.rs:80:19
   3: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/future/future.rs:119:9
   4: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}::{{closure}}
             at /Users/nga/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/basic_scheduler.rs:208:62
   5: tokio::coop::with_budget::{{closure}}
             at /Users/nga/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/coop.rs:106:9
   6: std::thread::local::LocalKey<T>::try_with
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/local.rs:400:16
   7: std::thread::local::LocalKey<T>::with
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/local.rs:376:9
   8: tokio::coop::with_budget
             at /Users/nga/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/coop.rs:99:5
   9: tokio::coop::budget
             at /Users/nga/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/coop.rs:76:5
  10: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}
             at /Users/nga/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/basic_scheduler.rs:208:39
  11: tokio::runtime::basic_scheduler::enter::{{closure}}
             at /Users/nga/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/basic_scheduler.rs:299:29
  12: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/nga/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/macros/scoped_tls.rs:61:9
  13: tokio::runtime::basic_scheduler::enter
             at /Users/nga/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/basic_scheduler.rs:299:5
  14: tokio::runtime::basic_scheduler::Inner<P>::block_on
             at /Users/nga/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/basic_scheduler.rs:197:9
  15: tokio::runtime::basic_scheduler::InnerGuard<P>::block_on
             at /Users/nga/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/basic_scheduler.rs:452:9
  16: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /Users/nga/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/basic_scheduler.rs:157:24
  17: tokio::runtime::Runtime::block_on
             at /Users/nga/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/mod.rs:450:46
  18: influxdb_iox::influxdb_ioxd::tests::test_server_shutdown
             at ./src/influxdb_ioxd.rs:674:9
  19: influxdb_iox::influxdb_ioxd::tests::test_server_shutdown::{{closure}}
             at ./src/influxdb_ioxd.rs:651:11
  20: core::ops::function::FnOnce::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
  21: core::ops::function::FnOnce::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

failures:
    influxdb_ioxd::tests::test_server_shutdown

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 84 filtered out; finished in 0.33s

error: test failed, to rerun pass '--bin influxdb_iox'

**Comment by tustvold** [comment]
Is this still an issue?

**Comment by NGA-TRAN** [comment]
@tustvold I have not hit this anymore for a while

**Comment by NGA-TRAN** [comment]
no longer applicable
