### ISSUE TITLE
Heap usage statistics / metrics likely broken when heappy is not enabled

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#2288]
@mkmik  points out: https://github.com/influxdata/influxdb_iox/pull/2279/files#r688568347 we have likely broken our memory usage statistics when adding heappy support

__Expected behaviour:__
We should remove `features = ["unprefixed_malloc_on_supported_platforms"]` only when heappy is enabled.

Otherwise our memory tracking metrics (which depend on jemalloc statistics) will be off because they won't be capturing croaring bitmaps

__Actual behaviour:__
`unprefixed_malloc_on_supported_platforms` has been removed entirely

**Comment by alamb** [comment]
FYI @mkmik and @NGA-TRAN

**Comment by mkmik** [comment]
We have enabled heappy (or at least we intended to) in the perf build target of circleci

**Comment by alamb** [comment]
https://github.com/influxdata/influxdb_iox/pull/2279#discussion_r689004773 is the location
