### ISSUE TITLE
Catalog checkpoints must include partition/database checkpoints

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#2318]
# Abstract
The checkpoints of the persisted catalog are currently a list of parquet files:

https://github.com/influxdata/influxdb_iox/blob/817ed4b46bd58c6d9278781d5b7d751cbdce178a/generated_types/protos/influxdata/iox/catalog/v1/catalog.proto#L55-L63

This corresponds to the set of persisted chunks that are present when the catalog checkpoint is created. For replay however we also need the database checkpoint and the latest partition checkpoints. These are normally in one of the chunks .... as longs as we don't drop any data (via `drop_partition` or `drop_chunk`).

# Example
Imagine the following scenario:

1. add new chunk
2. persist chunk (new transaction is created)
3. remove chunk (new transaction is created)
4. create catalog checkpoint

If we would just replay the catalog including step 3, everything works because we have the partition and database checkpoint persisted in step 2.

If we however start at the catalog checkpoint created at step 4, no such replay-related data will be left because the set of chunks (and therefore parquet files) will be empty.

# Impact
Note that this can only happen when the user deleted very recent data (it must be within the replay range of the last `DatabaseCheckpoint` or it must be the entire data so no db checkpoint remains). So the practical impact is rather low. The user experience of re-appearing data is "not nice" though.

# Proposal
1. Add a new action to the catalog named `MarkCheckpoints` that stores a single database checkpoints and a list of partition checkpoints
2. Whenever we persist data, store the last partition checkpoint within the in-memory partition
3. When creating a database checkpoint, also collect the data from step 2 and add them into the new action from step 1 (the database checkpoint can easily be created out of the partition checkpoints)
4. During catalog loading, also take these checkpoints into account for replay planning
5. During catalog loading, remember to re-init the "last partition checkpoint" from step 2 based on the `MarkCheckpoints` actions and the parquet files

**Comment by pauldix** [comment]
Not relevant to NG (new) catalog.
