### ISSUE TITLE
Support creation of a new database from a set of parquet files in object storage

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#2369]
__Use case:__
When working on query performance, I want to be able to run experiments locally on a subset of the actual data we have in the internal clusters. I can find the parquet files with the relevant data fairly quickly given the predictable naming convention, and there is code to "rebuild" a catalog from parquet files in the repo: https://github.com/influxdata/influxdb_iox/blob/main/parquet_file/src/rebuild.rs

However, this did not appear to be hooked up to anything in the server yet

I also imagine that  if we discover that the size of a catalog has grown too large and we want to do a manual purge, it would be nice to be able to nuke the catalog, clean up all parquet files we don't want to be part of the database, and then have IOx rebuild its state. 

__Proposal:__
Basically I would like a `rebuild` command from the CLI / management API that works like this:  
```shell
./target/debug/influxdb_iox database recover rebuild --force my_db 
```

This would:
1. Shutdown the `my_db` database (if it exists)
2. Wipe any catalog information that is present (not the rules.pb files but `transactions`)
3. Rebuild the catalog using any parquet files found in the appropriate place in object storage

__Current behaviour:__
If you delete the catalog, on startup IOx treats the catalog as empty (rather than rebuilding it)

Here is what I tied:

Step 1: Start IOx in one terminal:
```shell
./target/debug/influxdb_iox run --object-store=file --data-dir=$HOME/.influxdb_iox --server-id=42
```

Step 2: Create a new database + load data + make parquet files
```shell
./target/debug/influxdb_iox database create my_db
# Edit the config:
./scripts/edit_db_rules  localhost:8082 my_db
```

Set to the following (note I want to be persisting chunks immediately)
```json
{
  "rules": {
    "name": "my_db",
    "partitionTemplate": {
      "parts": [
        {
          "time": "%Y-%m-%d %H:00:00"
        }
      ]
    },
    "lifecycleRules": {
      "bufferSizeSoft": "52428800",
      "bufferSizeHard": "104857600",
      "immutable": false,
      "persist": true,
      "workerBackoffMillis": "1000",
      "catalogTransactionsUntilCheckpoint": "100",
      "lateArriveWindowSeconds": 1,
      "persistRowThreshold": "1",
      "persistAgeThresholdSeconds": 1,
      "mubRowThreshold": "1",
      "parquetCacheLimit": "0",
      "maxActiveCompactionsCpuFraction": 1
    },
    "workerCleanupAvgSleep": "500s"
  }
}
```

Then feed data:
```shell
./target/debug/influxdb_iox database write my_db tests/fixtures/lineproto/metrics.lp
```

Which resulted in a bunch of parquet files 💯  on disk:
```
/Users/alamb/.influxdb_iox/42/my_db/data/diskio/2020-06-11 16:00:00/2.d792621f-0c70-4757-acb6-fa28a82f3904.parquet
/Users/alamb/.influxdb_iox/42/my_db/data/net/2020-06-11 16:00:00/2.2a58dbcf-b8a0-48e0-8940-e0e7d8c6aaa9.parquet
/Users/alamb/.influxdb_iox/42/my_db/data/cpu/2020-06-11 16:00:00/2.99861ab2-d516-41ec-802a-5eb233eca525.parquet
/Users/alamb/.influxdb_iox/42/my_db/data/processes/2020-06-11 16:00:00/2.8d249e1c-226a-4c7c-8f44-22c1095f7241.parquet
/Users/alamb/.influxdb_iox/42/my_db/data/swap/2020-06-11 16:00:00/2.20f00d0a-c102-4ea2-abd7-f2ab8c0e9e4d.parquet
/Users/alamb/.influxdb_iox/42/my_db/data/system/2020-06-11 16:00:00/2.868c1f16-21dc-43b7-b24b-d5113188fc32.parquet
/Users/alamb/.influxdb_iox/42/my_db/data/disk/2020-06-11 16:00:00/2.05df9b93-b266-408d-85a8-1c44645d16d3.parquet
/Users/alamb/.influxdb_iox/42/my_db/data/mem/2020-06-11 16:00:00/2.1086108f-097b-49d3-985f-4c4e85861435.parquet
```

Step 3: Manually wipe catalog
I can "wipe" the catalog by deleting  the transaction files

First I stopped the `influxdb_iox` process

```shell
rm -rf ~/.influxdb_iox/42/my_db/transactions
```

Step 4: Attempt to Restart / recreate  Database
Then I restarted the IOx process
```shell
./target/debug/influxdb_iox run --object-store=file --data-dir=$HOME/.influxdb_iox --server-id=42
```

Without anything from me, it makes a new catalog (`transactions` directory) and brings the database up as though it were a new empty one:

```shell
ls ~/.influxdb_iox/42/my_db/transactions/
00000000000000000000/
```

```shell
(arrow_dev) alamb@MacBook-Pro:~/Software/influxdb_iox$ ./target/debug/influxdb_iox sql
Connected to IOx Server
Set output format format to pretty
Ready for commands. (Hint: try 'help;')
> use my_db;
You are now in remote mode, querying database my_db
my_db> show tables;
+---------------+--------------------+---------------------+------------+
| table_catalog | table_schema       | table_name          | table_type |
+---------------+--------------------+---------------------+------------+
| public        | system             | chunks              | BASE TABLE |
| public        | system             | columns             | BASE TABLE |
| public        | system             | chunk_columns       | BASE TABLE |
| public        | system             | operations          | BASE TABLE |
| public        | system             | persistence_windows | BASE TABLE |
| public        | information_schema | tables              | VIEW       |
| public        | information_schema | columns             | VIEW       |
+---------------+--------------------+---------------------+------------+

Returned 7 rows in 10.18793ms
```

__Desired behaviour:__
See above

**Comment by crepererum** [comment]
While I agree with the use case, I'm not sure if the concrete step-by-step example you give is what we want. Feeding parquet files into a running DB is a bit of a violation of how we use object store: the IOx node should be the only party touching its "subtree" of the object store. Also the files you create are no different from stale files and will therefore be cleaned up (=deleted) by IOx.

So I would rather propose that we should create the parquet files first and THEN create the DB w/ a special flag like "instead of creating a new catalog, rebuild one from existing files". How about that?

**Comment by alamb** [comment]
> So I would rather propose that we should create the parquet files first and THEN create the DB w/ a special flag like "instead of creating a new catalog, rebuild one from existing files". How about that?

@crepererum I think what you suggest sounds good; One thing I was thinking was figuring out "where do I create the parquet files (aka at what paths)?" especially as the storage gets more specialized -- e.g. @carols10cents  adding generations https://github.com/influxdata/influxdb_iox/pull/2355 etc) this might be non trivial

**Comment by crepererum** [comment]
Mmh, if the IOx node can stand the traffic, I think offering an "upload parquet" API would be nice. So the "user" (which isn't really an end user I think) doesn't need storage creds and construct the path.

In general the parquet handling is (at the moment, can be fixed!) very expert-like because it's not only about the parquet files, their tabular content and the paths but also about the special metadata that we expect them to have.

**Comment by alamb** [comment]
Yeah, if we ever wanted to use this tool for end users (rather than developers) having a proper API is a must

**Comment by capkurmagati** [comment]
>So I would rather propose that we should create the parquet files first and THEN create the DB w/ a special flag like "instead of creating a new catalog, rebuild one from existing files". How about that?

+1 for this idea. Actually, I ran into a situation that files got cleaned up by IOx. (It was caused by #2278 and has been resolved via #2361.)

I haven't looked into the details of #2355, but I wonder if this could work.
1. Shutdown the server
2. Increase `genernation_id` and put all files into the new directory
3. Run `rebuild` command which a) Builds catalog information, b) Set the `current active database id` (Or maybe the server will use the largest id automatically), c) (Optional) Wipes out the files of old generations.

It will be very useful for development.

**Comment by pauldix** [comment]
Not relevant to NG (new) catalog.

**Comment by crepererum** [comment]
> Not relevant to NG (new) catalog.

I disagree. Rebuilding a catalog from parquet files is also a feature that doesn't depend on the form of the catalog. We argue though if we wanna have this feature at all.

**Comment by alamb** [comment]
For what it is worth, I think the detailed description on this ticket is quite out of date -- in order to support re-creating a database / namespace from parquet files in the NG world, it would need some significant updating

**Comment by alamb** [comment]
Yes, I agree -- this can be done via `cargo debug build-catalog` -- thanks @crepererum
