### ISSUE TITLE
Simplify dependency between reader and its size

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb_iox#237]
maybe we could define a trait like `ReaderSize` or something that knows how to provide size and add that constraint to `convert` -- aka ` R: BufRead + Seek + ReaderSize`  rather than having to use a pair.

_Originally posted by @alamb in https://github.com/influxdata/delorean/pull/229_

**Comment by jacobmarble** [comment]
@e-dard can this be closed?
