### ISSUE TITLE
Table called "table" breaks SQL query

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#2389]
Not sure if this is a bug or an intended behaviour but the following code

```
flight
    .perform_query("database", "select * from table;")
    .await
    .unwrap();
```

Results in

```
called `Result::unwrap()` on an `Err` value: GrpcError(Status { code: InvalidArgument, message: "Error while planning query: SQL error: ParserError(\"Expected (, found: ;\")", metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Tue, 24 Aug 2021 12:46:09 GMT"} }, source: None })
```

I think this might be a bug in the SQL parser, or some feature of the SQL dialect I'm not familiar with

**Comment by alamb** [comment]
@tustvold  does the following work (note the extra `"`):
```sql
select * from "table";
```

**Comment by tustvold** [comment]
@alamb 

```
select * from "table"
```

And 

```
select * from cpu
```

Both work

**Comment by alamb** [comment]
I believe this is working as expected / per the SQL spec (where you use double quotes if you want to use SQL reserved words such as `TABLE` or `FROM` as identifiers

**Comment by alamb** [comment]
https://xkcd.com/327/

**Comment by tustvold** [comment]
> I believe this is working as expected / per the SQL spec (where you use double quotes if you want to use SQL reserved words such as TABLE or FROM as identifiers)

Aah, makes sense. I had figured it would be context-sensitive but I guess not :+1:

**Comment by alamb** [comment]
FWIW IOx is consistent with postgres (which is consistent with the standard):

```sql
alamb=# create table "table" (x int);
CREATE TABLE
alamb=# select * from "table";
 x 
---
(0 rows)

alamb=# select * from table;
ERROR:  syntax error at or near "table"
LINE 1: select * from table;
                      ^
```
