### ISSUE TITLE
Add distinct count to system.column_chunks

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#2393]
__Use case:__
Understanding details of what data is stored in chunks is helpful to understand the shape of the data. 

__Proposal:__
Add a `distinct_count` column to `system.chunk_columns`

The distinct count is available in partition_metadata:
https://github.com/influxdata/influxdb_iox/blob/0aa81bf405e1abf294b677ca299d94be62573e02/data_types/src/partition_metadata.rs#L318-L326

It should be a matter of hooking it into the code that creates `system.chunk_columns`
https://github.com/influxdata/influxdb_iox/blob/a6c9cc2bf294d113f66f85401a47e94206a93803/server/src/db/system_tables/columns.rs#L175-L197

__Current behaviour:__
No way to get access to the distinct count

**Comment by e-dard** [comment]
I've been fixing this as part of the sketch branch I have going on.

**Comment by alamb** [comment]
this is no longer relevant in IOx's architecture (there is no column_chunks system table)
