### ISSUE TITLE
Store only the database rules sent by the client (do not store default values)

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#2409]
__Use case:__
As described on an internal ticket https://github.com/influxdata/conductor/issues/468, the current behavior of IOx on database creation or a rules update is to fill in any missing values with their (current) defaults and save that configuration file to object store.

Not only is this behavior confusing, it makes the logic to keep configurations synchronized across multiple IOx nodes more challenging. 

__Proposal:__
1. IOx will store in object store exactly the configuration supplied by the client, 
2. The API to get database rules will have two modes:
Mode 1: Return the current configuration that is being used by the server, with all default values filled
Mode 2: Return the persisted configuration (aka only what was supplied when the database was created or last modified)

__Current behaviour:__
Given this chain of events:
1. Send a configuration to a server
2. Update the server software
3. Send the *exact same* configuration to the server running the new software

The effective configuration (the values used by the server's operation) can change (if the software has new default values). 

__Desired behaviour:__
If a  user sends the same config to a server, updates the server software and then send the same config, the server's effective configuration (the values it uses at runtime) will be the same.

__Alternatives considered:__
1. Require the user to send the entire configuration and if any fields are missing reject the request. This would likely require some additional "upgrade and persist upgraded configuration" type logic
2. Do nothing -- complicates conductor and any other software that is trying to manage the configuration of IOx, especially when trying to keep the configurations in sync

**Comment by pauldix** [comment]
Sounds good to me. FWIW the reasoning for storing the actual default values and using them going forward was specifically to address the issue of a new release changing defaults. We had this crop up multiple times with InfluxDB over the years where a default configuration value was updated, users would upgrade their server and then get a surprise when some behavior or performance changed as a result of the new default.

But this simplifies things, so 👍. We can give users a way to actually save the default values if they wish to.

**Comment by alamb** [comment]
👍  makes sense. I think this proposal allows a way to save the defaults if they want -- which would be to get the configuration values via "give me the entire config API" and then update the rules explicitly.

**Comment by domodwyer** [comment]
Perfect! Thanks for working through this 👍

**Comment by alamb** [comment]
Design goals from @tustvold : 

> Makes total sense to me, I'd only ask that we keep data_types::DatabaseRules not containing a load of option, etc... i.e. keep the optionality confined to the generated_types type if possible

I think I can do that 👍
