### ISSUE TITLE
doc: Write up design for CPU heavy task prioritization / resource management

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#241]
From the discussion and documentation in https://github.com/influxdata/delorean/pull/227 and #240 we still need to sort out is how to do resource management for processing in delorean

Issues such as:
* How are CPU heavy background tasks (e.g. data rearrangment) paused / pre-empted by higher priority tasks like query processing
* How can resources other than CPU (memory being the big one, but also open file handles, etc) be released during processing if needed? 

These all fall under the heading of "resource management" in other systems and we will need a design for them eventually

**Comment by jacobmarble** [comment]
@alamb can this issue be closed?

**Comment by alamb** [comment]
Realistically I don't think this ticket is adding much value -- when we are ready for a larger resource management project, we'll need a design, but making a new one is likely just as easy as finding this one
