### ISSUE TITLE
Metrics for Operations

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#2416]
__Use case:__
Being able to see operations over time and reason about their effects on other metrics (like memory/CPU usage, chunk creations etc.).

__Proposal:__
Expose most of the data that we currently have within this system table as metrics as well:

https://github.com/influxdata/influxdb_iox/blob/c81a65040904050156187ca768005fce895d7ac4/server/src/db/system_tables/operations.rs#L46-L63

__Current behaviour:__
Users have to use the system table, but that's somewhat messy because you cannot easily fold that into a dashboard + the table is gone after restarts.

**Comment by mkmik** [comment]
Poor man's approach:

```
./target/debug/influxdb_iox operation list | jq '.[]|select(.job.PersistChunks)|.wall_time.secs' | datamash perc:50 1 perc:90 1 perc:95 1 perc:97 1 perc:99 1 perc:100 1
0	106.8	112.7	125.4	142.18	150
```
