### ISSUE TITLE
Custom extensions to DatabaseRules

### ISSUE THREAD

**Issue by mkmik** [influxdata/influxdb_iox#2417]
Applications built on top of IOx may require adding extra information to every database. A common approach is to add a set key/value pairs to the schema. 

Here instead I propose to use a typed extension pattern using the protobuf [Any](https://developers.google.com/protocol-buffers/docs/proto3#any) mechanism. `Any` is used for example in gRPC to encode custom error details in error status responses.

```proto
import "google/protobuf/any.proto";

message DatabaseRules {
  // ...
  repeated google.protobuf.Any metadata = 13;
}
```

This `metadata` field can contain any protobuf message and its schema doesn't need to be known by the IOx server. The type of the *Any* payload message is encoded in the *Any* value.

If a client wants to use simple key/value pairs, all it takes is to pass a metadata payload that contains such a key/value set:

```proto
message LabelMetadata {
  map<string, Project> label = 1;
}
```

Otherwise the client can provide a more structured/typed message type.

Another advantage is that if you have multiple layers (a client that uses a framework that uses iox) each layer can have their own messages (possibly using key/value pairs), and each layer's custom metadata will be properly namespaced.

---

Caveat: prost support for `Any` is still in progress, see https://github.com/tokio-rs/prost/issues/277
but that's what happens when we choose rust, it's on us to help push the ecosystem.

**Comment by jacobmarble** [comment]
This feature makes sense. Why not just use string values? The customer can use JSON for composite and typed values, and I suspect most will just store bare string values. Also, string values are much easier to code for than protobuf `Any` types.

**Comment by alamb** [comment]
> This feature makes sense. Why not just use string values?

There is a lot of discussionon the pros / cons of using strings vs Protobuf `Any` on this ticket as well: https://github.com/influxdata/influxdb_iox/issues/3095#issue-1052101143

**Comment by mkmik** [comment]
I'm less concerned about the extensibility of something like the DatabaseRules of an active DB as I was with the extensibility of the permanent record about why a database has been disowned.

**Comment by carols10cents** [comment]
This isn't relevant anymore as DatabaseRules proto is no longer a thing.
