### ISSUE TITLE
Static Configuration

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#2436]
**Use Case:**

Currently IOx can only be provided with limited configuration at startup, specifically only server-global settings. This makes it tricky to manage declarative deployments of IOx, requiring some sort of sidecar or controller to push configuration into the IOx server once it has started.

It would be beneficial for integration tests, benchmarks, and possibly even some simple deployment scenarios, to be able to run IOx in a mode where the DatabaseRules are sourced from a set of configuration file(s) on startup. This would put IOx inline with most cloud-native tooling such as nginx, envoy, prometheus, telegraf, datadog-agent, etc...

**Proposal:**

Add a command line option `--conf-file` that instructs IOx to use the provided configuration file for database configuration.

Running with this option would disable the management API endpoints to mutate/delete database configuration, and would disable persistence of the rules files to object storage.

This JSON/YAML/TOML file would contain a list of DatabaseRules for this IOx instance. Additionally to avoid confusion with the database deletion tombstones, it should include the object store prefix for this database.

**Auto-reload:**

Not necessary for the first version, but the ability to auto-reload the configuration on update would make for a very compelling experience when combined with Kubernetes ConfigMaps. These can be mounted as regular files, and updated declaratively using standard Kubernetes tooling. When a ConfigMap is updated, the file mounted into any running containers is also updated. This is a very common pattern in kubernetes for services where restarts are not always desirable, e.g. ingress controllers.

Add a command line option `--autoreload` that instructs IOx to watch the provided configuration file, and apply any updates. If the config is invalid, or a database cannot be updated, the system should continue to operate with the old configuration and repeatedly log an error until the situation is resolved. 

Of course if this IOx replica is then restarted, it will lose this old configuration and be unable to startup with the new configuration, but this is a compromise - we avoid a typo bringing down the cluster at the cost of additional operator overhead. FWIW [nginx has the same behaviour](https://nginx.org/en/docs/control.html).

If a database is removed from the configuration, IOx should just forget about it - it should not write a delete tombstone as we cannot guarantee this will always take place (e.g. if the server is restarted before it has time to write it).

**Desired Behaviour:**

It should be possible to bring up an IOx instance, with statically configured databases

**Alternatives Considered:**

A bash pod that is provided with the configuration, and on startup waits for the server to start and then writes it out to the management API

**Comment by alamb** [comment]
sounds like a useful feature to me, though one that would be non trivial to implement

**Comment by tustvold** [comment]
Correct me if I'm missing something, but the non-trivial part is the patch logic to reconcile updates. Unless I'm mistaken we need this logic anyway to support database rules updates over the management API - all this ticket does is change where the updates come from?

**Comment by alamb** [comment]
I guess I was assuming that we would have to maintain the existing "update rules via API" as well as a 'read from config' --  I don’t necessarily think the code is all that complicated but was more thinking about having to maintain (and test) the dual config path. Not impossible, just more work (and I am likely being a crumudgeon)

**Comment by e-dard** [comment]
I think a config file is useful. I think the only thing to figure out is how the interaction between the management API might work. 

The main thing I think we need to hint to operators (or document clearly) would be that the way to get the current config is via the API and that it might differ from the contents of a loaded configuration file.

**Comment by tustvold** [comment]
> might differ from the contents of a loaded configuration file.

Why would it differ? I'd envisaged that you'd disable the mutation APIs when running in the static config mode to avoid this potential confusion?
