### ISSUE TITLE
High (200GB+) memory use when converting TSM (fully compacted?) to parquet 

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#245]
While converting some TSM data from our internal tools cluster, I
found the `delorean convert` command requires large amounts (100s of
GB) of memory do the conversion. It requires so much memory, in fact,
that it was not possible to complete the conversion at all for some
files on my fairly beefy laptop.

For example, running `delorean` to convert the file below takes ~200GB
of virtual address space before I have to kill it.

Reproducer:

1. Download this ([google drive link](https://drive.google.com/file/d/1bMpZGItDdLDZsWZsP-8A2-zZuOgc9See/view?usp=sharing), ask me if you need access) file
2. Uncompress: `bunzip 000000000068612-000000045.tsm.bz2`
3. Try and convert to tsm: `delorean -vv convert 000000000068612-000000045.tsm /tmp`

If you watch the memory consumed by the delorean process it will be
"very large" -- it got to reported ~200GB on my machine before I had
to kill it. During this time it is doesn't even start writing even a
single parquet parquet file

![Screen Shot 2020-07-15 at 6 35 21 AM](https://user-images.githubusercontent.com/490673/87536632-65331880-c667-11ea-80bc-8d695744fed1.png)

Note this is a 2G TSM file, but compresses to only 321M using bzip2
(which is a lower compression ration than many of the other files)

```
2.0G    /Users/alamb/Software/tsm_memory/000000000068612-000000045.tsm                                         |
321M    /Users/alamb/Software/tsm_memory/000000000068612-000000045.tsm.bz2   
```

**Comment by jacobmarble** [comment]
@alamb can this be closed?

**Comment by alamb** [comment]
Yeah, this is not relevant anymore (as we don't have the aforementioned code anymore)
