### ISSUE TITLE
Delete Predicate API

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#2463]
This is a part of Support Soft Delete #2396 that defines what Delete API we will support in IOx. The goal is to try to make it compatible with [Influx Delete](https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/delete/) as much as possible. However, since Flux needs something that IOx does not provide such as `bucket` and `org`, Flux Delete API and IOx Delete API are not equivalent. 

### [IOx Delelete API](https://github.com/influxdata/influxdb_iox/blob/fdfec8fa4f1c91653631a7f0ff016ddf7f0bb64c/generated_types/protos/influxdata/iox/management/v1/jobs.proto#L154) includes:

1. `db_name` 
2. `table_name` :  equivalent to Flux's `measurement` but Flux specifies measurement in the `predicate` below instead of providing it in a separated field. @e-dard I am debating where to keep this as a separated field  or we extract it from the `predicate`. What do you think?
3. `delete_predicate` :  equivalent to Flux's `predicate` without measurement (or we can make it with measurement, too). Currently, Flux only supports conjunctive predicate of binary expressions of `=` and `!=` and IOx will stick with this.
4. `start_time` : equivalent to Flux's start
5. `stop_time` : equivalent to Flux's stop

Comparing with Flux's syntax, here is some IOx valid examples:

#### Delete everything from table named `example-measurement`
```
db_name:  your_db_name
table_name: example-measurement   (or we do not have this field at all)
delete_predicate: either empty   or _measurement="example-measurement" depending on our decision to go with separated table_name or not
start_time: 1970-01-01T00:00:00Z
stop_time: $(date +"%Y-%m-%dT%H:%M:%SZ")
```

#### Delete points in a measurement with a specific tag value
```
db_name:  your_db_name
table_name: example-measurement
delete_predicate:  host="old-host"  (AND _measurement="example-measurement") -- the one in parentheses depend on design
start_time: 1970-01-01T00:00:00Z
stop_time: $(date +"%Y-%m-%dT%H:%M:%SZ"
```
#### Delete all points within a specified time frame for all tables
```
db_name:  your_db_name
table_name:  empty
delete_predicate: 
start_time: 2020-03-01T00:00:00Z
stop_time: 2020-11-14T00:00:00Z
```

#### Delete all points within a specified time frame for a specified table and its tag and field
```
db_name:  your_db_name
table_name:  example-measurement
delete_predicate: host="old-host" AND district=10 (AND  _measurement="example-measurement")
start_time: 2020-03-01T00:00:00Z
stop_time: 2020-11-14T00:00:00Z
```

### Some highlight of invalid expressions and the parser will throw error

1. Time is not in timestamp format
2. String is not embedded in double quotes such as `city=Boston`. The valid one is `city="Boston"`. From [Flux's parser tests](https://github.com/influxdata/idpe/blob/master/influxdbv2/predicate/parser_test.go) , it looks like we need to support string without embedded in double quotes. In Flux, `city=Boston` and `city="Boston"` are the same.
3. `or` expression such as `city="Boston" or city="New York"
4. invalid binary comparison such as `>`, `<`, `<=`, ....

### Questions 
1. Will we support tag and field with spaces, such as `"city name"`. I will verify with test in IOx

**Comment by pauldix** [comment]
I think the `table_name` should be its own field and not in the predicate. I would have two API endpoints, one where the table name is specified (and required) and another where it isn't specified. I split them in two because it feels like a footgun to me. The API that doesn't require a table name should be harder to call (or require an extra flag).

Column names and values need to support spaces and anything else InfluxDB 2.0 supports (except in places where we had a bug on the ingest path and allowed invalid characters in (non-utf, etc).

**Comment by jacobmarble** [comment]
Under "Delete everything from table named example-measurement", what is the value of `stop_time`?

For deleting without time bounds, why not leave `start_time` and `stop_time` unset?

**Comment by NGA-TRAN** [comment]
> Under "Delete everything from table named example-measurement", what is the value of stop_time? 
For deleting without time bounds, why not leave start_time and stop_time unset?

@jacobmarble That was the syntax of [Flux Delete](https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/delete/#delete-all-points-within-a-specified-time-frame). I think the purpose is avoid delete everything by accident but @e-dard knows this better as he asked me to include that

**Comment by NGA-TRAN** [comment]
Done in #2488
