### ISSUE TITLE
Database stuck in error state due to transient error while reading S3 

### ISSUE THREAD

**Issue by mkmik** [influxdata/influxdb_iox#2483]
after restarting a router a database was stuck in an error state. The cause of the error appears to be due to a transient error while reading from the object store 

```
      {
        "dbName": "844910ece80be8bc_3c0bd4c89186ca89",
        "error": {
          "message": "error finding active generation directory in object storage: AWS S3-based Object Store error: Unable to list data. Bucket: toolsus1.a.influxcloud.net-iox, Error: Request ID: None Body: \u003c?xml version=\"1.0\" encoding=\"UTF-8\"?\u003e\n\u003cError\u003e\u003cCode\u003eInternalError\u003c/Code\u003e\u003cMessage\u003eWe encountered an internal error. Please try again.\u003c/Message\u003e\u003cRequestId\u003eDM2BQRWCZMQPZ2E4\u003c/RequestId\u003e\u003cHostId\u003eHrNj5drKDiJ0tK1tRmMxLKOAtK5HhxMaOxvjYn9by/CflmEGEYt56LroHz7lNUD0OeFmntOAduw=\u003c/HostId\u003e\u003c/Error\u003e"
        },
        "state": "DATABASE_STATE_KNOWN"
      },
```

**Comment by crepererum** [comment]
CC @carols10cents

**Comment by alamb** [comment]
For what it is worth, I recommend adding logic to *all* AWS s3 calls in the `object_store` that retry the operation if they get back an internal error.

Perhaps by implementing some wrapper (e.g. `RetriedStore`, like `ThrottledStore` https://github.com/influxdata/influxdb_iox/blob/main/object_store/src/throttle.rs#L85) which would handle the retry logic

I think most object store implementations are likely to have such transient errors during communication, so being able to retry them will improve the resiliency of IOx in general (not just delete operation)

**Comment by crepererum** [comment]
1. I would implement retries within the actual store implementation rather than the wrapper because:
   - some cloud SDKs already implement retries
   - retry logic can be cloud-specific (e.g. multi-PUT file uploads, do you retry the whole upload or just the single request)
2. note that a generic retry wrapper would need unlimited buffering for generic retries, because our uploads are based on an async stream and w/o assuming anything about the cloud provider, you need to buffer the whole stream and retry the upload from thestart

**Comment by alamb** [comment]
I think the most important thing is to retry all S3 operations (not just specific calls related to IOx delete), and it sounds like that is the plan 💯 !

**Comment by carols10cents** [comment]
I've opened https://github.com/influxdata/influxdb_iox/issues/2645 for retrying Google Cloud Storage requests and https://github.com/influxdata/influxdb_iox/issues/2647 for retrying Azure blob storage requests.
