### ISSUE TITLE
Clean up / Simplify file stats interface in delorean_parquet/src/stats.rs

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#252]
As mentioned by @e-dard  and @carols10cents in https://github.com/influxdata/delorean/pull/250#discussion_r457421286, the interface in `delorean_parquet/src/stats.rs` could perhaps be simplified rather than requiring 5 trait bounds

**Comment by jkurian** [comment]
Hi, I am wondering if this is a task would be beginner-friendly? If so, I would be happy to take a stab at it!

**Comment by alamb** [comment]
Hi @jkurian ! If you wanted to take a shot at simplifying the code that would be great!

I suspect this is a beginner-to-iox friendly task, though perhaps not so beginner-to-Rust friendly.

There is not  much specific guidance to offer here -- the comments linked above basically say "this implementation seems overly complicated" (which I happen to agree with). However, I am not sure exactly how it would get simplified, though I haven't thought about it much so it may be that I was still learning Rust when I wrote this code. 

Note the file location of the referred code is now: https://github.com/influxdata/influxdb_iox/blob/main/ingest/src/parquet/stats.rs

**Comment by jacobmarble** [comment]
@alamb can this be closed?

**Comment by alamb** [comment]
Yeah this code is all gone. Removing
