### ISSUE TITLE
WriteBufferConsumer Partitioning Has No Effect

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#2534]
**Problem**

Currently data is partitioned within the routing tier and then sent as an already partitioned flatbuffer, to the write buffer. 

The query servers then pull these entries off the queue and enqueue them into the partitions identified by the entry. This ignores any partitioning that might be configured for that query server. This is rather confusing.

**Proposed Solution**

Store a non-partitioned data representation in the write buffer, possibly even the binary write protocol proto messages, and perform the partitioning in the query servers. 

This would potentially also allow eliminating flatbuffers as a dependency, which would have some other benefits:

* Removes a non-trivial dependency
* Removes a fairly large source of unsafe with currently very limited validation logic.
* Removes a significant amount of complexity from the write path to deal with flatbuffers (see #2497 or #1842 )

**Alternatives Considered**

Prevent configuring a partition key for a database with a write buffer consumer. This would avoid confusion but I think would lose a powerful capability for query servers to organise their data how they deem fit

**Comment by crepererum** [comment]
I fail to see how your proposal makes #2497 obsolete or reduces its complexity. You still need to calculate some stable sequencer ID based on the input data and using the table name and partition key is rather simple. We could replace the partition key in the distribution logic by something else (like a similar functionality that calculates a string key from columns, like a "sequencer key").

**Comment by tustvold** [comment]
> I fail to see how your proposal makes #2497 obsolete or reduces its complexity.

I wasn't suggesting this at all, I was using it as an example of how the flatbuffer dance is painful and adds a non-trivial amount of complexity. Sorry I should have been clearer.

**Comment by alamb** [comment]
> Store a non-partitioned data representation in the write buffer, possibly even the binary write protocol proto messages, and perform the partitioning in the query servers.

If we did this, does it mean that data from all partitions would be sent to all query servers, even if each query server was supposed to receive only a subset of the partitions? Maybe that already happens but it sounds strange to me

**Comment by alamb** [comment]
I guess then the downside is that the calculation of partitioning would be done in the (theoretically less elastically growable) query server

**Comment by NGA-TRAN** [comment]
@tustvold Is it possible to provide an example or a picture to describe the problem and your proposal? I have a hard time to understand it

**Comment by tustvold** [comment]
> I guess then the downside is that the calculation of partitioning would be done in the (theoretically less elastically growable) query server

Yes, this would be the downside. However, I'd counter it by saying that something is very wrong if partitioning the ingested data, a fairly trivial O(n) operation, is on the same order of magnitude in terms of compute time as compaction which is at least O(nlog(n)) with a much bigger n.

> I think I am confusing partitioning and sharding.

This is another slight funkiness with the way the write buffer is currently plumbed in, there is currently no concept of a shard within the write buffer write path. @mkmik has already created a ticket for this https://github.com/influxdata/influxdb_iox/issues/2134. The TLDR is write buffers should probably be per-shard, whereas currently they are database-global.

> Is it possible to provide an example or a picture to describe the problem and your proposal

Currently when a write lands in a routing server, either via the binary write protocol or line protocol, it is partitioned based on the partition key for that database on that routing server. The TableBatch for each partition are then bundled into a single Entry flatbuffer and sent to the write buffer.

Each query server then pulls this Entry off the write buffer and writes each TableBatch to a partition defined by the partition key embedded within it (well technically the PartitionedWrite). Even though the query server has a partition key configured, it will have no impact on how it actually partitions data, as this is decided for it by the routing tier.

This means that the routing tier decides both the sharding and the partitioning of all data, and this cannot be changed once data has been ingested. I would, perhaps naively, expect the routing tier to only decide the placement of data, i.e. the shard, and not how a node chooses to organise that data for query, lifecycle, etc... Related to this, I would expect to be able to define query servers consuming from the same shard with different partitioning.

FYI @pauldix if you haven't seen this issue yet.

**Comment by alamb** [comment]
I am convinced that doing partition key calculation at the routing tier does not make sense and that we should move it into the actual write server

**Comment by NGA-TRAN** [comment]
> This means that the routing tier decides both the sharding and the partitioning of all data, and this cannot be changed once data has been ingested. I would, perhaps naively, expect the routing tier to only decide the placement of data, i.e. the shard, and not how a node chooses to organise that data for query, lifecycle, etc... Related to this, I would expect to be able to define query servers consuming from the same shard with different partitioning.

Totally agree with this

**Comment by crepererum** [comment]
To me it looks like we have three levels that split data:

1. **sharding:** decided which server ID gets which part of the data
2. **write buffer distribution:** distributes data into multiple sequencers (e.g. Kafka partitions) for more efficient handling. This must be in-line with _partitioning_ (next step) so that it doesn't split partitions apart.
3. **partitioning:** controls lifecycle, the granularity of certain management operations, query efficiency
4. (you could argue that chunks represent yet another level, but that's not really important for the discussion here).

**Comment by tustvold** [comment]
> To me it looks like we have three levels that split data:

Agreed

> This must be in-line with partitioning (next step) so that it doesn't split partitions apart.

I think the important requirement for all three is they don't split a primary key across multiple shards, sequencers, or IOx partitions. I'm not sure if by in-line here you mean must be the same, as if so I disagree. 

It would be perfectly valid to:

* Shard based on the env column
* Distribute between sequencers within a shard based on the host column
* Partition within the query servers solely based on time

Each of these independently is not splitting a primary key, and so the system as a whole is perfectly valid. If that is what you mean, then yes I agree :laughing:

**Comment by crepererum** [comment]
On tricky thing that came up in #2497 is: how do we distribute delete predicates? Are we just sending the to all shard, sequencers and partitions? Esp. sending them to all sequencers is a bit heavy since multiple sequencers can write into the same partition so if you have 16 sequencers the consumers needs to process the delete predicate 16 times. I'm not saying that his cannot be done efficiently, I'm just wanna point out that doing so would need some special care.

**Comment by tustvold** [comment]
Closed by #2724
