### ISSUE TITLE
Provide an ephemeral identifier tied to the lifetime of a single IOx execution / set ready constraint

### ISSUE THREAD

**Issue by domodwyer** [influxdata/influxdb_iox#2610]
When an IOx node starts, Conductor will push database configurations to converge IOx to the desired config state. 

* IOx instance starts
* Conductor detects the new instance is ready to receive config
* Conductor pushes the database configurations and waits for them to be healthy
* Conductor sets the IOx server readiness to "ready" to allow it to serve queries

This happens for both a new IOx node, and an IOx node taking over an existing server ID as a new database may have been created / updated while the IOx node was down.

The intent of this is to maintain an invariant that all "ready" IOx instances that are serving queries have all the database configs they need, and they all have the same version of the config.

However, a well timed crashed can break this invariant:

* IOx instance starts
* Conductor detects the new instance is ready to receive config
* Conductor pushes the database configurations and waits for them to be healthy
* **The IOx instance crashes**
* **The IOx instance recovers**
* Conductor sets the IOx server readiness to "ready" to allow it to serve queries

In the above sequence, Conductor allows the IOx node to begin serving queries with potentially out-of-date configurations or unhealthy databases, as it has not yet observed the failure. At some point in the future Conductor will detect the failure, and restart the above bootstrapping process to converge the node but this leaves a period of time where the cluster is returning errors / incorrect query results.

While the above is from the perspective of our Conductor control system, the same applies to any cluster control implementation.

## Proposal

Conductor already solves a similar problem internally as it uses an asynchronous actor model and has the concept of an "instance ID" to constrain internal async actions to only operate on the correct IOx instance. The intent is that one instance ID maps to one execution of the IOx binary.

When Conductor detects an IOx node has been provisioned / restarted it assigns a new unique value as the instance ID to this IOx instance, and any future operations can constrain by this instance ID to effectively say "set this node to ready, if it's the IOx instance I think it is".

However because this instance ID is internal to conductor and assigned by the health check loop, until Conductor detects the IOx restart the instance ID is not changed and actions such as "set ready" constrained by this instance ID are allowed even though the actual IOx node has changed.

If an IOx node generated it's own random value / UUID at startup (it's own "instance ID"), made it available in the server status or other RPC call, and allowed the "set ready" RPC call to only succeed if given the same UUID by Conductor, the above ABA concurrency issues are prevented.

To summarise:
* Generate a unique value / UUID at startup
* Expose this UUID via the server status RPC (or other API)
* Allow the `SetServingReadiness` RPC caller to optionally provide this UUID back to IOx and fail if it does not match

This solution will be suitable for other control systems, not just Conductor.

## Alternatives

* Health check faster: at best reduces the window, at worst has no impact - the health check thread may be stalled or not scheduled on the CPU for a while, or Conductor may crash before detecting the failure and taking corrective action.

* List & check the databases before setting the node to ready: a crash after listing, but before setting to ready causes the same race.

* IOx (already) restores configs on startup: Conductor waits for databases to report as ready / caught up from Kafka / etc - a crash after this will cause Conductor to enable queries to a node that is not yet healthy, and may never become healthy.

* Do nothing and accept the window of brokenness: definitely an option, but solving the problem is simple enough

**Comment by pauldix** [comment]
It's worth thinking about this ID option in the context of the new "floating databases" design that @mkmik and @crepererum have been working on. Short preview of it is that the "server ID" is no longer in the path of the data files and catalog.

If we have this ID, should it take the place of the server ID/writer ID? If so, how would a server on startup know which databases it owns? There's probably two contexts worth thinking about:
1. A server running by itself with no external coordination (i.e. no Conductor or equivalent)
2. A server running with an external coordinator that manages restarts, etc. (e.g. with Conductor)

Thoughts?

**Comment by mkmik** [comment]
@pauldix this proposal is a different kind of ID, it just makes sure that when you call "set ready" you're talking to is the **same process** you just talked before when you asked it "how are you"?

I think it makes a ton of sense; I've seen this used in other places (where it was called just "server id" and sometimes passed to all requests via headers, but to us "server id" or "instance id" are already loaded names that mean something else).

I'd coin just a new name like "pidox" for it

**Comment by alamb** [comment]
I read this proposal and it also makes sense to me. @domodwyer  how high a priority is this? As in should I go and hack up an implementation?

**Comment by alamb** [comment]
How about we call this number `startup id` as it will be different after each process startup?

**Comment by domodwyer** [comment]
@alamb we should definitely land this (and implement it in Conductor - influxdata/conductor#541) before IOx is observable by customers.

Before then, it's a nice-to-have to reduce avoidable errors while we test, though it should be pretty simple to implement so a nice quick thing to get in.
