### ISSUE TITLE
Ensure that delete predicates don't get lost during lifecycle actions

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#2627]
Currently we capture delete predicates too here:

https://github.com/influxdata/influxdb_iox/blob/155d5a5cce267a538e9666f9f41c9d19223ef0fc/server/src/db/lifecycle/compact.rs#L69

https://github.com/influxdata/influxdb_iox/blob/155d5a5cce267a538e9666f9f41c9d19223ef0fc/server/src/db/lifecycle/persist.rs#L79

then we drop the chunk locks and later we use the captured predicates to create new chunks:

https://github.com/influxdata/influxdb_iox/blob/155d5a5cce267a538e9666f9f41c9d19223ef0fc/server/src/db/lifecycle/compact.rs#L118-L125

https://github.com/influxdata/influxdb_iox/blob/155d5a5cce267a538e9666f9f41c9d19223ef0fc/server/src/db/lifecycle/persist.rs#L143-L150

However in the meantime there might have been new predicates added to the chunks which we'll just forget. Note that the delete predicates that existed before dropping the lock might just be materialized during the compaction and split query, so we actually don't need to attach this set to the new chunks at all. To isolate the chunks that were added while the lifecycle action was running #2626 might be helpful.

**Comment by NGA-TRAN** [comment]
Since this is important, I have added it as a task of soft delete #2396
