### ISSUE TITLE
Integrate delete predicate persistence w/ replay / persistence windows

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#2629]
Somehow we need to figure out how to integrate delete predicate persistence w/ replay. As of #2628 delete predicates are persisted using a background worker and this progress must be captured somehow (e.g. in-flight delete predicates should could be reflected as part of the `DatabaseCheckpoint` sequence ranges).

**Comment by NGA-TRAN** [comment]
I also add this as a task of #2396

**Comment by NGA-TRAN** [comment]
@crepererum I am triaging to se what is left for delete and compaction. Is this done or still need our attention? Can you add a bit more detail what we have to do?

**Comment by crepererum** [comment]
This is done by flushing the mailbox when we're persisting new data:

https://github.com/influxdata/influxdb_iox/blob/fe0bc2180732cc2189cbfe9a4727294793d25f4d/server/src/db/lifecycle/write.rs#L161-L166
