### ISSUE TITLE
refactor: Remove routerify from codebase

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#2630]
__Use case:__
We no longer user any of routerify features so we should remove it from the code base to save compile time, potential security issues,  dependencies, and our custom fork

__Proposal:__
Remove use of routerify

__Current behaviour:__
Routerify is compiled and hookedup but no features are used.

__Context:__
We tried to remove it previously in https://github.com/influxdata/influxdb_iox/pull/2586 but had to back out the change when we observed a high error rate on write -- https://github.com/influxdata/influxdb_iox/pull/2623

**Comment by tustvold** [comment]
The issue appears to have been CPU starvation leading to an elevated request latency, leading to request timeouts

![image](https://user-images.githubusercontent.com/1781103/134891430-0e0cb0c9-15a8-4bc7-bda5-2b3b0745673e.png)

![image](https://user-images.githubusercontent.com/1781103/134891413-fd867740-8efa-470b-a8ec-3f6fbecba4b8.png)

As for what caused this, I don't know as I can't reproduce it locally

**Comment by alamb** [comment]
I likewise was not able to reproduce the issue locally

I wonder if it has something to do with how the Go code that does the "`tee`ing" works
