### ISSUE TITLE
Remove move_chunk_to_read_buffer lifecycle action

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#2663]
This has been superseded by compact_chunks, and is not called by the LifecyclePolicy.

I seem to remember it was largely kept around to avoid test churn, but its existence causes unnecessary confusion and it should just be removed

**Comment by NGA-TRAN** [comment]
Right. I believe you will need to replace it with corresponding compact function because we heavily use this function in our tests

**Comment by tustvold** [comment]
Closed by #2674
