### ISSUE TITLE
Support Persisted Chunks Within compact_chunks Lifecycle Action

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#2665]
It should be possible to compact persisted chunks

**Comment by alamb** [comment]
I would recommend writing up a design for this item -- specifically with a proposed API (do you say "compact all chunks in this partition", or "compact only these specific chunks", "compact all chunks in a table", etc)

Also, it would probably be good to explicitly spell out "can you compact chunks that are in different partitions" (answer is probably no, but it would be good to write down)

**Comment by tustvold** [comment]
> I would recommend writing up a design for this item

Will do as part of this ticket. I was envisaging that it'd just be a case of updating the compact_chunks lifecycle action to verify all the provided chunks are either persisted or not, and if they are persisted to perform the necessary dance to upsert the resulting chunk into the persisted catalog and then the in-memory catalog.

Adding a gRPC API is tracked by #1934

**Comment by alamb** [comment]
> Will do as part of this ticket. I was envisaging that it'd just be a case of updating the compact_chunks lifecycle action to verify all the provided chunks are either persisted or not, and if they are persisted to perform the necessary dance to upsert the resulting chunk into the persisted catalog and then the in-memory catalog.

Cool -- I don't think a detailed technical implementation design is needed (what you describe is probably good enough along with a well commented PR).

I think I was just getting at was clearly defining what was / was not allowed in terms of compacting persisted chunks together and how the user (e.g. conductor / an operator) will specify it

**Comment by NGA-TRAN** [comment]
I close this because the `compact_object_chunks` and `compact_object_store_partition` are available. I have created #3355 to add those into our lifecycle
