### ISSUE TITLE
Unsuppress RUSTSEC-2021-0116, RUSTSEC-2021-0117 and RUSTSEC-2021-0118

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#2670]
#2669 suppressed these, once an upstream fix is available we should remove these suppressions.

**Comment by carols10cents** [comment]
The issues to track:

- [RUSTSEC-2021-0116](https://rustsec.org/advisories/RUSTSEC-2021-0116): `BinaryArray` [offsets](https://github.com/apache/arrow-rs/issues/773) and [values](https://github.com/apache/arrow-rs/issues/772)
- [RUSTSEC-2021-0117](https://rustsec.org/advisories/RUSTSEC-2021-0117): https://github.com/apache/arrow-rs/issues/775
- [RUSTSEC-2021-0118](https://rustsec.org/advisories/RUSTSEC-2021-0118): `FixedSizeBinaryArray` https://github.com/apache/arrow-rs/issues/774

**Comment by Shnatsel** [comment]
The other issues not tracked by RustSec also look legit, I'd gladly accept PRs adding them to RustSec.

FWIW there is [`arrow2`](https://crates.io/crates/arrow2) crate that does not suffer from these issues, and appears to be both faster and safer.

**Comment by alamb** [comment]
> FWIW there is arrow2 crate that does not suffer from these issues, and appears to be both faster and safer.


Indeed, the author of `arrow2` is the one who filed the issues in arrow
