### ISSUE TITLE
Floating databases: Replace the tombstone file for database delete/restore with the release/claim API

### ISSUE THREAD

**Issue by carols10cents** [influxdata/influxdb_iox#2680]
- ~~On server startup, instead of listing object storage contents and checking for tombstone file existence to know if a database is active or inactive, check the server's config.pb to see what databases it owns~~ this part is already done
  - Make delete/restore aliases for the release/claim database command/API
  - Remove all code having to do with tombstone files

**Comment by carols10cents** [comment]
@mkmik moving this discussion here that was [started on the meta-issue](https://github.com/influxdata/influxdb_iox/issues/2672#issuecomment-931289790): 

> > Wait, so when the Disown API is used (instead of Delete), there _isn't_ a `DatabaseTombstone` context written?
> 
> When the Disown API is used, then the caller chooses what to put in the context. Usually the orchestrator tool (e.g. conductor) will have their own proto message that marks the operation as being done by conductor and gives some context (e.g. disowned as part of the migration from server 1 to server 2)

Ok, I think I understand, let me check:

If someone runs:

```
$ influxdb_iox database disown foo
```

and doesn't provide any context, then after the operation is complete, the `floating.pb` (or whatever we end up calling it) will contain:

```
FloatingDatabaseConfig {
    backlink = ''

    transactions = [
        OwnershipTransaction {
            backlink = 's3://<bucket..>/nodes/<previous-owner-server-id>'
            context = []
        }
    ]
}
```

and the characteristic of this `floating.pb` that identifies this database as "inactive" is the `backlink = ''`.

However, if someone runs:

```
$ influxdb_iox database delete foo
```

and doesn't provide any context, then after the operation is complete, the `floating.pb` will contain:

```
FloatingDatabaseConfig {
    backlink = ''

    transactions = [
        OwnershipTransaction {
            backlink = 's3://<bucket..>/nodes/<previous-owner-server-id>'
            context = [
                DeleteTombstone {}
            ]
        }
    ]
}
```

and we still only need to look at the `backlink` to see that this database is inactive.

At some point I was thinking we'd need to check the most recent `OwnershipTransaction` to see if it had a `DeleteTombstone` to know whether a database was owned/active or not, but I think that's captured in the current value of `backlink`, correct?

**Comment by mkmik** [comment]
correct!
