### ISSUE TITLE
Delete Predicate With Empty Timestamp Range Deletes Nothing

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#2687]
```
    #[tokio::test]
    async fn delete_all() {
        let db = make_db().await.db;
        write_lp(db.as_ref(), "cpu,tag1=cupcakes bar=1 10").await;
        write_lp(db.as_ref(), "cpu,tag1=cupcakes bar=3 23").await;
        write_lp(db.as_ref(), "cpu,tag1=cupcakes bar=2 26").await;
        db.delete("cpu", Default::default()).await.unwrap();

        let batches = run_query(db, "select count(*) from cpu").await;
        let expected = vec![
            "+-----------------+",
            "| COUNT(UInt8(1)) |",
            "+-----------------+",
            "| 0               |",
            "+-----------------+",
        ];
        assert_batches_sorted_eq!(&expected, &batches);
    }
```

Fails with 

```
expected:

[
    "+-----------------+",
    "| COUNT(UInt8(1)) |",
    "+-----------------+",
    "| 0               |",
    "+-----------------+",
]
actual:

[
    "+-----------------+",
    "| COUNT(UInt8(1)) |",
    "+-----------------+",
    "| 3               |",
    "+-----------------+",
]
```

Initial investigation shows that:

* The delete predicate is associated with the chunk
* Adding additional criteria, e.g. table name, to the predicate doesn't change the behaviour

**Comment by e-dard** [comment]
I'm guessing this needs to be handled as a "delete table" type operation somewhere.

**Comment by tustvold** [comment]
> I'm guessing this needs to be handled as a "delete table" type operation somewhere.

I don't think it needs to be handled any differently from any other predicates, it needs to be associated with the relevant chunks (all of them) and left to compaction to sort out. A separate but related task should then be to make the query/compaction detect when a delete predicate "covers" a chunk and optimise that case

**Comment by alamb** [comment]
Given that all deletes are supposed to have a timerange, I think the expected behavior in this case should be to reject the delete (aka raise an error on the call to `Db::delete()`.

I think sorting out how to drop all data in a database is a reasonable thing to do but applying no predicate is likely not the ideal way

**Comment by tustvold** [comment]
How about a chat at standup?

**Comment by tustvold** [comment]
So this fails

```
#[tokio::test]
    async fn delete_all() {
        use datafusion::prelude::*;
        let db = make_db().await.db;
        write_lp(db.as_ref(), "cpu,tag1=cupcakes bar=1 10").await;
        write_lp(db.as_ref(), "cpu,tag1=cupcakes bar=3 23").await;
        write_lp(db.as_ref(), "cpu,tag1=cupcakes bar=2 26").await;
        let predicate = PredicateBuilder::new().table("cpu").build();

        db.delete("cpu", Arc::new(predicate)).await.unwrap();

        let batches = run_query(db, "select count(*) from cpu").await;
        let expected = vec![
            "+-----------------+",
            "| COUNT(UInt8(1)) |",
            "+-----------------+",
            "| 0               |",
            "+-----------------+",
        ];
        assert_batches_sorted_eq!(&expected, &batches);
    }
```

But this does not

```
#[tokio::test]
    async fn delete_all() {
        use datafusion::prelude::*;
        let db = make_db().await.db;
        write_lp(db.as_ref(), "cpu,tag1=cupcakes bar=1 10").await;
        write_lp(db.as_ref(), "cpu,tag1=cupcakes bar=3 23").await;
        write_lp(db.as_ref(), "cpu,tag1=cupcakes bar=2 26").await;
        let predicate = PredicateBuilder::new().add_expr(lit(true)).build();

        db.delete("cpu", Arc::new(predicate)).await.unwrap();

        let batches = run_query(db, "select count(*) from cpu").await;
        let expected = vec![
            "+-----------------+",
            "| COUNT(UInt8(1)) |",
            "+-----------------+",
            "| 0               |",
            "+-----------------+",
        ];
        assert_batches_sorted_eq!(&expected, &batches);
    }
```
So it is likely something in how these predicates are converted to DataFusion

**Comment by alamb** [comment]
Consensus on the expected behavior from the sync up today  was that a
predicate such as `Predicate::default()` should effectively delete all rows

**Comment by NGA-TRAN** [comment]
This is a good catch @tustvold. I do not think this is a DF issue but the way we handle delete predicate in IOx (or at least that is where the fix should be I think). Let me look into this after #2546

**Comment by NGA-TRAN** [comment]
I assign this to myself and will start working on it on Monday

**Comment by NGA-TRAN** [comment]
After #2715 that we no longer allow default DeletePredicate, this is no longer an issue. We must provide a time range and optional list of expression. I feel a lot  better now and think this is definitely the right approach to avoid deleting everything by accident. So I close this without doing anything else.

Let @crepererum know so if he wants to introduce Default::default DeletePredicate, he needs to consider this.
