### ISSUE TITLE
Use influxdata.pbdata.v1.TableBatch in Write Path

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#2724]
**Problem**

Currently the write path is predominantly in terms of the flatbuffer `influxdata.iox.write.v1.Entry` and this acts as a major complication within the write path.

The following are things that would be eliminated/fixed by using influxdata.pbdata.v1.TableBatch

* Translation from protobuf to Entry - [here](https://github.com/influxdata/influxdb_iox/blob/main/entry/src/entry.rs#L304)
* Translation from LP to Entry (although replaced by LP to PB)- [here](https://github.com/influxdata/influxdb_iox/blob/main/entry/src/entry.rs#L83)
* Custom Entry wrapper involving:
    * ouroborous wizardry - [here](https://github.com/influxdata/influxdb_iox/blob/main/entry/src/entry.rs#L737)
    * wild iterators - [here](https://github.com/influxdata/influxdb_iox/blob/main/entry/src/entry.rs#L768)
* Complexity due to encoded nature of Entry making reconstruction expensive
    * Write masks due to cost of reconstructing Entry - [here](https://github.com/influxdata/influxdb_iox/pull/2258/files)
    * Up-front sharding, partitioning, etc... - [here](https://github.com/influxdata/influxdb_iox/blob/main/entry/src/entry.rs#L83)
    * Splitting into separate partition writes - [here](https://github.com/influxdata/influxdb_iox/pull/2497/files#diff-340c5e5ddcbd504a868fad33d8b85bf2a67fe27c670fce22c6c2f607edd869e6R310)
* Lack of deep-copy support - https://github.com/google/flatbuffers/issues/264
* Lack of human-readable serialization for debugging - (only C++ flatbuffers supports JSON)
* https://github.com/influxdata/influxdb_iox/issues/2139
* https://github.com/influxdata/influxdb_iox/issues/2534
* https://github.com/influxdata/influxdb_iox/issues/2243

Additionally it is worth considering the following:

* Ingest is unlikely to be the performance bottleneck given it is `O(n)` and compaction/persistence are `O(nlog(n))`
* Flatbuffer verification is expensive, eliminating a number of its advantages, and necessary to avoid UB with foreign input
* The binary write format is:
    * Columnar and not highly nested, so decoding overheads should be limited by this
    * Supposed to be the performant ingest, converting from it to another representation somewhat undermines this?
    * An external facing API allowing for interesting use-cases interacting directly with the write buffer
* We have invested heavily in protobuf linting, serialization, schema evolution, etc... we would likely need the same for flatbuffer
* We currently copy the data into the MUB anyway to get dictionary encoding, arrow-like representation, etc...

**Proposal**

Use `influxdata.pbdata.v1.TableBatch`, defined in [`influxdb_pb_data_protocol.proto`](https://github.com/influxdata/influxdb_iox/blob/main/generated_types/protos/influxdata/pbdata/v1/influxdb_pb_data_protocol.proto#L1) within the write path in IOx, i.e. the MUB would accept `TableBatch` instead of `Entry`.

Additionally the write buffer would use a protobuf message similar to

```
Entry {
    oneof operation {
        TableBatch batch = 1;
        DeletePredicate delete = 2;
    }
}
```

**Alternatives Considered**

https://github.com/influxdata/influxdb_iox/issues/2534 could be resolved by removing the partitioning from the flatbuffer, but at that point we are getting limited benefit from the flatbuffer as it will need to be reconstructed to partition it in the query server, and so we might as well just use a less obnoxious format...

**Comment by alamb** [comment]
@tustvold would this proposal effectively to remove the use of flatbuffers /`Entry`entirely and use the protobuf encoding? If so this seems like a reasonable idea to me 👍

**Comment by tustvold** [comment]
>  would this proposal effectively to remove the use of flatbuffers /Entry entirely and use the protobuf encoding?

Yes, the only remaining usage of flatbuffers would be arrow flight which is a "delegated concern" :smile:
