### ISSUE TITLE
Deletes and Write Buffer

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#2731]
**Problem**

Currently deletes are unaware of the write buffer this means:

* A delete sent to a routing server will be a no-op as the server will have no local data
* A delete sent to a query server following a write buffer will be applied breaking eventual consistency

**Proposal**

Deletes should behave the same as other writes:

* Deletes sent to a routing server are dispatched to the write buffer
* Calling delete directly on a query server following a write buffer will return an error

The routing sever should validate that the delete predicate is valid as much as possible, but at least initially the write buffer format should just contain the string representation. In future we may be able to store the parsed representation instead.

**Comment by NGA-TRAN** [comment]
A must to fully support #2396

**Comment by tustvold** [comment]
So there is a slight complexity w.r.t the interaction between replay and deletes.

**Background**

For background, data is not persisted in sequence number order. This mandates a replay process to recover a restarted database, as it needs to correctly handle what has already been persisted. To do this replay identifies 3 regions within each sequencer during replay

* Fully Persisted - all this data has been persisted
* Partially Persisted - some of this data has been persisted
* Not Persisted - none of this data has been persisted

Replay is solely concerned with the "Partially Persisted" window, and it replays data until it reaches "Not Persisted" data for that sequencer.

**Proposal**

On encountering a delete in the "Partially Persisted" window we **must** only apply it to the in-memory chunks and not the persisted chunks - as the persisted chunks might contain data that was written by a write sequenced after the delete :exploding_head: 

This implicitly assumes that we are not persisting during replay - I have therefore prioritized #2811.

An additional complexity is that deletes themselves are lazily persisted during normal operation, we **must** therefore guarantee that any persist operation for a partition also persists any deletes in the sequence number range identified by its PartitionCheckpoint (the partially persisted window). Ticket TBC

My reasoning for why this works is:

* Any delete in the partially persisted window must have already been applied to any persisted chunks
* Deletes are applied to the in-memory data only, which during replay can only come from writes sequenced before the delete

I _think_ this works but would appreciate if someone else could check my logic. Perhaps @crepererum ?

**Comment by alamb** [comment]
FWIW I think the logic above seems sound

> An additional complexity is that deletes themselves are lazily persisted during normal operation, we must therefore guarantee that any persist operation for a partition also persists any deletes in the sequence number range identified by its PartitionCheckpoint (the partially persisted window). Ticket TBC

I still worry about requiring all replay data to be done in memory (as it bounds the total time we can be down before replay will need more drastic action). Thus, rather than using "persisted data" as the check to determine if a delete should be applied, perhaps replay could track the chunks it has made and the check should be "was not created by replay" (rather than "is persisted")

**Comment by tustvold** [comment]
> as it bounds the total time we can be down before replay will need more drastic action

The downtime does not impact the amount of data to be replayed, replay is only concerned with the "Partially Persisted" region which necessarily must have fit in memory before the machine crashed/restarted

**Comment by NGA-TRAN** [comment]
> On encountering a delete in the "Partially Persisted" window we must only apply it to the in-memory chunks and not the persisted chunks - as the persisted chunks might contain data that was written by a write sequenced after the delete

Will we miss attaching deletes in partially persisted chunks if we do not apply delete on persisted chunks without RUBs? How do we solve this? It sounds like I miss something here

**Comment by tustvold** [comment]
> partially persisted chunks

I'm not sure what you mean by partially persisted chunks, partially persisted chunks here refers to a range of sequence numbers within a sequencer stream during replay, where some of the sequenced operations have already been made durable and some not. In this case any chunk that has already been persisted, necessarily has already had the delete applied if it makes sense to do so

**Comment by NGA-TRAN** [comment]
Oh, so it is fine then

**Comment by tustvold** [comment]
I believe all the outstanding correctness bugs have been closed, so closing this "meta-issue"
