### ISSUE TITLE
Add histogram metrics for ingestion

### ISSUE THREAD

**Issue by mkmik** [influxdata/influxdb_iox#2752]
Now that we can use custom histogram bucket sizes (thanks to #2365!), it's finally possible to emit a metric that measures the distribution of sizes of LP batches and/or eentries we write to / read from the write buffer (e.g. kafka)

- [x] `ingest_batch_size_bytes`
- [ ] `write_buffer_ingest_entry_size`
- [ ] (bonus points) compressed sizes for write buffer entries (may be hard since the compression is done transparently by the Kafka client library)

CC: @primeroz

**Comment by alamb** [comment]
I am going to take a shot at adding the histogram for kafka ingestion sizes
