### ISSUE TITLE
Inconsistent timestamp results from MUB and RUB

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#2779]
__Steps to reproduce:__
See these 3 current ignored tests (still in PR #2777):
  - sql::sql_select_with_delete_from_multi_exprs_max_time
  - sql::sql_select_with_delete_from_multi_exprs_min_time
  - sql::sql_select_with_delete_from_one_expr_max_time

Each test will run different  15 scenarios. When data is in MUB, timestamp format (e.g. `1970-01-01T00:00:00.000000020Z`) is returned. When data is in RUB, integer (e.g. `20`) is returned.

__Expected behaviour:__
The same format of timestamp should be returned

__Actual behaviour:__
Different format

**Comment by e-dard** [comment]
Since the MUB looks like it's doing the right thing I'm happy to take a look at this next week. How bizarre!

**Comment by e-dard** [comment]
@NGA-TRAN can you confirm that you're seeing `20` come out of the RUB? I'm unable to confirm this. I have annotated all the batches and schemas coming out of the RUB and I only see the timestamp with the correct `Timestamp(Nanosecond, None)` Arrow data type. 

Is it possible this is happening higher in DF where the aggregate is applied to the `time` column?

**Comment by NGA-TRAN** [comment]
It still happens with tests that are ignored due to this ticket. I will look into this after fixing #2776 .

**Comment by NGA-TRAN** [comment]
This still happens after #2776 is fixed. I am looking in to this today

**Comment by NGA-TRAN** [comment]
So found a difference that leads to the different results when `max(time)` is read from MUB and RUB. In MUB case, the full scan is run, while in RUB case we **seem** getting max value from `statistics` and embedded in the physical plan hence we do not need to scan the RUB which is good. While we embeded the statistics max value the in the query plan, we make it `Int64` instead of `timestamp`. I need to dig deeper to see my analysis is correct but here are the details to let me to this analysis

### MUB Optimized physical plan short version:
The plan shows the scan chunk will be scanned through `IOxReadFilterNode`
```
ProjectionExec: expr=[MAX(cpu.time)@0 as MAX(cpu.time)]
  HashAggregateExec: mode=Final, gby=[], aggr=[MAX(cpu.time)]
    CoalescePartitionsExec
      HashAggregateExec: mode=Partial, gby=[], aggr=[MAX(cpu.time)]
        ProjectionExec: expr=[time@1 as time]
          RepartitionExec: partitioning=RoundRobinBatch(4)
            DeduplicateExec: [foo@0 ASC,time@1 ASC]
              SortExec: [foo@0 ASC,time@1 ASC]
                IOxReadFilterNode: table_name=cpu, chunks=1 predicate=Predicate
```

### RUB Optimized physical plan short version:
The plan shows `EmptyExec: produce_one_row=true` which means no need to scan any chunk. It also shows `ProjectionExec: expr=[40 as MAX(time)]` which I think the max value is 40.

```
ProjectionExec: expr=[MAX(cpu.time)@0 as MAX(cpu.time)]
  RepartitionExec: partitioning=RoundRobinBatch(4)
    ProjectionExec: expr=[40 as MAX(time)]
      EmptyExec: produce_one_row=true
```

### The detailed RUB optimized physical plan:
It shows `expr: [(Literal { value: Int64(40) }, "MAX(time)")],` which, I think, means the max time `40` is `int64` data type which is wrong. It should be `timestamp` or the equivalent of `timestamp.

Optimized physical plan:
ProjectionExec { 
    expr: [(Column { name: "MAX(cpu.time)", index: 0 }, "MAX(cpu.time)")], 
    schema: Schema { 
        fields: [Field { name: "MAX(cpu.time)", data_type: Int64, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: None }], 
        metadata: {} 
    }, 
    input: RepartitionExec { 
        input: ProjectionExec { 
            expr: [(Literal { value: Int64(40) }, "MAX(time)")], 
            schema: Schema { 
                fields: [Field { name: "MAX(time)", data_type: Int64, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: None }], 
                metadata: {} 
            }, 
            input: EmptyExec { produce_one_row: true, schema: Schema { fields: [], metadata: {} } }, 
            metrics: ExecutionPlanMetricsSet { inner: Mutex { data: MetricsSet { metrics: [] }, poisoned: false, .. } } 
        }, 
        partitioning: RoundRobinBatch(4), 
        state: Mutex { data: RepartitionExecState { channels: {}, abort_helper: AbortOnDropMany([]) } }, 
        metrics: ExecutionPlanMetricsSet { inner: Mutex { data: MetricsSet { metrics: [] }, poisoned: false, .. } } 
    }, 
    metrics: ExecutionPlanMetricsSet { inner: Mutex { data: MetricsSet { metrics: [] }, poisoned: false, .. } } 
}

**Comment by NGA-TRAN** [comment]
The stats.column_statistics extracted from [fn take_optimizable_max](https://github.com/apache/arrow-datafusion/blob/295033492bbf335cdc02446cefb3751ab840f9b5/datafusion/src/physical_optimizer/aggregate_statistics.rs#L185) shows min and max are stored as  `Int64`. Will dig more but I think they should be `timestamp`  instead

```
stats.column_statistics:
 Some(
    [
        ColumnStatistics {
            null_count: Some(
                0,
            ),
            max_value: Some(
                Int64(40),
            ),
            min_value: Some(
                Int64(10),
            ),
            distinct_count: None,
        },
    ],
)
```

**Comment by NGA-TRAN** [comment]
And here is the IOx's `ColumnSummary` the stats above is extracted from:

```
                    ColumnSummary {
                                name: "time",
                                influxdb_type: Some(
                                    Timestamp,
                                ),
                                stats: I64(
                                    StatValues {
                                        min: Some(
                                            10,
                                        ),
                                        max: Some(
                                            40,
                                        ),
                                        total_count: 4,
                                        null_count: 0,
                                        distinct_count: None,
                                    },
                                ),
                            },
```

The `influxdb_type` is `Some(Timestamp,)` but its min and max values are `I64`

So I think the fix is in [IOxReadFilterNode's fn statistic ](https://github.com/influxdata/influxdb_iox/blob/60f0deaf1e22ce0c33d6e2224c44609428886387/query/src/provider/physical.rs#L165) that will be invoked by Datafusion to get the statistics. More precisely, the fix will be in [fn df_from_iox](https://github.com/influxdata/influxdb_iox/blob/60f0deaf1e22ce0c33d6e2224c44609428886387/query/src/statistics.rs#L33) where we verify the data type and return the right `timestamp` instead of `Int64`
