### ISSUE TITLE
last_timestamp of a field_columns test is wrong

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#2943]
__Steps to reproduce:__
Look at the test `test_field_name_plan`, the `last_timestamp` for `field2` should be 100 but it is 1000 for now. 

__Expected behaviour:__
 `last_timestamp` for `field2` should be 100

__Actual behaviour:__
 `last_timestamp` for `field2` is  1000

**Comment by e-dard** [comment]
Looks like this test is defined here:


https://github.com/influxdata/influxdb_iox/blob/e3ae1d27a83d9faea57c5e63340f864605dbcd0c/query_tests/src/influxrpc/field_columns.rs#L149-L178

We should figure out exactly what's happening here.
