### ISSUE TITLE
Dump catalog of detached databases

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#2981]
__Use case:__
Debug deleted databases.

__Proposal:__
Allow the "dump catalog" CLI command to take a UUID instead of a server ID + db name.

__Current behaviour:__
You can only dump attached databases.

__Desired behaviour:__
You can also dump detached databases.

__Alternatives considered:__
None.

**Comment by pauldix** [comment]
Not relevant to NG (new) catalog.
