### ISSUE TITLE
Flesh out the rest of the Line Protocol Parser

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#3]
There is a basic line parser now, but it's not complete. For example, it probably doesn't handle edge cases.

The current line protocol format is not perfect; there are bugs and weird rules, generally around how it handles escaping special values, and then how it handles backslash literals themselves.

We have a requirement to be strictly backward compatible, including any existing bugs.

There are tests for the Go implementation which should cover most of the edge cases:

- https://github.com/influxdata/influxdb/tree/master/models
- https://github.com/influxdata/influxdb/blob/master/models/points_test.go

There may also be some fuzz/quickcheck style tests somewhere.

Some differences:

- Duplicate tag key/value pairs should return an error — you can't have two tags with the same key. There's no need to de-duplicate them.

- Tag keys and field keys must be unique — you can't have a tag and a field with the same key.

- `time` should be a reserved key  — you shouldn't be able to use it for a tag or field.

The last performance test showed the Go line protocol parser at about 3M points/second.

Running some benchmarks in `influxdb/models/` show roughly ~110 MB/s:

```
% go test -test.bench BenchmarkParsePointsWithOptions
goos: darwin
goarch: amd64
pkg: github.com/influxdata/influxdb/models
BenchmarkParsePointsWithOptions/line-protocol.txt/1-12         	    1136	   1037854 ns/op	 112.17 MB/s	  280930 B/op	    1167 allocs/op
BenchmarkParsePointsWithOptions/line-protocol.txt/315-12       	       3	 334336998 ns/op	 109.68 MB/s	85948802 B/op	  366663 allocs/op
PASS
ok  	github.com/influxdata/influxdb/models	3.254s
````

**Comment by jacobmarble** [comment]
@pauldix can this be closed?
