### ISSUE TITLE
Kafa-based write buffer consumer might be poisoned

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#3026]
It it seems that some Kafka hiccups can poison the write buffer but it seems restarting IOx recovers the situation. #3019 changed the code to issue a warning in that case but we might need to issue some re-connect or queue flushing in case of errors. Let's see what these warnings print.

**Comment by crepererum** [comment]
CC @mkmik @primeroz

**Comment by mkmik** [comment]
Adding some context: the "hiccups" mentioned above are conditions that happen during normal administrative processes, like a rolling restart of a kafka cluster, which entails failing over from the current leader to its replica.

**Comment by primeroz** [comment]
For reference yesterday after a roll restart i must have forgotten to pkill iox-query-3000 on tools and it was broken until this morning, so it seems like it will never recover on its own.

Pkill-ed this morning and it recovered very quickly

Also, the more i look at this the more it seems to happen every time there is a `change of leadership` for the partitoin that the query is consuming , which is not really an `hiccup` but one of the most expected events in a kafka cluster 

Do we have the logs already on this pod ? 

![Screenshot from 2021-11-04 10-01-41](https://user-images.githubusercontent.com/2085772/140286382-1cdb707a-0b27-419b-a0c9-3fd2a27d6644.png)

![Screenshot from 2021-11-04 10-01-33](https://user-images.githubusercontent.com/2085772/140286374-745a5d01-bb88-4c00-a143-a33ae33e4f36.png)

**Comment by primeroz** [comment]
On stag03 during rollout the Ingest got broken , https://github.com/influxdata/influxdb_iox/issues/3030#issuecomment-960724704 

could this be an issue of caching the old ip of the broker instead of rediscovering brokers through the Service ?

**Comment by primeroz** [comment]
today i performed 2 restarts of kafka on tools and none of them caused any problem to iox-query3000 . not sure if anything was changed today that could explain this

**Comment by crepererum** [comment]
> today i performed 2 restarts of kafka on tools and none of them caused any problem to iox-query3000 . not sure if anything was changed today that could explain this

We didn't upgrade or change any Kafka-related stuff on our side (IIRC).
