### ISSUE TITLE
Router fails writing to write buffer when kafka leader changes

### ISSUE THREAD

**Issue by mkmik** [influxdata/influxdb_iox#3030]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behaviour.

1. have a routing tier that writes to kafka
2. perform a rolling restart of kafka (e.g. an upgrade or a change in parameters)

__Expected behaviour:__

The routing tier should continue to write to kafka despite the leader changing under its feet.
A small increase latency is expected

__Actual behaviour:__

Routing tier returns errors for a while and then recovers.

__Environment info:__

infludxdata's iox deployment on stag03's

__Logs:__

```
level=error msg="Error while handling request" error="Internal error writing points into org 3bd2399eac571807, bucket 8dc736eef15fc59d:  Cannot write to write buffer: Message production error: MessageTimedOut (Local: Message timed out)" method=POST uri=/api/v2/write?bucket=8dc736eef15fc59d&org=3bd2399eac571807 content_length="Some(\"9737\")" target="influxdb_iox::influxdb_ioxd::http" location="influxdb_iox/src/influxdb_ioxd/http.rs:423" time=1636026100004984263
level=error msg="librdkafka: Global error: BrokerTransportFailure (Local: Broker transport failure): iox-kafka-1.iox-kafka-brokers.iox.svc:9092/1: Disconnected (after 48985ms in state UP, 1 identical error(s) suppressed)" log.target=rdkafka::client log.module_path=rdkafka::client log.file=/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rdkafka-0.27.0/src/client.rs log.line=92 target="log" time=1636026105434016353
level=error msg="librdkafka: Global error: AllBrokersDown (Local: All broker connections are down): 4/4 brokers are down" log.target=rdkafka::client log.module_path=rdkafka::client log.file=/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rdkafka-0.27.0/src/client.rs log.line=92 target="log" time=1636026105434035113
level=error msg="librdkafka: FAIL [thrd:iox-kafka-1.iox-kafka-brokers.iox.svc:9092/1]: iox-kafka-1.iox-kafka-brokers.iox.svc:9092/1: Connect to ipv4#10.136.108.142:9092 failed: Connection refused (after 1ms in state CONNECT)" log.target=librdkafka log.module_path=rdkafka::client log.file=/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rdkafka-0.27.0/src/client.rs log.line=63 target="log" time=1636026105435571770
level=error msg="librdkafka: Global error: BrokerTransportFailure (Local: Broker transport failure): iox-kafka-1.iox-kafka-brokers.iox.svc:9092/1: Connect to ipv4#10.136.108.142:9092 failed: Connection refused (after 1ms in state CONNECT)" log.target=rdkafka::client log.module_path=rdkafka::client log.file=/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rdkafka-0.27.0/src/client.rs log.line=92 target="log" time=1636026105435602555
level=error msg="Error while handling request" error="Internal error writing points into org 3bd2399eac571807, bucket 8dc736eef15fc59d:  Cannot write to write buffer: Message production error: MessageTimedOut (Local: Message timed out)" method=POST uri=/api/v2/write?bucket=8dc736eef15fc59d&org=3bd2399eac571807 content_length="Some(\"9752\")" target="influxdb_iox::influxdb_ioxd::http" location="influxdb_iox/src/influxdb_ioxd/http.rs:423" time=1636026110014719372
level=error msg="Error while handling request" error="Internal error writing points into org 3bd2399eac571807, bucket 8dc736eef15fc59d:  Cannot write to write buffer: Message production error: MessageTimedOut (Local: Message timed out)" method=POST uri=/api/v2/write?bucket=8dc736eef15fc59d&org=3bd2399eac571807 content_length="Some(\"9749\")" target="influxdb_iox::influxdb_ioxd::http" location="influxdb_iox/src/influxdb_ioxd/http.rs:423" time=1636026150054380625
level=error msg="Error while handling request" error="Internal error writing points into org 3bd2399eac571807, bucket 8dc736eef15fc59d:  Cannot write to write buffer: Message production error: MessageTimedOut (Local: Message timed out)" method=POST uri=/api/v2/write?bucket=8dc736eef15fc59d&org=3bd2399eac571807 content_length="Some(\"9762\")" target="influxdb_iox::influxdb_ioxd::http" location="influxdb_iox/src/influxdb_ioxd/http.rs:423" time=1636026160064964580
level=error msg="Error while handling request" error="Internal error writing points into org 3bd2399eac571807, bucket 8dc736eef15fc59d:  Cannot write to write buffer: Message production error: MessageTimedOut (Local: Message timed out)" method=POST uri=/api/v2/write?bucket=8dc736eef15fc59d&org=3bd2399eac571807 content_length="Some(\"9748\")" target="influxdb_iox::influxdb_ioxd::http" location="influxdb_iox/src/influxdb_ioxd/http.rs:423" time=1636026170074046188
level=error msg="Error while handling request" error="Internal error writing points into org 3bd2399eac571807, bucket 8dc736eef15fc59d:  Cannot write to write buffer: Message production error: MessageTimedOut (Local: Message timed out)" method=POST uri=/api/v2/write?bucket=8dc736eef15fc59d&org=3bd2399eac571807 content_length="Some(\"9756\")" target="influxdb_iox::influxdb_ioxd::http" location="influxdb_iox/src/influxdb_ioxd/http.rs:423" time=1636026210114558357
level=error msg="librdkafka: FAIL [thrd:iox-kafka-2.iox-kafka-brokers.iox.svc:9092/2]: iox-kafka-2.iox-kafka-brokers.iox.svc:9092/2: Connect to ipv4#10.136.23.205:9092 failed: Connection timed out (after 128736ms in state CONNECT)" log.target=librdkafka log.module_path=rdkafka::client log.file=/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rdkafka-0.27.0/src/client.rs log.line=63 target="log" time=1636026213366958414
level=error msg="librdkafka: Global error: BrokerTransportFailure (Local: Broker transport failure): iox-kafka-2.iox-kafka-brokers.iox.svc:9092/2: Connect to ipv4#10.136.23.205:9092 failed: Connection timed out (after 128736ms in state CONNECT)" log.target=rdkafka::client log.module_path=rdkafka::client log.file=/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rdkafka-0.27.0/src/client.rs log.line=92 target="log" time=1636026213367020019
```

CC: @crepererum @primeroz

**Comment by primeroz** [comment]
problem happened again on stag03 during roll restart upgrade of kafka 

logs shows

```
connect to ipv4#10.136.108.142:9092 failed: Connection refused (after 1ms in state CONNECT)" 

Connect to ipv4#10.136.23.205:9092 failed: Connection timed out (after 128736ms in state CONNECT)" 
```

those ips are _wrong_ as in they are the ip before the pods were rolled and their ip changed.

I would expect the library to handle this and use the `service` to reconnect and rediscover the brokers and their ips

**Comment by crepererum** [comment]
This might be an rdkafka issue (I would at least expected it to handle this).

**Comment by crepererum** [comment]
That sounds similar to https://github.com/edenhill/librdkafka/issues/3396. Looking at [the default configs](https://github.com/edenhill/librdkafka/blob/v1.7.0/CONFIGURATION.md), the default `broker.address.ttl` (which we don't overwrite) is 1000ms. Should we try to reduce that?

**Comment by mkmik** [comment]
what would happen if we reduce that? would it be able to retry without propagating the error to the client or will it just ensure that we return less errors to the clients?

**Comment by mkmik** [comment]
according to our monitoring the write errors lasted for 2m40s

**Comment by crepererum** [comment]
This doesn't sound like this config does what it should do.

**Comment by primeroz** [comment]
probably those 1000ms ar eadded to some other timeouts on the write itself

**Comment by primeroz** [comment]
say the 1000ms have not expired, a new write will try to connect and probably hit at least `socket.timeout.ms` before trying again ?

**Comment by crepererum** [comment]
It could be `socket.timeout.ms` which is 60000ms by default. Maybe we should just lower that to a reasonable amount (like 5000ms).

**Comment by primeroz** [comment]
> That sounds similar to edenhill/librdkafka#3396. Looking at the default configs, the default broker.address.ttl (which we don't overwrite) is 1000ms. Should we try to reduce that?

Assuming that with established connections to brokers when everything is stable there is not really any need to refresh broker addresses ... we could reduce this as well to make it less likely we hit the socket timeout at all

**Comment by primeroz** [comment]
also this timeout could have a part in this 

https://github.com/influxdata/influxdb_iox/blob/c42a60beee93d98de64d6e323131dc7aac855ddf/write_buffer/src/kafka.rs#L216

**Comment by crepererum** [comment]
FYI: I'm able to reproduce that issue locally. You need a K8s cluster that ideally assigns new IPs to recreated pods. KinD in combination w/ Strimzi does the job. Then all you need to do is `kubectl delete pod ...` on the partition leader.

The issue seems that connecting to a broker (= reconnect while the old pod is killed but the DNS doesn't point to the new pod yet) has a very long timeout (over 2mins in my case). That's why the old broker IP appears in the logs after such a long time. DNS resolution and clean re-connect to the new broker IP seems to work perfectly once the timeout expires. I currently try to figure out how to fix that issue.

**Comment by primeroz** [comment]
we need to understand where the DNS cache is happening but something else sounds weird though, 

if you _just delete one pod_ the leader for that partition _will failover cleanly to another pod_ and the producer should get informed of this and should connect to the other pod which have not changed ip with effectively 0 downtime. 

I have done this many times with both Java and Golang producers and worked 100% of the time ... so something else might be going on here.

**Comment by primeroz** [comment]
For the DNS part, i wanted to double check if Istio on our clusters id playing a role in this ( i don't think it is but is worth checking ) ... i assume you are not running Istio in your local kind setup ?

**Comment by mkmik** [comment]
I think @crepererum reproduced the issue locally with kind and without istio

**Comment by primeroz** [comment]
Let me know if you want to have a chat, maybe i misunderstood something but this 

> Then all you need to do is kubectl delete pod ... on the partition leader.

is really strange to me since it should not be an issue , it makes me think something else is messed up

**Comment by mkmik** [comment]
Yeah, it's definitely a surprising behavior. 

I'd like to find a smaller reproducer and compare the behaviour of the java client and the c++ client (Rd Kafka) that we're using indirectly
