### ISSUE TITLE
M1 build fails "Bad CPU type in executable"

### ISSUE THREAD

**Issue by jacobmarble** [influxdata/influxdb_iox#3071]
```jacobmarble@Jacobs-MBP influxdb_iox % cargo build
  Downloaded libc v0.2.106
  Downloaded tracing-subscriber v0.3.1
  Downloaded tokio v1.13.0
...
   Compiling schema v0.1.0 (/Users/jacobmarble/influxdb_iox/schema)
   Compiling arrow_util v0.1.0 (/Users/jacobmarble/influxdb_iox/arrow_util)
error: failed to run custom build command for `pbjson-types v0.1.0`

Caused by:
  process didn't exit successfully: `/Users/jacobmarble/influxdb_iox/target/debug/build/pbjson-types-84687aa755224341/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=/Users/jacobmarble/.cargo/registry/src/github.com-1ecc6299db9ec823/pbjson-types-0.1.0/protos/google/protobuf/types.proto

  --- stderr
  Error: Custom { kind: Uncategorized, error: "failed to invoke protoc (hint: https://docs.rs/prost-build/#sourcing-protoc): Bad CPU type in executable (os error 86)" }
warning: build failed, waiting for other jobs to finish...
error: build failed```

**Comment by crepererum** [comment]
We're not on prost 0.9 yet which adds support for Apple silicon (see [release notes](https://github.com/tokio-rs/prost/releases/tag/v0.9.0)). IIRC we're waiting for upstream dependencies to catch up. @tustvold might know more about that.

**Comment by tustvold** [comment]
We're currently blocked on https://github.com/apache/arrow-rs/pull/864 which is blocked on arrow 7.0

@alamb Will know when that is due

**Comment by alamb** [comment]
Arrow 7 is due to be released around end of January 2022. If it is a critical need we can fork arrow / datafusion in the interim (or we can start a discussion to release arrow-rs 7 earlier than the rest of arrow)

**Comment by alamb** [comment]
I remember a discussion that bumping (effectively) major versions of dependencies in rust was considered a backwards incompatible change. However, I can't find that information at this point. I'll ask @carols10cents  about this and report back

**Comment by jacobmarble** [comment]
After installing the protobuf homebrew package and XCode and a bunch of other software, and upgrading MacOS to Monterey, I can't reproduce this issue. I have tried uninstalling all homebrew packages, uninstalling rustup, re-cloning this repository, but nothing.
