### ISSUE TITLE
Proposal: Server Self preservation mode (via server wide memory limit)

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#3132]
![image](https://user-images.githubusercontent.com/490673/142064364-74738418-6451-4717-8d7e-117dd9ae14d4.png)

__Use case:__
If the knobs currently exposed by the IOx lifecycle manager are not tuned correctly for a workload, it is  Out of Memory (OOM) killed. Specifically, when the `influxdb_iox` process exceed whatever memory budget has been allotted to it by the runtime environment (`k8s`) and the process is then killed by that environment 🔪 . 

We see this happening frequently in our pre-production testing cluster where the knobs have not been tuned and we worry about this happening if we put many (e.g 10,000s) of small databases on a single server when most receive very minimal traffic but in an unpredictable pattern. 

__Proposal:__
I propose a server wide `total_memory_threshold` limit that applies to *all* memory used by an IOx process, across all databases. 

If the memory used by IOx exceeds this threshold, IOx will go into "Self Preservation Mode" 

While in Self Preservation Mode, IOx will attempt to evict as much from memory as possible until it is again under the `total_memory_threshold`:
1. Trigger eviction of RUB chunks, starting with the ones that consume the most memory
2. (Possibly) Trigger persist operations prior to their being 
3.  (Possibly) Trigger some databases to reject / delay ingesting additional writes

*Fairness*: `Self Preservation` mode *will not* attempt to spread the pain fairly across databases. It will simply attempt to reduce memory used as quickly as possible to get back under the target limit. Given the alternative is the process is OOM killed, regardless of what gets evicted all tenant databases on that server are still better off

*Precedent*: This behavior is similar to the Linux kernel when it comes under memory pressure and must evict some workload (it typically kills the biggest consumers first), which makes sense as the alternate is the kernel may run out of memory itself and the system crashes. 

The default value for `total_memory_threshold` can be something reasonable (80% of the available system memory?) and over rideable with a server configuration. 

__Current behaviour:__
Memory limits are defined per database and nothing explicitly limits total memory consumed by all databases

__Desired behaviour:__
In addition to the existing memory limits per data

__Alternatives considered:__

*Option 1*: Configure each server so that the sum of the soft limits of all databases will never exceed the total memory available (perhaps enforced by some server wide config setting); 

*Option 2*: Automatically reduce memory limits for databases so that that the sum of the soft limits of all databases will never exceed the total memory available (e.g. divy up memory equally across databases)

*Option 3*: Do Nothing: We can allow IOx to be killed by the runtime environment (and it will recover), though that has an even more drastic effect on all databases hosted by this server

Option 1 and 2 have the downside that for a system with many databases, and where only a small number of databases get workload in an unpredictable manner, most memory will be reserved and never used. Self Preservation Mode allows a server to be over provisioned and fallback more gracefully than being OOM killed

**Comment by alamb** [comment]
Through proper configuration, it would be possible to prevent Self Preservation Mode from ever being triggered (aka by ensuring sum of all soft limits never exceed the memory available to the server(

**Comment by e-dard** [comment]
I think that the key part of this basic global memory limit is that no database limits are configured. That way, memory is not over provisioned "from the off".

This means tenants with more ingest will get more memory than other tenants up until server memory limits are hit. It's not clear to me that's what we want, but perhaps if memory is reclaimed proportionally to the database's memory usage it would have some notion of fair.

**Comment by alamb** [comment]
> I think that the key part of this basic global memory limit is that no database limits are configured. That way, memory is not over provisioned "from the off".

@e-dard  my proposal leaves the individual database configuration as they are -- I do not envision any changes in those knobs and there are definitely per-database limits in addition to the global one. Over time the basic policies will move data out of memory as dictated by the policy. 

The rationale for an *additional* global limit is an adaptive reaction to avoid being OOM killed in the event that the per-database limits aren't triggered promptly to move them out. 

If we care that all little tenant are guaranteed some chunk of memory we can configure their individual databases that way.

**Comment by e-dard** [comment]
> @e-dard my proposal leaves the individual database configuration as they are -- I do not envision any changes in those knobs and there are definitely per-database limits in addition to the global one. Over time the basic policies will move data out of memory as dictated by the policy.

In that case I think one would treat this more like k8s.. You over provision the databases' memory limits to some maximum value you think any tenant should be entitled to. Then you let the server global limit handle the case where you're hitting your total memory limits by evicting chunks based on `whatever_policy`.

For example you have `100GB` - you set the server limit to `80GB`. You decide that for this tier of users `200MB` is an appropriate memory limit for chunk data so you set all database soft limits to `200MB`.

If you have  `400` users using their `200MB` everything is golden. However if—more likely—you have 100 tenants using their `200MB` and `800` tenants not doing much at all, that's also fine and you have packed more tenants on.

If the over provisioning starts to bite the server global limit can kick in.

**Comment by mkmik** [comment]
The "self preservation" mechanism pushes "downwards".

A "reservation" mechanism (a-la k8s) would push "upwards". (The reservation could be zero)

The slack in between the two limits would allow for databases that need more memory to use it.

**Comment by alamb** [comment]
@tustvold  has noted that we can get a similar effect by changing the default config for all databases to enable persistence and setting the soft buffer limit very low (like `1`) so it seems like we may punt on this project in favor of a more holistic design to separate ingest and query
