### ISSUE TITLE
Consider support for InfluxQL `TagValuesGroupedByMeasurementAndTagKeyRequest` operation

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb_iox#3177]
Within our Cloud environment our InfluxQL query nodes can request that much of the work needed to be done by a `SHOW TAG VALUES` statement be pushed all the way down to storage.

In order to allow the same sort of work to be pushed down to IOx within that environment we would need to implement the operation associated with `TagValuesGroupedByMeasurementAndTagKeyRequest` as defined here:

<TODO>

**Comment by alamb** [comment]
@e-dard  Was this fixed with https://github.com/influxdata/influxdb_iox/pull/3373 and https://github.com/influxdata/influxdb_iox/pull/3406?
