### ISSUE TITLE
Reproducible Query Performance Tests 

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#3209]
**Problem**

In order to quantitatively evaluate various design trade-offs it is desirable to be able to construct an IOx server with a given state and run queries against it. This is currently quite difficult to achieve and requires manually ingesting data, and then triggering lifecycle actions to move the data into the desired storage locations.

**Proposal**

* Add the ability to reload a parquet file back into the RUB and expose this in the management API and CLI
* Expose the ability to rebuild the catalog for a set of parquet files written by IOx in the CLI

The combination of these two pieces of functionality would allow you to construct an IOx server with a subset of data sourced from some system, potentially written into IOx by the data generator, and then test the query performance with chunks in the RUB or not. If/when we add parquet file caching, the procedure would be much the same where you would need an API to prefetch or evict certain files.

**Alternatives Considered**

A "snapshot" mode, that would take a list of parquet files and a config file and construct an IOx server with a corresponding in-memory state. This would be significantly more intrusive to implement, as it would need to still behave largely like a standard `database` mode process, but with a seeded initial state. It is also unclear how you would run this on a remote instance.

A CLI tool to automate loading data into a server and driving the lifecycle manually to a desired end state. This potentially combined with the ability to upsert entire parquet files. This would likely work, but it is better if you can avoid re-ingesting data.

**Comment by e-dard** [comment]
This is what my dreams are made of ❤️

**Comment by alamb** [comment]
The high level proposal looks good to me 👍 

Here is a proposed API.

```bash
# Create a new, empty database
./influxdb_iox database create my_db

# tell the database to adopt all parquet files located in <url>, recursively
# URL must be accessable to the server (TODO other restrictions on url)
./influxdb_iox database import s3://iox-bucket/servers/21/data/foo

```

The idea would be that all metadata from all parquet files with prefix `/data/foo` would be read, and added to the catalog of `my_db`. No other catalogs would be modified, and no data would be moved in object store.

Open questions:
1. Should we move data into the proper location in object storage for `my_db` to  take control of them? Pros would be that my_db now acts like any other catalog. Cons is that data movement is required

**Comment by tustvold** [comment]
@alamb I was actually proposing something far more basic. You would need to take the files and copy them to an S3 bucket with the topology expected by IOx. All the CLI would provide is the ability to reconstruct a catalog from those files. Writing a generalized data migration tool seems like a load of extra work that doesn't help with being able to run query tests?

**Comment by alamb** [comment]
@tustvold  can you please provide an example  of how your feature would work (aka how this feature would be used from a user's perspective)? 

Something like:
```shell
# step 1: copy some files from prod locally (maybe `aws s3 sync`?)
# PUT COMMAND HERE

# step 2: start iox pointing at files downloaded from step 1
# PUT COMMAND HERE

# step 3: run a command to rebuild catalog
# PUT COMMAND HERE
```

Or whatever the story would actually be?

**Comment by alamb** [comment]
My usecase is:
1. I want to test query performance on IOx with real customer data and real customer queries (could also be "real tools data"), ideally without having to reingest the data myself. For example, I may only be interested in one table rather than all tables that were ingested by that databse

I think I would like to be able to copy some files from s3 locally and start IOx up to point at them.

**Comment by tustvold** [comment]
I've created two separate tickets that track this work, #3225 in particular describes the rebuild functionality
