### ISSUE TITLE
Rebuild Catalog

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#3225]
We wish to be able to rebuild the catalog of a database in the event the catalog is lost or corrupted. This functionality is currently implemented `parquet_catalog::rebuild::rebuild_catalog` but is not user-accessible. It should be possible to request that IOx attempts to rebuild the catalog for a Database, if it has failed to load i.e. it is in `DatabaseState::CatalogLoadError`. 

This would be similar to the similar to the existing `WipePreservedCatalog` but would instead run the rebuild logic.

This will also enable building a catalog from a set of parquet files produced by IOx.

* Create new database
* Stop IOx so it doesn't delete "orphaned parquet files"
* Delete transactions directory so catalog load on startup fails
* Add parquet files to `data` directory
* Startup IOx and run a catalog rebuild e.g. `influxdb_iox database recover rebuild`

Split out from #3209

**Comment by alamb** [comment]
@tustvold  would this feature be able to rebuild a catalog from a subset of parquet files (e.g. if only the parquet files for a particular table were copied to a new location)??

**Comment by tustvold** [comment]
@alamb Yup, depending on what you copied you might even be able to resume where you left off from the same write buffer.

Longer-term I think we will want more sophisticated catalog splitting machinery, that's able to preserve deletes, etc... but this is a quick and dirty mechanism that doesn't require anything more than a bit of gRPC plumbing, and that we want for disaster recovery anyway.

**Comment by alamb** [comment]
I think this is a fine interim step (rebuild from what is actually there). We can work on more sophisticated strategies, as you say, as part of a larger story
