### ISSUE TITLE
Delete predicate handling during parquet compaction

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#3255]
# Abstract
We need to be a bit careful w/ delete predicates during compaction of preserved chunks (i.e. parquet files).

# Assumptions
The schema that will be used makes the following assumptions:

## A.1 Chunk UUIDs
Chunks are addressed by UUIDs (version 4). This makes chunk addresses unique, even over multiple server restarts.

## A.2 Excessive Preserved Delete Predicates
The preserved catalog might contain delete predicates for unknown chunks. The unknown chunks are just ignored during catalog loading.

## A.3 Lazy Predicate Preservation
Incoming new predicates are never preserved directly but are attached to affected chunks and are also added to a mailbox. The mailbox content is stored regularly either by a background worker loop or during every other chunk preservation.

## A.4 Failable IO
Transaction to the preserved catalog might fail. To avoid out-of-sync situations of the in-mem catalog and the preserved catalog, we use the following schema:

1. Mark affected in-mem chunks
2. Transaction IO
3. If successful: commit in-mem change

## A.5 Short-lived locks
Chunks and partitions MUST NOT be locked during IO or longer calculations (e.g. compaction).

# Schema
The compaction job does the following:

1. Generate UUID for the result chunk
2. With partition write lock:
   1. Mark all to-be-compacted chunks using a lifecycle marker `CompactingOS`. This lifecycle marker shall also contain the UUID from step 1.
3. Run compaction (no locks at this point!).
4. With parquet clean-up lock.
   1. Write parquet file.
   2. Create preserved catalog transaction with new persisted chunk (no delete predicates required here). Exit if it fails.
5. With partition lock:
   1. Add new parquet-file-based chunk using the UUID from step 1
   2. Delete compacted chunks.

The mailbox insertion mechanism here

https://github.com/influxdata/influxdb_iox/blob/f165faf5bce152bef6676f4af7fef699c5cfd085/server/src/db.rs#L573-L583

must be modified to also check if a chunk is in the newly introduced `CompactingOS` state. If so, it also marks the to-be-created chunk as affected. This works due to assumption A.2.

**Comment by tustvold** [comment]
This matches our discussion on the topic, thank you for writing it up. I described a slight variation on this [here](https://github.com/influxdata/influxdb_iox/pull/3252#discussion_r759111008) that is is possibly slightly less hacky?? but the broad concept is the same. All that changes is where the translation takes place

**Comment by NGA-TRAN** [comment]
This description helps. I think I only need to twist PR #3252 a bit to match this

**Comment by NGA-TRAN** [comment]
@crepererum 

> Mark all to-be-compacted chunks using a lifecycle marker CompactingOS. This lifecycle marker shall also contain the UUID from step 1. 

Is there an available way to include UUID while marking lifecycle or we have to implement it? This is the code I wrote to mark `ComactingObjectStore`. It knows nothing about the new Chunk ID (UUID)

https://github.com/influxdata/influxdb_iox/blob/197634ed50ae19e981d3762957d5eef6cc4641d3/server/src/db/catalog/chunk.rs#L752

**Comment by crepererum** [comment]
I think you have to implement this. I would expect that this

https://github.com/influxdata/influxdb_iox/blob/c161d1176a2652a7cc8615db61f5342489ef365e/data_types/src/chunk_metadata.rs#L100-L101

enum variant just contains the said UUID.
