### ISSUE TITLE
Parquet Scan Performance

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#3282]
**Problem**

Currently the scan path for a parquet file in object storage is as follows:

* DbChunk::snapshot - obtain snapshot of ParquetChunk by cloning Arc
* DbChunk::read_filter
* ParquetChunk::read_filter
* Storage::read_filter
* Storage::download_and_scan_parquet

This final step downloads the file from object storage to a temporary file, and then runs Datafusion's ParquetExec on the file returning the yielded SendableRecordBatchStream.

This will download the same parquet file repeatedly, even if the object store implementation is disk-based. This is clearly unfortunate.

**Proposal**

Introduce a new trait `ParquetReader` with a single method (or more depending on how implementation shakes out)

```
trait ParquetReader {
    fn read_filter(
        predicate: &Predicate,
        selection: Selection<'_>,
        schema: SchemaRef,
        path: ParquetFilePath,
    ) -> Result<SendableRecordBatchStream>
}
```

Each `ParquetChunk` will contain an `Arc<dyn ParquetReader>` instead of `Arc<IoxObjectStore>` that will be used by `ParquetChunk::read_filter`.

Multiple implementations of `ParquetChunk` will then be written:

* ParquetReaderStore - streams data from object storage
* ParquetReaderFileStore - streams data from a file-system based object store
* ParquetReaderCached - streams data from a local parquet cache

**Alternatives Considered**

There is some existing plumbing for an `ObjectStoreFileCache` within the `object_store` crate. Unfortunately this is limited by the fact it has to still expose the ObjectStore API, limiting the ability to push down projections, predicates etc..., avoid additional memory copies, stream data, etc... This proposal instead abstracts away the object store, allowing great implementation flexibility

Another question is whether the cache should support writes, I decided against this for two reasons:

* It requires a non-trivial amount of additional functionality from implementations
* Longer-term the servers performing writes may not be the same ones servicing queries
* Query should drive caching not ingest

**Comment by e-dard** [comment]
This proposal seems like a good one to me 👍🏻

**Comment by crepererum** [comment]
Why is the `ParquetReader` dynamic per chunk instead of per object store?

**Comment by tustvold** [comment]
> Why is the ParquetReader dynamic per chunk instead of per object store?

I would expect chunks for the same database to share the same `Arc<dyn ParquetReader>`. Sorry that was not clear. I didn't want to specify exactly how it plumbs in, as tbh I'm not entirely sure yet :sweat_smile: . I _think_ it should be constructed at the `Server` level, but then the interaction between `IoxObjectStore` is complex...

**Comment by alamb** [comment]
The basic idea sounds good. 

Here is some prior art that might be worth checking out:

The interface you describe for `ParquetReader` is pretty similar to `ParquetExec` 
https://github.com/apache/arrow-datafusion/blob/b2a5028e0717e37b0f3c6a4f261ea1b2458b3c52/datafusion/src/physical_plan/file_format/parquet.rs#L90

Rather than wrapping ParquetExec as suggested above, you may be able to implement the DataFusion [object store interface](https://github.com/apache/arrow-datafusion/blob/b2a5028e0717e37b0f3c6a4f261ea1b2458b3c52/datafusion/src/datasource/object_store/mod.rs#L41-L47) for `LocalFile` (already done), `Cache` and `IoxObjectstore` 

In terms of implementation, I might help to check out how @rdettai implemented something similar in DataFusion's (relatively) new `ListingTable ` -- https://github.com/apache/arrow-datafusion/blob/b2a5028e0717e37b0f3c6a4f261ea1b2458b3c52/datafusion/src/datasource/listing/table.rs

**Comment by tustvold** [comment]
@alamb Ooh - that looks very nice, will check it out :+1:

**Comment by tustvold** [comment]
Had a good chat with @alamb, I'm going to proceed with a custom `ParquetReader` instead of using `ParquetExec` for a a couple of reasons that I'm documenting here for posterity:

* It gives us more control over how parquet files are read, with the ability to experiment with alternative implementations (i.e. C++)
* It gives greater control over when scan operations are started and how they are scheduled
* It exposes query details as opposed to opaque byte-ranges, which may be important to future caching optimisations
* It avoids a fair bit of complexity that we don't need as we have an in-memory catalog

**Comment by alamb** [comment]
I believe this ticket has been completed (and is fairly OG specific). Filed https://github.com/influxdata/influxdb_iox/issues/5397 for some follow on work in NG
