### ISSUE TITLE
Limit Plan Parallelism

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#3288]
**Problem**

Currently if you run a query against a large parquet dataset without very restrictive predicates it will try to fetch and scan all the files in parallel. With a filesystem based object store this results in a wall of error logs and failed query

```
Parquet reader thread terminated due to error: ParquetError(ArrowError("IO error: Too many open files (os error 24)"))
```

**Proposal**

Limit the maximum parquet scan fanout so as to not fetch and scan in parallel more files than available CPU threads.

**Comment by tustvold** [comment]
Having spoken to @alamb this is possibly a more general problem of limiting parallelism within our generated plans. Currently every chunk is mapped to a Datafusion partition, which means we have potentially unbounded fanout. This has implications beyond just parquet files. I have updated the ticket description as such

**Comment by alamb** [comment]
I do not think this is a problem anymore and we have improved the situation substantially. Closing
