### ISSUE TITLE
Spike: Parquet Encoding Evaluation

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#3299]
**Problem**

Circumstantial testing suggests that data is not being encoded within parquet in a manner that is particularly optimal. 

In particular:

* Block compression seems to be netting only a 2x return at best, and in some cases making the data sizes worse
* We are dictionary encoding **all** columns, despite this likely not providing much benefit outside of tags
* We aren't [binary packing](https://github.com/apache/parquet-format/blob/master/Encodings.md#delta-encoding-delta_binary_packed--5) integers
* We aren't using [byte-stream-split](https://github.com/apache/parquet-format/blob/master/Encodings.md#byte-stream-split-byte_stream_split--9) on floating point numbers
* Dictionaries are not sorted, limiting future query optimizations

**Proposal**

We should investigate if changes to how we encode data to parquet can improve data sizes, query performance, etc... 

This investigation would likely benefit from #3298

**Comment by e-dard** [comment]
What are we using on floats? I did some previous work comparing byte-stream-split and Gorilla and didn't find a significant difference in performance. I can't recall if I compared to `zst` or other block compressors but I _think_ I did, and didn't see a huge difference.

**Comment by tustvold** [comment]
> What are we using on floats

Currently we are RLE-dictionary encoding them, which will bit-pack the keys, but PLAIN encode the floats themselves. Everything is then zstd compressed with very limited returns.

> I did some previous work comparing byte-stream-split and Gorilla

Byte-stream-split isn't a compression algorithm, its a hack to make a subsequent block compression pass more effective. I suspect for a lot of data the real return will be from casting float columns to integers where possible, but this is more than a simple encoding detail :sweat_smile:

**Comment by e-dard** [comment]
> Byte-stream-split isn't a compression algorithm, its a hack to make a subsequent block compression pass more effective.

Yes. Specifically I compared BSS +zstd to Gorilla and to (I think )`zstd` on its own. I wasn't very clear above.
