### ISSUE TITLE
Parquet Decode Performance

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#3300]
**Problem**

The performance of reading data from parquet is currently sub-optimal, with query performance 10x slower than alternative tools operating on the same datasets. Some quick profiles show ~50% of the query time spent decoding the string columns from parquet.

![image](https://user-images.githubusercontent.com/1781103/144763171-43c25960-a02b-4a9d-b28e-ff788434b11e.png)

In particular

![image](https://user-images.githubusercontent.com/1781103/144763186-d83a07a8-847d-43db-8531-10c1d7aadd8f.png)

Immediately some things stand out to me

* `packed_string_to_dictionary` suggests it is decoding the dictionary from parquet and then repacking into a new dictionary
* There is a surprising amount of time spent in LevelDecoder, `eq_scalar` and other functions related to null handling
* Time is spent in functions related to repetition levels, which is surprising as we shouldn't have nested data

**Proposal**

We should invest some time into understanding what the existing code is doing, and work out how to improve the performance of this codepath.

Having poked around in the code I'm fairly confident that improvements could be made to the upstream, generic parquet -> arrow conversion logic. That being said I do wonder if the combination of the limited subset of parquet IOx will produce, the importance of it to performance, and our highly selective queries, might warrant a lower-level integration than streaming out entire column chunks as arrow RecordBatches. For example, it would be relatively straightforward to integrate at the page level, which would give us a lot of control over what data to "materialize" into arrow arrays, and allow for pushing down more than just predicates.

Perhaps @alamb or @pauldix have some thoughts on whether to invest time optimising the upstream parquet -> arrow conversion or to instead pursue tighter integration with the actual data format.

**Comment by alamb** [comment]
> Perhaps @alamb or @pauldix have some thoughts on whether to invest time optimising the upstream parquet -> arrow conversion or to instead pursue tighter integration with the actual data format.

Does "tighter integration with the actual dataformat" mean "write (or fork and modify) our own parquet reader"?

I think improving the upstream parquet reader / arrow conversion is the way to go. While this will likely take longer (review / release cycles, for example) it gives us access to bug fixes / testing from the broader community and I think is strategically aligned with "IOx fits in with the broader ecosystem").

I believe there are all sorts of things we can do to improve the performance of the (existing) parquet reader code I got 2 orders of magnitude improvement with a prototype that pushing predicates down into the actual parquet page reader, which I think is the same basic concept as what you are describing as 'integrate at the page level'. Writeup: https://docs.google.com/document/d/1Fz5dhB2WUE4iTul4xuUIm-dBE8VK3LJAKtfSMpqph0M/edit#


Also, it is claimed that [parquet2](https://github.com/jorgecarleitao/parquet2) us much faster than the existing parquet reader, so perhaps some inspiration can be taken from there. However, I do think pushing down predicates (to avoid materializing large swaths of string data) is likely the be the biggest win

**Comment by e-dard** [comment]
I agree with @alamb. It's better long term to push improvements into Parquet query perf upstream from the get go.

**Comment by tustvold** [comment]
> Does "tighter integration with the actual dataformat" mean "write (or fork and modify) our own parquet reader"?

I had meant integrate with [SerializedFileReader](https://docs.rs/parquet/latest/parquet/file/serialized_reader/struct.SerializedFileReader.html) instead of [ParquetFileArrowReader](https://docs.rs/parquet/latest/parquet/arrow/arrow_reader/struct.ParquetFileArrowReader.html). So using the upstream parquet reader, but writing our own logic to extract record batches from it.

Whilst I can understand how to potentially graft predicate pushdown using the ParquetFileArrowReader, I'm not sure how one would implement late materialization or similar operations? That document, which as an aside is fantastic, shows somewhat confirms my hunch that these optimizations net massive returns for our query patterns?

**Comment by alamb** [comment]
@tustvold  the ideal outcome, in my mind, would be to extend / modify  [ParquetFileArrowReader](https://docs.rs/parquet/latest/parquet/arrow/arrow_reader/struct.ParquetFileArrowReader.html) with predicate pushdown. 


> I'm not sure how one would implement late materialization or similar operations?

It probably depends on what you mean by late materialization

I haven't studied the code, but I can't think of any reason why `ParquetFileArrowReader` couldn't do 'late materialization' of the code *after* predicates had been applied within the `ParquetFileArrowReader` itself. 

If you mean "carry positions out of `ParquetFileArrowReader` and fetch values in some other operator" (which I have seen be valuable for joins, but not sure we need it in IOx) then using the current ParquetFileArrowReader may be challenging

**Comment by alamb** [comment]
> That document, which as an aside is fantastic, somewhat confirms my hunch that these optimizations net massive returns for our query patterns?

yes, that was my conclusion: there is a lot of room for improvement in the parquet reader when it becomes critical
