### ISSUE TITLE
Database Init Recovery

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#3335]
# Current Situation
At the moment we require "operator intervention" for basically every database init error:

https://github.com/influxdata/influxdb_iox/blob/76befe94ad14cd121d6fc5c58aa112997d9e211a/server/src/database.rs#L837-L850

Note that we we already retry many IO operations, but this might not be sufficient of larger issues (e.g. unhealthy K8s cluster, connectivity issues, AWS downtimes like yesterday). So at the moment we basically terminate the init process and wait for some operator to do something. This is quite some burden for servers w/ 1k+ databases. Also we don't actually provide gRPC APIs and CLI commands to recover a database from all the error states ("force rebuild catalog" from #3292 being a notable exception / escape hatch).

The init process is a bit special because in contrast to admin actions, catalog inspect calls, queries, writes and metrics (basically all HTTP and gRPC) as well as lifecycle-driven ops and write buffer-driven writes -- all of which are retried by the external or internal driver/actor--, IOx itself is the actual driver and currently doesn't retry.

# Proposal
Add a retry logic to most/all init states. Most error states can be reset to a non-error state that they have originated from.

We might need to spend some thought if this also applies to "replay" though, because this would probably double-replay some messages. So we might need to reload the preserved catalog.

The error states should be kept however, since they convey important information to the users and conductor. I think [`wait_for_init`](https://github.com/influxdata/influxdb_iox/blob/76befe94ad14cd121d6fc5c58aa112997d9e211a/server/src/database.rs#L484-L512) should also stop and fail on the first error, so we don't block forever.

# Prior Art
In #3318 the error handling was changed for the write buffer creation, so we don't terminate database initialization when a Kafka cluster is unhealthy. However the wiring could probably be improved to add an improved, potentially increasing backoff mechanism.

# "Real World" Cases
- #3287
- test bench errors if minio gets restarted, e.g.:
  `2021-12-08T10:55:30.848240Z ERROR server::database: database in error state - operator intervention required db_name=myorg_mytemplate3343 e=error getting database owner info: error loading owner info: AWS S3-based Object Store error: Unable to GET data. Bucket: iox, Location: dbs/de87efa5-c2c1-405d-a227-3437240ed319/owner.pb, Error: Error during dispatch: connection error: Connection reset by peer (os error 104) (HttpDispatch(HttpDispatchError { message: "Error during dispatch: connection error: Connection reset by peer (os error 104)" })) state=OwnerInfoLoadError`

**Comment by alamb** [comment]
@crepererum  I really like the idea of making the database startup "self healing" (aka not require operator intervention). 

I wonder if we could do something relatively simple here like "if the database got into an error state, put it back into `Initializing` after some period of time (10 seconds?)"

 This would definitely not be as efficient as per-error state recovery / retry but I bet the code would be a lot simpler (and easy to test)

**Comment by crepererum** [comment]
The actual error recovery is actually quite simple, I'm nearly done with it and it doesn't really add much complexity.
