### ISSUE TITLE
Allow data generator to assign agents to databases through regex match

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#3344]
Currently, the data generator allows users to specify what ratio of the supplied list of databases should use what configs. A user should alternatively be able to assign agents to databases based on a regex match against their name. These would be mutually exclusive in a data generator spec. Either the user can use ratios or they can use regexes.

**Comment by alamb** [comment]
Is the idea here is to be able to model scenarios such as a single agent sending massive traffic to one database and lots of little agents sending tiny amounts of data to many databases?
