### ISSUE TITLE
Performance improvements backlog

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#336]
This issue lists potential performance improvements we ran into while implementing v1 of delorean. This is sort of a dumping ground now so I don't forget these possibilities (aka so I can sleep at night while leaving lots of inefficiencies)

##  Better dictionary array support in DataFusion 
https://github.com/apache/arrow/pull/8359 added basic dictionary support, but the behavior is to unpack all dictionary values to compute on them. This pretty much voids all value we might get from DictionaryArrays in the first place (#334)
** Improvements: implement dict/dict equality comparison kernel / proper dict/dict comparison support in DataFusion
** Improvement: Special case comparing to a scalar value (now an arrow array full of the same value is created which is very very wasteful)

## Save min/max values in write buffer columns
If we saved min/ma values for the Columns in delorean_writebuffer/src/column.rs then the timestamp predicate evaluation could likely be significantly faster (as we could potentially rule out entire columns based on timestamp)

## Improve the datafusion plans used in write buffer
There are several things we can do to improve the plans:
1. Enable the data fusion optimizer + predicate pushdown (it is disabled now, I think)
2. Don't convert the entire write buffer table to a RecordBatch -- instead make a custom scan node (ideally with predicate push down) that only converts requested columns. And let the data fusion optimizer figure out what columns are actually needed.  Aka get rid of:
```
        // TODO avoid materializing here
        let data = self.to_arrow_impl(partition, &requested_columns_with_index)?;
```

**Comment by jacobmarble** [comment]
@alamb can this be closed?

**Comment by alamb** [comment]
I think these are either no longer relevant or covered elsewhere. Let's let actual profiling data drive future work
