### ISSUE TITLE
Move lifecycle up to server level and simplify

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#3366]
Lifecycle rules should be removed from the individual databases. Instead, the server should have settings for the following:
* Hard buffer memory limit (stop accepting writes when this many bytes have been buffered up)
* Soft buffer memory limit (start persisting data and evicting it from memory when this limit is crossed). This should represent the steady state memory footprint while ingesting. When hit this should cause the server to persist and evict the largest partition across all databases.
* Max age data (if data in a table/partition is older than this duration, trigger persistence for that partition). This allows operators to set the upper bound on how far back into Kafka an ingester must go on restart.

**Comment by alamb** [comment]
I believe the rationale for this ticket is that  The current per-database lifecycle policy knobs are too complicated to configure, especially when multiple databases with unknown workloads are shared on the same server

There are also some additional thoughts on rationale and ideas on https://github.com/influxdata/influxdb_iox/issues/3132

**Comment by pauldix** [comment]
This is no longer valid as the new ingester works with a different lifecycle.
