### ISSUE TITLE
Abort Database Init State Machine

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#3368]
Currently database shutdown waits for replay to finish or error, this by extension means that server shutdown waits for replay to finish.

The scenario where I observed this, had one database with an incredibly large replay window with replay taking a significant length of time, and another database that panicked during replay. The latter database would trigger server shutdown, but the server would wait until replay of the other database had finished before actually exiting.

It should be possible to trigger shutdown of database's in the process of initializing and have them terminate in a timely manner

**Comment by crepererum** [comment]
It's probably sufficient to call `abort` on this handle here:

https://github.com/influxdata/influxdb_iox/blob/d0f588d3b800894fe0ebd06b6f9a184ca6a603d7/server/src/database.rs#L188

**Comment by tustvold** [comment]
This problem is more general, and can also occur if initialization gets stuck in a given stage. Going to pick this one up as it is preventing recovering production, where initialization is stalling because Kafka no longer contains the offset to resume consumption from.
