### ISSUE TITLE
Parquet Reader Blocking Thread Count

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#3400]
**Problem**

In https://github.com/influxdata/conductor/issues/854 @alamb observed ~500 threads active.

`tokio::spawn_blocking` will spawn new blocking threads as needed to handle blocking tasks, up to a limit. This default limit is 512 which fits with this.

Currently within IOx we use `tokio::spawn_blocking` to

* Interface to rdkafka
* Scan parquet files

It is my suspicion that the latter is the main source of the high thread-count as a result of #3288 

**Proposal**

In addition to fixing #3288 we should probably limit concurrent parquet scans and do something a bit more sophisticated than just relying on `spawn_blocking` to eventually make progress

**Comment by crepererum** [comment]
I also think that our `rdkafka` interface is NOT the issue here since we only use `spawn_blocking` for a very limited set of metadata calls during the connection phase.

**Comment by alamb** [comment]
FWIW here are the threads that were active: 
[gbd-stacks.txt](https://github.com/influxdata/influxdb_iox/files/7735032/gbd-stacks.txt)


I don't see all that many doing anything related to parquet -- it looks like a bunch are related to parquet and then we have 3x# cores (which is like 3 x 40 = 120) for the three tokio task pools (query, reorg, and main)

**Comment by alamb** [comment]
Although there are many named `Thread 671 (LWP 161136 "tokio-runtime-w"):` which may be related

**Comment by alamb** [comment]
The DataFusion parquet reader (which IOx uses) no longer uses spawn blocking so I do not think this ticket is relevant any longer
