### ISSUE TITLE
Replace RwLock on Tables of the Catalog with an Arc

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#3404]
__Use case:__
We try not to lock when it is not necessary. It looks like this Tables' lock is not necessary and can be replaced with an Arc:

[tables: RwLock<HashMap<Arc<str>, Table>>](https://github.com/influxdata/influxdb_iox/blob/8a2410e161996603a4147e319c71e5bb38ca9cb7/server/src/db/catalog.rs#L94)

__Proposal:__
Replace the RwLoc with Arc

**Comment by NGA-TRAN** [comment]
What do you think @tustvold ?

**Comment by alamb** [comment]
I don't think we should mess with locking code until we have measurements that guide us

**Comment by NGA-TRAN** [comment]
Yeah, #3405 will provide some measurements and I will work on it first.
As an extra note, @tustvold left a comment `/// TODO: Remove this unnecessary additional layer of locking` on [tables: RwLock<HashMap<Arc<str>, Table>>](https://github.com/influxdata/influxdb_iox/blob/8a2410e161996603a4147e319c71e5bb38ca9cb7/server/src/db/catalog.rs#L94)

**Comment by tustvold** [comment]
> RwLock with Arc

These are not the same thing? You wouldn't be able to add or remove table to `Arc<HashMap<_, _>>`

> It looks like this Tables' lock is not necessary

There is a TODO above it that I put there, which was from when we have an RWLock around `Catalog` itself when stored on `Db`. I think this might be out of date...

**Comment by NGA-TRAN** [comment]
@tustvold : What I meant was Mutex Arc. But if it works the same as RwLock then no point to do so

**Comment by tustvold** [comment]
If anything a `Mutex` will result in more contention

**Comment by NGA-TRAN** [comment]
Close this and will remove the TODO comment with my next PR
