### ISSUE TITLE
File Object Storage Resolve `~`

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#3442]
Running the command

```
 ./influxdb_iox  run --object-store=file --data-dir=~/.iox/data --server-id=42
```

I expect IOx to resolve the `~` to my home directory.

Current master instead creates a directory called `~` in the current working directory

I'm sure this used to work, but it no longer appears to

**Comment by alamb** [comment]
As a workaround I use `$HOME/.iox` in case that is helpful to you

**Comment by crepererum** [comment]
TBH I'm not sure if this is really a bug. Are all CLI tools really expected to expand `~` for every possible path? Shouldn't this be done by the shell? Note that we also don't expand environment variables.

**Comment by tustvold** [comment]
```
 ./influxdb_iox  run --object-store=file --data-dir ~/.iox/data --server-id=42
```

Works so going to close this as PEBCAC.

In other news I accidentally ran `rm -rf ~` whilst debugging this... I aborted it quickly and don't appear to have lost anything important, but who knows... :scream:

**Comment by alamb** [comment]
Today I Learned PEBCAC: "Problem Exists Between Chair and Computer"

I have heard the same sentiment described as "Working as Expected"
