### ISSUE TITLE
Ingester: split Kafka partition into IOx Partitions

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#3451]
# Rationale 
This is a feature defined in the checklist of #3447.

An Ingester is responsible for:
1. Reading data from the Write-Buffer (in Kafka) for a set of assigned Kafka partitions. 
2. Split each Kafka partition into smaller IOx partitions based on partition key (default  is day).
3. Persists IOx partition when they are old or big enough based on redefined settings.

Number 1 exists in the code today and will be used as is. Number 2 is the task of this ticket.

# Design

## Requirements:
1. Not use existing catalog. All catalog info must be retrieved from the new IOx Catalog in Postgres. Refer to the ERD Diagram of the new Architecture Design for the content of the new IOx Catalog.
2. Not use the current Data Life Cycle. No Chunk creation needed. Incoming data of each IOx Partition will be kept as is (if possible) and persist to Parquet File when they are old or big enough.
3. No need to sort data in the Ingester (Not sure if this is possible). We need to balance between this one and the work in the Querier to load data back as RUBs.

## Design Thinking

When an Ingester is created, it will be assigned with a set of `Kafka Partitions`, each is equivalent to  a `sequencer_id`(or simply a sequencer)  in today existing IOx code and will be kept as is.

When an ingester starts up and finishes some must-do-at-startup such as  reading default rules and recovery (done in other tickets), it will start reading/ingesting data from its assigned sequencers (Kafka Partitions). Each sequencer is implemented in its own thread (or process?) and should not share data with other thread (process). For each sequencer, keep reading data, split them into IOx Partitions and store in memory.

**Questions:**  If we handle each sequencer in a process that does not share data with other processes, do we need a kind of resource management to make sure a process does not consume most resources? If we handle each sequencer in a thread, can we assume to do not need to worry much about resource management?

If I assume we go with the thread solution, our in-memory data will look like:
1. a map[Sequencer, SequencerData]
2. Each SequencerData will include a map[Namespace, Tables]
3. Each Table contains a map[Table -> IOx Partitions]

**Need more thinking:**
1. What is the best structure to use to persist an IOx partition into a parquet file while still accept new writer into that partition?
2. Why we need to keep persisted partitions  in memory of the ingester? I do not see the benefits to keep them if the Querier reads persisted data from Object Store. If we keep them, our design will be more complicated to to keep track of persisted ones for later eviction when needed.

**Comment by tustvold** [comment]
I believe 2. already exists and can be found [here](https://github.com/influxdata/influxdb_iox/blob/main/mutable_batch/src/payload.rs#L103). It takes a payload from the write buffer and splits it up to be written to one or more IOx partitions

**Comment by NGA-TRAN** [comment]
@tustvold I have update the `Design` sections with some requirements and thinking for our chat.
@pauldix: What do you think about this preliminary design and thinking? I also have questions for you there.

**Comment by NGA-TRAN** [comment]
We have the [design doc](https://docs.google.com/document/d/14NlzBiWwn0H37QxnE0k3ybTU58SKyUZmdgYpVw6az0Q/edit#heading=h.y9fy1bda7k50) that this task is a part of it. Close this as it is tracked in #3347
