### ISSUE TITLE
IOx Catalog Insert and Update

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#3454]
# Rationale

Since our new Architecture design has a central `Catalog` used by `Router`, `Ingester`, `Compactor`, `Querier`, and `Query Router`, this ticket list who will insert and update that central `Catalog`.

1. Kafka_Topic
     . Inserted by: When an **ingester cluster** is created
2. Query_Pool
     . Inserted by: When a **query pool** is created?
3. Name_Space
     . Inserted by: Router?
4. Sequencer
     . Inserted by: When an **ingester cluster** is created
     . Updated by: Ingester on `min_unpersisted_sequnce_number` field
5. Table_name
     . Inserted by: Router
6. Column_name
     . Inserted: Router
7. Partition
     . Inserted by: Ingester  -- @pauldix and @domodwyer : If Router is the one that splits data into IOx partitions, it will be responsible to update this Partition table. I do no think anything else in the Catalog needs to be changed.
8. Parquet_File
     . Inserted by: Ingester & Compactor
     . Updated by: Compactor on `to_delete` field
     . Deleted by: Compactor?
9. Tombstone
     . Inserted by: Ingester
     . Deleted by: Compactor
10. Processed_Tombstone
     . Inserted by: Ingester & Compactor
     . Deleted by: Compactor

**Comment by NGA-TRAN** [comment]
@pauldix @mkmik @domodwyer @crepererum : Since there is so much information for us at his stage, I creates this for us to refer to. Can you see if this reasonable? Refer to the ERD diagram of the Architecture doc for the meaning of the tables

**Comment by pauldix** [comment]
That all looks correct except Processed_Tombstone should also be inserted by Compactor. A tombstone can be applied to many Parquet files so processing of the tombstone will be incremental and the compactor won't be able to delete it until all Parquet files it applies to have been compacted.

**Comment by NGA-TRAN** [comment]
Updated to have Processed_Tombstone inserted by Compactor too

**Comment by domodwyer** [comment]
Thanks for this @NGA-TRAN  - this fits with my mental model too 👍

**Comment by NGA-TRAN** [comment]
Close this as it only includes information for our communication when the project was started
