### ISSUE TITLE
Add query complete time to Queries System Table

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb_iox#3457]
Currently the `queries` system table has query issue time, which records the wall-clock time when the query was issued.

Whilst investigation problems with Query mirroring internally I would find it helpful to easily see which queries are still running and how long queries took to run.

I would like to add two new columns to this table:

 1. completed: a boolean column where the value indicated whether the query has completed or not.
 2. completed_duration: a duration column where the value is `NULL` until the query completes, and then is it is the non-null duration that the query took to complete.

### Proposed Approach

I have taken a quick look around and would probably do something like this:

First, add an arc-wrapped atomic to the `QueryLogEntry` that can be used to track the duration a query took to complete:

https://github.com/influxdata/influxdb_iox/blob/a750da43f1ae580948f1ee470b6a782c9aab09cc/db/src/query_log.rs#L9-L19

Second, I would change the `record_query` method on the `QueryDatabase` trait to return a closure. This closure will be used to signal a query was completed:

https://github.com/influxdata/influxdb_iox/blob/a750da43f1ae580948f1ee470b6a782c9aab09cc/query/src/lib.rs#L80-L104

When the closure is called it would update the atomic on the `QueryLogEntry`. This would be handled in the `record_query` method  of the `QueryCatalogAccess` implementation of the `QueryDatabase` trait.

https://github.com/influxdata/influxdb_iox/blob/a750da43f1ae580948f1ee470b6a782c9aab09cc/db/src/access.rs#L213-L240

Thirdly, I would update the queries system table to add the new columns. We could use a sentinel duration, e.g., `-1` to indicate that a query was still running (setting the completed column for the row to `false` and the `query_duration` column to `NULL`). 

Fourthly, I would update all the points that call `record_query` to hold onto the closure and then call it once the query was completed.

Something like:

```rust
let finish =  db.record_query("sql", &q);
...
...
...
...

finish();
```

**Comment by alamb** [comment]
@e-dard  some thoughts:

I think `completed` is redundant -- it is the same as `completed_duration IS NULL`


> Second, I would change the record_query method on the QueryDatabase trait to return a closure. This closure will be used to signal a query was completed:

Rather than a closure the caller has to call, what would you think about a `RAII` type thing

like 
```rust
struct QueryDurationToken {
  data: Arc<...>
}

impl Drop for QueryDurationToken {
  fn drop(&mut self) {
    // update self.data correctly...
  }
}
```

**Comment by e-dard** [comment]
@alamb I'm fine with excluding `completed`. 

I'm not a big fan of the implicit magic of the RAII style side-effects to be honest, because I think it can be confusing for future code-readers, but let's try it and see how it pans out.
