### ISSUE TITLE
Can't deserialize canceled `IoxOperation` with `serde_json` after pbjson update to 2.0: "data did not match any variant of untagged enum Content"

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#3458]
List the minimal actions needed to reproduce the behaviour.

Try and encode/decode an `IOxOperation` that is canceled using `serde_json` (and thus implicitly `pbjson`)

This (non canceled) operation successfully parses as an `:`

```json
{
  "operation": {
    "name": "51",
    "metadata": {
      "typeUrl": "type.googleapis.com/influxdata.iox.management.v1.OperationMetadata",
      "value": "CPGJARCYr4beAxgBKgcKBYCU69wDaAE="
    },
    "done": true,
    "response": {
      "typeUrl": "type.googleapis.com/google.protobuf.Empty"
    }
  },
  "metadata": {
    "cpuNanos": "17649",
    "wallNanos": "1002543000",
    "totalCount": "1",
    "successCount": "1",
    "dummy": {
      "nanos": [
        "1000000000"
      ]
    }
  }
}
```

This FAILS to parse as an `IoxOperation`(note that it has an `error` rather than `response`)
```json
{
  "operation": {
    "name": "50",
    "metadata": {
      "typeUrl": "type.googleapis.com/influxdata.iox.management.v1.OperationMetadata",
      "value": "CNlDELjejwEYASoHCgWAlOvcA3gB"
    },
    "done": true,
    "error": {
      "code": 1,
      "message": "Job cancelled"
    }
  },
  "metadata": {
    "cpuNanos": "8665",
    "wallNanos": "2355000",
    "totalCount": "1",
    "cancelledCount": "1",
    "dummy": {
      "nanos": [
        "1000000000"
      ]
    }
  }
}
```

Full repro: 
[repro.zip](https://github.com/influxdata/influxdb_iox/files/7864314/repro.zip)
1. Unzip
2. Point `Cargo.toml` at your local checkout of `influxdb_iox` with the changes from https://github.com/influxdata/influxdb_iox/pull/3455
3. `cargo run`

__Expected behaviour:__
Test should pass and no panic produced)

__Actual behaviour:__
Test errors with
```
thread 'main' panicked at 'Parsing: Error("data did not match any variant of untagged enum Content", line: 10, column: 15)', src/main.rs:41:60
```

**Comment by alamb** [comment]
@tustvold  FYI

**Comment by tustvold** [comment]
I plan to look into this today

**Comment by alamb** [comment]
Adding link from slack: https://github.com/serde-rs/json/issues/559

**Comment by tustvold** [comment]
Filed https://github.com/apache/arrow-rs/pull/1175 which should "fix" this in the short term. Further context https://github.com/apache/arrow-rs/issues/1174 and I've filed https://github.com/serde-rs/json/issues/846 for what I think is the real solution
