### ISSUE TITLE
Update write buffer interface to take specific partitions

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#3500]
Given the ingester will be configured at startup to only consume from specified kafka partitions, the write buffer needs an interface to be able to initialize and consume only from those partitions.

This might be just a new abstraction within the write buffer crate given that it's only router2 and ingester going to be using it. And there's no need to support rdkafka in addition to rskafka. Whatever makes it easiest to get done while letting both the previous system and the new architecture operate at the same time.

**Comment by crepererum** [comment]
This is already supported. "Partitions" are called "sequencers" in write buffer terms. You can ask both producer and consumer for the set of sequencers and produce/consume to/from certain sequencers. IOx currently only uses sequencer 0.

https://github.com/influxdata/influxdb_iox/blob/56abfba0f0e5f45274154d5b2938cde85b4c85d8/write_buffer/src/core.rs#L15-L52

https://github.com/influxdata/influxdb_iox/blob/56abfba0f0e5f45274154d5b2938cde85b4c85d8/write_buffer/src/core.rs#L75-L98
