### ISSUE TITLE
Command to init Kafka Partition config in catalog

### ISSUE THREAD

**Issue by carols10cents** [influxdata/influxdb_iox#3509]
We need a command that:

- Is idempotent
- Inserts into the catalog records for the kafka topic and the number of partitions that currently exist in Kafka

**Comment by domodwyer** [comment]
I think @lukebond might be a great candidate for this - he has heaps of experience with our CD pipelines so can stich it all together 👍

**Comment by lukebond** [comment]
just trying to spec this out a bit so i can get started. here's my understanding of it:

- the catalogue in postgres needs stuff added to it that we want to be able to configure in a Kubernetes CRD via jsonnet
- i *think* this means inserting into the kafka_topic and namespace tables only?
- define a CRD in k8s that allows us to configure this for a cluster
- write a CR for ioxShared with the configuration we need
- hook that into the jsonnet that mkm is working on
- write a CLI tool that runs on deployments and takes the data in the CR and applies it to modify the postgres database (i.e. a bunch of SQL inserts in a transaction)

is that about right?

**Comment by crepererum** [comment]
@lukebond and I had a quick chat and agreed that he's taking care of the infrastructure side (i.e. when and how are partitions added) while I'll provide a CLI interface that admins as well as machines can use. So here's a draft for the CLI:

```console
$ # Run SQL migrations
$ # - To be executed once per postgres DB and for every new IOx version.
$ # - Is idempotent.
$ # - DSN can also be passed via INFLUXDB_IOX_CATALOG_DSN.
$ influxdb_iox catalog setup \
    --catalog-dsn "postgres://<user>:<password>@<host>[:<port>]/<db>"

$ # Create/update new topic
$ # - To be executed once per topic.
$ # - Is idempotent.
$ # - Currently this only adds topics since besides the name we don't have any options/parameters.
$ # - DSN can also be passed via INFLUXDB_IOX_CATALOG_DSN.
$ # - Will NOT interact w/ Kafka. The actual topic is created via a Strimzi custom resource.
# # - Returns numeric topic ID.
$ influxdb_iox catalog topic update \
    --catalog-dsn "postgres://<user>:<password>@<host>[:<port>]/<db>" \
    "<topic>"
42
```

Let's NOT do anything about the `namespace` table for now (it's not used at the moment and to me it looks that we need to clarify a few things in there).
