### ISSUE TITLE
Add abstraction to query system tables across databases

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb_iox#3591]
One thing in common with all databases on an IOx query node are the schemas associated with their _system tables_.

As I now begin to run IOx on production workloads where there any often many databases per user/query node it can be invaluable to get a picture of what's going on for the entire server (across all databases).

Therefore I propose that we teach the `influxdb_iox` binary to be able issue a query for system tables across all databases on the server.

The query need not union or aggregate across all the databases. Instead, it would just be valuable (to me, anyway) to just have the same query run on each database independently, and the results be emitted separately to the user.

**Comment by alamb** [comment]
I think the `observer` command in sql repl mode already does this: 

https://github.com/influxdata/influxdb_iox/blob/4f2503d92c8b5abd79ccfe3734ef9f52e1b17492/docs/sql.md#observer

**Comment by e-dard** [comment]
👍
