### ISSUE TITLE
InfluxRPC Table Predicates

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#3601]
**Problem**

The current process for handling InfluxRPC predicates is as follows:

1. RPCNode structure is decoded from gRPC
2. The tree is searched for InList predicates on TagRefValue("__measurement") and this is stored as `table_names`
3. When snapshotting chunks from the catalog we either snapshot chunks from tables in `table_names` or all tables if not present
4. Rewrite predicate for each table, replacing `col("__measurement")` with the name of the table among other modifications
5. Snapshot catalog for each table, and prune, plan and execute the query

Unfortunately this will fail to deduce a narrow set of tables in a number of situations:

* Multiple table predicates OR-ed together, e.g.  `__measurement = "foo" or __measurement = "bar"`
* A table predicate using a regex, e.g. `__measurement ~ "foo"`

**Proposal**

Correctly deducing the minimal set of tables from an arbitrary expression tree is a non-trivial problem, however, with #3600 and in particular #3557 we wish to simplify the predicates prior to handing them to Datafusion - between steps 4. and 5. above. This simplification should include the existing constant propagation and boolean reduction passes in Datafusion. 

Additional logic should be added to detect when the predicate is no longer satisfiable, e.g. `Boolean(false)` and skip further evaluation for that table. This will effectively turn step 2. into a best effort approximation of the minimal set of tables, with the combination of 4. and the predicate simplification serving to prune the rest.

**Alternatives Considered**

Special case more table predicates, to make the table selection in 2. more accurate. This is likely to quickly become non-trivial, but could also be done in addition to what is proposed in this ticket

**Comment by alamb** [comment]
> when the predicate is no longer satisfiable, e.g. Boolean(false) 

I think it is actually `Boolean(false)` OR `null`

**Comment by alamb** [comment]
> This simplification should include the existing constant propagation and boolean reduction passes in Datafusion.

I believe this part is handled in https://github.com/influxdata/influxdb_iox/pull/3557 (each predicate is 'table normalized' and simplified prior to metadata evaluation of `QueryChunk::apply_predicate_to_metadata`): https://github.com/influxdata/influxdb_iox/blob/21c1824a7a60eeb5d40f4cf654fd916753fb110e/query/src/lib.rs#L160-L169

> Additional logic should be added to detect when the predicate is no longer satisfiable, e.g. Boolean(false) and skip further evaluation for that table.

This may need some more work. Specifically:
1. `QueryChunk::apply_predicate_to_metadata` often bails if there are any `Exprs` (even if it is `null` or `Boolean::False`)
2. Prior to the actual scan, the `MissingColumnsToNull` rewrite is applied to the predicate for each chunk and the predicate is not further simplified after this nor is the chunk ruled out

**Comment by alamb** [comment]
I think such predicates are correctly simplified now. I will write a test to demonstrate it happening to close this ticket

**Comment by alamb** [comment]
https://github.com/influxdata/influxdb_iox/pull/3649
