### ISSUE TITLE
Update router to send mutable batches belonging to a single partition

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#3603]
The setting for how data is partitioned in a namespace will be a property of the namespace. The router should automatically partition the data as it comes in (along with sharding it) based on the partition settings in the namespace. It should add the partition key (a string) to the mutable batch so that it can be read by the ingester.

For now, partitioning can just be hard coded by day. We'll need to come up with some expression to specify how to partition data later.

The ingester will be responsible for creating any partition records in the catalog.

The code in `data.rs` in #3533 will need to be updated so that it doesn't generate the partition key itself.

**Comment by domodwyer** [comment]
Update: 

* Router partitions the data using a hard coded YMD date string
* Key is not propagated across the API boundary to the ingester - currently the ingester is inferring it from the data it gets
