### ISSUE TITLE
Ingester: move deletes into snapshot batch

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#3699]
Delete tombstones should move into the snapshot batch whenever snapshotting is done so they get cleared out of the buffer. Any data arriving after the delete tombstones shouldn't have them applied.

**Comment by NGA-TRAN** [comment]
@pauldix There are 2 more things we need to do when we move delete tombstones to snapshot batch:
1. Those tombstones should be added to existing snapshots.
2. Those tombstones need to be moved to a separated list the DataBuffer  if there is an existing PersitingBatch. They will be needed in case a query comes while persisting. This list will be emptied when a new PersistngBatch is created.
