### ISSUE TITLE
Should Shutdown Trigger Persistence?

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#3726]
As pointed out by @alamb in https://github.com/influxdata/influxdb_iox/pull/3720#issuecomment-1036139822 database shutdown currently makes no attempt to flush buffers. This is irrespective of what initiated the shutdown, be it a gRPC call to shutdown a single database, part of server shutdown, etc...

This means that in the absence of a write buffer, any unpersisted data is liable to be lost.

On one level this is expected behaviour, the write buffer is the durability story, but perhaps in the event of a controlled shutdown we could do better? This will likely result in parquet files in object storage with overlapping time ranges, but maybe this isn't a problem? We'd also likely need to have some sort of maximum grace period to prevent shutdown stalling indefinitely...

Creating a ticket to keep a record of this, and to track any future action taken

**Comment by alamb** [comment]
I think the least surprising behavior to users would be to expose two types of user initiated shutdown:

1. "normal" shutdown attempts to persist any data ingested to that point (and stops accepting new writes). No timeout should be given
2. A "fast" / "force" version of the shutdown which skips persistence (or has only a limited timeout for it to occur before forcing a flush)

**Comment by tustvold** [comment]
Closing as relates to OG
