### ISSUE TITLE
More accurate ExecutorType for an Executing Query

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#3752]
# Rationale

Currently, there are only 2 enums defined in ExecutorType to identify which purpose a query is running for https://github.com/influxdata/influxdb_iox/blob/8dd96127d64a94057ee080457bb5656e7cbf7108/query/src/exec.rs#L65

Since we now have different types of servers, Router, Ingester, Compactor, and Querier that will build and run query plans (Router may not need this), we may need to make the enum more specific more the specific needs

**Comment by alamb** [comment]
it is not clear this is needed, closing for now. Please reopen if it is tracking something we plan to do or there is some other reason it should remain open
