### ISSUE TITLE
Write Buffer Aggregator Index Out Of Bounds

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#3805]
The write buffer frequently panics with output along the lines of

```
2022-02-15T14:52:26.013800841Z level=error msg="Thread panic" panic_info="panicked at 'index out of bounds: the len is 0 but the index is 0', write_buffer/src/kafka/aggregator.rs:467:22" target="panic_logging" location="panic_logging/src/lib.rs:94" time=1644936746013732368
```

This concerns the logic for matching the list of produced offsets, to the tags that produced them. In particular `Deaggregator::tag_to_record` appears to be empty, when it is expected it is expected to not be. I have never seen the panic caused by a non-empty `tag_to_record`. This suggests to me some sort of bug in the flush logic, either in IOx or rskafka, that causes `Aggregator::flush` to be called more than once, but I've yet to find a smoking gun

**Comment by tustvold** [comment]
Will close once I've confirmed issue is fixed, and have cleaned up additional logging

**Comment by crepererum** [comment]
This is fixed (at least we no longer see this issue).
