### ISSUE TITLE
Split API logic out of influxdb_iox crate into separate crates

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#3884]
The influxdb_iox crate is extremely slow to compile, and this is adding a frustrating amount of latency to getting code into production.

I therefore collected a self-profile to try to understand what it was spending time doing

```
$ RUSTFLAGS="-Zself-profile=$PWD/profiles -Zself-profile-events=default,args" cargo build --release
$ crox --dir profiles --minimum-duration 1000
```

[chrome_profiler.zip](https://github.com/influxdata/influxdb_iox/files/8161890/chrome_profiler.zip)

If my interpretation of this is correct, it is primarily bottlenecked on LLVM codegen, with the majority of time spent in `LLVM_module_optimize` and `LLVM_passes`.

I therefore collected data about what functions were creating the most IR.

[lines.zip](https://github.com/influxdata/influxdb_iox/files/8161941/lines.zip)

This suggests to me that the tonic, and hyper code are responsible for a significant amount of generated LLVM IR. This is not hugely surprising as they rely extensively on generics. I therefore think that there might be value in splitting the various gRPC and HTTP server and client code into separate crates so that they can be compiled in parallel.

Perhaps something like

* `influxdb_iox_common`
* `influxdb_iox_database`
* `influxdb_iox_router`
* `influxdb_iox_router2`
* `influxdb_iox_compactor`
* `influxdb_iox_querier`
* `influxdb_iox_cli`

**Comment by alamb** [comment]
I like the sound of this plan. Please let m eknow if I can help

**Comment by alamb** [comment]
I was thinking sequencing wise we would do a single PR that broke out one or two of the crates to define the pattern and then just apply that pattern to everything else

This might also help with with querier side of things (which will likely be a plumbing exercise I think) so I can justify it that way

**Comment by NGA-TRAN** [comment]
@alamb Does it mean 'influx_iox_compactor` will be used for the new NG compactor? We do not have any code for it yet but I will add one soon/tomorrow.

**Comment by alamb** [comment]
> @alamb Does it mean 'influx_iox_compactor` will be used for the new NG compactor? We do not have any code for it yet but I will add one soon/tomorrow.


Yes, I think so @NGA-TRAN  -- I hope to have the first PR done shortly and then you can just follow the model of the other services (database, router, router2) and hopefully not be affected much

**Comment by NGA-TRAN** [comment]
Thanks @alamb . I plan to reuse/invoke available compaction functions

**Comment by alamb** [comment]
I am just going to shuffle directories around

**Comment by cannonpalms** [comment]
Big +1 to this. It would really improve operations to be able to manage components independently from one another. The "one binary to rule them all" approach has many strengths, but it is not a good fit for a cloud environment.
