### ISSUE TITLE
Ingester: test bench OOM + panic

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#3888]
Use the test bench and let it running for a while. The `ingester` pods will OOM, even though their config gives them enough headspace (1GB RAM, `INFLUXDB_IOX_PAUSE_INGEST_SIZE_BYTES` is 0.5GB, `INFLUXDB_IOX_PERSIST_MEMORY_THRESHOLD_BYTES` is 0.25GB).

My somewhat uneducated guess is that there might be too many persist jobs running in parallel here:

https://github.com/influxdata/influxdb_iox/blob/63bea75ee1d7ab5c567ac79c0108598801ddeb83/ingester/src/lifecycle.rs#L238-L255

The last log messages before the container dies are a bit fishy though:

```text
{"timestamp":"2022-03-01T16:34:59.903202Z","level":"ERROR","fields":{"message":"Thread panic","panic_info":"panicked at 'table med_measurement_10_card_7_16 for namespace myorg_mybucket0 not in sequencer 2 state', ingester/src/data.rs:210:17"},"target":"panic_logging"}
thread 'tokio-runtime-worker' panicked at 'table med_measurement_10_card_7_16 for namespace myorg_mybucket0 not in sequencer 2 state', ingester/src/data.rs:210:17
stack backtrace:
```

There's no stacktrace BTW. I'm not sure if this is somewhat a flux because the whole process gets messed up during the OOM, or if the panic triggers the OOM.

**Comment by domodwyer** [comment]
Quick update on this - I've been running various test envs under various configs and haven't hit an OOM yet with the ingester. I'll keep an eye out 👍

**Comment by domodwyer** [comment]
So it's been a few weeks and we haven't managed to reproduce this - I'll close it until it pops up again.
