### ISSUE TITLE
Consider Partition Key in Deduplicator

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#3899]
**Problem**

Currently deduplication only inspect chunk statistics to determine overlap, it does not take into account partitioning. This will cause it to deduplicate across partition boundaries if the chunk statistics are insufficient to prove no overlap.

**Proposal**

Chunks in different partitions by definition cannot overlap, the Deduplicator should use this to improve the generated plans.

**Comment by NGA-TRAN** [comment]
We have organized data in the NG catalog in a way that a parquet file will belong to only one partition which intern only belongs to one sequencer. When we compact them in both Ingester and Compactor, we will always compact files of the same partition and no need to worry about considering partition key while compacting/deduplicating

**Comment by tustvold** [comment]
I'm not sure I follow your reasoning here, the same is true in the OG catalog - a chunk belongs to a single partition. The issue concerns the way the query logic is hooked up, it is given a collection of QueryChunk from across all partitions, and does not take into account their partitions when determining what needs to be deduplicated?

**Comment by NGA-TRAN** [comment]
I think I got your point. This is for the work needed in the Querier not in the Ingester or Compactor. Either we consider this during deduplication, or we design the Querier to have a query plan to scan data per partition and do deduplication there so we do not have to do extra work during duplication.

**Comment by crepererum** [comment]
This was fixed by the new plan construction, or precisely by:

https://github.com/influxdata/influxdb_iox/blob/442cd1457a0651b84bf359bd6a82920ff7804733/iox_query/src/physical_optimizer/dedup/partition_split.rs#L21-L25
