### ISSUE TITLE
I can't build 

### ISSUE THREAD

**Issue by ljp1314258** [influxdata/influxdb_iox#3909]
thread 'main' panicked at 'failed to execute command: No such file or directory (os error 2)', /home/joekoe/.cargo/registry/src/github.com-1ecc6299db9ec823/tikv-jemalloc-sys-0.4.3+5.2.1-patched.2/build.rs:334:19

**Comment by tustvold** [comment]
Could you possibly provide some information on your system, the commands you ran with their full output, the output of `cargo --version`, etc... This will help us determine what is going wrong :smile:
