### ISSUE TITLE
Proposal: Local all-in-one mode NG

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#3926]
__Use case:__
* As a developer working on a feature such as query performance or a correctness bug
* I want to run / poke at a local instance of IOx NG in my development environment
* so that I can use the tools I feel most comfortable and productive with (e.g. debugger, modify code / rerun, etc) to be maximally productive

__Proposal:__
Allow users to create a fully functioning, single node, minimal IOx NG set of services. The cluster will require only the most minimal configuration options. Anything more sophisticated (for example, multiple routers, or queriers, etc) is out of scope and will be orchestrated by some other system (like our cloud deployment system for InfluxDB Cloud)

Specifically propose adding a command called `run2` after the similarly named `run` command in the current system This would be invoked like this (with reasonable defaults):

```shell
 influxdb_iox run2 --pg_dsn postgresql://localhost:5432/alamb  --object-store=file --data-dir=$HOME/.influxdb_iox
```

This will setup the following configuration (not at all configurable):
```text
┌─────────────┐  ┌─────────────┐   ┌─────────────┐   ┌─────────────┐
│   Router    │  │  Ingester   │   │   Querier   │   │  Compactor  │
└─────────────┘  └──────┬──────┘   └──────┬──────┘   └──────┬──────┘
       │                │                 │                 │       
       │                │                 │                 │       
       │                │                 │                 │       
       └────┬───────────┴─────┬───────────┴─────────┬───────┘       
            │                 │                     │               
            │                 │                     │               
         .──▼──.           .──▼──.               .──▼──.            
        (       )         (       )             (       )           
        │`─────'│         │`─────'│             │`─────'│           
        │       │         │       │             │       │           
        │.─────.│         │.─────.│             │.─────.│           
        (       )         (       )             (       )           
         `─────'           `─────'               `─────'            
                                                                    
        Existing         Object Store        kafka / redpanda       
        Postgres        (file, mem, or                   
       (started by      pre-existing)         (file, mem, or        
          user)        configured with        pre-existing)         
                        --object-store       configured with        
```

At some point in the future, (but not part of this project) we may provide a way to run without a pre-existing postgres installation.

__Alternatives considered:__

It may seem tempting to use some other technology like `gopm` or `docker compose` to manage the multiple processes required for IOx NG. However, this is non ideal , as @lukebond  noted, as then we have another tool to learn and another way to maintain configuration

Also, since all parts of NG are rust programs / processes, the additional complexity of installing other toolchains and build environments is not required

Somewhat related to the end to end tests: https://github.com/influxdata/influxdb_iox/pull/3905#pullrequestreview-899544829

**Comment by crepererum** [comment]
Sounds good to me :+1:

**Comment by e-dard** [comment]
> It may seem tempting to use some other technology like gopm or docker compose to manage the multiple processes required for IOx NG. However, this is non ideal , as @lukebond noted, as then we have another tool to learn and another way to maintain configuration

FWIW I use `gopm` with IOx regularly, and IOx isn't "in" `gopm`. You can use `gopm` to setup the other Influx Cloud bits, and then configure `gatewayd`, `queryd` and `influxqld` to talk to a local IOx process. With the design you propose above I think it would still be perfectly possible to carry on this workflow by pointing everything at the single IOx NG binary.

**Comment by e-dard** [comment]
@alamb can you expand on the `in-mem` version of Kafka? Are you planning to implement that as part of this work? We have solved this problem in Cloud by writing a "simple stream service", which is basically a process that acts as a pipe between gateway and storage. 

But in this case I think it would be worth having a simple "in process" pipe that replaces Kafka/red panda. Is that in scope for this?

Overall, looks like a good idea.

**Comment by lukebond** [comment]
if i understand correctly this will run a single process with the four iox components all started? rather than orchestrating the running of 4 iox processes running in each mode plus connection params to talk to the external components.

this i like, because it prevents us going down the orchestration route and having to maintain configuration in multiple places.

what i'd like to avoid is using this in CI or anywhere we want to gate the correctness of the system- that should be a system configured the one and only maintained way: k8s manifests, running in remocal.

if people want to run test suites locally against this setup then we should enable and facilitate that. but correctness should be demonstrated only against a correctly configured system that is production-like and comes out of our jsonnet codebase.

**Comment by alamb** [comment]
> But in this case I think it would be worth having a simple "in process" pipe that replaces Kafka/red panda. Is that in scope for this?

My goal is to minimize dependencies so that kafka/redpanda are not required to run NG

> @alamb can you expand on the in-mem version of Kafka?

@e-dard  I was not planning to add anything new; Rather I plan to reuse what we had already (and assumed we had a totally in memory version, but now that I research maybe we do not).

Looks like we have
1. a file backed version https://github.com/influxdata/influxdb_iox/blob/main/write_buffer/src/file.rs
2. a mock: https://github.com/influxdata/influxdb_iox/blob/main/write_buffer/src/mock.rs

I am not sure if the mock is ok for a memory version -- I'll look into it as part of this work

**Comment by alamb** [comment]
> FWIW I use gopm with IOx regularly, and IOx isn't "in" gopm.

To be clear, what I am trying to avoid is *requiring* `gopm` to run in local mode -- I don't want to preclude or prevent iox NG from running under gopm as part of other cloud services

**Comment by lukebond** [comment]
@alamb yes i think this would be useful at some layer, but not e2e IMO. 

however terminology differs from developer to developer. so your e2e may not be mine! to me, e2e is a prod-like complete system so must run in k8s. to me integration tests are more like our unit tests but many people use that term to mean the highest level :shrug:

**Comment by pauldix** [comment]
This all-in-one mode is actually something I have on the list for the future open source release. What I had envisioned was a setup that uses SQLite for the catalog, a file based WAL for the write buffer, and the filesystem for the object store. Although with the option to use Postgres, Kafka, and ObjectStore for the services. This would be the primary open source release and the thing that operates at the edge.

I didn't think we'd need it at this point because I assumed that the debugging and testing would happen with the individual components. But if it's useful now then I guess we're just getting a jump on that future thing.

**Comment by alamb** [comment]
I am stuck in tonic generics hell and need a break.

Basically, the issue is the same as why we currently use macro magic in [rpc.rs](https://github.com/influxdata/influxdb_iox/blob/79f40c7/influxdb_ioxd%2Fsrc%2Frpc.rs#L39-L77) which is that the type of the thing returned by tonic::Server::add_service is some complicated generic type. This means it works great when you have a static setup and don't have to name the types

Like this works great: https://github.com/hyperium/tonic/blob/4b0ece6/examples/src/reflection/server.rs#L39-L43

```rust
    Server::builder()
        .add_service(service)
        .add_service(proto::greeter_server::GreeterServer::new(greeter))
        .serve(addr)
        .await?;
```

But if you want to do something like
```rust
trait MaybeAddServices {
  fn add_services(&self, router: Router<...>) -> Router {
    ...
  }
}
```

You are out of luck because Router is generic you can't write out the actual type. I am thinking about this.

**Comment by alamb** [comment]
https://github.com/hyperium/tonic/issues/886 is a similar ticket in tonic and https://github.com/hyperium/tonic/pull/830 removes many/most of the generics.

**Comment by alamb** [comment]
I wonder if I can port https://github.com/hyperium/tonic/blob/6763d191d267c1b9f861b96ad0f4b850e0264f4d/tonic/src/transport/service/router.rs#L36 (and add some simple http router stub rather than axum) as a workaround 🤔 

I'll try that later today or tomorrow depending on how long it takes me to get through a review backlog

**Comment by carols10cents** [comment]
I'm not sure I completely understand the problem (can you share code that I could poke at? I don't think your tonic generics hell is in your PR :))

But I have a question that might be related... are the 4 modes that are all going to be running in the same process still going to communicate with each other via gRPC? Even though they're not R anymore? I could see going either way, keeping them communicating via gRPC to minimize the differences between the code and performance of all-in-one vs separate... but if the processes communicate with each other directly, then the all-in-one would only need to expose the gRPC to write data into the router and to get data out from the querier, correct?

**Comment by alamb** [comment]
> I'm not sure I completely understand the problem (can you share code that I could poke at? I don't think your tonic generics hell is in your WIP PR :))


I'll try and get an example up tomorrow if the workaround I am thinking of doesn't work. 

> But I have a question that might be related... are the 4 modes that are all going to be running in the same process still going to communicate with each other via gRPC?

I think they will mostly communicate via the catalog (posgres) and the object store and kafka. I haven't quite figured out what will happen with the querier talking with the ingester, but I am thinking at the moment it will likely use gRPC over the loopback (which is silly I know, but will keep the code simple)

> then the all-in-one would only need to expose the gRPC services to write data into the router and to get data out from the querier, correct?

That is my intent, yes -- basically the `all in one` will look mostly like the existing `influxdb_iox run` command in the services that are exposed.

**Comment by crepererum** [comment]
I see you're running into the same type madness that @tustvold and I also encountered that made me hack around the whole thing by using untyped macros :sweat_smile:.

The problem w/ backporting tonic changes or using a GIT version: tonic is directly used by arrow-flight, so you'll probably have to have an unstable port of that as well.

**Comment by tustvold** [comment]
I'm not sure which generics in particular are causing issue, but I'd be happy to lend a hand if you can point me at some code. I've a reasonable amount of experience with the tower generic soup 😅

FWIW the serving readiness functionality I remember added some non-trivial complexity and could probably just be removed as it was only needed for conductor

**Comment by alamb** [comment]
> I'm not sure which generics in particular are causing issue, but I'd be happy to lend a hand if you can point me at some code. I've a reasonable amount of experience with the tower generic soup 😅

🙏  thank you. I made a PR showing what I am trying to do, perhaps you can help implement it the interface there: https://github.com/influxdata/influxdb_iox/pull/3981

**Comment by alamb** [comment]
So the core problem is that the type of the thing created by `tonic::Server::add_service`  are bound to the specific type of service that was added so can only be run down one path.

For example, the actual type of `builder` is different in these cases:

```rust
let builder = tonic::transport::Server::builder()
  .add_service(db_service);
```

```rust
let builder = tonic::transport::Server::builder()
  .add_service(db_service)
  .add_service(ingest_service)
```


I think the options at this point are:
1. Implement our own version (likely a copy/paste) of tonic::transport::server, where the result of calling `add_service` is the same, likely taking the ported bits of axum (and replace when tonic 0.7 ships)
2. Run all in one mode on several different ports.


I think 1 is cleaner, but 2 will be faster to implement so I am going to proceed in that direction

**Comment by alamb** [comment]
After some sleep and discussion with @tustvold  I think I am going to try option 1 before entirely abandoning it

**Comment by jacobmarble** [comment]
@alamb do you mind revising this? Either a bit of copy-pasta, or I don't understand how S3 can be used as a message queue. :)

<img width="141" alt="Screen Shot 2022-03-10 at 10 50 02 AM" src="https://user-images.githubusercontent.com/622263/157734084-fd78a4a0-a4af-4208-a08d-6cd411639a70.png">

**Comment by alamb** [comment]
@jacobmarble  fixed -- yes i think the object store was copy/pasta'd for message queue
