### ISSUE TITLE
NG Compactor: Read catalog for level-0 and level-1 parquet files

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#3946]
# Rationale
The ticket is to implement step 1 and step 3 of the [Loop Find & Compact Files in the NG Compactor design](https://docs.google.com/document/d/1lfILhw5ckzTlXFOk7VXKQOiz3TvDDlx-tdCgQ0YiG8E/edit#heading=h.y3uqgzkpk0vx).

For step 1: build a function like this 
```rust
     get_level_0(sequencer_id) ->  Result<Vec<ParquetFile>>
```

Step 3:
```rust
   get_level_1(sequencer_id, table_id, partition_id) -> Result<Vec<ParquetFile>>
```

**Comment by carols10cents** [comment]
Going to start this, building atop https://github.com/influxdata/influxdb_iox/pull/3972

**Comment by carols10cents** [comment]
@NGA-TRAN For step 3, for this aspect of level 1 files:

```
( ( min_time <= level-0-file.min_time AND 
    max_time >= level-0-file.min_time) )  OR
( ( min_time > level-0-file.min_time AND 
     min_time <= level-0-file.max_time) ) 
```

and looking at this code in compact.rs: https://github.com/influxdata/influxdb_iox/blob/95f461b90769c48cc920cba9e13c70bc8e7ed87d/compactor/src/compact.rs#L82-L86

there are multiple `level-0-file`s to consider here when trying to find level 1 files. So is the `get_level_1` function supposed to:

* Option 1: Use the min of all level 0 file min times and the max of all level 0 file max times, to find all level 1 files that overlap with any time of the outer bounds of all level 0 files, but some level 1 files might not actually overlap with any
* Option 2: Iterate through each level 0 file and request the level 1 files that overlap with each one, which means calling `get_level_1` N times where N=number of level 0 files, and this might put duplicates into the list of files to consider if a level 1 file overlaps with more than one level 0 file
* Something else?

Thanks!

**Comment by NGA-TRAN** [comment]
@carols10cents I think we will go with Option 1 with  extra notes:
1. Since only files in the same partition (= same sequence_id, table_id, partition_id) may overlap, the option 1 should be repeated for each same-partition group of level-0 files.
2. After you get level-1 files in option 1, you may want to go over them and remove the ones that are not really overlapped with any level 0. Since the compaction is not cheap, we do not want to compact data that are not really needed.

**Comment by NGA-TRAN** [comment]
To be clear, point 1 means you do not need to iterate over N level-0 files but you need to iterate over M same-partition groups and M <= N.

**Comment by carols10cents** [comment]
> 2\. After you get level-1 files in option 1, you may want to go over them and remove the ones that are not really overlapped with any level 0. Since the compaction is not cheap, we do not want to compact data that are not really needed.

So if we go with Option 1 and I understand correctly, all the level 0 and level 1 files will be in the `val` vec after getting all the level 1 files that overlap the time range of the min(all level 0 files' min times) to max(all level 0 files' max times). Then, when we create the groups of files that overlap, we can disregard any groups that only contain level 1 files, and I think that will take care of what you're saying here? Does that sound right?

**Comment by NGA-TRAN** [comment]
@carols10cents 
> Then, when we create the groups of files that overlap, we can disregard any groups that only contain level 1 files, and I think that will take care of what you're saying here? Does that sound right?

Yes, perfect. I like you implement it that way. 👍 
I think in a few rare cases, we will find a group > 1 file that contains all level-1 overlapped files which are worth compacting into one, too.

**Comment by carols10cents** [comment]
> I think in a few rare cases, we will find a group > 1 file that contains all level-1 overlapped files which are worth compacting into one, too.

Looking at https://github.com/influxdata/influxdb_iox/pull/4001, I see that `compact` returns without doing anything if it gets only 1 file and no tombstones (regardless of level), so I think that should take care of not doing anything if there's a group of 1 file of level 1 that should do nothing.... and here, it sounds like you're saying we *do* want to compact groups of more than 1 file of level 1.... so I don't think there's anything further to do in this or any other ticket for this case? Just want to make sure we don't lose anything that needs to be changed!

**Comment by NGA-TRAN** [comment]
Right @carols10cents . I just pointed out the fact that we had not seen before and it is a good fact. Nothing else needs to be changed.
