### ISSUE TITLE
NG Compactor: Update the catalog of parquet files of a given list of parquet IDs to level 1

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#3950]
# Rationale
This ticket implements step 8 of [Find and Compact files](https://docs.google.com/document/d/1lfILhw5ckzTlXFOk7VXKQOiz3TvDDlx-tdCgQ0YiG8E/edit#heading=h.y3uqgzkpk0vx). The input is a list of parquet file IDs 

```rust
fn update_to_level_1(&[ParquetFileId]) -> Result<()>
``` 
Each update can be in its own transaction but for better performance, we prefer all the updates are in one transaction

**Comment by carols10cents** [comment]
I'm going to do this along with https://github.com/influxdata/influxdb_iox/issues/3946 because it's currently hard to create level 1 files without this function, and it would be hard to test that level 1 files were created without being able to query for them :)

**Comment by carols10cents** [comment]
@NGA-TRAN What should happen if we try to update the level of a parquet file id that doesn't exist? What if only some of the parquet files in the list exist and are successfully updated, but some aren't? Should this be an error or should the nonexistent files be ignored?

By default, if you ask Postgres to update something that doesn't exist, the operation isn't considered an error, so that would be the easiest thing to write but I'm not sure if it's the correct behavior :)

**Comment by NGA-TRAN** [comment]
@carols10cents : This is a good point. Talking about correctness, there should not be any error because these files should still be in the catalog. However, there are always unknown things going on, for example, a bug in Postgres or IOx. I would say, we do not error out but log the ID that we cannot update (if you can get some thing back from postgres saying nothing was updated) and continue updating the rest. Side effects of this:

1. We need a monitor (or an alert) to track the log and tell us this happens.
2. In the next compacting cycle, we will repeat compacting this unnecessary files which is not good for the compaction performance if they keep staying in level 0. That is why we need to log and investigate them.

**Comment by NGA-TRAN** [comment]
Maybe something for a broader discussion CC @pauldix

**Comment by carols10cents** [comment]
> 2\. In the next compacting cycle, we will repeat compacting this unnecessary files which is not good for the compaction performance if they keep staying in level 0. That is why we need to log and investigate them.

Well, if the update fails because the file doesn't exist in the catalog, then presumably the file won't be found in the next compacting cycle either, since it doesn't exist... hopefully...
