### ISSUE TITLE
NG Compactor: Update Catalog for processed compaction

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#3952]
This ticket implements step 6.b.iii of [Find and Compact files](https://docs.google.com/document/d/1lfILhw5ckzTlXFOk7VXKQOiz3TvDDlx-tdCgQ0YiG8E/edit#heading=h.y3uqgzkpk0vx).

**Comment by carols10cents** [comment]
Actually, doing this and #3951 together will be straightforward.

**Comment by carols10cents** [comment]
Actually actually, [I misunderstood](https://github.com/influxdata/influxdb_iox/pull/4058#discussion_r829487915), so this issue will now cover all updates to the catalog after a compaction.
