### ISSUE TITLE
NG Compactor: Remove soft deleted parquet files

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#3954]
# Rationale
This ticket implements [Remove soft deleted Parquet Files](https://docs.google.com/document/d/1lfILhw5ckzTlXFOk7VXKQOiz3TvDDlx-tdCgQ0YiG8E/edit#heading=h.r1i52kutaqb8)

**Comment by carols10cents** [comment]
Should cleaning up old files marked for deletion also happen on a per-sequencer basis, as the rest of the compactor does?

**Comment by NGA-TRAN** [comment]
@carols10cents : the latter. No need to check for the same sequencer as long as they use the same Time Provider unless @pauldix tells us otherwise
