### ISSUE TITLE
ingester: Store consistent sort key for all parquet files of the same partition (and the same table, too?)

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#3968]
# Parts

- [x] https://github.com/influxdata/influxdb_iox/issues/4194
- [x] https://github.com/influxdata/influxdb_iox/issues/4195
- [x] https://github.com/influxdata/influxdb_iox/issues/4196

# Rationale

- Since sort order of a parquet file is an important performance factor in Querier, we will store the sort order in the parquet file.
- To avoid resort parquet files (chunks) for deduplication at read time, we want to have consistent sort order for all parquet files. To do this, the Ingester will compute the sort order during persistence of first parquet of a table based on the column cardinality from low to high. The following persistence of the same table will reuse that sort order. 

### TBD : 
Because different parquet files may contain different columns, the latest parquet file may not include all columns of the sort order. For example:

- Persist 1:  parquet file includes `tag1, tag2, tag3, field1, field2, time`.  The computed sort order: `tag3, tag1, tag2, time`
- Persist 2: parquet file includes `tag2, tag 3, tag4, field1, field2, time`.  This file does not have `tag1` but contains a new `tag4`. What will be the sort order of this file based on the sort order above? Either?
    1. `tag3, tag1, tag2, tag4, time` (Keep `tag1` and add `tag4` infant of `time`): If so, the sort order contains column `tag1` that is not in the file.
    2. `tag3, tag2, tag4, time` (ignore `tag1` because it is not in the file): If so, in order for us to know the sort order to reuse for future persistence, we need to read both parquet files.

### Design update: 
The ingester uses this [compact](https://github.com/influxdata/influxdb_iox/blob/5a29d070ea6f5d8e3e961bf4deea15ef29be463c/ingester/src/compact.rs#L113) to build a query plan to compact its writes.  Since the sort key is not provided, the plan will sort the column lexicographically for deduplication. In order to support consistent sort key and that sort key should be computed before compacting, this compact should be replaced with this [compact_plan](https://github.com/influxdata/influxdb_iox/blob/26a7a61d0a38785ad5c413fefec6950640b3da70/query/src/frontend/reorg.rs#L105)

**Comment by alamb** [comment]
https://github.com/influxdata/influxdb_iox/pull/4110 may be related from @crepererum

**Comment by NGA-TRAN** [comment]
@carols10cents search for `compute_sort_key` that we use for OG. You may want to modify that function to make it work for both OG and NG

**Comment by carols10cents** [comment]
> Persist 1: parquet file includes tag1, tag2, tag3, field1, field2, time. The computed sort order: tag3, tag1, tag2, time

@NGA-TRAN This sentence makes it sound like only tags should be considered when analyzing cardinality for the sort order... but I don't think the ingester knows anything about tags vs fields? Am I making an incorrect assumption or missing this info in the ingester?

**Comment by NGA-TRAN** [comment]
@carols10cents : the sort key includes columns in primary key. Primary key includes all tags and time. So yes, only tags and should be considered. There must be a way for the Ingester to know which column is a tag or field. We usually do it through schema. If you look at `compute_sort_key_for_chunks` you will find it

**Comment by carols10cents** [comment]
All parts of this are now done!
