### ISSUE TITLE
Cache namespaces that have reached their table/column limit

### ISSUE THREAD

**Issue by domodwyer** [influxdata/influxdb_iox#4062]
__Use case:__
Prevent avoidable load on the catalog - potential path to an easy DoS.

Once #3832 merges, we will limit tables/columns per namespace by failing the column/table insert into the catalog. Retrying this request will then hit PG again with the same outcome.

__Proposal:__
A potential solution to this takes advantage of the fact we only allow _adding_ schema elements at the moment, not removing, so the number of columns/tables never goes down. We can remember when we've seen a `ColumnCreateLimitError` for a given namespace, and not bother hitting postgres.

See https://github.com/influxdata/influxdb_iox/pull/3832#issuecomment-1072303363

__Current behaviour:__
No caching, each request hits the catalog.

__Desired behaviour:__
Cache a set of namespaces that have reached their limits in the router and short-circuit.

**Comment by lukebond** [comment]
whilst we can't currently remove columns and rows, we can reduce the limit. perhaps we blow that cache whenever the limits change?

**Comment by domodwyer** [comment]
Closed by #5819.
