### ISSUE TITLE
NG Compactor: break compaction check up to more bite size pieces

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#4120]
The compaction code currently looks for all possible things to compact, constructs a view of all of them, then tries to do all those compactions and then update for all compactions against the catalog (if I'm understanding the current code correctly).

This should be broken up more so that the compaction for a single partition can be run separately. I'm thinking of something like this:
1. For each sequencer:
2. Identify the best partition to compact
    1. Based on the most level 0 files
    2. Or the most tombstones
    3. Break tie against either criteria by picking the oldest (i.e. created_at is oldest for the level 0 files)
    4. Or if nothing is left to compact, return none
3. Return that info to the caller so that it can schedule compaction for the selected partition

The promotion of older level 0 files with no time overlap to level 1 could happen as part of step 2 if we want to save on work. But the running of compaction should be possible on the single identified partition per sequencer. Then the loop can just check for the next best partition after it completes the last one.

At the very least we need separation of identifying which partitions are highest priority to compact vs. actually running the compaction. So we can limit the scope of work and decide how many compactions to run concurrently.

**Comment by NGA-TRAN** [comment]
@pauldix The code somehow does already split the work as you describe (not exactly the same but can put in that way easily). My original plan to create many tokios to run many of them in parallel (wherever there is a loop or many streams). But I think your plan to have a kind of an intermediate function to group sub-functions together sounds good especially if you want to further identify which group contains oldest data.
Btw, I will highly have a large PR out for review today which may conflict with what you plan to do. Maybe wait for that PR first
