### ISSUE TITLE
Create e2e test for schema endpoint

### ISSUE THREAD

**Issue by lukebond** [influxdata/influxdb_iox#4121]
As @alamb mentioned in [this PR](https://github.com/influxdata/influxdb_iox/pull/4105), the new schema endpoint, client and CLI needs an e2e test. Now that the framework is [about to land](https://github.com/influxdata/influxdb_iox/pull/4114), we can add this.

**Comment by alamb** [comment]
I am going to take a shot at this (as a good excuse to get an end to end test for CLI going in NG)
