### ISSUE TITLE
Querier: Remove binary parquet metadata from catalog

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#4124]
The querier currently needs the binary (thrift + zstd) parquet file metadata to create parquet chunks. However these binary blobs are quite large and it would be nice if the querier could work w/o it. There are multiple options:

- the querier fetches (and caches) the blobs from the actual parquet files on-demand
- we serialize enough metadata/stats within the catalog so the querier could work reasonably well

It would be helpful if we would have some real world perf testing in place before working on this issue so that we can judge how bad "fetch on demand" would be.

**Comment by carols10cents** [comment]
The first step I'm going to take here is to continue *storing* the parquet metadata in the catalog, but not *fetching* it when doing catalog queries.

**Comment by domodwyer** [comment]
I have discovered the compactor actually depends on this metadata too:

* There is an explicit catalog method that returns parquet info with the metadata: [`list_by_partition_not_to_delete_with_metadata()`][catalog]
* This is called by the compactor [here][call]
* Before passing the result into [`compact()`][compact]
* Where the [`IoxMetadata` is resolved][ioxmeta]
* By calling [`ParquetFileWithTombstone::iox_metadata()`][withtombstone]
* Which [uses the embedded metadata](https://github.com/influxdata/influxdb_iox/blob/df7b3c3a88091cd920a3d16cd3d37eabb77e2075/parquet_file/src/chunk.rs#L214-L216)

At the time of writing, the following fields in the resolved `IoxMetadata` appear to be used:

* [partition ID](https://github.com/influxdata/influxdb_iox/blob/df7b3c3a88091cd920a3d16cd3d37eabb77e2075/compactor/src/compact.rs#L607)
* [table name + sort key](https://github.com/influxdata/influxdb_iox/blob/df7b3c3a88091cd920a3d16cd3d37eabb77e2075/compactor/src/compact.rs#L614-L615)
* [sequencer ID, namespace ID, namespace name, partition key](https://github.com/influxdata/influxdb_iox/blob/df7b3c3a88091cd920a3d16cd3d37eabb77e2075/compactor/src/compact.rs#L689-L695)

All of this information can be accessed via the catalog directly - it appears using this emebeded metadata is unnecessary.


[catalog]: https://github.com/influxdata/influxdb_iox/blob/df7b3c3a88091cd920a3d16cd3d37eabb77e2075/iox_catalog/src/postgres.rs#L1699-L1715

[call]:https://github.com/influxdata/influxdb_iox/blob/df7b3c3a88091cd920a3d16cd3d37eabb77e2075/compactor/src/compact.rs#L357

[withtombstone]:https://github.com/influxdata/influxdb_iox/blob/df7b3c3a88091cd920a3d16cd3d37eabb77e2075/compactor/src/utils.rs#L128-L131

[ioxmeta]:https://github.com/influxdata/influxdb_iox/blob/df7b3c3a88091cd920a3d16cd3d37eabb77e2075/compactor/src/compact.rs#L576

[compact]:https://github.com/influxdata/influxdb_iox/blob/df7b3c3a88091cd920a3d16cd3d37eabb77e2075/compactor/src/compact.rs#L422

**Comment by domodwyer** [comment]
[`ParquetFileWithTombstone::to_queryable_parquet_chunk()`](https://github.com/influxdata/influxdb_iox/blob/df7b3c3a88091cd920a3d16cd3d37eabb77e2075/compactor/src/utils.rs#L95) also uses the embedded metadata - this is called as part of [`compact()`](https://github.com/influxdata/influxdb_iox/blob/df7b3c3a88091cd920a3d16cd3d37eabb77e2075/compactor/src/compact.rs#L612-L617) too.

**Comment by domodwyer** [comment]
I actually started removing the compactor's usage of this binary metadata - I have a commit (not pushed) that removes all the usage mentioned in https://github.com/influxdata/influxdb_iox/issues/4124#issuecomment-1141220956 except the sort key (which would need to become a first-class field in the `parquet_file` catalog table).

I stopped when I noticed https://github.com/influxdata/influxdb_iox/issues/4124#issuecomment-1141276741 which is rather tightly coupled with information within the binary metadata in the catalog.

**Comment by crepererum** [comment]
> which would need to become a first-class field in the `parquet_file` catalog table)

@domodwyer the sort key is part of the partition table. This should be sufficient to derive the parquet file sort key since this one is only a projection (i.e. only contains the columns) of the partition-wide sort key

Same goes for all the other information you have listed: they should already be somewhere in the catalog. The only information that is NOT there and that can improve **querier** perf. are the statistics.

**Comment by domodwyer** [comment]
Does it matter that the sort key can evolve over time (adding new fields)? A partition's sort key can contain fields that the file does not have - I don't know if/how this would affect compaction/query in any way.

For the other point, the compactor initialises a [`ParquetChunk`][chunk] which makes [heavy use of the metadata][meta], including the column statistics too.


[chunk]:https://github.com/influxdata/influxdb_iox/blob/79c054ffc9e2b23e4e3fc3d1e2e35c81e5c3b6f6/compactor/src/utils.rs#L98-L102
[meta]: https://github.com/influxdata/influxdb_iox/blob/79c054ffc9e2b23e4e3fc3d1e2e35c81e5c3b6f6/parquet_file/src/chunk.rs#L82-L87

**Comment by crepererum** [comment]
> Does it matter that the sort key can evolve over time (adding new fields)? A partition's sort key can contain fields that the file does not have - I don't know if/how this would affect compaction/query in any way.

The sort key can only evolve by inserting columns into the sorted list. The existing columns should not be reshuffled (relative to each other).
