### ISSUE TITLE
Release build doesn't include git_hash

### ISSUE THREAD

**Issue by mkmik** [influxdata/influxdb_iox#4191]
Our release build doesn't seem to include the `git_hash` commit anymore

__Expected behaviour:__

```
level=info msg="InfluxDB IOx server starting" git_hash=<some git hash> num_cpus=32 build_malloc_conf="\u{0}" target="ioxd" location="ioxd/src/lib.rs:104" time=1648737910972101624
```

__Actual behaviour:__

```
level=info msg="InfluxDB IOx server starting" git_hash=UNKNOWN num_cpus=32 build_malloc_conf="\u{0}" target="ioxd" location="ioxd/src/lib.rs:104" time=1648737910972101624
```

__Environment info:__

* happens in our internal testing cluster with image: quay.io/influxdb/iox@sha256:5bc74fa39fff3277ae6ddf874aea98b17bb3abebe74015e1574a2b1a03460748

**Comment by alamb** [comment]
What happened is that the GIT_SHA env is being set in the `influxdb_iox` crate  but the message is being created in the `ioxd` (formerly `influxdb_ioxd`) crate which thus can't find ir.

I plan a two step fix:
1. Move the relevant code out of `ioxd`  which aligns with https://github.com/influxdata/influxdb_iox/issues/4145
2. Cause build to fail if the value can't be found, as suggested by @domdwyer
