### ISSUE TITLE
Querier: Add write token support to `/api/v2/delete` end point to support deletes

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#4209]
The idea is to add write tokens to the response of the HTTP DELETE endpoint so that users can then ask the ingester when their data no longer appears in new queriers. 

# Definition of Done
- [ ] Code
- [ ] End to end test

# Context
write tokens added to http write in https://github.com/influxdata/influxdb_iox/pull/4202

**Comment by carols10cents** [comment]
I think this is moot with the kafkaless design, so I'm closing.
