### ISSUE TITLE
Rename Sequencer to Shard in Catalog / Codebase

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#4246]
@NGA-TRAN  noted, and it was agreed by @domodwyer and @pauldix that the notion of "shard" and "sequencer" in the NG architecture are actually the same entity

Thus the proposal would be to:
- [ ] Replace `Sequencer` with `Shard` in the `ingester` (and replace `sequencer_id` with `shard_id`)
- [ ] Update the postgres catalog / schema to use the term `shard` rather than `sequencer`

**Comment by domodwyer** [comment]
We should also rename the associated metrics which also use a spread of names for the same thing (from @pauldix) 👍

**Comment by carols10cents** [comment]
I think this is completely moot now that shards are going away 👍🏻

**Comment by alamb** [comment]
❤️
