### ISSUE TITLE
Assert firing in MutableBatch::column_mut()

### ISSUE THREAD

**Issue by domodwyer** [influxdata/influxdb_iox#4326]
[An assert] validating the number of rows in a mutable batch is being hit in prod:

```
level=error msg="Thread panic" panic_info="panicked at 'assertion failed: `(left == right)`\n  left: `1`,\n right: `0`: expected 0 rows in column \"InputPower\" got 1 when performing write of 1 rows', mutable_batch/src/writer.rs:638:9" target="panic_logging" location="panic_logging/src/lib.rs:94" time=1649950675785265461
thread 'tokio-runtime-worker' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: expected 0 rows in column "InputPower" got 1 when performing write of 1 rows', mutable_batch/src/writer.rs:638:9
stack backtrace:
```

(there was no backtrace)

[An assert]:https://github.com/influxdata/influxdb_iox/blob/fe8d9948d5cc235e51811f2f06773bc6f970b28c/mutable_batch/src/writer.rs#L638

**Comment by alamb** [comment]
adding to iox project

**Comment by domodwyer** [comment]
The issue stems from LP that specifies a field more than once:

```text
table A=1,A=1
```

The following variations of the above should be handled gracefully, most of which currently trigger the assert:

* duplicate fields, same value (`whydo field=300i,field=300i`)
* duplicate fields, different value (`whydo field=300i,field=42i`)
* duplicate tags, same value (`whydo,tag=300i,tag=300i field=42i`)
* duplicate tags, different value (`whydo,tag=300i,tag=42i field=42i`)
* same name for tag and field (`whydo,v=300i v=300i`)
* same name for tag and field, different type (`whydo,v=300i v=30.0`)

The current semantics of how some of these variants are handled in cloud2 are unclear, I propose:

* duplicate fields, same value - do nothing/coalesce
* duplicate fields, different value - reject the request
* duplicate tags, same value - do nothing/coalesce
* duplicate tags, different value - reject the request
* same name for tag and field - reject the request
* same name for tag and field, different type  - reject the request

We have observed the same field being repeated with the same value in prod (`table A=1,A=1`) and presumably is accepted by cloud2.

**Comment by pauldix** [comment]
Your proposal sounds good to me. In previous versions of InfluxDB you could have a tag and a field with the same name, but that's more of a bug that became a feature. It's definitely not recommended use and I'd prefer not to support it going forward.

**Comment by domodwyer** [comment]
![image](https://user-images.githubusercontent.com/9275968/164472741-91f97e99-0aa3-4258-bf82-bc7c0f7ac45d.png)

**Comment by domodwyer** [comment]
> duplicate fields, different value: .... Accepted and it looks like last field value wins.

This is unfortunate :( rejecting the write in IOx for case will be a behavioural difference between cloud2/iox, but I'd argue it is the right thing to do - it's very unlikely the end user is intending to exercise this last-value-in-one-line-wins behaviour. I'll ask around if anyone objects.

Thanks for confirming the current behaviour 👍

**Comment by domodwyer** [comment]
After asking around, keeping parity with TSM is preferable, especially as "last write wins" can is also true for successive LP lines, so the new proposal is:


* duplicate fields, same value - do nothing/coalesce
* duplicate fields, different value - **last write wins**  `<-- different`
* duplicate tags, same value - **reject the request** `<-- different`
* duplicate tags, different value - reject the request
* same name for tag and field - reject the request
* same name for tag and field, different type  - reject the request

I'll put a PR up for this tomorrow.

**Comment by domodwyer** [comment]
We rationalised the above edge case handling rules given the following set of clearly defined, desired write semantics (from @jacobmarble):

```
Rule 1: If duplicates are submitted in separate payloads, then the last value wins.
Rule 2: If duplicates are submitted in separate lines in one payload, then the last value wins.
Rule 3: If duplicates are submitted in separate fields in one line, then the last value wins.
```

However this is not strictly upheld by TSM in the presence of type conflicts. Given a write containing conflicting types within a single LP line:

```
table v=1i,v=2.0
```

The write completes successfully, but only the **FIRST** value is committed:

```console
% influx query
from(bucket: "ddwyer's Bucket")
  |> range(start: -1h, stop: now())
  |> filter(fn: (r) => r["_measurement"] == "table")
  |> filter(fn: (r) => r["_field"] == "v")

Result: _result
Table: keys: [_start, _stop, _field, _measurement]
                   _start:time                      _stop:time           _field:string     _measurement:string                      _time:time                  _value:int
------------------------------  ------------------------------  ----------------------  ----------------------  ------------------------------  --------------------------
2022-04-22T09:43:58.011661006Z  2022-04-22T10:43:58.011661006Z                       v                   table  2022-04-22T10:28:13.510047721Z                           1
```

This is obviously a violation of the "last write wins" rule within a line, but is understandable knowing we internally explode the points and apply them in sequence within TSM:

```
table v=1i
table v=2.0
```

This sequence would cause the second write to fail, resulting in a state of `v=1i`.

Repeating the write is also accepted, and has the same effect:

```console
% influx write --format=lp --bucket="ddwyer's Bucket" "table v=1i,v=2.0"
```

Resulting in two points of `v=1i`:

```console
                   _start:time                      _stop:time           _field:string     _measurement:string                      _time:time                  _value:int
------------------------------  ------------------------------  ----------------------  ----------------------  ------------------------------  --------------------------
2022-04-22T09:59:04.918934536Z  2022-04-22T10:59:04.918934536Z                       v                   table  2022-04-22T10:28:13.510047721Z                           1
2022-04-22T09:59:04.918934536Z  2022-04-22T10:59:04.918934536Z                       v                   table  2022-04-22T10:58:48.432029034Z                           1
```

However submitting a write where the values are reversed (so, invalid float type first, valid int second):

```console
% influx write --format=lp --bucket="ddwyer's Bucket" "table v=2.0,v=1i"
```

Doesn't return an error (not surprising due to lack of schema validation in cloud2), but no points are recorded at all:

```console
                   _start:time                      _stop:time           _field:string     _measurement:string                      _time:time                  _value:int
------------------------------  ------------------------------  ----------------------  ----------------------  ------------------------------  --------------------------
2022-04-22T09:59:36.227949722Z  2022-04-22T10:59:36.227949722Z                       v                   table  2022-04-22T10:28:13.510047721Z                           1
2022-04-22T09:59:36.227949722Z  2022-04-22T10:59:36.227949722Z                       v                   table  2022-04-22T10:58:48.432029034Z                           1
```

Given that switching to IOx as the storage backend will bring schema validation to cloud2, I think the end user has a reasonable expectation that a line containing an internal type conflict would fail in the same way two successive writes containing a type conflict would also fail (so our example of `table v=1i,v=2.0` would be rejected as a schema violation / 4xx). 

I therefore **intend reject internally type-conflicted lines** and present the user with a failure when this occurs, rather than applying a last-write-wins strategy, or replicating the first-write-wins behaviour of TSM.

Given the above, the full set of intra-line parsing behaviours to implement becomes:

* duplicate fields, same value - do nothing/coalesce
* duplicate fields, different value - last write wins
* duplicate fields, different types - reject the request `<-- new`
* duplicate tags, same value - reject the request
* duplicate tags, different value - reject the request
* duplicate tags, different type - reject the request `<-- new`
* same name for tag and field - reject the request
* same name for tag and field, different type  - reject the request

(@philjb)

**Comment by e-dard** [comment]
![](https://media0.giphy.com/media/vioq0XT2W0m5c3icbI/giphy.gif)

**Comment by philjb** [comment]
> However this is not strictly upheld by TSM in the presence of type conflicts. Given a write containing conflicting types within a single LP line:

Yeah the "last write wins" rule applies with a caveat that a field can only have one type and the generally the first write establishes that type (I say generally because I can delete the series entirely to and can then change the field type). 

So for your example

```
table v=1i
table v=2.0
```

At least one point will be rejected here, but we don't know which one in advance and both might be rejected. 

Say `table v=hello` was written yesterday, then both points are rejected. If `table v=1i` is truly the first, then `table v=2.0` is rejected.

**Comment by philjb** [comment]
> However submitting a write where the values are reversed (so, invalid float type first, valid int second):
> Doesn't return an error (not surprising due to lack of schema validation in cloud2), but no points are recorded at all:

gah. I consider this a cloud2 bug.

**Comment by philjb** [comment]
> duplicate tags, different type - reject the request <-- new

tags are only strings...

**Comment by domodwyer** [comment]
> > However submitting a write where the values are reversed (so, invalid float type first, valid int second):
> > Doesn't return an error (not surprising due to lack of schema validation in cloud2), but no points are recorded at all:
> 
> gah. I consider this a cloud2 bug.

In that case should I file a ticket for this?
