### ISSUE TITLE
Add a End User Visible API for determining a write's status

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#4354]
__Use case:__

As a user, if want to know when a write to IOx will become readable or persisted. Readable is illustrated in this diagram from [Data Lifecycle in NG](https://docs.google.com/document/d/19fA0XtXHPBnBxB2yc6jFMu3cBnv1jsVpovbFL1NqVzc/edit#):

```
                    │                │  │                  │  │
    ░░░░░░░░░░░░░░░   ░░░░░░░░░░░░░░░      ░░░░░░░░░░░░░░░       ░░░░░░░░░░░░░░░
    ░░░░Durable░░░░ │ ░░░Readable░░░░│  │  ░░░Parqueted░░░ │  │  ░░░Compacted░░░
    ░░░░░░░░░░░░░░░   ░░░░░░░░░░░░░░░      ░░(Persisted)░░       ░░░░░░░░░░░░░░░
    ░░░░░░░░░░░░░░░ │ ░░░░░░░░░░░░░░░│  │  ░░░░░░░░░░░░░░░ │  │  ░░░░░░░░░░░░░░░
start
────────────────────┼────────────────┼──┼──────────────────┼──┼──────────────▶Time
    In Write          In Ingester          In Parquet            Different
    Buffer          │ Memory         │  │  File in         │  │  Parquet File in
                                           Object Store          Object Store
    NOT             │                │  │                  │  │
    externally        externally           externally            externally
    readable        │ readable       │  │  readable        │  │  readable
```

We have added an API to get this information in the end to end tests (GetWriteInfoService), but as @crepererum notes in https://github.com/influxdata/influxdb_iox/pull/4341, https://github.com/influxdata/influxdb_iox/pull/4341#pullrequestreview-945939479  it is complicated to use (needs access to a full set of ingesters) and likely leaks more implementation detail than is necessary

__Proposal:__

We should deign and implement a user facing API and provide a reasonable to use end-user client.

__Current behaviour:__
Describe what currently happens.

__Desired behaviour:__
Describe what you want.

__Alternatives considered:__
Describe other solutions or features you considered.

**Comment by carols10cents** [comment]
I believe this is moot with the kafkaless design, so I'm closing this.
