### ISSUE TITLE
org/bucket namespace collision

### ISSUE THREAD

**Issue by zeebo** [influxdata/influxdb_iox#436]
This code has the same output for `org="org_a", bucket="bucket"` and `org="org", bucket="a_bucket"`:

https://github.com/influxdata/influxdb_iox/blob/141527425d4d7a460d33a1f3ee346addeda9239b/storage/src/lib.rs#L126-L132

This leads to writes to distinct databases ending up in the same database.

**Comment by alamb** [comment]
This is a good point Be something we should definitely sort out before GA

**Comment by e-dard** [comment]
Thanks @zeebo. You should get youself on the contibutors list on this one too 😉

**Comment by alamb** [comment]
The basic solution to this is likely to 'encode' the org and bucket name somehow. The key will be to pick some encoding that is straightforward and yields valid names for file systems and object stores. 

URL encoding the name (forcing `_` to `%5f`) might work. 

So for the input
* `org="org_a", bucket="bucket"` --> database name `org%5fa_bucket`
* `org="org", bucket="a_bucket"` --> database name `org_a%5fbucket`

I am sure there are other schemes too
