### ISSUE TITLE
UUID-based IDs for catalog

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#4365]
# Current State
Currently we use sequential IDs for our catalog entities. These are auto-generated by postgres:

https://github.com/influxdata/influxdb_iox/blob/0642ec0b8202e8085a29f84b9490b897125171a2/iox_catalog/migrations/20211229171744_initial_schema.sql#L43-L50

This is how "get or create" methods are implemented:

https://github.com/influxdata/influxdb_iox/blob/0642ec0b8202e8085a29f84b9490b897125171a2/iox_catalog/src/postgres.rs#L963-L969

## Current Bug

This will bump the ID generator even when the entry already exists, leading to issues like:

`Server command failed: Error in ingester subcommand: error initializing ingester: Catalog error: unhandled sqlx error: error returned from database: nextval: reached maximum value of sequence "sequencer_id_seq" (32767)`

Debugging confirms the hypothesis:

```text
iox_catalog=# select * from iox_catalog.sequencer_id_seq;
 last_value | log_cnt | is_called
------------+---------+-----------
      32767 |       0 | t
(1 row)

iox_catalog=# select min(id), max(id), count(*) from iox_catalog.sequencer;
 min | max | count
-----+-----+-------
   1 | 100 |   100
(1 row)
```

## Other Disadvantages
- **Ordering:** People might assume that IDs are ordered (I've seen that in discussions before). They are not (or at least not in the sense that people assume), because "generation time != commit time".

# Proposal
We should use UUIDs instead of sequential IDs.

## Advantages
This would have the following advantages:

- **Cheap Get-or-Insert:** The bug illustrated above doesn't exist.
- **Ordering:** People won't assume that IDs have any order.
- **Flexible Generation:** Both the catalog (=postgres) and the client can generate IDs.
- **Catalog Union:** Namespaces can easier be moved between catalogs (= postgres databases)
- **Flexible Backend:** It's easier to use other catalog backends like KV stores since we no longer need a global sequence generator.

## Drawbacks
- **Larger IDs:** In Rust IDs would always take up 128bits.
- **gRPC/protobuf Mapping:** UUIDs (which are 128bit) don't map well to protobuf (see https://github.com/protocolbuffers/protobuf/issues/2224 ). We had the same issue for OG chunk IDs where we decided to just use `bytes`. This makes it also clear to the API user that the ID is opaque.

# Alternatives
- **Larger Integers:** Just use larger integers so they don't overflow.
- **Check before Insert:** Extend "get or insert" to check if an entry exists before attempting to insert it to put less load on the ID generator, making overflows less likely.
- **Advanced ID Generator:** Some some ID generator that can recycle unused IDs. This is potentially quite expensive.

**Comment by e-dard** [comment]
UUIDs don't seem like the right thing to do here. I would be inclined to increase the size of the ID to 64-bit for the moment.

**Comment by mkmik** [comment]
bumping the key size to signed 32 bit integer will be good enough to handle 4 replicas crashlooping with no backoff at a rate of 1 crash per second for 17 years.

I was exploring an alternative "quick fix" in https://github.com/influxdata/conductor/issues/930 that didn't involve a schema migration in the first place (since currently we don't test schema migrations with non-empty databases).

**Comment by mkmik** [comment]
w.r.t UUIDs, it's hard to tell if the performance issues matter at all. On one hand I like the simplicity, on the other I hate the schema migration it involves, but we can wipe the catalogs in our test clusters.

**Comment by mkmik** [comment]
we have many other places where we consume sequence numbers

```
impl NamespaceRepo for PostgresTxn {
    async fn create(
        &mut self,
        name: &str,
        retention_duration: &str,
        kafka_topic_id: KafkaTopicId,
        query_pool_id: QueryPoolId,
    ) -> Result<Namespace> {
        let rec = sqlx::query_as::<_, Namespace>(
            r#"
INSERT INTO namespace ( name, retention_duration, kafka_topic_id, query_pool_id )
VALUES ( $1, $2, $3, $4 )
RETURNING *;
        "#,
        )
        .bind(&name) // $1
        .bind(&retention_duration) // $2
        .bind(kafka_topic_id) // $3
        .bind(query_pool_id) // $4
        .fetch_one(&mut self.inner)
        .await
        .map_err(|e| {
            if is_unique_violation(&e) {
                Error::NameExists {
                    name: name.to_string(),
                }
            } else if is_fk_violation(&e) {
                Error::ForeignKeyViolation { source: e }
            } else {
                Error::SqlxError { source: e }
            }
        })?;
```

perhaps we could just rip the bandaid and switch to uuids

**Comment by mkmik** [comment]
Another option for tables like sequencer is to make `kafka_topic_id` and `kafka_partition` immutable and using them as composite primary key. Foreign keys to the sequencer will be bigger, but smaller than a UUID. Upserts would be simple.

**Comment by alamb** [comment]
cc @pauldix
