### ISSUE TITLE
Wait-free WAL

### ISSUE THREAD

**Issue by CJP10** [influxdata/influxdb_iox#437]
### New struct
```
pub struct Wal {
    files: FileLocator,
    sequence_number: AtomicU64,
    total_size: AtomicU64,
    active_file: crossbeam_epoch::Atomic<File>,
    file_rollover_size: u64,
}
```

### Don't bother with tokio-fs
Tokio just spawns sync io on a threadpool so you might as well cut out the middleman channels and just `spawn_blocking` sync io.

### New algorithm 
Atomically increment `sequence_number` and `total_size` on append.
If `total_size` > `file_rollover_size`, Mark `active_file` (needed to prevent two threads trying to role the active file) and CAS to a new active file. This will not block any writes but you might go a bit over `file_rollover_size` depending on load.
Commit the writes using `pwrite`/`pwritev`(or equivalents on non-linux platforms).

If y'all think this is worth implementing, I'm happy to flesh the idea out and make a PR.

**Comment by shepmaster** [comment]
See also a previous implementation at https://github.com/influxdata/influxdb_iox/tree/df39eca0437c647ef7b353be56a8628ebe4e7cfc/delorean_wal

**Comment by CJP10** [comment]
@shepmaster from a surface level read, the improvement in my proposal is that the `pending` list is removed and rollovers don't block.

**Comment by alamb** [comment]
The use of tokio fs was added in https://github.com/influxdata/influxdb_iox/pull/378 as a way to allow IOx  to run with a "basic" tokio scheduler as well as the (default) threaded one. If `spawn_blocking` works with the basic scheduler that sounds fine to me. 

While making the write / flush of the WAL non blocking would certainly improve its throughput, I am not quite sure how it would affect the durability story (aka at what point could data survive a process crash and would we be able to reason about which WAL files were ok and which might be corrupted).

I also think @pauldix  has some thoughts / plans / in progress changes to the WAL in support of replication

**Comment by pauldix** [comment]
Yeah, I have some work I'm doing that will change IOx to just buffer the WAL in memory and occasionally flush it out to object storage. The idea is that if you want stronger durability guarantees, you have multiple servers replicated and when you make a write request you specify that you need more than N of them to ack before success.

We might keep the option of using a locally persisted WAL that is fsyncd on every write, but it's not something we'll be using in our own cloud environment. We're more than happy to take the change to improve this WAL implementation, but its not something we're focused on at the moment.

**Comment by CJP10** [comment]
@pauldix Makes sense, Kafka uses a similar mechanism and so this seems totally reasonable. I want ahead and made the PR anyway to have a bit of fun :smile: .

**Comment by CJP10** [comment]
@pauldix instead of buffering the WAL in-memory it could make more sense to use the WAL as is and just not sync every write. If you just let the page cache sync the write you essentially get the buffer to memory for free. LevelDB uses this as it's default so there is some prior art. Bit of opinion here but I would say it's easier to push already persisted WAL files to object store than holding an in-memory buffer.
