### ISSUE TITLE
 Make all-in-one a suitable / drop in replacement for OG database mode

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#4399]
__Use case:__
`all-in-one` mode is becoming more important as we move local testing from OG to NG:

1. Developers such as @onelson currently run IOx from a local checkout / from the docker image using a command such as `cargo run database -vv`.
2. It is used to verify that the flux acceptance tests run successfully against IOx
3. @pauldix  is working on tools to migrate parts of namespace from production to local all all-in-one mode  

Thus the easier it is to start the better. 

__Proposal:__
Make all-in-one mode easy to run in both entirely ephemeral mode (memory only) as well as file-based state in a single directory:

```shell
# in memory catalog, in memory writebuffer, in memory objectstore
influxdb_iox run all-in-one

# postgres catalog, file based objectstore, write buffer both rooted in <data_dir>
influxdb_iox run all-in-one --catalog-dsn postgres:///mkm --data-dir=~/iox_data

# (not for this ticket as file based catalog doesn't exist yet) 
# file based catalog, object store, write buffer, all rooted in <data_dir>
influxdb_iox run all-in-one --data-dir=~/iox_data
```

So the idea is the state will be persisted if you run IOx like:

```shell
# startup 
influxdb_iox run all-in-one --catalog-dsn postgres:///mkm --data-dir=~/iox_data

# load some data
./influxdb_iox database write my_db test_fixtures/lineproto/metrics.lp

# <stop the previous influxdb_iox process>

# restart, data should still be present:
influxdb_iox run all-in-one --catalog-dsn postgres:///mkm --data-dir=~/iox_data
```

__Example Issues with current implementation:__
Currently , all-in-one mode currently only supports 1 partition and requires the magic set of config to say so

@mkmik recently discovered that specifying `--write-buffer-partition-range-start` and `--write-buffer-partition-range-end` values other than 0 don't work

```
./target/debug/influxdb_iox run all-in-one --write-buffer file --write-buffer-addr /tmp/wb2 --write-buffer-partition-range-start 0 --write-buffer-partition-range-end 99 --pause-ingest-size-bytes 10000000 --persist-memory-threshold-bytes 1000000 --catalog-dsn postgres:///mkm
Server command failed: Error in all in one subcommand: Ingester error: error initializing ingester: Write buffer error: WriteBufferError(Unknown): Unknown sequencer: 1
```

The reason for this is https://github.com/influxdata/influxdb_iox/blob/7fb5cd6283f2feaabe4d768c93dc4171dc22b653/influxdb_iox/src/commands/run/all_in_one.rs#L286

__Implementation Notes:__

We'll need to remove the following arguments and have the all in one code supply good default values

```
--write-buffer-partition-range-start
--write-buffer-partition-range-end 
--pause-ingest-size-bytes
--persist-memory-threshold-bytes
```

* `--write-buffer-partition-range-start` -- default to 0
* `--write-buffer-partition-range-end` -- default to 0
* `--pause-ingest-size-bytes` -- default to TBD (ask @pauldix )
* `--persist-memory-threshold-bytes` -- default to TBD (ask @pauldix )

The all in one mode should always use a single write buffer partition and provide reasonable defaults for the others

**Comment by pauldix** [comment]
I think this looks good. Is the plan that the other config settings can be supplied in all in one mode, just that they have defaults? For example if I wanted to set the cold persist duration, could I do so with all in one?

For the arguments you ask about, I think make `--pause-ingest-size-bytes` very large (like 100GB) and make `--persist-memory-threshold-bytes` something like 1GB. I think those should work ok.

**Comment by alamb** [comment]
> Is the plan that the other config settings can be supplied in all in one mode, just that they have defaults

Yes @pauldix . And furthermore the defaults would only apply to all-in-one mode. Ingester mode would not be changed

**Comment by carols10cents** [comment]
> ```shell
> # in memory catalog, in memory writebuffer, in memory objectstore
> influxdb_iox run all-in-one
> ```

Weeeee problem: we don't have an in-memory writebuffer yet, only file-based... if `--data-dir` isn't specified, should we use a `TempDir`?

**Comment by alamb** [comment]
> Weeeee problem: we don't have an in-memory writebuffer yet, only file-based... if --data-dir isn't specified, should we use a TempDir

I think using a `TempDir` if a data-dir isn't specified would be a great idea. Thank you @carols10cents
