### ISSUE TITLE
(FLUX Integration) Support computing series across multiple record batches not yet supported

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#4401]
__Use case:__

@onelson reported that he was hitting a "Computing series across multiple record batches not yet supported" when testing iox with larger datasets in IOX.

I believe he was hitting the following unimplemented code assertion:

https://github.com/influxdata/influxdb_iox/blob/22b24bdab30f3c746581145ff402d7177420577e/query/src/exec/seriesset/converter.rs#L94-L97

This code assumes that the output of a query comes in a single large `RecordBatch` but the execution plans are now streaming more successfully and thus come back with multiple `RecordBatches`

__Proposal:__
1. Implement the  missing piece of functionality

**Comment by alamb** [comment]
@onelson does this sound like the message you were hitting?

**Comment by onelson** [comment]
Yes, this is precisely the panic I saw yesterday.

**Comment by onelson** [comment]
n.b. I have seen this with _small and large_ datasets and I can only guess that this relates to post-ingest activity (compaction?) or otherwise flushing points to disk. I'm not clear on the semantics, but I've had small datasets hit this and then work later on, after a period of "rest".

**Comment by alamb** [comment]
That would make sense

**Comment by alamb** [comment]
@crepererum  notes we are hitting this issue often in the NG querier on our production system

I am going to put in a workaround temporaily to concat all the `RecordBatches` before converting them? 

This is non ideal, but will unblock some of our testing while I am working on a proper fix
