### ISSUE TITLE
flaky test: end_to_end_ng_cases::querier::multi_ingester::basic_multi_ingesters

### ISSUE THREAD

**Issue by domodwyer** [influxdata/influxdb_iox#4426]
https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/18500/workflows/8ed3bf8a-5ded-4669-8650-b22577bd5f66/jobs/154402

**Comment by alamb** [comment]
Seems like a dupe of https://github.com/influxdata/influxdb_iox/issues/4395

**Comment by alamb** [comment]
Closing as a dupe
