### ISSUE TITLE
flake: e2e test failures

### ISSUE THREAD

**Issue by domodwyer** [influxdata/influxdb_iox#4457]
PR #3577 slightly changes the timing of router2 startup (lengthening it by a very small amount) - [in CI I have observed][1] lots of flaky tests and have collated them below:

```
end_to_end_ng_cases::cli::remote_partition_and_get_from_store
end_to_end_ng_cases::ingester::ingester_flight_api
end_to_end_ng_cases::ingester::ingester_flight_api_namespace_not_found
end_to_end_ng_cases::ingester::ingester_flight_api_table_not_found
end_to_end_ng_cases::metrics::test_metrics
end_to_end_ng_cases::namespace::querier_namespace_client
end_to_end_ng_cases::querier::basic_no_ingester_connection
end_to_end_ng_cases::querier::basic_on_parquet
end_to_end_ng_cases::querier::influxrpc::metadata::capabilities
end_to_end_ng_cases::querier::influxrpc::metadata::measurement_fields
end_to_end_ng_cases::querier::influxrpc::metadata::measurement_names
end_to_end_ng_cases::querier::influxrpc::metadata::measurement_tag_keys
end_to_end_ng_cases::querier::influxrpc::metadata::measurement_tag_values
end_to_end_ng_cases::querier::influxrpc::metadata::offsets
end_to_end_ng_cases::querier::influxrpc::metadata::tag_keys
end_to_end_ng_cases::querier::influxrpc::read_filter::read_filter
end_to_end_ng_cases::querier::multi_ingester::basic_multi_ingesters
end_to_end_ng_cases::querier::table_not_found_on_ingester
end_to_end_ng_cases::router::write_via_grpc
end_to_end_ng_cases::schema::ingester_schema_cli
end_to_end_ng_cases::schema::ingester_schema_client
```

The only constant is `end_to_end_ng_cases::metrics::test_metrics`

[1]: https://app.circleci.com/pipelines/github/influxdata/influxdb_iox?branch=dom%2Fschema-cache-warm&filter=all

**Comment by domodwyer** [comment]
These e2e tests rarely flake locally but seems to always be preceded by:

```
Server command failed: Error in ingester subcommand: Run: Unable to bind to listen for HTTP requests on 127.0.0.1:8205: 2022-04-28T10:35:44.377822Z  WARN executor: DedicatedExecutor dropped without calling shutdown()
error creating server listener: Address already in use (os error 48)
```

@alamb has [WIP PR to re-use the servers][1] instead of re-creating which might help 🎉 

[1]:https://github.com/influxdata/influxdb_iox/pull/4387

**Comment by alamb** [comment]
Interestingly, as @crepererum pointed out, there is code in the test fixture designed to handle this case by testing if the address is available before binding to it: https://github.com/influxdata/influxdb_iox/blob/main/test_helpers_end_to_end_ng/src/addrs.rs#L33-L44

**Comment by alamb** [comment]
I am not sure this PR is tracking anything actionable anymoe

**Comment by crepererum** [comment]
The port-collision protection has some gaps (see #2449), but I rarely seen any errors (except when some IDE or weird tooling starts to run test binaries in parallel).

**Comment by crepererum** [comment]
So let's close this for now.
