### ISSUE TITLE
feat: Implement read_series_cardinality gRPC endpoint

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#447]
# Background
 https://github.com/influxdata/influxdb_iox/pull/444 updated the protobug gRPC definitions for the storage service to be up to date with InfluxDB 

A new service called `read_series_cardinality` was added, and the corresponding Rust stub is here:
https://github.com/influxdata/influxdb_iox/pull/444/files#diff-c4973a9ab1bc42d58211f28b424dfecdb3c472caed83e377f843be390d4ca5ccR425

# Success criteria / definition of done
1. Research what read_series_cardinality is / what it should return (is it a single number? Or does it return numbers for each series?)
2. Implement the corresponding gRPC service in IOx (including backing storage implementation and tests) for this service

See also https://github.com/influxdata/influxdb_iox/issues/369

**Comment by alamb** [comment]
I think @e-dard  said he was interested in working on this so assigning him the issue. I may be mistaken however, so please reassign if needed

**Comment by e-dard** [comment]
I don't think we need this in the short/medium term because we won't be exposing the same cardinality data as TSM.

**Comment by pauldix** [comment]
This is not something we intend to implement. Computing it would be costly and difficult and series cardinality isn't a useful measure of anything in IOx.
