### ISSUE TITLE
Port OG's NoData case in query_tests to NG

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#4488]
https://github.com/influxdata/influxdb_iox/blob/c9908b260c1241aed8a688e866040d636b5c0404/query_tests/src/scenarios/library.rs#L124

**Comment by alamb** [comment]
(so when we get around to this ticket, the tests can be found in that PR's description)

**Comment by NGA-TRAN** [comment]
Close this since it was removed from #4515 and not clear plan to add it back
