### ISSUE TITLE
feat: Research and confirm the ordering requirements for read_filter, read_group and read_window 

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#450]
# Background /  Open Question

What are the requirements with respect to returned series order in `read_filter`, `read_group` and `read_window_aggregate`?

## Subquestion A:
How do `_measurement` and `_field` tags apply, if at all. @e-dard  notes that 
> in the db we store keys like this` \x00=cpu,tag_k1=tag_v1,tag_k2=tag_v2,\xff=field_name`
> _m, _measurement etc are just aliases.

So if we are sorting by "TagSet" where do the `_measurement` and `_field` tags belong in that ordering?

*Answer*: `_measurement` belongs at the front, and `_field` belongs at the back 

## Subquestion B:

Should series with an empty tag values (e.g ‘NULL’) come before or after series with a value for that tag

Specifically, should the following (note the `region=`) be nulls last:
```
SeriesFrame, tags: _field=value,_measurement=cpu_load_short,host=server01,region=us-east, type: 0
SeriesFrame, tags: _field=value,_measurement=cpu_load_short,host=server01,region=us-west, type: 0
SeriesFrame, tags: _field=value,_measurement=cpu_load_short,host=server01,region=, type: 0
```

Or nulls first:
```
SeriesFrame, tags: _field=value,_measurement=cpu_load_short,host=server01,region=, type: 0
SeriesFrame, tags: _field=value,_measurement=cpu_load_short,host=server01,region=us-east, type: 0
SeriesFrame, tags: _field=value,_measurement=cpu_load_short,host=server01,region=us-west, type: 0
```

# Additional Background

@stuartcarnie nicely points out this link for the use of the merging code https://github.com/influxdata/idpe/blob/43dafcc58ffb2150ed86b70c3a70d0b0572c80b7/storage/merge/merge.go#L108-L111

Reads are represented by the ResultSet interface: https://github.com/influxdata/idpe/blob/43dafcc58ffb2150ed86b70c3a70d0b0572c80b7/storage/reads/store.go#L13-L31

Each Cursor() is a single series key and the time / values associated with it. The Next() function moves to the next series key.

A GroupResultSet and GroupCursor are interfaces for streaming a series of ResultSets grouped / ordered by 1 or more tag keys.
https://github.com/influxdata/idpe/blob/43dafcc58ffb2150ed86b70c3a70d0b0572c80b7/storage/reads/store.go#L33-L77

https://github.com/influxdata/idpe/blob/master/storage/merge/mergegroupresultset_test.go

# Success Criteria / Definition of Done
1. Ensure that measurement / field ordering in IOx has the behavior explained in the answer to Question A, including test coverage
2. Research the nulls first / nulls last question (aka find an answer to Question B)
3. Ensure that nulls first / last ordering in IOx is the  behavior explained in the answer Question B, including test coverage

See also #369

**Comment by e-dard** [comment]
@alamb as far as I can recall:

```
SeriesFrame, tags: _field=value,_measurement=cpu_load_short,host=server01,region=, type: 0
```

Is not possible in InfluxDB. There is no concept of `NULL` in influxdb. However there is a concept of a tag key existing or not existing on a series key. The idea that `region IS NULL` would be represented by a series key without a region tag, like:

```
SeriesFrame, tags: _field=value,_measurement=cpu_load_short,host=server01, type: 0
```

And then to answer **Subquestion B**.... "NULL"s would be ordered first in the series keys because they're ordered lexicographically:

```
SeriesFrame, tags: _field=value,_measurement=cpu_load_short,host=server01, type: 0
SeriesFrame, tags: _field=value,_measurement=cpu_load_short,host=server01,region=us-east, type: 0
SeriesFrame, tags: _field=value,_measurement=cpu_load_short,host=server01,region=us-west, type: 0
```

**Comment by e-dard** [comment]
Oh, to be screwy.. NULLS actually don't have a defined order I guess because consider you're talking about the `host` tag key, i.e., not the last tag on a key.. Now you have...

```
SeriesFrame, tags: _field=value,_measurement=cpu_load_short,host=server01,region=us-east, type: 0
SeriesFrame, tags: _field=value,_measurement=cpu_load_short,host=server01,region=us-west, type: 0
SeriesFrame, tags: _field=value,_measurement=cpu_load_short,region=us-west, type: 0 // "null host tag"
```

😂

**Comment by alamb** [comment]
Here is some more information from @stuartcarnie : 

> The client that merges the gRPC requests encodes these requirements:
https://github.com/influxdata/idpe/blob/1ae1cc5da753f5886360a9019a8f52e9b2a7c8d6/storage/reads/group_resultset_test.go#L18

**Comment by alamb** [comment]
Given the coverage we have in the flux and influxql suites, I believe this ticket can now be closed.
