### ISSUE TITLE
NG: Background task to automatically delete parquet (and other?) files from object store that do not have a corresponding catalog entry

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#4577]
__Steps to reproduce:__
1. Wipe catalog `drop schema iox_catalog cascade`

__Expected behaviour:__
Eventually something should clean up any parquet files in object store that are not referenced in the catalog

__Actual behaviour:__
Said parquet files hang out in object store indefinitely, slowing growing Jeff Bezos's bank account

Note we had this feature in OG.

Tracked by  https://github.com/influxdata/influxdb_iox/issues/1313 and implemented by @crepererum  in https://github.com/influxdata/influxdb_iox/pull/1554 so we can perhaps resurrect some of that code / ideas

**Comment by NGA-TRAN** [comment]
All the files in the catalog that mark `to_delete` needs to be deleted, too

**Comment by alamb** [comment]
I have added this to the "big 5 migration epic" for consideration. I suspect it is not a critical priority as the catalog size is now growing less quickly and this will be a performance optimization at best. 

> The command that does the cleanup of object store files not present in the catalog could also call the compactor garbage collector?

I think @crepererum wants them to be separate as they are somewhat separate concerns

> what "old" means.

I suggest conservatively start at 1 or 2 weeks

**Comment by alamb** [comment]
I think there are three outstanding items here:
1. Complete code to remove files not referenced: https://github.com/influxdata/influxdb_iox/pull/5024
2. Deploy the "unreferenced file deleter" to production
3. Connect up the "remove delete=true" items automatically from the catalog with a background process

I will file tickets for the last two items and the close this ticket to avoid confusion

**Comment by alamb** [comment]
Updated links to remaining items, closing this ticket down as all actions are now covered by other tickets
