### ISSUE TITLE
why develop iox as the influxdb new core 

### ISSUE THREAD

**Issue by duanshuaimin** [influxdata/influxdb_iox#461]
the performance

**Comment by alamb** [comment]
I think https://github.com/influxdata/influxdb_iox/blob/main/README.md#influxdb-iox links to some writeup of the rationale. Specifically:


> For more details on the motivation behind the project and some of our goals, read through the [InfluxDB IOx announcement blog post](https://www.influxdata.com/blog/announcing-influxdb-iox/). If you prefer a video that covers a little bit of InfluxDB history and high level goals for [InfluxDB IOx you can watch Paul Dix's announcement talk from InfluxDays NA 2020](https://www.youtube.com/watch?v=pnwkAAyMp18). 
For more details on the motivation behind the selection of [Apache Arrow, Flight and Parquet, read this](https://www.influxdata.com/blog/apache-arrow-parquet-flight-and-their-ecosystem-are-a-game-changer-for-olap/).
