### ISSUE TITLE
Minimize the number of ingesters contacted by the querier to increase robustness to failure

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#4621]
__Use case:__
There will be cases where one or more ingesters required for the query's answers can not be contacted by the querier. We are debating the finer details of what to do in this case on https://github.com/influxdata/influxdb_iox/issues/4608.

However, we can reduce the likelihood of needing to deal with an unavailable ingester by making the querier smarter about which ingesters might have *any* data for the query. At the time of writing , the querier asks *all* ingesters that are configured

@pauldix  notes that 

> Based on the current sharding, the querier should only have to hit a single shard per table in the query. In storage gRPC this means that every query should hit a single ingester. 

__Proposal:__

Teach the queriers enough about sharding that they can determine which ingesters might have any data for the query -- this may be part of  #4297 

__Current behaviour:__

Querier asks all ingesters it knows about

__Desired behaviour:__
Querier asks minimal set of ingesters

__Alternatives considered:__
N/A

**Comment by carols10cents** [comment]
I think there are going to be a few parts to this, please correct me if anything here is incorrect, too much, or too little:

- Queriers need to use [the same sharding as the router](https://github.com/influxdata/influxdb_iox/blob/46de8d6cb3b34230bc982f94687b68d5434ddcd2/router/src/sharder/jumphash.rs#L117-L138) to be able to take a table name and namespace and get a sequencer id
- Queriers need to know, in addition to [the address for each ingester](https://github.com/influxdata/influxdb_iox/blob/46de8d6cb3b34230bc982f94687b68d5434ddcd2/clap_blocks/src/querier.rs#L20-L39), which [write buffer partition numbers they're responsible for](https://github.com/influxdata/influxdb_iox/blob/46de8d6cb3b34230bc982f94687b68d5434ddcd2/clap_blocks/src/ingester.rs#L4-L16)
- The [request for partitions](https://github.com/influxdata/influxdb_iox/blob/46de8d6cb3b34230bc982f94687b68d5434ddcd2/querier/src/ingester/mod.rs#L365-L399) needs to take either a sequencer id (and then know the ingester-to-sequencer-range mapping) or an ingester address

**Comment by alamb** [comment]
(note sequencer_id == kafaka partition in some parts of the code, which makes things super confusing)

> Queriers need to use  to be able to take a table name and namespace and get a sequencer id

Yes, I think this is a key part. 

> Queriers need to know, in addition to the address for each ingester, which write buffer partition numbers they're responsible for

Yes, that is the case; However, it isn't just a coding exercise -- it is also a configuration / deployment design exercise as well (the more full featured discussion is on https://github.com/influxdata/influxdb_iox/issues/4297). I think we should get @mkmik 's opinion / advice before implementing anything here

**Comment by carols10cents** [comment]
@mkmik I'm almost to the point of needing the querier to have ingester addresses plus sequencer ids (aka kafka partition ids), do you have thoughts/pointers/opinions on how to specify this information to the queriers?

**Comment by mkmik** [comment]
I think a static map is the simplest thing. We can pass a simple json file that contains a full map of sequencers:

```
{
  "sequencers": {
     "0": { "addr": "http://ingester-1:8082" },
     "1": { "addr": "http://ingester-1:8082" },
...
     "25": { "addr": "http://ingester-2:8082" },
```

it would be trivial to generate from our jsonnet templates

**Comment by mkmik** [comment]
another option is to just include the sequencer we "target" in a gRPC header (aka metadata) and let Istio do the routing to the appropriate ingester

this way we only have one ingester address.

**Comment by mkmik** [comment]
the gRPC header requires minimal changes
