### ISSUE TITLE
WAL buffer should log an error when it drops segments that haven't been persisted

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#466]
The WAL buffer has a setting that lets users configure it to drop segments that haven't been persisted when the buffer goes over its set max capacity. This should be logged.

**Comment by alamb** [comment]
https://github.com/influxdata/influxdb_iox/pull/464#discussion_r527633085 is the specific location

**Comment by mbStavola** [comment]
I'd like to take this!
