### ISSUE TITLE
Doc lint CI failures are not fatal

### ISSUE THREAD

**Issue by domodwyer** [influxdata/influxdb_iox#4676]
We pay the price of running the rustdoc generation in CI to lint the documentation in IOx, but currently the resulting warnings are not fatal and go unnoticed.

We should make the rustdoc lint failures fatal.

**Comment by alamb** [comment]
Here is an example where the CI test fails due to OOM:

https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/19617/workflows/c4eefcd0-1fd1-4e76-bc2c-51032a13e13a/jobs/166115

**Comment by alamb** [comment]
@lukebond  had the same issue in https://github.com/influxdata/influxdb_iox/pull/4675

**Comment by domodwyer** [comment]
Here is an example of the `cargo doc` stage running successfully (indeed the entire pipeline was green) - there are lint failures emitted as warnings which should be fatal, and they do not fail the doc stage: https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/19602/workflows/3efe7a9e-9169-48e9-b514-0a9c17e5f236/jobs/165956

**Comment by carols10cents** [comment]
Jake and I were seeing this too, and it did look like an OOM-- when he bumped the memory for the doc ci job, it passed consistently. that change is on main now, but maybe it wasn't in your branch? https://github.com/influxdata/influxdb_iox/pull/4645

**Comment by carols10cents** [comment]
Errrr hmmm that doesn't seem to be working.... 

```
cargo doc -- -D warnings
error: Found argument '-D' which wasn't expected, or isn't valid in this context

	If you tried to supply `-D` as a value rather than a flag, use `-- -D`

USAGE:
    cargo doc [OPTIONS]

For more information try --help
```

will investigate in the background of working on other things

**Comment by carols10cents** [comment]
oh hey https://github.com/rust-lang/cargo/issues/8424#issuecomment-1070988443
