### ISSUE TITLE
Add Querier caches for parquet files in read buffer

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#4681]
# Background / Abstract:
On every query today the querier might request one or more parquet files directly from the object store, decodes them and discards them at the end of the query

this is especially wasteful for common workloads that repeatedly query the same table

We would like to cache the results of fetching and decoding the parquet files using the ReadBuffer (👋  @e-dard ) in the querier. 

The read buffer has had significant effort on memory efficiency and runtime performance. 

# Acceptance Criteria / Definition of Done
- [ ] Create a new type of [`Cache`](https://github.com/influxdata/influxdb_iox/blob/8c537c94672586a0aadd437a024e92c3c3c3664b/cache_system/src/driver.rs#L17-L29) that maps from [`ParquetFileId`](https://github.com/influxdata/influxdb_iox/blob/4d8ece5524bd8927df830a578186fbbdc8f028ea/data_types/src/lib.rs#L296-L299) to a [ReadBuffer `Chunk`](https://github.com/influxdata/influxdb_iox/blob/8c537c94672586a0aadd437a024e92c3c3c3664b/read_buffer/src/chunk.rs#L53-L60) 
- [ ] The cache should properly account for memory consumption and have a [LRU](https://github.com/influxdata/influxdb_iox/blob/main/cache_system/src/backend/lru.rs) eviction policy
- [ ] When the querier runs a query, if the parquet data is in the cache, the data should be read from the read buffer in the cache rather than fetching the parquet file (see "ReadBuffer Chunk" section below)

## ReadBuffer Chunk
To wire up the ReadBuffer into the querier (and ultimately making it visible to the query engine) it needs to implement [`QueryChunk`](https://github.com/influxdata/influxdb_iox/blob/95e6a8ed4679552d90ffdb60b5ae40880577652b/iox_query/src/lib.rs#L177-L249), which in turn requires [`QueryChunkMeta`](https://github.com/influxdata/influxdb_iox/blob/95e6a8ed4679552d90ffdb60b5ae40880577652b/iox_query/src/lib.rs#L38-L91). The querier does this already for parquet chunks ([`
impl QueryChunk for QuerierChunk`](https://github.com/influxdata/influxdb_iox/blob/95e6a8ed4679552d90ffdb60b5ae40880577652b/querier/src/chunk/query_access.rs#L55), [`impl QueryChunkMeta for QuerierChunk`](https://github.com/influxdata/influxdb_iox/blob/95e6a8ed4679552d90ffdb60b5ae40880577652b/querier/src/chunk/query_access.rs#L21)) and ingester chunks ([`impl QueryChunk for IngesterPartition`](https://github.com/influxdata/influxdb_iox/blob/95e6a8ed4679552d90ffdb60b5ae40880577652b/querier/src/ingester/mod.rs#L574), [`impl QueryChunkMeta for IngesterPartition`](https://github.com/influxdata/influxdb_iox/blob/95e6a8ed4679552d90ffdb60b5ae40880577652b/querier/src/ingester/mod.rs#L535)). Something similar needs to be done for ReadBuffer-backed chunks. The new chunks must then be created in [`Reconciler::reconcile`](https://github.com/influxdata/influxdb_iox/blob/95e6a8ed4679552d90ffdb60b5ae40880577652b/querier/src/table/state_reconciler.rs#L56-L59) instead of the parquet-backed chunks (these currently have the somewhat confusing type `QuerierChunk`).

For more information on how to wire up a read buffer into the query engine (i.e. how to implement these traits for this specific type), see [this OG code](https://github.com/influxdata/influxdb_iox/blob/37c7ce793cc12a7f5dc29b3bc3d575c6c500f2bf/db/src/chunk.rs). There one may just copy the implementation for `DbChunk` when its state is `State::ReadBuffer`.

We probably want to keep the parquet-backed chunks for now because we might need them again soon. While for this ticket here we will create ReadBuffers for every parquet file unconditionally, we probably wanna use some improved heuristics in the future (after measuring / observing prod!).

**Comment by alamb** [comment]
A follow up here: Post deployment of this PR the resource usage of the querier on production is much much better:
![Screen Shot 2022-06-06 at 2 38 38 PM](https://user-images.githubusercontent.com/490673/172228380-4ca3a930-76dc-4f85-bffd-0ee2858234f9.png)


![Screen Shot 2022-06-06 at 2 39 48 PM](https://user-images.githubusercontent.com/490673/172228322-3a7f0cb8-85e3-48a4-9734-7e0bd2ead1c6.png)
![Screen Shot 2022-06-06 at 2 40 14 PM](https://user-images.githubusercontent.com/490673/172228326-74aa21aa-e640-4716-9617-3436288ddd89.png)
![Screen Shot 2022-06-06 at 2 45 55 PM](https://user-images.githubusercontent.com/490673/172228327-0d74fd1e-ca85-4b53-bfe1-80b241d2bfc0.png)
![Screen Shot 2022-06-06 at 2 40 43 PM](https://user-images.githubusercontent.com/490673/172228330-c86805b6-318e-4224-ab94-fa140ca9f025.png)

**Comment by aierui** [comment]
@alamb 👍 Looks great.
