### ISSUE TITLE
Possible compactor deadlock

### ISSUE THREAD

**Issue by domodwyer** [influxdata/influxdb_iox#4696]
Logs for compactors 0, 2 & 3 in prod show they progress up until they begin executing the query plan, and then appear to deadlock - they emit no further logs, do not use any significant amounts of CPU or RAM, or upload/download any files from the object store.

**Comment by NGA-TRAN** [comment]
C0: possibly deadlock deadlock

. Compacting partition candidates: n_candidates=8098
. Actuall selected partitions to compact: n_compactions=7
. Num files and columns of those selected partitions
  -- num_files: 126, 236, 114, 136, 373, 257, 2
  -- num_cols: 9, 12, 15, 15, 14, 9, 51

C1: panic 
. Compacting partition candidates: n_candidates=10438
. Actuall selected partitions to compact: n_compactions=1
. Num files and columns of those selected partitions
  -- num_files: 218
  -- num_cols: 72 

level=error msg="failed to upload parquet file to object storage" error="Generic S3 error: Unable to PUT data. Bucket: prod01-eu-central-1.aws.influxdata.io-iox, Location: 1/1032/51/19010293/9d912f0e-e0fc-450b-ab8c-e5b52cddf93b.parquet, Error: Could not get credentials from iam: Request timed out (Credentials(CredentialsError { message: \"Could not get credentials from iam: Request timed out\" }))" meta="IoxMetadata { object_store_id: 9d912f0e-e0fc-450b-ab8c-e5b52cddf93b, creation_timestamp: 2022-05-25T11:06:56.688889174+00:00, namespace_id: NamespaceId(1), namespace_name: \"797a0180da80497c_e0d34f2f9ce72d08\", sequencer_id: SequencerId(51), table_id: TableId(1032), table_name: \"prometheus\", partition_id: PartitionId(19010293), partition_key: \"2022-05-11\", min_sequence_number: SequenceNumber(153531009), max_sequence_number: SequenceNumber(155716198), compaction_level: 1, sort_key: Some(SortKey { columns: {\"ansible_version\": SortOptions { descending: false, nulls_first: true }, \"enabled\": SortOptions { descending: false, nulls_first: true }, \"external_logger_enabled\": SortOptions { descending: false, nulls_first: true }, \"external_logger_type\": SortOptions { descending: false, nulls_first: true }, \"insights_analytics\": SortOptions { descending: false, nulls_first: true }, \"last_isolated_check\": SortOptions { descending: false, nulls_first: true }, \"license_type\": SortOptions { descending: false, nulls_first: true }, \"managed_by_policy\": SortOptions { descending: false, nulls_first: true }, \"pendo_tracking\": SortOptions { descending: false, nulls_first: true }, \"tower_version\": SortOptions { descending: false, nulls_first: true }, \"hostname\": SortOptions { descending: false, nulls_first: true }, \"tower_url_base\": SortOptions { descending: false, nulls_first: true }, \"listener\": SortOptions { descending: false, nulls_first: true }, \"status\": SortOptions { descending: false, nulls_first: true }, \"type\": SortOptions { descending: false, nulls_first: true }, \"launch_type\": SortOptions { descending: false, nulls_first: true }, \"delayedOperation\": SortOptions { descending: false, nulls_first: true }, \"host\": SortOptions { descending: false, nulls_first: true }, \"cloud\": SortOptions { descending: false, nulls_first: true }, \"groupId\": SortOptions { descending: false, nulls_first: true }, \"version\": SortOptions { descending: false, nulls_first: true }, \"error\": SortOptions { descending: false, nulls_first: true }, \"networkProcessor\": SortOptions { descending: false, nulls_first: true }, \"node\": SortOptions { descending: false, nulls_first: true }, \"topic\": SortOptions { descending: false, nulls_first: true }, \"url\": SortOptions { descending: false, nulls_first: true }, \"partition\": SortOptions { descending: false, nulls_first: true }, \"request\": SortOptions { descending: false, nulls_first: true }, \"name\": SortOptions { descending: false, nulls_first: true }, \"time\": SortOptions { descending: false, nulls_first: true }} }) }" target="parquet_file::storage" location="parquet_file/src/storage.rs:137" time=1653484491654784534

level=error msg="Thread panic" panic_info="panicked at 'invalid statistics: NoRowGroup', parquet_file/src/metadata.rs:397:14" target="panic_logging" location="panic_logging/src/lib.rs:107" time=1653484492112195739


C2: possibly deadlock deadlock

. Compacting partition candidates: n_candidates=7561
. Actuall selected partitions to compact: n_compactions=2
. Num files and columns of those selected partitions
  -- num_files: 181, 587
  -- num_cols: 688, ?

level=warn msg="compaction on partition 20336491 failed with: QueryingPartition { source: SqlxError { source: PoolTimedOut } }" target="compactor::handler" location="compactor/src/handler.rs:183" time=1653476813740502804

C3: possibly deadlock deadlock
. Compacting partition candidates: n_candidates=8678
. Actuall selected partitions to compact: n_compactions=3
. Num files and columns of those selected partitions
  -- num_files: 165, 287, 3831
  -- num_cols: 17, 44, 7

**Comment by NGA-TRAN** [comment]
Close this as we no longer see deadlock. Must be fixed with the work in the Querier
