### ISSUE TITLE
Build error on Centos 8: thread 'main' panicked at '`flatc` failed to compile the .fbs to Rust', generated_types/build.rs:65:44

### ISSUE THREAD

**Issue by duanshuaimin** [influxdata/influxdb_iox#470]
build influxdb_iox on CentOS 8 but it fails 
thread 'main' panicked at '`flatc` failed to compile the .fbs to Rust', generated_types/build.rs:65:44
OS:CentOS 8

**Comment by duanshuaimin** [comment]
the flatc is installed ,but it is called flatcc

**Comment by alamb** [comment]
Thanks for the report @duanshuaimin !

**Comment by tustvold** [comment]
The generated flatbuffer code is now checked in
