### ISSUE TITLE
Expose semaphore metrics

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#4739]
~#4737 introduced two semaphores (one for file size, one for number of files).~ (this code is now gone but the generic problem still exists for other semaphores)

As @mkmik [pointed out](https://github.com/influxdata/influxdb_iox/pull/4737#pullrequestreview-990067371) it would be nice if we would have some metrics detecting that we hit these semaphores.

**Comment by alamb** [comment]
I believe the relevant code was removed in https://github.com/influxdata/influxdb_iox/pull/4741 so this ticket can probably be closed

**Comment by alamb** [comment]
I believe the relevant code was removed in https://github.com/influxdata/influxdb_iox/pull/4741 so this ticket can probably be closed

**Comment by crepererum** [comment]
I think a similar problem applies to other async semaphores in our code base and I'm soooo close to implement a generic wrapper (similar to what we have for sync locks), so I would steal this ticket and change the scope a bit.

**Comment by crepererum** [comment]
this is done (the only remaining async semaphore is the query concurrency limiter)
