### ISSUE TITLE
Compactor: Split a large file into smaller non-overlapped ones, each smaller than a configured max size

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#4790]
# Rationale
Currently, we compact all overlapped files into one file which can be very large. This ticket is to find those large files and split them into many non-overlapped ones, each smaller than a configured max size

# Initial Solution
Include 2 separated implementations:
1. While compacting several overlapped files, if they are huge, we will split them at that time.
2. A different background task (or add this into a compact background loop) to find large files and split them.

If we discover large files in #1 then #2 almost does nothing and may consider not to be implemented

**Comment by pauldix** [comment]
I don't think we should need part 2 of this. Unless we see that we have large files and that they're a problem.
