### ISSUE TITLE
Remove gRPC write API

### ISSUE THREAD

**Issue by domodwyer** [influxdata/influxdb_iox#4866]
The routers expose a [gRPC write API][router] which uses the same wire format as the kafka messages. This coupling of external/public API with internal message formatting creates [problems](https://github.com/influxdata/influxdb_iox/pull/4864#discussion_r898095113).

@pauldix has stated this current gRPC API is unnecessary and should be removed.

[router]:https://github.com/influxdata/influxdb_iox/blob/4df2964566f770f6914c7d252231f4ec24ebacc2/router/src/server/grpc.rs#L148

Currently this API is used by:

1. [`influxdb_iox_client::write_lp()`][lp]
2. [`influxdb_iox_client::write_pb()`][pb]

For 1 this call should be switched to use the HTTP API. 2 should be removed.

[lp]:https://github.com/influxdata/influxdb_iox/blob/4df2964566f770f6914c7d252231f4ec24ebacc2/influxdb_iox_client/src/client/write.rs#L55
[pb]:https://github.com/influxdata/influxdb_iox/blob/4df2964566f770f6914c7d252231f4ec24ebacc2/influxdb_iox_client/src/client/write.rs#L80

**Comment by crepererum** [comment]
I thought we wanted to offer the protobuf format as a more efficient alternative to LP? IIRC the format is/was actually public (why is https://github.com/influxdata/influxdb-pb-data-protocol archived?).

**Comment by crepererum** [comment]
> Having the internal kafka message format be a public API is never going to be a good idea. Ideally we would like to change the kafka messages to reference by object id, rather than object name/strings, for example instead of sending the namespace/table/column/partition key strings, send their catalog IDs. That's not going to be a very good public API.

Depends. Having a Kafka format for which we have proper tooling and that is widely used has it benefits. I'm not sure about the strings, to me it smells like premature optimization w/o numbers.

**Comment by domodwyer** [comment]
It was an example of why evolving the internal message format is made difficult if it's also the public API - any internal changes you want to make to optimise/improve/replace/deprecate/etc instantly affects all users of the public API which is a silly position to put ourselves in.

> Having a Kafka format for which we have proper tooling

This is not really a reason for having a public API use the internals.

**Comment by domodwyer** [comment]
Unfortunately the IOx API client's `write_lp()` method seems to be incompatible with the HTTP write API, as it accepts a single "database name" and not an org/bucket pair (needed for the HTTP API):

https://github.com/influxdata/influxdb_iox/blob/0fbff981ecb5b1deb152ae6b5b6a13a9fe9d6078/influxdb_iox_client/src/client/write.rs#L55-L60

This is used by both the IOx CLI to write to arbitrary databases:

https://github.com/influxdata/influxdb_iox/blob/0fbff981ecb5b1deb152ae6b5b6a13a9fe9d6078/influxdb_iox/src/commands/write.rs#L49

And the IOx / TSM comparison tool (internal).

This is blocking https://github.com/influxdata/influxdb_iox/issues/4897.

## Proposal

Support specifying an arbitrary DB to write to via the HTTP write API in addition to the org & bucket. This would be via a `?db=bananas` query param, much like the `?org=blah&bucket=foo` query params currently used.

## Alternatives

Force the internal tool, and CLI to use the org/bucket naming strategy. This could be OK (and less invasive) but I do not know if this is feasible.

**Comment by crepererum** [comment]
The proposal sounds good to me :+1:

**Comment by domodwyer** [comment]
This is blocking https://github.com/influxdata/influxdb_iox/issues/5323 due to the public gRPC write API also being the Kafka wire format.

Removing the gRPC write API will allow the Kafka wire format to be changed, necessary to facilitate a different batched DML representation on the wire.
