### ISSUE TITLE
Create metric for counting level-0 file compacted files

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#4901]
# Rationale

Currently, we keep track of number of both level-0 and level-1 files compacted for each partition in [compaction_counter and here](https://github.com/influxdata/influxdb_iox/blob/bf6fec24473e7627f45444371d2e806f93bd67a8/compactor/src/compact.rs#L548). Since we want to compare the speed of ingesting (level-0 files) with the speed of compacting those files, we want another counter to track only level-0 files compacted for each partition

**Comment by NGA-TRAN** [comment]
@carols10cents 
When we compact a partition, we read all non-deleted files both level 0 and 1 (or 2). The level-1 are the ones we compacted before that. The available counter counts both of them. What we want is another count to only count the level-0 files.

**Comment by carols10cents** [comment]
But promotion_counter is only counting the files that are getting promoted *from* level 0, right? [Or am I reading this code wrong somehow? ](https://github.com/influxdata/influxdb_iox/blob/3aef5ac697892250f2e5f87d58f9d17b3053ae88/compactor/src/compact.rs#L665-L668)

**Comment by NGA-TRAN** [comment]
So they are different
1. Level-0 files that are compacted will stay level-0 but their `to_delete` will be set to a value (means they are deleted)
2. Level-0 files that should be compacted but because they are already in compacted form (e.g. in this case we compact all files into one, if `all files` includes only 1 file and there are no tombstones for it at all, we do not need to compact it) and they will be promoted to level-2.

This ticket wants to count the former ones

**Comment by carols10cents** [comment]
Ah, ok, I see now! Thank you!!
