### ISSUE TITLE
Support multiple streams in StreamSplitExec

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#4915]
# Rationale

Currently [StreamSplitExec](https://github.com/influxdata/influxdb_iox/blob/70337087a83827959a88668d2e51fe225833b246/iox_query/src/exec/split.rs#L168) only supports [2 running streams](https://github.com/influxdata/influxdb_iox/blob/70337087a83827959a88668d2e51fe225833b246/iox_query/src/exec/split.rs#L157). Since we want to split a compacted result into many more non-overlapped streams, this ticket is to make those 2 hard-code streams into an array/list of n streams

**Comment by domodwyer** [comment]
Once you change the `SplitStreamExec` to output more partitions in parallel, the compactor will automatically start parallelising across all the output partitions without needing any code changes :+1:
