### ISSUE TITLE
Ingester should pause ingesting whenever persisting can't keep up with ingesting

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#4928]
# Use case: 
There are times (during replay especially) that we saw the ingester ingesting faster than the `persist` operation. If this continues unabated eventually the ingester will be OOM killed (due to out of memory) as each persist gets bigger. 

This meant that despite setting `INFLUXDB_IOX_PERSIST_PARTITION_SIZE_THRESHOLD_BYTES` to limit the maximum size of an individual persist operation, we were persisting larger partitions -- see here for an example https://github.com/influxdata/conductor/issues/980#issuecomment-1159094137 

# Proposal
Pause ingest if a partition exceeds the `INFLUXDB_IOX_PERSIST_PARTITION_SIZE_THRESHOLD_BYTES` setting and a persist is already underway.

**Comment by alamb** [comment]
>  Just to clarify, you'll only pause if a persist is already underway for the partition that has crossed the threshold?

Yes,  only pause if a persist is already underway for the partition that has crossed the threshold (again)

**Comment by alamb** [comment]
> Just to clarify, you'll only pause if a persist is already underway for the partition that has crossed the threshold?

In coding this up, @pauldix mentioned to me that persists happen "in batches" meaning no new persist operation happens while there is an existing persist operation outstanding. 

Thus as soon as any partition exceeds the partition threshold it can't be persisted until the next persist batch is calculated.  

Once we make persist happen per-partition (rather than in batches) changing the algorithm to pause only when a partition with an outstanding persist goes over makes sense.

**Comment by alamb** [comment]
Per discussions, this goal has been lowered in priority, so unassigning myself https://influxdata.slack.com/archives/CRK9M8L5Q/p1657812384568659?thread_ts=1657739394.189219&cid=CRK9M8L5Q

The ingester I think is "stable enough" for the time being

**Comment by alamb** [comment]
Resetting this as "nice to have" status as I am not sure it is actually needed / useful

**Comment by jacobmarble** [comment]
Related to "bimodal workload priority".

**Comment by alamb** [comment]
I think github got over eager closing this ticket -- I believe @domodwyer 's intention on https://github.com/influxdata/influxdb_iox/pull/6316 was that when we switch IOx to use ingester2 this issue will be solved
