### ISSUE TITLE
Ingester's "total memory accounting" does not account for memory being persisted

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#4936]
As pointed out by @domodwyer  on https://github.com/influxdata/influxdb_iox/pull/4931#issuecomment-1164402251

The ingester maintains a rough "total memory in use" counter it uses to try and limit the amount of memory the ingester is using overall:

https://github.com/influxdata/influxdb_iox/blob/fe235d0b0e3e2166d50b72c0b2c30146747a0971/ingester/src/lifecycle.rs#L317-L319

When the ingester triggers a persist operation, it immediately stops accounting for the memory the partition is using:

https://github.com/influxdata/influxdb_iox/blob/fe235d0b0e3e2166d50b72c0b2c30146747a0971/ingester/src/lifecycle.rs#L307-L310

Which is called in `mark_persisting()` at the start of the persist [here][1], while it is very much still using the memory (and soon more as the parquet is generated). This would cause the ingester to falsely believe it has memory headroom, and it will continue ingesting, pushing memory usage over the limit.

The ingester should move this decrement to be _after_ the persist is complete so it accounts for the partition memory until it has been actually freed, which should help the OOMs as we will correctly account for the in-use memory and pause ingest.

[1]: https://github.com/influxdata/influxdb_iox/blob/fe235d0b0e3e2166d50b72c0b2c30146747a0971/ingester/src/lifecycle.rs#L479

**Comment by domodwyer** [comment]
I am actively working on this :+1:
