### ISSUE TITLE
Compators memory usage higher after Ingester changes

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#4939]
# Rationale
With recent changes in Ingesters to persist smaller files, the Compactors have to compact more files and from the [Compactor dashboard](https://grafana.prod01-eu-central-1.aws.influxdata.io/d/z7-FhLsnk/compactor?orgId=1), they seem use a lot more memory. One of the Compactor `iox-shared-compactor-1-0` hits OOMs frequently. This may related to #4886 too

**Comment by alamb** [comment]
FWIW I hope to tune the ingesters over the next few days to hopefully reduce the number of smaller parquet files; https://github.com/influxdata/conductor/issues/1006
