### ISSUE TITLE
Compactor dashboard new metrics and fixes

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#4987]
# Rationale

The [Compactor Dashboard ](https://grafana.prod01-eu-central-1.aws.influxdata.io/d/z7-FhLsnk/compactor?orgId=1) has many metrics but they either not that accurate or enough for us to say the Compactor is working well. A few things to add into this dashboard:
  1. Fix inaccurate ones (I think all he panels of `Input Compacted File Rate` and `Output Compacted File Rate` are not accurate). **- Fixed in July 2022**
  2. Some performance metrics to see if Compactor catches up well with the Ingester (aka: does it compacted all necessary files). Here are the requirements for a partition:
         i. Should contain all non-overlapped files
         ii. Size of each file should be smaller than an config max size
         iii. Should not contain files that are too small. Small and contiguous files should be compacted into one larger file 
    **Update:  Will use different metrics for this and they are defined in https://github.com/influxdata/influxdb_iox/issues/5305**

 3. Metrics for us to know if there partition/files that should be compacted but never get compacted (either bugs or starving issues) 4. 
     Update: This is less a concern with our today better hot compaction; and with cold compaction, we will collect all partitions. No longer need this
This is related to #4838, #4901 and can be done in parallel

**Comment by aierui** [comment]
Hi @NGA-TRAN , can you share the monitoring metrics for grafana dashborad ?

**Comment by carols10cents** [comment]
> 2. Some performance metrics to see if Compactor catches up well with the Ingester (aka: does it compacted all necessary files). Here are the requirements for a partition:
> i. Should contain all non-overlapped files
> ii. Size of each file should be smaller than an config max size
> iii. Should not contain files that are too small. Small and contiguous files should be compacted into one larger file

I don't think any of these are relevant in the current state of the code where we're attempting to compact all files of a partition into one file. Please correct me if I'm wrong!

> 3. Metrics for us to know if there partition/files that should be compacted but never get compacted (either bugs or starving issues)

Would this be addressed if, in every iteration of [the `while` loop in `run_compactor`](https://github.com/influxdata/influxdb_iox/blob/80b6c5c82fc69893122ef0380b98167ede005392/compactor/src/handler.rs#L177-L178), a metric was recorded of the total number of level 0 parquet files in the catalog? Or should the age of level 0 parquet files be recorded somehow?

**Comment by NGA-TRAN** [comment]
@carols10cents 

>> Fix inaccurate ones (I think all he panels of Input Compacted File Rate and Output Compacted File Rate are not accurate)

> What makes you think these are inaccurate, exactly? Are they too high or too low?

Dom and I looked into them and they are inaccurate. I will look into them again soon and I will see if I can fix them by just changing the dashboard or we need to create a different metrics

>> Some performance metrics to see if Compactor catches up well with the Ingester (aka: does it compacted all necessary files). Here are the requirements for a partition:
i. Should contain all non-overlapped files
ii. Size of each file should be smaller than an config max size
iii. Should not contain files that are too small. Small and contiguous files should be compacted into one larger file

> I don't think any of these are relevant in the current state of the code where we're attempting to compact all files of a partition into one file. Please correct me if I'm wrong!

Right. We do not need to worry about these now unless we do something more

>> Metrics for us to know if there partition/files that should be compacted but never get compacted (either bugs or starving issues)

> Would this be addressed if, in every iteration of [the while loop in run_compactor](https://github.com/influxdata/influxdb_iox/blob/80b6c5c82fc69893122ef0380b98167ede005392/compactor/src/handler.rs#L177-L178), a metric was recorded of the total number of level 0 parquet files in the catalog? Or should the age of level 0 parquet files be recorded somehow?

I do not think this will help us. I need to think a bit more how to  identify those files

compaction_output_counter
