### ISSUE TITLE
Improve Ingester speed to catch up / replay

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#5000]
__Steps to reproduce:__

When catching up from Kafka, the ingesters only manage ~1MB/s per Kafka partition

![image](https://user-images.githubusercontent.com/1781103/176664324-6962662d-7597-44a6-9225-d715e54cf0b7.png)

This is significantly below the 10-20 MB/s we were seeing with OG

The ingesters never appear to use more than 1 CPU, so it is possible there is lock contention somewhere

![image](https://user-images.githubusercontent.com/1781103/176663801-257d429b-36da-45f5-9207-ee73a0fd14cf.png)

Also looking at the sequence number graphs

![image](https://user-images.githubusercontent.com/1781103/176664690-ee8e44a0-f3bd-4843-ac9e-c890c3a651e4.png)

It would appear they are catching up ~16M messages. This might suggest that the aggregation in the routers is not working effectively, and we are ending up with a lot of very small message payloads.

__Expected behaviour:__

We should be able to catchup at many multiples of the steady state ingest speed. This would allow buffering more data in memory before persisting it, helping to reduce over-all system churn due to small parquet files

**Comment by tustvold** [comment]
We also see the rate of consumption from individual partitions varying wildly during replay

![image](https://user-images.githubusercontent.com/1781103/176738443-101d8fca-5067-44c3-bef5-e62e4b34cca2.png)

![image](https://user-images.githubusercontent.com/1781103/176738498-85f5f1f1-09cc-4403-a6e3-11b9bb124f1b.png)

This would suggest to me that we are bottlenecking somewhere, as I would expect it to saturate the throughput for each partition

**Comment by alamb** [comment]
Related to https://github.com/influxdata/conductor/issues/971

**Comment by alamb** [comment]
I believe @tustvold  is working on this one so assigning to him

**Comment by alamb** [comment]
What if one partition has most of the data writes (and thus dominates the max TTBR and limits the maximum amount of concurrency we can get -- aka even with 20 partitions the TTBR will be dominated by the single large partition). 

🤔 I wonder if we could pipeline the "read next message from kafka and decode it"  from the actual insertion. Or maybe even use more than one core if decoding the messages are the bottneck.

But that still doesn't seem to explain why only a single cor eis busy

**Comment by alamb** [comment]
@tustvold  is working on https://github.com/apache/arrow-rs/issues/1764 which should also help significantly

**Comment by alamb** [comment]
@tustvold  I was profiling stuff and I have a trace related to the writing of parquet, in case you are interested. Here is the data [profile.zip](https://github.com/influxdata/influxdb_iox/files/9057327/profile.zip)

Visualized via
```shell
go tool pprof -http=localhost:6060 profile.proto
```

![Screen Shot 2022-07-06 at 2 50 09 PM](https://user-images.githubusercontent.com/490673/177622069-1122909f-c7d1-4090-8515-9aef210f0e60.png)

**Comment by alamb** [comment]
(the other half is related to sorting string dictionaries -- I have several ideas to speed up this process as well (aka make all the arrays have the same sorted dictionary and then sort the indices)

**Comment by alamb** [comment]
But first I need to figure out what is serializing all the writes
