### ISSUE TITLE
(kafka) Ingester to persist in-memory buffers during normal shutdown

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#5013]
__Use case:__
During a rollout of new IOx versions, any data that has been ingested but not persisted must be "replayed" by the ingester. During the replay, TTBR (time to become readable) is elevated until replay catches up. 

Thus minimizing the amount of data that needs a replay will minimize the time during with TTBR is elevated during rollout. 

In parallel we are investigating speeding up replay in #5000 but avoiding the need for as much replay will be even faster ;)

__Proposal:__
When the Ingester receives a request to shutdown (aka `SIGTERM`) it should:
1. Stop ingesting new data
2. Immediately attempt to persist all unpersisted partition data
3. Wait for all persist operations (currently outstanding and newly started) to complete
4. Give up on cleanup after configurable time duration (by default, Kubernetes sends SIGKILL 120s after SIGTERM, unless the process exits first)

__Current behaviour:__
When the Ingester receives a request to shutdown (aka `SIGTERM`) it:
1. Stop ingesting new data
2. Wait for all persist operations currently outstanding to complete

**Comment by mkmik** [comment]
The risk of doing this is that we tune for the happy path.

**Comment by alamb** [comment]
> The risk of doing this is that we tune for the happy path.

@mkmik  Do you mean that this won't improve worst case recovery time, but will make it less common. Thus when we hit "worst case" it will be more painful?

**Comment by mkmik** [comment]
Yes. If we exercise our unhappy path often (e.g. at each rollout) we're better equipped at understanding what will happen when a more rare event happens. That's not the only way to do it, but it's generally the easiest way since otherwise you have to engineer in something that exercises the unhappy path often enough and yet doesn't cause the same problem you worked around by special casing the happy path.

**Comment by alamb** [comment]
I see that is a good point -- so it seems like this ticket should be characterized as a "resource / cost optimization" rather than anything related to improving recovery times of the system (as it doesn't improve the worst case)
