### ISSUE TITLE
Remove min_sequence_number

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#5044]
# Rationale

@pauldix and I have talked last week and we decided keeping the range [min_sequence_number, max_sequence_number] is unnecessary and even causes some headache seem-like-a-bug (e.g. https://github.com/influxdata/conductor/issues/1013).

This needs a lot of changes in Ingester, Compactor and Querier.

# Steps:
 Since `min_sequence_number` can be null, the approach is to modify the code to neither use nor set this value. Then when the code is available, go and drop this column in a migration script

- [x] #5152
- [x] #5153
- [x] #5154

**Comment by alamb** [comment]
I haven't thought through the implications of removing min_sequence_number

**Comment by crepererum** [comment]
While I agree that the range itself might be unnecessary for the happy path, it might be a really valuable information for:

- sanity checking
- data lineage (which will be extremely helpful for debugging)

To me it looks like the bugs https://github.com/influxdata/conductor/issues/1013 clearly show that some invariant / state change wasn't understood or that we indeed have a bug. So just removing the value and sanity checks around it smells like YOLO-engineering :shrug: [^1]

[^1]: I'm clearly overplaying it here. I'm not suggesting that any team member is such a kind of engineer, just that the proposal w/o any further investigation sounds a bit bold.

**Comment by NGA-TRAN** [comment]
@crepererum After going thru all scenarios I can think of, I agree with you and I do not (yet) see any value to remove `min_sequnce_number`. I actually found the bug of https://github.com/influxdata/conductor/issues/1013 and will add repro there.

I keep this one open because @pauldix suggested us to do so. Will close this after discussion with him

**Comment by NGA-TRAN** [comment]
After some more discussion, we decided to remove `min_sequence_number` since it is not necessary at all and has introduced confusion so far

**Comment by NGA-TRAN** [comment]
Done
