### ISSUE TITLE
parquet files marked "to_delete" in the catalog are never actually deleted

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#5055]
Originally posted by @carols10cents in https://github.com/influxdata/influxdb_iox/issues/4577#issuecomment-1176263221

We have implemented code that marks catalog entries of compacted files with `delete = true`. There is code implemented in https://github.com/influxdata/influxdb_iox/pull/4131 to actually delete those entries from the catalog and the corresponding files, but that code isn't actually called anywhere yet:

```
$ git checkout main # e193913
$ grep garbage_collector
compactor/src/lib.rs
15:pub mod garbage_collector;
$
```

@carols10cents  notes that there are still questions about [if the granularity of removing files is correct, how and how often the task cleaning up to_delete=true files should run](https://github.com/influxdata/influxdb_iox/pull/4131#pullrequestreview-921855435), and [what "old" means](https://github.com/influxdata/influxdb_iox/blob/425b8a63cf6347ef232e255e63cdd84378f0f25d/compactor/src/garbage_collector.rs#L55).

# Definition of Done:
- [x] Resolve outstanding questions about frequency and where to run this
- [ ] Implement the plan

**Comment by alamb** [comment]
I propose running the code implemented in https://github.com/influxdata/influxdb_iox/pull/4131 to actually delete those entries from the catalog and the corresponding files from object store once when the `garbage_collector` service starts up. 

Namely https://github.com/influxdata/influxdb_iox/tree/main/garbage_collector/src

So each time it gets deployed it would clear out old catalog entries first and then proceed to delete unreferenced object store files

**Comment by alamb** [comment]
@carols10cents  / @NGA-TRAN  / @pauldix / @crepererum   do you have any issues with removing parquet files that were marked "to delete" from the catalog / object store now?

**Comment by crepererum** [comment]
@alamb I don't fully understand your question TBH. The files shall be deleted eventually but they MUST be kept around for a while because there might be in-flight queries that use them. This is the whole reason for marking them instead of pruning them from the catalog instantly.

**Comment by alamb** [comment]
@crepererum  there are, confusingly,  two "garbage collectors"

1. The [first](https://github.com/influxdata/influxdb_iox/tree/main/garbage_collector/src) that deletes anything in object store that does not have a catalog reference but does not touch any file that is marked `to_delete` in the catalog
2. The [second](https://github.com/influxdata/influxdb_iox/blob/main/compactor/src/garbage_collector.rs) in the compactor that actually removes parquet files marked as `to_delete` from the catalog and object store

The first is hooked up and working well (it is the one you sped up in https://github.com/influxdata/influxdb_iox/pull/5364)

The second is not yet hooked up to anything (and thus all files that the compactor has marked as `to_delete` are not actually yet deleted.

**Comment by NGA-TRAN** [comment]
@alamb I have no issues to remove files that are marked to_delete

**Comment by alamb** [comment]
👍  thanks @NGA-TRAN  -- this can be a nice to have / backburner issue I suppose then

**Comment by alamb** [comment]
I am marking this as Lighthouse as without it we will not ever truly "purge" any data from IOx (it will live in old parquet files that are referenced from the catalog). In order to implement correct retention intervals we'll probably need to fix that

**Comment by lukebond** [comment]
i will do this as part of the existing garbage collector. have it periodically query the catalog for parquet files older then 2 weeks (configurable) and delete the rows.
