### ISSUE TITLE
Metrics for the number of partitions per sequencer ID (shard)

### ISSUE THREAD

**Issue by carols10cents** [influxdata/influxdb_iox#5081]
Extracted as a smaller task from https://github.com/influxdata/influxdb_iox/issues/4838

[Note from this comment](https://github.com/influxdata/influxdb_iox/issues/4838#issuecomment-1179270741):

> We want all: total partitions, partitions chosen to compact, partitions have been compacted

**Comment by NGA-TRAN** [comment]
Recently, our dashboard has shown that the hot candidates chosen is smaller than the max we allow (50). This means we compact all hot compaction. I do not think this metrics is needed anymore

![Image](https://user-images.githubusercontent.com/20850014/190718577-067d9550-91b6-4be5-b5d8-6b9c10ba02f1.png)
