### ISSUE TITLE
Compactor metrics: memory usage, time needed to compact a partition

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#5082]
# Rationale

Sine a partition may include a lot of ingested files (may reach over 10K files) and their large total size (20GB), we need to understand how long and how much memory a compaction needs given the input (number of files and their sizes to compact)

Not sure what is the best way to measure this beside writing to the log `(num_input_files, total_input_file_size, runtime, memory_usage)`

**Comment by alamb** [comment]
I recommend in addition to logs, also write "metrics" (maybe as a histogram) to get some sense of how the inputs vary

**Comment by jacobmarble** [comment]
Tracing with 100% sampling might be more helpful than metrics, though metrics are certainly required for dashboards and alerts

**Comment by NGA-TRAN** [comment]
We have added same/similar metrics for this
