### ISSUE TITLE
Select partitions to compact first

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#5105]
# Rationale

Detailed design and implementation for `Selection of partition to compact first` of [Compaction Strategy & Algorithm](https://docs.google.com/document/d/1G4B0YlXyfBx6A_GLXM7FKneu_NE-TuHKkRovpa_XIaI/edit#heading=h.cpiu6bk26nwq)

# Design

This is how a cycle of a compaction looks like

-  For each **sequencer_id** the compactor manages
       - Select  **n** most recent highest ingested throughput partitions (1)
       - In parallel, run **m** `compact a partition` (2), where **m**  <=  **n** and **m** is computed  based on our available memory and the size of the selected partitions.

- For our first version, m = n = 1, which means we will compact everything in serial.

## (1) Select most recent highest ingested throughput partitions:

The below query will be used to select **n** most recent highest ingested throughput partitions. Since we have created an index on `(sequencer_id, compaction_level, to_delete)` this query runs quite fast, around 55ms on 5 or 6 days of data. We will create histogram metrics for this query

```SQL
select partition_id, count(id)
from parquet_file 
where compaction_level = 0 and to_delete is null
    and sequencer_id = seq_id
    and to_timestamp(created_at/1000000000) > now() - interval 'num_hours hour'
group by 1
having count(id) >= num_files
order by 2 DESC
limit n;
```

There are 4 parameters for this query:
- **seq_id**: id of the sequencer we want to compact
- **num_hours**: how much recent we want to measure the throughput. We will start with the last 4 (hours) and if we do not have data back, we will increase it to 24 hours. If still nothing, we will select top **n** partitions with the most level-0 files for that  sequencer and compact them.
- **num_files**: Minimum number of recent ingested files. The default is 2.
- **n**: Number of most recent highest ingested throughput partitions we want to consider to compact in parallel (note that the real number of partitions to run in parallel will be smaller than this value and depending on available memory). The default value is 1 which means we will run only one partition per sequencer in a cycle.

## (2) Compact a partition
See #5106

**Comment by carols10cents** [comment]
> ```sql
> group by 1
> ...
> order by 2 DESC
> ```

What are 1 and 2 here?

**Comment by carols10cents** [comment]
What should be logged when? Are there any metrics other than how long this query takes to run that would be helpful?

**Comment by NGA-TRAN** [comment]
>> ```sql
>> group by 1
>> ...
>> order by 2 DESC
>> ```

> What are 1 and 2 here?

The number after `group by` and `order by` are the order of ones in `select`. 1 means the first in the list which is `partition_id`, 2 means the second which is count(id)

**Comment by NGA-TRAN** [comment]
> What should be logged when? Are there any metrics other than how long this query takes to run that would be helpful?

Good questions. I will log number of candidates chosen per cycle. I may log [sequencer_id, partition_id] for them too. 
What else do you think I should log?
