### ISSUE TITLE
Ingester needs metric for kafka batch size

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#5117]
As part of the disucssions on https://github.com/influxdata/conductor/issues/971 there is a lot of theorizing about how the kafka message size distribution could be affecting the ingester performance

It would be great to add a Histogram metric in the ingester that showed the distribution of kafka message sizes read by the ingester to get more information on this topic

**Comment by crepererum** [comment]
Uh, I'm not entirely sure how to implement this in a nice API. The messages themselves are NOT exposed from rskakfa to API users because the API is kinda higher level. I also would like to avoid using the IOx metrics framework within rskafka because it's IOx specific and nobody else out there uses it. So I see the following ways to make this possible:

- **opentelemetry:** Use the opentelemetry SDK in rskafka (optional dependency) and hook that into the IOx metrics exporter (or does the hook already exists?)
- **return information:** return the stats from rskafka API calls. That's a bit messy because how would this map to the stream consumer that consumes records within a single message?
- **stats callback:** that's what rdkafka is doing. They have some kind of callback that you can pass to the client. We probably need multiple callbacks for multiple stats though (since they are produced at different rates) but overall I think this could work quite well and the API user can do with it whatever they like.

@tustvold any thoughts?

**Comment by alamb** [comment]
I guess I was imagining the of the payloads (rather than the actual messages read from kafka). Aka the same value used to report `write_buffer_bytes_read`: in https://github.com/influxdata/influxdb_iox/blob/main/ingester/src/stream_handler/sink_instrumentation.rs#L163

**Comment by domodwyer** [comment]
The current average payload size across all sequencers is ~2103 bytes, with some variation across sequencers:

![Screenshot 2022-08-04 at 15 16 07](https://user-images.githubusercontent.com/9275968/182856448-e1121a7d-4941-45e5-83e5-bd2aa3281ff0.png)

This is the distribution of average payload sizes over sequencers:

![image](https://user-images.githubusercontent.com/9275968/182859422-ae5bda19-f704-4589-952f-48ac28981e35.png)

Clearly a large majority of average message sizes are <3KiB

<details><summary>
Raw sequencer payload sizes
</summary>

| kafka_partition|avg_payload_size |
|---------------:|:----------------|
|               0|988              |
|               1|2.97KiB          |
|              10|7.73KiB          |
|              11|1.72KiB          |
|              12|2.56KiB          |
|              13|2.86KiB          |
|              14|1.62KiB          |
|              15|1.07KiB          |
|              16|1.24KiB          |
|              17|2.24KiB          |
|              18|1.99KiB          |
|              19|2.49KiB          |
|               2|2.04KiB          |
|              20|1.54KiB          |
|              21|1.22KiB          |
|              22|2.11KiB          |
|              23|1005             |
|              24|1.56KiB          |
|               3|1.38KiB          |
|               4|1.85KiB          |
|               5|1.61KiB          |
|               6|4.38KiB          |
|               7|1.36KiB          |
|               8|1.43KiB          |
|               9|1.15KiB          |
|              50|2.39KiB          |
|              51|1.35KiB          |
|              52|1.97KiB          |
|              53|2.75KiB          |
|              54|1.24KiB          |
|              55|1.15KiB          |
|              56|1.39KiB          |
|              57|1.25KiB          |
|              58|1.34KiB          |
|              59|1.85KiB          |
|              60|2.11KiB          |
|              61|1.24KiB          |
|              62|3.11KiB          |
|              63|1.70KiB          |
|              64|7.92KiB          |
|              65|1.98KiB          |
|              66|1.47KiB          |
|              67|1.24KiB          |
|              68|1.46KiB          |
|              69|1.41KiB          |
|              70|1.37KiB          |
|              71|10.59KiB         |
|              72|1.83KiB          |
|              73|1.59KiB          |
|              74|1.16KiB          |
|              25|5.68KiB          |
|              26|815              |
|              27|1.81KiB          |
|              28|2.36KiB          |
|              29|1.19KiB          |
|              30|1.40KiB          |
|              31|2.98KiB          |
|              32|954              |
|              33|1.17KiB          |
|              34|2.35KiB          |
|              35|1.30KiB          |
|              36|1.80KiB          |
|              37|2.76KiB          |
|              38|4.27KiB          |
|              39|1.33KiB          |
|              40|1.53KiB          |
|              41|1.38KiB          |
|              42|850              |
|              43|4.04KiB          |
|              44|1.52KiB          |
|              45|3.09KiB          |
|              46|2.03KiB          |
|              47|2.02KiB          |
|              48|1.33KiB          |
|              49|3.34KiB          |
|              75|1.52KiB          |
|              76|1.08KiB          |
|              77|1.12KiB          |
|              78|1.49KiB          |
|              79|1.33KiB          |
|              80|2.06KiB          |
|              81|2.37KiB          |
|              82|1.16KiB          |
|              83|960              |
|              84|925              |
|              85|1.12KiB          |
|              86|2.87KiB          |
|              87|1.57KiB          |
|              88|1.19KiB          |
|              89|3.10KiB          |
|              90|1.43KiB          |
|              91|2.03KiB          |
|              92|7.53KiB          |
|              93|1.35KiB          |
|              94|1.82KiB          |
|              95|2.64KiB          |
|              96|1.74KiB          |
|              97|991              |
|              98|924              |
|              99|1.79KiB          |
</details>

This obviously doesn't capture the distribution of payload sizes and I have an _intense_ hatred of `avg()` for stuff like this, but the average does provide some insight in this case as it is so low.

I thought I'd check if this provided enough information to satisfy the theorisation before adding the metric. @alamb I'll wait for a confirmation 👍 

## Summary

Yes, small messages compared to the configured **10MiB max message size**.

**Comment by alamb** [comment]
Thanks @domodwyer  -- I agree that the analysis above helps. 👨‍🍳 👌 

As I recall, the batch size is a parameter of the kafka client (and affects how many payload messages are fetched on each request) 

There was speculation that the max message size for some partitions might be causing issues as well, but I can't really remember.

So in summary, I would say I don't see a compelling reason at this time to justify spending a bunch of time adding new metrics, though I do think a histogram distribution tracking them over time would be useful.

So perhaps we can change this ticket to "Nice to have" priority or something
