### ISSUE TITLE
Given a candidate partition for compaction, gather all parquet files and organize them

### ISSUE THREAD

**Issue by carols10cents** [influxdata/influxdb_iox#5118]
- Get all the files in the partition: `select * from parquet_file where partition_id = $`
  - Use the existing `iox_catalog` [`list_by_partition_not_to_delete` method](https://github.com/influxdata/influxdb_iox/blob/89c24dfec0c3316a7c34306722dc2b9f46e4260f/iox_catalog/src/interface.rs#L548)
- In memory, separate out the files into two collections:
  - L0 files ordered by max_sequence_number asc
  - L1 files (their order isn’t important as they’re non-overlapping)
- Log... the partition ID and the number of files in each collection? Anything else?
- Would the number of files in each collection be a helpful metric? Anything else?

**Comment by NGA-TRAN** [comment]
I do not see any values to log anything here yet

**Comment by carols10cents** [comment]
I think logging how many L1 files are in the collection would help validate our assumption that splitting L1 files into 80% and 20% means that only the 20% is likely to need to be recompacted... if this group often has more than one L1 file, then I think that means something isn't working the way we hoped?

**Comment by NGA-TRAN** [comment]
I agree logging number of L1 files is a good metric as you pointed out. We can do this log inside #5120 instead. Overthere you record number of total L1  and the number of compacting L1. Maybe logging ratio compacting/total more useful? 🤔
