### ISSUE TITLE
Given an organized subset of L0+L1 files, compact into a set of new L1 files

### ISSUE THREAD

**Issue by carols10cents** [influxdata/influxdb_iox#5121]
Given the output of https://github.com/influxdata/influxdb_iox/issues/5120, which should be a collection of parquet files where the L1 files come first and the L0 files come after and the L0 files keep their ordering by sequence number, first:

- Log the partition ID, number (and IDs?) of L0 input files, number (and IDs?) of L1 input files, total size of input files
- Would the number of files of each level and total size make useful metrics too? Anything else?

Then compact the L0 and L1 files into a new set of L1 files with this criteria:

- If the total size of the files is < 30MB: 
  - Write everything into a single L1 file
  - This value is `INFLUXDB_IOX_COMPACTION_PERCENTAGE_MAX_FILE_SIZE * .01 * INFLUXDB_IOX_COMPACTION_MAX_DESIRED_FILE_SIZE_BYTES`, which defaults to `30 * .01 * 100 MB = 30 MB` (needs to be converted to bytes)
- If the total size is > 30MB and < 130MB: 
  - Write 80% of the data into one L1 file and 20% into another, split based on time.
  - Use the min and max times of the files and figure out the 80% point, assume data is roughly evenly distributed.
  - Percentage is `INFLUXDB_IOX_COMPACTION_SPLIT_PERCENTAGE` that defaults to 80
- If the total size is > 130MB: 
  - Determine a split based on time where files of about 100MB are output with some remainder of 10MB or so is left for the last file. 
  - Again the split should be based on time... **wait, how do we convert between approximate size and time? Just start streaming and stop when the file size goes over the limit?**
  - This value is `(1 + INFLUXDB_IOX_COMPACTION_PERCENTAGE_MAX_FILE_SIZE * .01) * INFLUXDB_IOX_COMPACTION_MAX_DESIRED_FILE_SIZE_BYTES`, which defaults to `(1 + 30 * .01) * 100 MB = 130 MB` (needs to be converted to bytes)

After completion of writing all files to object storage:

Within a transaction:

- Create records for all the new L1 files in the catalog
- Mark the input files (both L0 and L1) as to_delete = 't' in the catalog

Then:

- Log successful compaction of partition ID with the number (and IDs?) of new L1 files and the total size of those files 
- Would the number of new L1 files and their total size? Or each size? Make useful metrics?

**Comment by carols10cents** [comment]
I could even see implementing and deploying this in 3 parts-- 99.99% of the partitions will be under that 30MB and that's also the simplest case to implement, so we could do that first then do the more complicated splitting cases.

**Comment by NGA-TRAN** [comment]
>  Given the output of https://github.com/influxdata/influxdb_iox/issues/5120, which should be a collection of parquet files where the L1 files come first and the L0 files come after and the L0 files keep their ordering by sequence number

As mentioned in #5120, you do not need to keep this list sorted at all. The  return value of  the chunk's `order` function (0 for L1 and `max_sequence_number` for L0) is a must and good enough.

> Log the partition ID, number (and IDs?) of L0 input files, number (and IDs?) of L1 input files, total size of input files

Yes. So far I do not see the value of logging the file IDs while playing with log files and they make the log so long.  But if it is helpful for you to debug, it is good to do so.

> Again the split should be based on time... wait, how do we convert between approximate size and time? Just start streaming and stop when the file size goes over the limit?

We actually split the result even before knowing what the result looks like 😄 . The split will be based on input size and assume the input is evenly distributed. Use this compute_split_time function for it https://github.com/influxdata/influxdb_iox/blob/3aef5ac697892250f2e5f87d58f9d17b3053ae88/compactor/src/utils.rs#L259
you can clearly see if the result happens to be a lot smaller (as a result of eliminating a lot of duplicates and/or applying tombstones), we still split it.

If you do not need to split the result, use compact_plan https://github.com/influxdata/influxdb_iox/blob/35dacf388b1bc11ff820351019130bf3c1a677c8/iox_query/src/frontend/reorg.rs#L67

If you have to split the file, use split_plan https://github.com/influxdata/influxdb_iox/blob/35dacf388b1bc11ff820351019130bf3c1a677c8/iox_query/src/frontend/reorg.rs#L140
The  `split_plan` and `compute_split_time` we're recently built/changed for this splitting purpose.

> Would the number of new L1 files and their total size? Or each size? Make useful metrics?

I think so

We also want to have metrics for run time and memory usage for each compaction like this. If you have some ideas do them easily, please do so (in the same or different ticket)

**Comment by carols10cents** [comment]
I think this is all fixed now!
