### ISSUE TITLE
For each partition compaction operation, record metrics for total run time and memory usage

### ISSUE THREAD

**Issue by carols10cents** [influxdata/influxdb_iox#5123]
Extracted from https://github.com/influxdata/influxdb_iox/issues/5121

Once we have a function calling all the pieces that perform a compaction operation for a partition:

> We also want to have metrics for run time and memory usage for each compaction like this. If you have some ideas do them easily, please do so (in the same or different ticket)

**Comment by NGA-TRAN** [comment]
We have recorded metrics for  runtime, compacted file bytes, and estimated memory usage. The general memory usage also shows memory usage at a certain time.

The only thing we miss is memory usage per partition compaction which I do not think we know how to do it and we do not need this anymore. The general memory usage is good enough for us and reported in ticket https://github.com/influxdata/conductor/issues/1075 for our improvement work
