### ISSUE TITLE
Ingester drops more writes than needed when Kafka offset is missing

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#5128]
If the ingester receives a `WriteBufferErrorKind::UnknownSequenceNumber` it concludes that the retention policy may have deleted the data and automatically jumps to the newest entry:

https://github.com/influxdata/influxdb_iox/blob/512f9850ee575c153ebd89ca8f53d7e290f0a410/ingester/src/stream_handler/handler.rs#L242-L263

Kafka (and other write buffers) however have a closed range of known sequence numbers though. The conclusion is only right on the lower end, i.e. if the known range is above the requested sequence number. If the requested sequence number was too new, then this either means we encountered a write buffer bug (e.g. https://github.com/influxdata/rskafka/issues/147 ) or something else is wrong (catalog data is wrong, some manual Kafka operation, ...). In that case we must bubble up the error.

May require https://github.com/influxdata/rskafka/issues/148.

**Comment by jacobmarble** [comment]
Before implementing a fix, please consider matching [the behavior and log message that TSM uses](https://github.com/influxdata/idpe/blob/45701c0f522d3f0211214bfdf439e8979b0f7aee/storage/store/store.go#L689-L697). A Graylog alert checks for this error message, and notifies the team when it is found.

**Comment by jacobmarble** [comment]
Having slept on the subject, I'm satisfied that we should not try to alert on the log. Alert (loudly) on a metric. The data is likely lost forever, but person receiving the page (1) should notify affected customers via support, and (2) might be able to prevent more such errors with config adjustments.

**Comment by crepererum** [comment]
The metrics part now lives in #5321
