### ISSUE TITLE
Design and Implement "Task" resource management system 

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#529]
__Use case:__

One of the IOx's execution system's goals is to (be able to) use many CPU cores, and thus the code uses a unified thread pool (the tokio task pool) and breaks most computations down into many smaller `async` tasks that can be performed on these thread pools. 

There is a need for people operating IOx (e.g. 'operators') and  orchestration systems (like `Conductor`) to:
1.  control how many resources (eg CPU and memory) are spent on various tasks when there is more work to do than resources available
2. . have visibility into the ongoing tasks as well (and the ability to cancel them)

We have previously discussed thread management (see [multi_core_tasks.md](https://github.com/influxdata/influxdb_iox/blob/main/docs/multi_core_tasks.md) but I think IOx is heading more towards a single thread pool rahter than the dual pools described there. 

As IOx starts contemplating more concurrent operations (e.g. query and write to parquet / object store #526) the need to allow the operator to control how many resources are consumed by what type of task becomes greater. 

__Current behaviour:__

The  IOx resource allocation strategy at time of writing is "greedy" -- namely consume as much CPU as possible to complete the task as quickly as possible.  This likely will cause issues when multiple queries are executing as they will contend for CPU as well as using memory for buffers that are waiting for CPU

__Desired behaviour:__
* As an operator of IOx, I want to control how much CPU is allocated across various attributes such as *user*, *organization*,  *query types*, *system tasks*, etc, so that I can control the user experience to match my goals

* As an operator of IOx, I want visibility into the tasks the system is running so I have the information I need to adjust the policy to optimize my resource usage for the outcomes I desire

* As an operator of IOx I want the ability to cancel outstanding tasks so that I can abort long running queries or other operations that are abusing my system. 

Open items:
* If the operator has said "25% CPU for queries, do we allow the system to use more than 25% if there is no contention? The upside of doing so is more efficient resource usage, the downside is that users will experience unpredictable performance (sometimes their query will go faster than others), based on other system usage. 

__Proposal:__
TBD

Definition of done for this ticket is:
* A written design doc with a proposed design (and maybe prototype, etc)
* Follow on tasks filed for the implementation

**Comment by jacobmarble** [comment]
@alamb is this issue still relevant? Can any new issues be linked to it?

**Comment by alamb** [comment]
I think this is fairly well covered by the `Jobs` / `operations` abstraction @tustvold  implemented. Nothing more to do here I agree
