### ISSUE TITLE
Querier Cache: Rework TTL

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#5318]
# Why
Currently [TTL (time-to-live)](https://github.com/influxdata/influxdb_iox/blob/main/cache_system/src/backend/ttl.rs) is used for some caches to enforce "freshness", e.g. we want to renew the namespace schema after a while. The way it is implemented however is the following:

> When we request a certain key from the cache and it is cached, we check its age[^1] and delete it if it is too old.

This archives freshness, however it adds substantial latency to requests since now the key is gone and we need to actively fetch the data again.

Now you may wondering if deletes are not a good thing because they gradually fade out unused data. However time alone is not a reason why data should be uncached. The only reason is resource scarcity / pressure and this is already achieved by the [LRU subsystem](https://github.com/influxdata/influxdb_iox/blob/main/cache_system/src/backend/lru.rs).

# What
Change the TTL system from the current lazy deletion system to some active refresher. A value should be refreshed in certain intervals but while it is being loaded, the existing value should still be available. Refreshing must be stopped when the key is evicted from the cache due to other reasons (e.g. [LRU](https://github.com/influxdata/influxdb_iox/blob/main/cache_system/src/backend/lru.rs) or [predicate-based evictions](https://github.com/influxdata/influxdb_iox/blob/main/cache_system/src/backend/shared.rs)).

# How
Not sure yet, this needs some proper API design so it is easy to understand and use.

[^1]: Actually we check the age of all keys using a heap data structure, but from an observer point of view this doesn't make a difference.

**Comment by alamb** [comment]
> Change the TTL system from the current lazy deletion system to some active refresher.

>  A value should be refreshed in certain intervals but while it is being loaded, the existing value should still be available. 

I think this would be a good first step (rather than expire an entry in the cache and wait for it to be reloaded, instead, cause it to be actively refreshed).

The key will be how to decide which elements to proactively refresh without overwhelming the backend (e.g. catalog)

One thought might be to give each querier a 'proactive refresh' budget like "10 catalog ops / second" and then, among keys that  have not been refreshed within some interval (10s?) pick the ones that were most recently accessed

That heuristic intuition is that cache access is a estimate of how important that value is and the more important a value is the more resource should be spent on keeping it up to date.

**Comment by alamb** [comment]
Another possible thing to consider is prioritize negative hits / errors somehow - like try and refresh more actively cache contents that caused an error (e.g. "Table not found")

**Comment by crepererum** [comment]
The "don't refresh if we don't need to" is a good point, I thought about that as well this morning. I think one approach could be to have two durations:

1. background refresh: if the key gets hit that is older than this initialize a background refresh. The key is considered "old" but not "too old".
2. throw away: if a key gets hit that is older that this then throw it away aka "blocking force-refresh". The content is definitely considered to be too old. This only happens if the key wasn't used for ages, otherwise case 1 would already be triggered.

As a rough estimate for the two durations, we should set (2) to the current TTL and (1) to TTL - "what it takes to refresh and a bit of buffer".

**Comment by alamb** [comment]
I think it is probably good to apply this more sophisticated heuristic to only the data -- we should attempt to cache as much of the catalog as possible (while also trying to ensure it doesn't get stale). The rationale being that the cache is relatively cheap in terms of memory and refreshing it is quite expensive (limited by catalog ops/sc) and uses a global resource 

I think the two durations sounds like a good way to configure this algorithm

I also think it is important to limit the resources (catalog ops) spent on refresh in some way, but maybe that would need a more thoughtful limiting strategy (that also took into account new queries)
