### ISSUE TITLE
Implement path wrapping/handling for object store

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#534]
We need to ensure that paths used in the object store work across any of the different object store implementations and the file system. We'll need something like `PathBuf` but for our paths in object storage. For example, table names are used in the file path, but those names could have characters that aren't legal file system paths. We should clean those and handle joining paths together. There's some discussion of this in #526

**Comment by carols10cents** [comment]
I *believe* this can be closed now. Please reopen if there's still more to do!
