### ISSUE TITLE
EPIC: Implement InfluxQL parser

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb_iox#5353]
In order to process InfluxQL queries in IOx, we require a Rust implementation of an InfluxQL parser. This is a large task and would ideally be broken down into smaller issues to deliver incrementally.

The first step is in choosing an approach, which may be one of the following

* extend the `sqlparser` crate to understand InfluxQL; or
* implement a separate crate to parse InfluxQL. 

Once that is decided, further issues may be created to break down the task into manageable steps.

**Comment by lee3164** [comment]
so, what's the final decision?

**Comment by stuartcarnie** [comment]
Closing this, as the parser is feature complete with respect to the statements we intend to parse. New issues will be created for any improvements.
