### ISSUE TITLE
ci: run cargo check under all cfg variations

### ISSUE THREAD

**Issue by domodwyer** [influxdata/influxdb_iox#537]
__Use case:__
Currently code that is behind a cfg attribute and is not compiled in by default is not checked as part of the CI process, specifically the `test_aws` and `test_gcs` cfgs (others?) in the `object_store`.

__Proposal:__
Until we can run e2e against these stores, we should at least run `cargo check` to ensure the code is valid.

__Current behaviour:__
Code behind the cfg is ignored and not checked for correctness.

__Desired behaviour:__
A CI failure when code in these areas does not compile.

__Alternatives considered:__
Ignoring the problem at the expense of future sanity.

**Comment by domodwyer** [comment]
We discussed this in standup:

* We should try and have at least `cargo check` run to ensure the code at least compiles
* The integration tests should run each night against `main`
* Ideally there would be a way to trigger the integration test suite to run against a specific branch/PR manually at review time
* If at all possible, it'd be nice if the results of this manual run were included in the "merge checks" with the other tests rather than having to direct contributors to some secondary source of truth - not sure how feasible this is though.

**Comment by domodwyer** [comment]
I had a quick go at tackling this - I got it working but it adds quite a bit of runtime to the CI process.

By adding `RUSTFLAGS="--cfg test_gcs"` to `cargo check --workspace --all-targets` it triggers a full rebuild of IOx (or the crate it is run in) and all the dependencies which is a bit annoying.

One alternative is to remove the conditional compilation and to skip the tests if the envs are not set. We can also introduce a "TEST_INTEGRATION_REQUIRED" env that can optionally panic if any of the tests are skipped when we're expecting them not to - this should be fairly doable in a DRY way with some sort of simple macro.

**Comment by jacobmarble** [comment]
@crepererum can this be closed? Looks like you recently added #2595 `cargo audit` to CI, which also runs `cargo fmt`, `cargo lint`, `cargo build`, `cargo test`.

https://github.com/influxdata/influxdb_iox/blob/f650962221bf9fbcce9aedba3c4f73e98e1cb7f6/.circleci/config.yml

**Comment by crepererum** [comment]
No, we still don't run `clippy` for all features (`--all-features` would be the correct flag). As trivial as it sounds to just add this flag, the issue is that we now have mutually exclusive features (for the memory allocator) so that doesn't "just work". So I guess we need to rework our features again to not be mutually exclusive (it's actually somewhat an anti-pattern).

CC @mkmik

**Comment by crepererum** [comment]
I think I might have a solution for it, will file a PR later...
