### ISSUE TITLE
Schema verification error reports column name but not table name: LP parsing layer

### ISSUE THREAD

**Issue by mkmik** [influxdata/influxdb_iox#5407]
Helps with https://github.com/influxdata/conductor/issues/1053
Helps with https://github.com/influxdata/conductor/issues/1021

__Steps to reproduce:__

Minimal actions needed to reproduce the behaviour:

1. write:
```
bar,foo=1 v=1
bar foo=1,v=1
```

__Expected behaviour:__

```
Unable to insert iox::column_type::field::float type into table bar, column foo with type iox::column_type::tag
```

__Actual behaviour:__

```
Unable to insert iox::column_type::field::float type into column foo with type iox::column_type::tag
```

__Context:__

In #5220 we added the column name to the error message. However it's quite common to have many columns with the same names across many tables (measurements). It's very hard to to pinpoint the offending table/measurement if the error message doesn't include it.

___Note:___

https://github.com/influxdata/influxdb_iox/issues/5408 is a similar issue, but in a different layer of the write codepath.

**Comment by jacobmarble** [comment]
I believe this is fixed. Infor was getting 400s and the error logged included the table name.
