### ISSUE TITLE
feat(tracing): propagate tracing span IDs across RPC boundaries

### ISSUE THREAD

**Issue by domodwyer** [influxdata/influxdb_iox#541]
__Use case:__
Distributed request correlation requires propagating the span IDs across the RPC boundaries to allow them to be correlated by the span collector.

__Proposal:__
Propagate spans across boundaries, preferably using whatever mechanisms (i.e. HTTP header key/values, etc) the Go ecosystem uses so it "just works" with all our other components.

__Current behaviour:__
Spans start/stop when a request enters/leaves IOx.

__Desired behaviour:__
Correlated requests - a request from node A should be seen to be connected to node B.

__Alternatives considered:__
Being blissfully unaware of other distributed system components

**Comment by alamb** [comment]
I think go uses the Zap framework:  https://godoc.org/go.uber.org/zap

I spent 10 minutes trying to figure out what HTTP header it used for sending span ids and I am not sure

**Comment by domodwyer** [comment]
Zap is a logging framework and it's not tied nicely with the distributed tracing like in Rust unfortunately! It's a bit more annoying to glue it all together in Go (in my personal experience - maybe I just did it the hard way!)

I imagine the tracing span IDs would be injected by gRPC / HTTP middleware - lets have a quick chat and we can chase it down 👍

**Comment by objectiser** [comment]
Haven't tried it out, but the rust otel sdk includes examples that might be useful: https://github.com/open-telemetry/opentelemetry-rust/tree/master/examples/http and https://github.com/open-telemetry/opentelemetry-rust/tree/master/examples/grpc.

You don't need to be aware of [which HTTP headers need to be propagated.](https://github.com/open-telemetry/opentelemetry-rust/blob/master/examples/http/src/client.rs#L36) - just inject the trace context into the request headers.

**Comment by domodwyer** [comment]
Hey @objectiser thanks for the examples, I hadn't seen them!

Do you know if the OpenTelemetry HTTP header is backwards compatible with the [jaeger client](https://github.com/jaegertracing/jaeger-client-go/blob/9a2c34e98c9fcaeb7f124edf0ed60e072d290414/constants.go#L56-L58)? I'm not sure what our existing components are using.

**Comment by objectiser** [comment]
I know in some of the language SDKs they have added support for the jaeger propagation format, and from [this example](https://github.com/open-telemetry/opentelemetry-rust/tree/master/opentelemetry-jaeger#kitchen-sink-full-configuration) it appears they have in rust.
```
global::set_text_map_propagator(opentelemetry_jaeger::Propagator::new());
```
However I am not a rust developer so can't be sure (but [looks like it](https://github.com/open-telemetry/opentelemetry-rust/blob/master/opentelemetry-jaeger/src/propagator/mod.rs)) - also it would be good if multiple propagators could be added, so making it possible for both the w3c trace context and jaeger (or b3 or ...) to all be supported. Like this [MultiTextMapPropagator](https://github.com/open-telemetry/opentelemetry-java/blob/master/api/context/src/main/java/io/opentelemetry/context/propagation/MultiTextMapPropagator.java) in java. But doesn't look like [rust](https://github.com/open-telemetry/opentelemetry-rust/tree/master/opentelemetry/src/api/propagation) has the same thing.

**Comment by tustvold** [comment]
Superceded by #2273
