### ISSUE TITLE
Throttle Jaeger tracing exporter

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#5446]
# Why
This is related to https://github.com/influxdata/influxdb_iox/issues/5445. We often see that prod drops tracing spans and the Jaeger UDP protocol provides us no way to detect this. We should be a better citizen and not overload Jaeger.

# What
Limit the tracing Jaeger exporter by packages/s and/or bytes/s.

# How
The tracing spans are queued in a bound/limited queue anyways and we even log a warning when the queue is full (we don't block in this case, we just throw away the span). Not sure how to come up with reasonable limits for packages/s and bytes/s though (maybe we find some prod network measure that provides us a useful hint).

**Comment by crepererum** [comment]
Labeling with https://github.com/influxdata/influxdb_iox/labels/Querier since this is the server mode that is mostly affected by this.

**Comment by alamb** [comment]
Yeah, while it is sad that our tracing is limited by the tools to capture it (aka Jaeger) I think we should bow to that reality and reduce the granularity of data produced (and perhaps cry a little in our minds)

**Comment by jacobmarble** [comment]
Are we sampling traces today?

**Comment by alamb** [comment]
I think there are certain spans that are one per parquet file (not quite per record batch)

**Comment by crepererum** [comment]
The querier produces spawns mostly during two phases:

- **planning:** We have spawns for every cache request. The finest granularity is per chunk (= per parquet file).
- **execution:** Here we follow the DF physical plan (for SQL you may retreive this via `EXPLAIN SELECT ...`). The granularity may be per parquet file, but in most cases its coarser.

**Comment by wolffcm** [comment]
What determines the number of parquet files, does it depend on how much compaction has had a chance to combine them?

It seems like we could get most of the same information by logging multiple events in the same span vs creating new spans. (though it may be less digestible)

**Comment by alamb** [comment]
> What determines the number of parquet files, does it depend on how much compaction has had a chance to combine them?

Yes -- and the time range over which there is data (there is at least 1 parquet file per day of data that was loaded)

**Comment by crepererum** [comment]
> It seems like we could get most of the same information by logging multiple events in the same span vs creating new spans. (though it may be less digestible)

That assumes that "the number of files" is the information we're looking for, which is incomplete. Every file results in cache requests to the querier internal data structures and they are reflected by the traces.

Also I'm somewhat hesitant to build half-baked trace aggregation into IOx to selectively work around apparent weaknesses of the Jaeger protocol. It's a code mess and I don't wanna maintain it. I would instead rather apply client side throttling (spans are colłected into a size-limited submission buffer already) or(even better) move us to the open telemetry grpc protocol for submission where the client actually gets a signal for server overloads.
