### ISSUE TITLE
style: decide on project style for coercing &str into String

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb_iox#553]
(This issue seems somewhat limited and pedantic but I think it's an interesting test issue for the wider point of "how do we programatically enforce any coding-style we might want in the project).

There are a few ways you can take a borrowed `&str` or string literal and create an allocated `String`.

```rust
"foo".into()

"foo".to_string()

"foo".to_owned()

String::from("foo")
```

Whilst it was not always the case (please correct me if I'm wrong @carols10cents / @shepmaster) as of today these all basically perform the same in Rust. I think in fact several of them end up calling one of the other alternatives. E.g., `to_string` calls `String::from` calls `to_owned`.

Implementation-wise it doesn't matter too much which we call, but I think from a consistency point of view I think it could be confusing for people starting on Rust or the project. 

Therefore I propose that where possible (which I _think_ is always?) we use `.to_owned` when converting from `str` to `String`. I like `to_owned` because it clearly describes what's happening. 

Assuming we agree to care about this the next steps are:

- [ ] decide on choice of method.
- [ ] update style guide
- [ ] replace instances in project with the blessed method.

My only concern with this is that it's not something that's worth investing cognitive load in (via reviewing) because fundamentally there is no difference in correctness or performance between the approaches, so ideally this is something we would have a clippy/style lint for. I have no idea if you can have custom clippy lints for example.

**Comment by carols10cents** [comment]
There is this clippy lint! https://rust-lang.github.io/rust-clippy/master/index.html#str_to_string

**Comment by alamb** [comment]
I think the consensus is 

“If clippy can do it, then do whatever clippy can enforce” -- so like @carols10cents said

**Comment by domodwyer** [comment]
So I actually started running this lint and got:

![image](https://user-images.githubusercontent.com/9275968/102387588-77bfce00-3fc8-11eb-9eb7-5a627553a86b.png)

🤷

**Comment by carols10cents** [comment]
WHO LINTS THE LINTERS

**Comment by carols10cents** [comment]
It looks like `str_to_string` [was readded in Rust 1.50](https://github.com/rust-lang/rust-clippy/pull/6333) (relevant discussion [in this issue](https://github.com/rust-lang/rust-clippy/issues/5610) if you're interested) so we could turn that on and fix the problems in all the crates (someday, https://github.com/rust-lang/cargo/issues/5034, someday I will get to you)

**Comment by e-dard** [comment]
I started to introduce these lints in #3597
