### ISSUE TITLE
InfluxQL: Implement statement parsers

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb_iox#5633]
Teach the InfluxQL parser how to parse the following statements, which are supported in Cloud 2

### Schema exploration 

See #5643 

- [x] `SHOW DATABASES`
- [x] `SHOW MEASUREMENTS`
- [x] `SHOW RETENTION POLICIES`
- [x] `SHOW TAG KEYS`
- [x] `SHOW TAG VALUES`
- [x] `SHOW FIELD KEYS`

### Data query

See #5692

- [x] `SELECT`

### DML Statements

See #5656

- [x] `DELETE` to delete series
- [x] `DROP MEASUREMENT`

### Debugging statements

See #5763

InfluxQL supports `EXPLAIN` statements. The output is not documented, so we can leverage the existing DataFusion `EXPLAIN` output:

- [x] `EXPLAIN`
- [x] `EXPLAIN ANALYZE`

This is not supported by InfluxQL but is worth adding:

- [x] `EXPLAIN VERBOSE`
- [x] `EXPLAIN ANALYZE VERBOSE`

**Comment by NGA-TRAN** [comment]
All nice syntax.
Question: Is this ticket is to `parse the statement` only or to `parse and run them to return to results`?

**Comment by stuartcarnie** [comment]
@NGA-TRAN this is only to develop the parser and parse the statements. Future issues will be created to define how we'll transform these ASTs into a logical plan that can be executed by DataFusion.
