### ISSUE TITLE
Trace querier->ingester requests

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#5723]
# What
Propagate tracing through querier->ingester requests.

# Why
Let's figure out why the ingester requests are so slow. Also see #5722.

# How
Tracing spans are already propagated down. They just need to flow through the InfluxDB IOx client.

**Comment by carols10cents** [comment]
Could you elaborate a bit on this? What sort of work needs to be done, exactly? How can I tell/test that I've done what you need successfully?

**Comment by crepererum** [comment]
This span here:

https://github.com/influxdata/influxdb_iox/blob/42b89ade030c623283618af7ea85f53796dd04f5/querier/src/ingester/mod.rs#L400

exists on the querier side. However it is NOT sent over the wire to the ingester and the ingester currently creates no tracing span based on that. This makes it pretty hard to judge where exactly we spend time in this interaction.

So first the span (or a child of it) needs to be passed into this method here:

https://github.com/influxdata/influxdb_iox/blob/42b89ade030c623283618af7ea85f53796dd04f5/querier/src/ingester/mod.rs#L421

and the flight implementation needs to send it over the wire. We already do this for our CLI client:

https://github.com/influxdata/influxdb_iox/blob/3b97b364b262a666fafd5da3956b41ebcb60fc45/influxdb_iox/src/main.rs#L227-L238

However we don't do that for the in-querier flight client yet. Also note that the CLI sets the trace ID once for the whole connection (because the CLI only uses the connection once), but the querier should set the trace ID for every request. So this might need a different code path.

On the ingester side, the context can be pulled out from our middleware using something like:

https://github.com/influxdata/influxdb_iox/blob/3b97b364b262a666fafd5da3956b41ebcb60fc45/service_grpc_flight/src/lib.rs#L232-L232

Then it should use `SpanRecorder` to create recorders and children, all the way down to 

https://github.com/influxdata/influxdb_iox/blob/3b97b364b262a666fafd5da3956b41ebcb60fc45/ingester/src/querier_handler.rs#L291-L291

Writing tests for this is hard and I advice to just use a local `Jaeger` instance and a querier and ingester (I think you can use the all-in-one mode as well):

1. Start jaeger:
   
   ```console
   $ podman run -it --rm -p 6831:6831/udp -p 16686:16686 jaegertracing/all-in-one
   ```

2. Run IOx:

   ```console
   $ cargo run -- run all-in-one --catalog-dsn 'postgres://...' --data-dir '...' --traces-exporter jaeger
   ```

3. Issue a query w/ tracing enabled:

   ```console
   $ cargo run -- query xxxx_zzzz "select count(*) from foo" --gen-trace-id
   ```

4. Visit jaeger (<http://localhost:16686/>) and see if you one trace tree that contains both the querier and the ingester part.

5. Ask @crepererum if you have questions.
