### ISSUE TITLE
feat: Implement Chunks in the Mutable Buffer (previously Write Buffer)

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#579]
Goal is to allow IOx to switch ingested parts of data into a read-only area in preparation for writing to object store and turn into read buffer.

Right now as data comes into the mutable buffer, it is appended into mutable in-memory structures. At some point this structure needs to be "frozen" (read only), so that it can be written in an optimized form to parquet / objectstore as well as the ReadBuffer (previously named Segment Store)

### Roll current mutable chunk --> immutable chunk for a partition

* If any new data comes in to this partition creates a new mutable chunk

* queries should read both mutable and immutable chunks across for partition

### Drop immutable chunk from a partition

After some other process has orchestrated writing the data from the chunk into object store / read buffer it will call the "drop" API

The chunk will be freed from memory and if there are no remaining chunks in a partition (either mutable or immutable) then all structures related to that partition itself in the write buffer will also be freed.

### Immutable Chunks details

When an immutable chunk is created, it gets an 
* ID
*  timestamp (at which it became immutable)
* writer id of the writer that created it (??) TBD

**Comment by alamb** [comment]
FYI @pauldix  -- is this what you had in mind for Chunk support in the MutableBuffer (write buffer)?

**Comment by pauldix** [comment]
I would say that a `chunk` should have a `created_at` time, which is the time of the first write it receives. Then it should have a `locked_at` time, which would be when it gets converted to be immutable. The `id` should be a `u64` and every chunk should have it (so even the mutable one).

Great to have the `writer_id` and the `partition_key` as metadata for the immutable chunk, but that will be part of the path in object store, so might not need that as a member on the chunk struct.

👍 on rollover and drop of the chunk.
