### ISSUE TITLE
Explicitly push projection down to scan plan & operator

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#5816]
This is a task of #5751 . Currently, we let DataFusion plan to discover which columns to read and push them down the scan. WIth the need of Querier to tell Ingesters which columns to return, we now know ahead which columns we need and we want to tell the scan earlier for that and make it stay that way

**Comment by crepererum** [comment]
How is this different from #5624?

**Comment by NGA-TRAN** [comment]
This is specific to query plan. We let DF to push projection downs with the columns in the query. We may do this earlier. I happened to run into this while exploring the code. I will have a specific link for this when I work on this. I  may end of not doing anything if I discover it was pushed down early enough

**Comment by NGA-TRAN** [comment]
It turns out we should not push this down prior to deduplication because we need all columns
