### ISSUE TITLE
Make IOx run "out of the box" -- Provide a default value for the server write id

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#587]
__Use case:__
I am a new developer  to InfluxDB IOx and I want to give it a try locally in my development environment. At the moment, I need to know to set INFLUXDB_IOX_ID environment variable otherwise I will get errors about "server id not set". It would be nice to run `influxdb_iox` in some configuration that works "out of the box"

__Proposal:__
If the server id is not provided, default it to a recognizeable known value, for example 1337  

__Current behaviour:__
If you run `influxdb_iox` and then try to write data via the `/api/v2/write` endpoint, you get the following error:

```
Dec 21 08:46:43.468 ERROR influxdb_iox::server::http_routes: Error while handling request error=WritingPoints { org: "26f7e5a4b7be365b", bucket_name: "917b97a92e883afc", source: IdNotSet } error_message="Internal error writing points into org 26f7e5a4b7be365b, bucket 917b97a92e883afc:  unable to use server until id is set" method=POST uri=/api/v2/write?bucket=917b97a92e883afc&org=26f7e5a4b7be365b
```

In order to have iox work, you need to provide a writer id via the  `INFLUXDB_IOX_ID` environment variable. For example `INFLUXDB_IOX_ID=1 ./influxdb_iox`

__Desired behaviour:__
Running `./influxdb_iox` works without any modification

__Alternatives considered:__
If there is danger in using a default in a production setting, we could consider adding a config file that defines things like writer_id and then check a default config file into the source tree that will be found by default

**Comment by tustvold** [comment]
I believe this functionality is provided by --server-id CLI option
