### ISSUE TITLE
CLI Command to fetch all parquet files for a table

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#5967]
__Use case:__
I want to more easily be able to copy the parquet files for a table from our production cluster locally for reproduction. 

Currently I can fetch individual files using the `influxdb_iox remote store get <UUID>` command but there is no way to download but I need to know the UUID to use this

To find the UUID I need to go poke in the postgres catalog 

__Proposal:__
I would really like a command that worked like this

```shell
# fetch all files from the database 12345_6788 and table 'sensors' to the directory named sensors
influxdb_iox remote store get-table 12345_6788 'sensors'
```

After running this command, I would expect to see a directory like this with the relevant files

```shell
$ ls -l sensors/
total 3376
-rw-r--r--  1 alamb  staff   6.7K Oct 24 13:40 28bf025a-5175-408d-a380-18c4358844b6.parquet
-rw-r--r--  1 alamb  staff   258K Oct 24 13:40 4fd5f739-b76c-42bf-9635-98da4ae209a7.parquet
-rw-r--r--  1 alamb  staff   376K Oct 24 13:40 67798467-9b72-43f2-8980-cab0f7b853ff.parquet
-rw-r--r--  1 alamb  staff   332K Oct 24 13:40 8e6887cb-6b0a-4487-8531-c61d555ccbff.parquet
-rw-r--r--  1 alamb  staff   604K Oct 24 13:40 efad01a2-f510-47b4-ae6e-613485478ce3.parquet
```

Bonus points:
- [ ] Allow the output directory to be specified (`influxdb_iox remote store get-table 12345_6788 'sensors' -o output_directory`)
- [ ] Add the partition_id in the file names  (`<UUID>`.`<PARTITION_ID>`.`parquet`)
- [ ] Support incremental downloads / restarting (check to see if the parquet file already exists with the correct size and skip downloading it if so)
- [ ] Support streaming file reads (right now all data is buffered in memory)
 

I think this would be a matter of:
- [ ] Extending the catalog service so it could provide information on a table (like what parquet files are there)
- [ ] Adding the new cli command to use the new catalog service and existing remote service

**Comment by pauldix** [comment]
You can do this with an individual partition already. Look at `remove partition`.  You should be able to specify the namespace, table name, and partition key (e.g. 2022-10-27) and the local catalog DSN (Postgres running on your laptop) and object store info (your local filesystem).

**Comment by alamb** [comment]
@pauldix  yes in fact that is what I was doing -- however it is quite tedious (I found) to form the required posgres query to figure out the correct parquet uuids took some annoying scripting.

@carols10cents  has built on your great `remote partition` work to basically build the scripting into the CLI (it still uses the same gRPC service under the covers)

**Comment by carols10cents** [comment]
Yup, I did see `remote partition`, however, I didn't use it directly because it did different things than what @alamb asked for here. I do think we could unify:

- `remote partition pull` (specify namespace, table, partition key to get parquet files and catalog entries)
- `remote store get` (specify a parquet file UUID and get only that file)
- `remote store get-table` (specify namespace and table and get only the parquet files)

but I wasn't sure exactly which commands should stay and with what behavior, so I got @alamb what he needed first and I'll open a new issue for reorganizing.

**Comment by alamb** [comment]
My first major usecase is to Get parquet files for a table locally so that I can:

1. inspect them locally (e.g. convert them to line protocol)
2. test out how datafusion-cli works with them
3. Reload them into other IOx instances (e.g. my perf instance) to test write path or compaction

This is what `remote store get-table` gets me. However, all the data needs to go through the "front door" (and the ingester and compactor)

A second similar usecase is to import the data into IOx in the same physical layout (e.g. the actual parquet file layout) which is what `remote partition pull` I think was meant to handle.

I haven't used this much because I want that data in a transportable way -- like I can easily reload into my iox all in one local instance.

So in order to use `remote partition pull` I would really want it in two parts;

```shell
# Save whatever metadata and parquet files are needed for a partition or table into `data.zip`
influxdb_iox remote table save data.zip
```

And then a corresponding

```shell
# Load the table  and parquet files from `data.zip` into the catalog and object store
influxdb_iox remote table load data.zip
```
