### ISSUE TITLE
Enable write buffer ZSTD compression

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#5981]
Enable ZSTD compression for the write buffer.

While doing so, please disable the rskafka `snappy` feature since this is unused and all other cluster no longer have snappy-compressed data in them.

**Comment by crepererum** [comment]
This is currently blocked by some experiments we perform but shall be done afterwards.

**Comment by cannonpalms** [comment]
@crepererum What is blocking this? I would like to pick it up to improve WAL performance during replay.
