### ISSUE TITLE
metrics name's character duplicate

### ISSUE THREAD

**Issue by aierui** [influxdata/influxdb_iox#5995]
Definition of metrics. 
https://github.com/influxdata/influxdb_iox/blob/4f031b4abde3e835dfc164c339f4e68b173298b1/router/src/server/http.rs#L253-L279
The export will also splice in a fixed suffix.
https://github.com/influxdata/influxdb_iox/blob/4f031b4abde3e835dfc164c339f4e68b173298b1/metric_exporters/src/lib.rs#L61-L70

__Steps to reproduce:__
List the minimal actions needed to reproduce the behaviour.

1.  step up server
2.  curl 'http://127.0.0.1:8080/metrics'
3. ...

__Expected behaviour:__
```log
...
# TYPE http_write_body_bytes_total_total counter
http_write_body_bytes_total 2907520224
# HELP http_write_fields_total_total cumulative number of line protocol fields successfully routed
# TYPE http_write_fields_total_total counter
http_write_fields_total 25960002'
...
```

__Actual behaviour:__

```log
...
# TYPE http_write_body_bytes_total_total counter
http_write_body_bytes_total_total 2907520224
# HELP http_write_fields_total_total cumulative number of line protocol fields successfully routed
# TYPE http_write_fields_total_total counter
http_write_fields_total_total 25960002
# HELP http_write_lines_total_total cumulative number of line protocol lines successfully routed
# TYPE http_write_lines_total_total counter
http_write_lines_total_total 25960002
# HELP http_write_tables_total_total cumulative number of tables in each write request
# TYPE http_write_tables_total_total counter
http_write_tables_total_total 25960
...
```

**Comment by domodwyer** [comment]
Doh!

Thanks for reporting - if you fancy submitting a PR @ me and I'll happily review :)

**Comment by aierui** [comment]
No problem, I'll do it.
