### ISSUE TITLE
Add new field into catalog tables namespace & partition

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#6022]
# Rationale 

As a task of #3053, we need to add `retention_period_nano` into `namespace` table and `to_delete` to `partition` table. Both will be default NULL. Let us do this first and ensure everything runs nicely before setting data for them.

**Comment by alamb** [comment]
What would you think about calling this `retention_period_ns` to use the standard nanosecond abbreviation of `ns`?

**Comment by NGA-TRAN** [comment]
`retention_period_ns` sounds good @alamb

**Comment by lukebond** [comment]
should we remove `retention_duration` to avoid confusion?

**Comment by alamb** [comment]
> should we remove retention_duration to avoid confusion? i'll create a ticket if so, and do it before https://github.com/influxdata/influxdb_iox/issues/6024 and https://github.com/influxdata/influxdb_iox/issues/6025

Yes, I think so - @NGA-TRAN  mentioned something similar on https://github.com/influxdata/influxdb_iox/pull/6041#discussion_r1014452466
