### ISSUE TITLE
Support gRPC for setting its retention period

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#6023]
# Rationale

This is a task of #3053 and should be done after #6022 to provide 2 gRPCs:

1. Create name space with a specified hours of data retention

```shell
influxdb_iox namespace create <namespace_name> <num_hours>
```

2. Modify retention hours of a give namespace 

```shell
influxdb_iox namespace retention <namespace_name> <num_hours>
```
'num_hours` is an integer number >=0.  We will convert this num_hours into nanoseconds and record it into the `retention_period_nano` field of the `namespace` table.

If num_hours is 0, we will record `retention_period_nano`  as NULL to say it is infinite.

This task also:
- creates a default configuration parameter INFLUXDB_IOX_RETENTION_HOURS at set it to 0 which means infinite.
- modifies the current create namespace in Router (or Ingester?) to use NFLUXDB_IOX_RETENTION_HOURS to set the value of the namespace `retention_period_nano`

**Comment by alamb** [comment]
I think you can extend the existing schema gROC service with the necessary commands:

https://github.com/influxdata/influxdb_iox/blob/main/service_grpc_schema/src/lib.rs

Maybe it would be good to move the `influxdb_iox debug namespace` command into `influxdb_iox namespace` and then add the new `create` and `retention` subcommands there

**Comment by NGA-TRAN** [comment]
@alamb Good point. Let me move `influxdb_iox debug namespace` command into `influxdb_iox namespace`

**Comment by NGA-TRAN** [comment]
Since creating a namespace must provide its topic and query pool which will likely change in the future. I will create a different tickets to do that
