### ISSUE TITLE
Add config param for when to do cold compaction on partition

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#6038]
# Rationale

Currently we hard code 8 as the num of hours without new writes before we start doing cold compaction on that partition. Let us make it config param so we can change it easily.

Thought: do we also want to create config params for when we do hot compaction? Currently we hard code within 4 hours and then 24 hours

**Comment by alamb** [comment]
> Thought: do we also want to create config params for when we do hot compaction? Currently we hard code within 4 hours and then 24 hours

I think a config parameter for hot compactions would also be very useful for testing 🙏
