### ISSUE TITLE
Add config param for when to do hot compaction on a partition

### ISSUE THREAD

**Issue by lukebond** [influxdata/influxdb_iox#6059]
See also #6038

Currently the number of hours before doing hot compactions is hardcoded. Make it configurable.

**Comment by NGA-TRAN** [comment]
Currently we hardcode 4 and 24 hours here https://github.com/influxdata/influxdb_iox/blob/ba53e71935c29043ba789015064bfce98553bbe2/compactor/src/hot.rs#L194

We want to define those parameters here https://github.com/influxdata/influxdb_iox/blob/ba53e71935c29043ba789015064bfce98553bbe2/clap_blocks/src/compactor.rs#L8 and use in above function instead
