### ISSUE TITLE
Limit number of files to compact per partition even if we have budget to do more

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#6091]
# Rationale

Currently, we have this config param `INFLUXDB_IOX_COMPACTION_MAX_COMPACTING_FILES` that limits the number of files to compact to avoid OOM. If the minimum number of overlapped files  exceed that number, we put its partition into the `skipped_compactions` table to avoid considering it again.

Recently, since we improve our memory usage, we are able to increase that limit to have the compact to compact many files at once. However, it seems to me from the compactor dashboard https://grafana.prod01-eu-central-1.aws.influxdata.io/d/z7-FhLsnk/compactor?orgId=1, compacting 20 files at once may not be faster than compacting them twice 10 files each. 

This ticket is to create a different limit, INFLUXDB_IOX_COMPACTION_MAX_COMPACTING_FILES_PER_PARTITION, to limit number of files per partition even if we have more resource to do more. With this support, we will compact a smaller number of files per partition (which I predict DF handles better) but we will concurrently compact more partitions.

**Comment by NGA-TRAN** [comment]
@lukebond : this will need changes in the center of the compactor code. Maybe eve some refactor

**Comment by lukebond** [comment]
Clarifying information after speaking to Nga offline:

Currently max_num_compacting_files do 2 things:

1. Limit number of files a partition gets compacted at a time
1. If the minimum number of overlapped L0 and L1 files exceed that limit, we put that partition into the skipped_compactions and no longer compact that partition.

We want to separate those 2 and the ticket is to create a way to do so. We will use the existing param for item 2, and create a new param for item 1

**Comment by lukebond** [comment]
After a chat with Nga offline:

- the main issue this ticket is aiming to address is when the first L0 file for a partition plus its overlapping L1 files overshoots the `max_num_compacting_files` limit and gets skipped
- if this limit is hit on the first L0 file, we should just do it anyway, as long as it fits in memory
- in that case, we shouldn't take any more files for this partition
