### ISSUE TITLE
More efficient IOx scans with overlapping files/ingester data (rework physical plan construction)

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#6098]
# What
Update 2023-01-27: the way we create physical nodes leads to plans that refer to many parquet files to use too much memory than we have, leading to OOMs and other bad behavior. 

Currently we create physical nodes out of `QueryChunk`s in an imperative style to hopefully produce some optimal (or at least: not horrible) physical plan. Instead I would rather construct an naive plan and use optimizer passes to improve them.

# Why
The current code is:
- deeply-if-nested imperative code and hard to understand
- debug (no intermediate steps visible)
- it's unclear how well it plays with the remaining DF optimization framework
- hard to extend (see #6028)

# How

## Naive Plan
Produce a plan like this:

```text
         +------------+
         | FilterExec |
         +------------+
                ^
                |
          +----------+
          | SortExec |
          +----------+
                ^
                |
       +-----------------+
       | DeduplicateExec |
       +-----------------+
                ^
                |
   +-------------------------+
   | SortPreservingMergeExec |
   +-------------------------+
                ^
                |
          +-----------+
          | UnionExec |
          +-----------+
                ^
                |
      +---------+-------+---------------...
      |                 |
 +----------+      +----------+
 | SortExec |      | SortExec |         ...
 +----------+      +----------+
      ^                  ^
      |                  |
+-------------+  +-------------------+
| ParquetExec |  | RecordBatchesExec |  ...
+-------------+  +-------------------+
```

It is important that the plan is technically correct and easy to understand. All easy optimization like predicate pushdown or sort elimination should be modeled as optimizer passes!

## Optimizer Passes
TODO

**Comment by alamb** [comment]
I think this is a great idea in the long run. I am not sure how critical it is in the short term

Other than possibly easier to maintain code, we might also be able to parallelize the plan better (aka repartition the data into disjoin partitions and do deduplication in parallel, for example)

 @mingmwang is introducing a pass that has similarities in DataFusion  https://github.com/apache/arrow-datafusion/pull/4122

Brainstorm: in order to pull off this design we would perhaps need optimizer passs that knew
1.  how/when to push deduplicate through sort preserving merge (probably can't without partitioning)
2. How to eliminate redundant sorts 
3. How to add repatitioning without destrying the sort order

**Comment by crepererum** [comment]
Another weirdness of the current phys. plan construction is that we don't emit subtrees for every single chunk that has a delete predicate instead of grouping them together (where possible).

**Comment by alamb** [comment]
Update here is that @crepererum  and I think this is a bit more than "tech debt" at the moment, and this would be the mechanism to better support handling large (100+) parquet files 
-- e.g. https://github.com/influxdata/idpe/issues/16768#issuecomment-1387056833 )

Not only would this help query performance, it would also likely help compactor and avoid OOMs that we see with high fanout in the compactor sometimes

**Comment by alamb** [comment]
I think it is also important to point out that the datafusion optimizer has gotten significantly better (and sort and partition aware) since we were first creating physical plans, so we can probably avoid a bunch of the complexity in the exisiting design

**Comment by alamb** [comment]
I am pretty sure I saw another example where this was causing issues (basically making queries against the leading edge of data be slower than it needed to be because already sorted parquet data was being resorted). See https://github.com/influxdata/idpe/issues/17128#issuecomment-1424401983

**Comment by alamb** [comment]
I believe we also think the current plan construction technique is causing the compactor to use more memory than required exacerbating OOMs under load

**Comment by alamb** [comment]
https://github.com/apache/arrow-datafusion/pull/5419 is merged, and I have a PR to get it into IOx: https://github.com/influxdata/influxdb_iox/pull/7100
