### ISSUE TITLE
Put a cap on number of files for the minimal must-compact number of files

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#6157]
# Rationale

With recent change https://github.com/influxdata/influxdb_iox/pull/6144#event-7822870930, we do not cap the max number of files for the first/minimal number of files to compact but only rely on memory cap. We soon hit OOM and the investigation shows the memory needs actually can be very small https://influxdata.slack.com/archives/C040Z1T53RB/p1668624115812019. I think we need to cap number of files for this case, too.

@lukebond Maybe you and I should brainstorm on this

We want this code to increase this temporarily settings which are too low
https://github.com/influxdata/k8s-idpe/pull/13786

**Comment by NGA-TRAN** [comment]
Let us go over this to discuss why we need a cap for this

```SQL
SELECT shard_index, table_id, partition_id, partition_key, left(reason, 25),
  num_files, limit_num_files, estimated_bytes, limit_bytes, to_timestamp(skipped_at) skipped_at
FROM skipped_compactions, partition, shard
WHERE partition.id = skipped_compactions.partition_id and partition.shard_id = shard.id
   and table_id not in (42, 188)
ORDER BY skipped_at desc;
 shard_index | table_id | partition_id | partition_key |      left      | num_files | limit_num_files | estimated_bytes | limit_bytes |    skipped_at
-------------+----------+--------------+---------------+---------------------------+-----------+-----------------+-----------------+-------------+------------------------
     59 |    22 |   19233159 | 2022-11-12  | over limit of num_files  |    45 |       40 |   3773528272 | 32212254720 | 2022-11-14 10:27:32+00
     52 |    32 |   19233158 | 2022-11-12  | over limit of num_files  |    41 |       40 |   3498023096 | 32212254720 | 2022-11-14 10:27:32+00
     59 |    22 |   13711168 | 2022-11-07  | over limit of num_files  |    64 |       40 |   1338558970 | 32212254720 | 2022-11-07 22:09:18+00
     52 |    32 |   13710553 | 2022-11-07  | over limit of num_files  |    63 |       40 |   1463606446 | 32212254720 | 2022-11-07 22:07:08+00
```

**Comment by lukebond** [comment]
if i'm reading this correctly, we had a few examples of this feature compacting 60+ files and needing very little memory (and wasn't the culprit of the OOMs). but you think it's prudent to have a limit regardless?

if so i would guess around `80` might be a good limit. what do you think?

**Comment by NGA-TRAN** [comment]
@lukebond Yes, we have examples to show that we are able to compact hundreds of files of a partition but it also depends on how many of partitions in parallel. The estimation can be brittle in certain combination that we are not clear yet.

The idea is we want to use the current config params to control the OOMs if they happen. However, the SQL on `skipped_compactions` above shows that the number of file can be a lot (hundreds or even more) and their estimated  memory is still small. If OOMs happen because of that, the only way today for us adjust the config params is the reduce `INFLUXDB_IOX_COMPACTION_MEMORY_BUDGET_BYTES` a lot and increase `INFLUXDB_IOX_COMPACTION_MIN_ROWS_PER_RECORD_BATCH_TO_PLAN` a lot at the same time. This will lead to the consequence that we won't be able to compact a lot of partitions (and they will end up in skipped_comapctions) and reduce the concurrency level, too.

To avoid adjust the to config params above, we want to create one more config param to cap this case. 80 sounds good but if you want observe it, I think we can make it the same as `INFLUXDB_IOX_COMPACTION_MAX_COMPACTING_FILES` (40 today?) to keep the same behavior over the weekend. Next week, we increase it (to 80 to lower) and see
