### ISSUE TITLE
Feature request: Implement a Sqlite backed catalog

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#6169]
__Use case:__

1. I create a reproducer using non trivial amounts of data and/or steps on a local IOx instance (either for performance or for a crash issue)
2. I want to be able to change the code, recompile and test out fixes / changes locally (which may potentially change the catalog) without having to recreate the reproducer again

I also want to share the database in the broken state with another engineer so they can help debug whatever problem I am having.

# Context:

While working on https://github.com/influxdata/idpe/issues/16485 -- see the complicated reproducer setup in https://github.com/influxdata/idpe/issues/16485#issuecomment-1318746719

There are similar, hard to follow repro instructions on https://github.com/influxdata/idpe/issues/16298#issue-1427259604

__Proposal:__

Instead I would like to be able to run IOx against a sqlite file backed database which can be trivally moved from computer to computer

__Current behaviour:__
Technically I can save the database state today with local postgres instance and/or a docker image. However, doing so is cumbersome.

```shell
INFLUXDB_IOX_CATALOG_DSN=postgres://postgres@localhost:5432/postgres influxdb_iox
```

__Desired behaviour:__
We already use https://docs.rs/sqlx/latest/sqlx/ in iox

Currently we use the postgres driver: https://docs.rs/sqlx/latest/sqlx/postgres/index.html

sqlx  has a sqlite driver: https://docs.rs/sqlx/latest/sqlx/sqlite/index.html 

So I would like to be able to start iox like:

```shell
INFLUXDB_IOX_CATALOG_DSN=sqlite://data.db influxdb_iox run ingester
```

And have it use the sqlite database in `data.db`

https://docs.rs/sqlx/latest/sqlx/sqlite/struct.SqliteConnectOptions.html

__Alternatives considered:__

There are other potential ways of doing this (for example a of save/restore tool that extracts relevant entities from the catalog and object store into local files).

I don't see the two as mutually exclusive -- eventually it would be awesome to use sqlite as the format for the relevant catalog entities in a dump, for example

**Comment by aierui** [comment]
MySQL may also be an option.

**Comment by alamb** [comment]
I agree @aierui -- however, I think it is pretty similar to postgres in the sense that it isn't directly designed to be a single file you can transport between systems

**Comment by madgene** [comment]
I have completed the sqlite backend catalog recently. A pull request will be opened when I have the time.

**Comment by alamb** [comment]
Thanks @madgene  -- I look forward to checking it out!

**Comment by mkmik** [comment]
SQLite+litestream ❤️

**Comment by damageboy** [comment]
Just out of curiosity, @alamb, the way you see this is that two catalog impls live side by side in the code, and the user basically decides which get triggered according to the prefix of the DSN?

e.g. `INFLUXDB_IOX_CATALOG_DSN=sqlite://...` vs. `INFLUXDB_IOX_CATALOG_DSN=postgres://...` is the discriminator?

**Comment by alamb** [comment]
> Just out of curiosity, @alamb, the way you see this is that two catalog impls live side by side in the code, and the user basically decides which get triggered according to the prefix of the DSN?

That is an interesting idea @damageboy 

I was actually thinking they would specify via the INFLUXDB_IOX_CATALOG_TYPE config alue https://github.com/influxdata/influxdb_iox/blob/b20226797af41cd25299aa9090f5b1cff4f7c94a/clap_blocks/src/catalog_dsn.rs#L49-L57

But the DSN is probably a better idea
