### ISSUE TITLE
Proposal: "warm" mode for compactor

### ISSUE THREAD

**Issue by lukebond** [influxdata/influxdb_iox#6179]
# Background

Currently the compactor has two modes:

1. "hot" - finds partitions with recently-written L0 files and compacts as many of those files L1 files that it can do in the memory budget
2. "cold" - finds partitions without recent writes, compacts any remaining L0 files into L1 files, and then will compact those L1 files into L2

Currently the system is configured to run four hot compaction cycles and then one cold compaction cycle.

# Hypothesis

This compaction model is leaving around a lot of small L1 files that could be combined which would improve query performance. They are too "warm" to be picked up by the cold compaction, and they don't necessarily overlap hence won't be picked up by hot compaction.

# Proposal

Introduce a new "warm" mode that looks for small [^1], adjacent L1 files that, if combined, would be less than `large_cutoff_bytes`

We could adjust the compaction schedule to do something like:

1. 1x hot compaction cycle
2. 1x warm compaction cycle
3. 2x hot compaction cycle
4. 1x cold compaction cycle

...the theory being that it's important to combine these to improve query performance, not so important as hot compaction, but maybe more important than the last round or two of hot compaction.

---
[^1]: small is defined as between `small_cutoff_bytes` and `(large_cutoff_bytes - small_cutoff_bytes) / 2`

**Comment by NGA-TRAN** [comment]
Your proposal looks good @lukebond . I think
1. If you define numbers of hot, warn and cold as config params, we can always adjust them as we want. We have had requests to compact more/immediately from a few use cases
2. I think the small can just be `<  large_cutoff_bytes  / 2`. Or to make it simple, `< max_desired_file_size_bytes/2`. 
3. You may consider another parameter: Min number of L1 files to consider partitions are warm. That number will be used in your SQL to get warm partitions and their L1s

**Comment by lukebond** [comment]
Thanks @NGA-TRAN. To summarise:

1. make compaction schedule configurable
2. add warm mode that selects partitions with at least a configurable minimum number of L1 files
3. warm mode compaction will compact adjacent L1 files that are smaller than `max_desired_file_size_bytes` but when combined are not larger than `large_cutoff_bytes`

from an initial reading of the code this will likely involve writing a warm candidate selection function (and underlying sql query as per item 2 above), changing the `spit` arg to `compact_one_partition()` to be an enum of either `Split` or `Merge`, and having a match arm in that function that will focus on merging files according to the above rules.

**Comment by NGA-TRAN** [comment]
> warm mode compaction will compact adjacent L1 files that are smaller than max_desired_file_size_bytes but when combined are not larger than large_cutoff_bytes

I think we should reuse the current mechanism/functions and not worry about this. The idea is:
1. We keep (estimated) size all L1/L2 files smaller  than  `max_desired_file_size_bytes`
2. In the code there is already a place we check to not compact files > `max_desired_file_size_bytes` (or something near that) to avoid compact files that are already large

I would say modify your summary as:

1. make compaction schedule configurable
2. add warm mode that selects partitions with at least a configurable minimum number of L1 files. Implementation:  writing a warm candidate selection function and underlying sql query
3. warm mode compaction will compact adjacent L1 files. Implementation: use the current functions for this. You only need to provide sorted/adjacent input files to that function. I think Carol refactored to make this very easy to reuse but you please refactor them further as needed

**Comment by alamb** [comment]
I know this might sound contrarian but I suggest rather than adding another mode, we reconsider how the compactor does its prioritization.

The current formulation has a static schedule based on hot/cold heuristics so even adding more sophisticated heuristics is still static (can't react to changes in parquet files).

So rather than making a more sophisticated (yet still static) scheduler, what about something like:

1. Maintain a priority queue (in order) of partitions the compactor wants to compact. We can encode heuristics like "compact the L0 files first" by putting those files in with higher priority.
2. The compactor main loop simply runs `MAX_NUM_CONCURRENT_COMPACTION` and when one job is done it picks the next one in the queue

I think the current hot/cold cycles simply become then "when to run the catalog queries necessary to find compaction candidates" and likely could be largely reused
