### ISSUE TITLE
Perf: incremental snapshotting within the MUB / Maximize concurrent read/write throughput to the active mutable buffer chunk + define semantics

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#635]
__Use case:__
Most data  in IOx is stored in immutable chunks, and thus querying historical data can proceed without any contention or special consideration. However, the the active chunk in the immutable buffer (where all new data goes) is queried (which will be very frequently) we need a way to ensure IOx gets the right query results but also doesn't slow down ongoing writes unecessairly

The initial implementation of getting a readable chunk snapshot from the Mutable Buffer (in #630 ) is likely going to make a snapshot of the open chunk by copying the entire open chunk. This copying happens under a read lock that will prevent any writes from occurring (though it won't block other readers). This is not ideal.

The requirements as we understand them are:
1. Querying the open chunk from the mutable buffer should impact the write throughput as little as possible
2. It should be possible to construct an IOx client that "sees its own writes" -- namely that if the client writes data it should (optionally) be able to specify that subsequent queries see that data was written (even if it means slowing the query down to wait for consistency)
3. IOx will not offer cross client consistency or isolation guarantees (e.g. if multiple clients are writing to the same open chunk, IOx won't guarantee anything about the order in which their updates are applied or offer any isolation from seeing updates fro other clients

See additional backstory here: https://github.com/influxdata/influxdb_iox/pull/630#discussion_r554569501

__Proposal:__
@pauldix ,  @domodwyer ,  @carols10cents  and I discussed several options. The assumption is that IOx doesn't need to provide consistency across clients. 

The high level design proposal was to buffer incoming writes into a Chunk into a smaller buffer within the open chunk that *does* need some sort of lock or other synchronization to access, but periodically flush that buffer into some form (e.g. Arrow Record Batches) within the open chunk that does *not* require cross thread synchronization (e.g. can just `clone()` some Arcs

Note that it may make sense to design / implement the "read your own writes" semantics as part of another ticket.

**Comment by alamb** [comment]
@tustvold  is this tracking anything useful anymore? Or shall we say it is as done as it will be?

**Comment by tustvold** [comment]
I think it tracks incremental snapshotting within the MUB, this hasn't been implemented but I'm not sure it is something we intend to implement anymore

**Comment by alamb** [comment]
Cool -- thanks -- I'll leave it in the icebox

**Comment by jacobmarble** [comment]
@tustvold please check in here again. Still useful?

**Comment by tustvold** [comment]
We need to collect some empirical data from a workload that has non-trivial mixed read-write workloads to know if we do or don't need this functionality. 

An alternative mechanism to implement an approximation of this would be to keep multiple, smaller closed MUB chunks before compacting them into the RUB, but again we need some real world data to test this out.

In short - I don't know :laughing:

**Comment by tustvold** [comment]
Closing as relates to OG
