### ISSUE TITLE
Implement Block reader

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb_iox#64]
I need to implement a Block reader. A block read can take a serialised block, e.g., in a file, and deserialise it into a Rust `Block` object. 

Things to consider:

 - provide support for just reading the initial part of the block without the block summary and block data.
- provide support for lazily reading block data (not decoding it but just storing compressed data).

**Comment by alamb** [comment]
@e-dard  is this one complete? I think it may be.

**Comment by jacobmarble** [comment]
@e-dard can this be closed? If not, does "Block" mean "TSM Block"?

**Comment by alamb** [comment]
I think this was related to TSM. Closing. Please reopen if that was a mistake
