### ISSUE TITLE
bug(ingester2): When ingester restarts router (rpc mode = 2) doesn't recover

### ISSUE THREAD

**Issue by mkmik** [influxdata/influxdb_iox#6446]
__Steps to reproduce:__

1. roll ingesters without rolling the routers.

__Actual behaviour:__

<img width="555" alt="image" src="https://user-images.githubusercontent.com/52673/208560058-2dba91f3-a3de-4e9c-b086-02adcaa6cf7b.png">

__Environment info:__

our eu-central-1 internal testing env

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__

```
level=warn msg="failed ingester rpc write" error="upstream ingester error: status: Unavailable, message: \"upstream connect error or disconnect/reset before headers. reset reason: connection failure\", details: [], metadata: MetadataMap { headers: {\"content-type\": \"application/grpc\", \"server\": \"envoy\", \"date\": \"Tue, 20 Dec 2022 01:19:12 GMT\"} }" target="router::dml_handlers::rpc_write" location="router/src/dml_handlers/rpc_write.rs:128" time=1671499152623685211
```

**Comment by domodwyer** [comment]
Do they eventually recover on their own? or do we have to roll the routers for them to recover?

I'm not familiar with the gRPC connection handling - I wonder if we're holding onto a cached connection hoping it comes back, or only doing a DNS lookup once or something.

**Comment by mkmik** [comment]
I had to roll the routers on both prod and stag

**Comment by tustvold** [comment]
> or only doing a DNS lookup once or something.

https://isitdns.com/ :laughing: 

On a more serious note, if the ingesters are StatefulSets and we are addressing them based on these identities, we will need to aggressively flush any DNS caching as they are headless services - https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id.

We could also potentially construct manual `ClusterIP` services to work around this, by giving them a stable IP, and leaving kube-proxy to do the routing for us.

**Comment by mkmik** [comment]
I have a vague memory we already had this problem; @lukebond do you remember influxrpc_compare routing issue with individual pods?

**Comment by domodwyer** [comment]
I have confirmed that routers do recover locally with no issue after #6504 (I didn't check beforehand) - if this persists, we can look at being aggressive with DNS purging or some other workaround.

FWIW, I saw DNS resolution failures in the logs (see #6503) but these should now be transient and not impact write availability if at least one ingester is resolvable and up.

**Comment by domodwyer** [comment]
I don't think this happens anymore after https://github.com/influxdata/influxdb_iox/pull/6504 - below I killed all the routers (quickly) at 15:50, waited 10 minutes, and then killed all the ingesters at 16:00:

![image](https://user-images.githubusercontent.com/9275968/210825626-ad0acc38-9432-4904-a9eb-eceecb6d3baf.png)

I have https://github.com/influxdata/influxdb_iox/issues/6173 logged to improve discovery/downed ingesters in general.
