### ISSUE TITLE
Ingester2 should delete WAL files after replay

### ISSUE THREAD

**Issue by domodwyer** [influxdata/influxdb_iox#6461]
When the ingester starts up, it replays any WAL files it finds in the configured directory.

Currently one replayed, the ingester resumes normal ingest and the WAL files remain.

Instead, once replayed, the data should be persisted and then the WAL files dropped before ingest resumes.

As an optimisation in the future we may allow concurrent ingest & persist operations.

**Comment by aierui** [comment]
Will consider support the WAL file limit the size of a single file and multi WAL files? @domodwyer

**Comment by domodwyer** [comment]
@aierui I think we'll wind up having to do this, yes!

It's indirectly limited by the amount of data we can hold in 5 minutes, but that's not going to be a good long-term solution.

**Comment by aierui** [comment]
Well, that's great. ❤️
