### ISSUE TITLE
Implement WAL recovery and tracking

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#651]
#642 adds support to persist WAL segments to object storage. We need a strategy for recovering from the WAL that reads in as little of it as possible. Every time a chunk is written to object storage, that provides a potential checkpoint for how far back in the WAL we need to go.

The biggest problem to solve is that closing a chunk and persisting it doesn't actually provide a WAL truncation point. This is because writes in the WAL can go to multiple partitions, which means that a chunk in partition A could be persisted, while a chunk in partition B might still be open and have writes older than ones that were in partition A's chunk.

The other issue is that if a server is subscribed to the WAL of multiple other servers, it will need to know where to pick up writes from each of those servers after restart. This means that subscribers should also know the writer_id and segment_id that each write is coming from.

Here are the stages of the lifecycle, each of which can happen on a different server:
1. Parse input format into ReplicatedWrite and assign a writer_id and sequence_number (always increasing)
2. Put write into WAL Segment. Each segment has its own id (monotonically increasing int) and its own writer_id (the server persisting the segment)
  A. Persist segment after some time or size
1. Put write into mutable buffer
2. Close chunk(s) from mutable buffer and write to object storage

The server is what is coordinating all of this writing into the object storage, so it should be the thing that tracks whatever additional state is required when writing out the chunk. In addition to the schema and summary stats in each chunk, it should also contain for each writer id:
1. The lowest and highest sequence number write the chunk has
2. The lowest and highest segment number the chunk has

Each time a chunk is persisted, a single file that contains the metadata plus this information should be written out in the chunk directory.

Each database should have a summary that contains the information for all partitions and chunks that server handles. This should be in `<writer id>/<database>/checkpoints/<0 padded id>.checkpoint`. Each time a chunk is persisted, a new checkpoint with an id + 1 of the previous checkpoint should be written. A chunk won't be considered to be persisted until this checkpoint has been written, making chunk persistence atomic. Older checkpoints should be deleted as we go to keep list operations on this directory efficient.

Also in this checkpoint file will be the min segment id for each writer for all the chunks that were open when the chunk that triggered this checkpoint was closed. If no chunks were open for a given writer that is in the chunk that has just been closed, the max segment id from that chunk will be used.

On startup the server can read the latest checkpoint for each database (in parallel). For each writer that has segment information in the checkpoint, read in all WAL segments from that point forward to put into the mutable buffer. While replaying each segment, individual writes can be ignored if their sequence number is >= the highest number in a partition (which is the highest for all persisted chunks within that partition). This will ensure that writes that were previously persisted aren't duplicated in the mutable buffer.

I think that covers everything, but there are a few things we'll have to enforce to make this actually work. First is that servers that assign sequence numbers need to have a strategy for ensuring their sequence numbers are always increasing, even after restart. Second is that replication and subscriptions need to be structured in such a way that writes from a single writer (i.e. the same process) happen in order. Both of these should be achievable.

The first one will be tricky because we won't want to capture the state of the most recent sequence number assigned on every single write. I think something like writing it out every 10k (or whatever) increments, with restarts picking up at previous increment + 20k would work, but I'm open to ideas.

Thoughts and feedback on all of the above? @e-dard @alamb @domodwyer

**Comment by alamb** [comment]
Nice writeup -- thanks @pauldix 

I like the idea of `<writer id>/<database>/checkpoints/<0 padded id>.checkpoint` -- I am tempted to say we should call that thing the database wide metadata  catalog -- e.g `<writer id>/<database>/catalog/<0 padded id>.checkpoint` -- it serves as the single definition of what chunks and WAL segments make up the database. Using that checkpoint and the contents of the object store, we can recover the databases state.  Using older versions of the checkpoint file could also restore the database to previous points in time too which is cool. 

While persisting checkpoints, I worry that a large file with most of the same content might be continually re-written to object store, but we can always go all Delta Lake on it and add its own update log to avoid writing snapshots over and over again.

> First is that servers that assign sequence numbers need to have a strategy for ensuring their sequence numbers are always increasing, even after restart

It seems to me like we could store the "highest sequence number stored in a wal segment file" as part of the checkpoint file itself. As we'll have to update the checkpoint when segments are written anyways, we know at that point what the highest sequence number that could be recovered was.  The contents of the checkpoint can also be used to tell the mutable buffer what chunk number to start from .

All in all, I am excited about this proposal. 


Note that I don't understand why a segment number is needed if each write has a unique sequence number; You can uniquely identify every segment by picking one write id or the range of the sequence numbers contained within it
