### ISSUE TITLE
Ensure writes go into mutable buffer and WAL or not at all

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#654]
In servers where both the mutable buffer and the WAL are enables, writes should succeed on both or not at all. Currently, the write happens against the mutable buffer first. If there's an error, the write bails. However, if it succeeds it then moves on to write into the WAL Buffer. Writes to the WAL Buffer may fail if there isn't enough space and previous writes can't be dropped (due to not being persisted yet). Currently, this would cause the write to fail, but it would remain in the mutable buffer.

We've discussed doing a write reservation in the WAL to handle this. See discussion https://github.com/influxdata/influxdb_iox/pull/642#discussion_r556737037

**Comment by jacobmarble** [comment]
@pauldix I believe this can be closed, as we have switched the WAL design to Kafka for now.

Do you agree?

**Comment by pauldix** [comment]
Yeah, this is no longer applicable.
