### ISSUE TITLE
ingester2 gRPC API to request persistence on demand

### ISSUE THREAD

**Issue by carols10cents** [influxdata/influxdb_iox#6540]
Mostly for tests that want a setup where a known set of data is persisted and another known set of data is in ingester2's memory: we can set up an ingester2 that effectively never persists and then the test can ask the ingester to persist after writing the first set of data and then not after the second set.

Needed for #6497

From [this comment](https://github.com/influxdata/influxdb_iox/pull/6497#issuecomment-1372402162):

> > I think we do need a gRPC API to the ingester to ask it to persist on-demand
>
> I think this is a reasonable approach - there exists a method for taking the buffer tree containing all buffered data, enqueuing it for persistence, and (async) blocking until it is complete:
>
> https://github.com/influxdata/influxdb_iox/blob/main/ingester2/src/persist/drain_buffer.rs#L16-L25
>
> The system is decoupled and the necessary components exist and should be easy to reuse, and the buffer tree is already Arc'd - it should be trivial to create an RPC handler that basically [does this](https://github.com/influxdata/influxdb_iox/blob/e1d0bcdaad46ad24b8e7f4b136761d77e8e6ffd6/ingester2/src/wal/rotate_task.rs#L115).

**Comment by domodwyer** [comment]
I had this commit locally to move the `PartitionIter` for re-use (avoids us conflicting!)

https://github.com/influxdata/influxdb_iox/pull/6548
