### ISSUE TITLE
Add background task tracking to server

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#655]
Currently, the server can have a few different background tasks running. One for WAL Segment persisting and one for writing Chunks to object storage. We need a way to track which tasks are running in the background so we can report on them and potentially cancel them out for orderly server shutdowns.

**Comment by alamb** [comment]
I had some plan that this would be added to an `Executor` structure or something similar: https://github.com/influxdata/influxdb_iox/blob/c672bb341d99d703561be5d496340de9dc1f7e29/query/src/exec.rs#L233-L236

However, I realize such a task tracking system shouldn't really be in the query crate --
