### ISSUE TITLE
Retention/namespace service in kafkaless land

### ISSUE THREAD

**Issue by carols10cents** [influxdata/influxdb_iox#6592]
## What happened

I tried to port the retention query test that uses the [`ThreeChunksWithRetention`](https://github.com/influxdata/influxdb_iox/blob/0edda47af2a5b13ae36a68b967b5e2f0e1fa06e2/query_tests/src/scenarios/library.rs#L987-L1038) setup as part of https://github.com/influxdata/influxdb_iox/pull/6497, but I found out [the `RpcWriteGrpcDelegate` doesn't implement the `NamespaceService`](https://github.com/influxdata/influxdb_iox/blob/0edda47af2a5b13ae36a68b967b5e2f0e1fa06e2/router/src/server/grpc.rs#L22-L72) that [the `GrpcDelegate` does](https://github.com/influxdata/influxdb_iox/blob/0edda47af2a5b13ae36a68b967b5e2f0e1fa06e2/router/src/server/grpc.rs#L151-L162), so there isn't a way to create a namespace with particular retention policies using a gRPC request in router2.

I tried searching existing issues and the "IOx Write Path without Kafka" doc, and I didn't find any mention of this. My guess is that retention was deemed out of scope for the current milestone but I can't find any confirmation of that?

I'm going to skip this test for now but wanted to file this issue to discuss and track.

cc @domodwyer @pauldix

**Comment by domodwyer** [comment]
The router should still provide the `NamespaceService` - I'd hope it wasn't tightly coupled with Kafka (it should have nothing to do with Kafka!)

I think it just needs adding back - it was probably a development effort that after we split out the RPC stuff.

**Comment by alamb** [comment]
This is needed as part of the query_test migration
