### ISSUE TITLE
InfluxQL-IOx: Make planner not async

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#6607]
Planning InfluxQL is now async due to https://github.com/apache/arrow-datafusion/pull/4607 -- @tustvold had a clever way to avoid this in DataFusion (see  https://github.com/apache/arrow-datafusion/pull/4607) but I didn't want to try and replicate it in IOx (aka I was being lazy)

This ticket tracks making the planning non `async` again

 The reason (the deepest blue function) is that `create_table_ref` finds the table provider which is now async. It used to be

```rust
        if let Ok(provider) = self.state.get_table_provider(table_ref) {
```
But now needs to be:

```rust
        if let Ok(provider) = self.ctx.inner().table_provider(table_ref).await {
```

In DataFusion, @tustvold  made a pass over the sqlparser tree and looked up all providers for all referenced tables before calling the planner. I think the same treatment could be given to the influxql planner

_Originally posted by @alamb in https://github.com/influxdata/influxdb_iox/pull/6603#discussion_r1073390942_

**Comment by tustvold** [comment]
At least currently it doesn't need to be anything that complicated, as creating a TableProvider within IOx is currently sync - it is just the DF trait that is now async.

**Comment by alamb** [comment]
FYI @stuartcarnie
