### ISSUE TITLE
Port query_tests to query_tests2 

### ISSUE THREAD

**Issue by carols10cents** [influxdata/influxdb_iox#6617]
- [x] https://github.com/influxdata/influxdb_iox/pull/6497
- [x] Port `query_tests/influxrpc` tests
  - [x] https://github.com/influxdata/influxdb_iox/pull/6709
  - [x] https://github.com/influxdata/influxdb_iox/pull/6743
  - [x] https://github.com/influxdata/influxdb_iox/pull/6755
  - [x] https://github.com/influxdata/influxdb_iox/pull/6757
  - [x] https://github.com/influxdata/influxdb_iox/pull/6760
  - [x] https://github.com/influxdata/influxdb_iox/pull/6801
- [ ] https://github.com/influxdata/influxdb_iox/pull/6807
- [ ] Port `query_tests/table_schema` tests

**Comment by alamb** [comment]
I think we are getting pretty close 🤞
