### ISSUE TITLE
compactor2: shadow mode

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#6645]
# What
Provide a way for the compactor to read from "normal" source (like prod) but write to mock sinks.

# Why
This simplifies testing with prod data, debugging, experiments, and large parts of my life.

# How
- split object store config into two stores (source and sink)
- use the component system to use mock sinks when a "shadow" config flag is passed

**Comment by alamb** [comment]
This would be amazing. 

Another feature, that I would have found useful in the past, is some way to tell the compactor "run all compactions now, with all available resources" (when I was trying to reproduce bugs or get my local iox installation into a fully optimized / compacted state

**Comment by crepererum** [comment]
> Another feature, that I would have found useful in the past, is some way to tell the compactor "run all compactions now, with all available resources" (when I was trying to reproduce bugs or get my local iox installation into a fully optimized / compacted state

https://github.com/influxdata/influxdb_iox/issues/6648
