### ISSUE TITLE
compactor2: refine metrics and logs

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#6647]
This is mostly a reminder for myself to sit down and look at the metrics to at least have the basic stuff in place before it can run in an actual deployment. I don't know the actual outcome of this yet.

One example that comes to my mind: include a metric for the number of filtered-out partitions (in addition to the existing counters for ready and failed partitions).

**Comment by NGA-TRAN** [comment]
This is super important IMO
