### ISSUE TITLE
Ordering files/chunks after compaction

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#6674]
# What
We need a logical clock to order parquet files.

# Why
The ingester2 currently creates files with a `created_at` timestamp. We hand-waving decided that this can be used to order files during query. This is only true for level-0 files. After the compactor picked files up and created new ones, the `created_at` timestamp is no longer a proxy for ingest order. The compactor should however use `now()` for `created_at` since this is important information for data lineage / debugging.

# How
Get ingester2 to write a logical clock (can be "current timestamp" i.e. same as `created_at` for now) for every parquet file. The compactor should use that to create new logical clock entries for its output files (probably `max(file.clock for file in input)`) and has to ensure to only compact "closed ranges" (i.e. if files are ordered ABC; only compact A, AB, B, BC, or ABC, but NOT AC).

**Comment by NGA-TRAN** [comment]
@crepererum Since L1 files do not overlap with each other and L2 files d not overlap with each other, the logical for ordering them can be simpler. If we stick to these variants, we do not have to worry about L1 and L2 orders:

1. Only compact overlapped L1s (with L0s in hot and L2s in cold)
2. L1 files are always older than their overlapped L0 files. This means we have to compact L0s (with their overlapped L1s) in the order of **L0 creation**.
3. L2 files are always older than their overlapped L1 files. This means we have to compact L1s (with their overlapped L2s) in the order of **L1 min-max time range**.

It took us a while to come up with those invariance to keep deduplication right and simplified our algorithm. If you change them, we will have a new headache discussion and algorithm

**Comment by crepererum** [comment]
Let's have an example then, showing that this is a problem no matter how the compaction algorithm looks like:

1. ingester receives data, stores it in file 1
2. ingester receives data, stored it in file 2
3. compactor sees file 1 and 2, starts compacting job
4. ingester receives data, stores it in file 3
5. compactor finishes compaction job, stores it in file 4

Now file 4 has a `created_at` timestamp after the one of file 3, but the data in file 4 is clearly BEFORE the one in file 3. Hence the `created_at` logic doesn't work.

**Comment by NGA-TRAN** [comment]
@crepererum Yes, that is why we do not use `create_at` to order L1s and L2s. We always assume L0 file created in #4 is older than L1/L2 files created in #5

**Comment by crepererum** [comment]
And how shall the **querier** order chunks? I've been told "just use `create_at`" which is obviously wrong.

**Comment by NGA-TRAN** [comment]
This is what we currently do
https://github.com/influxdata/influxdb_iox/blob/dcc1eb9a21f6c095fe84716b4a3c6b1bb56e0a2c/compactor2/src/components/df_planner/query_chunk.rs#L181

**Comment by crepererum** [comment]
> This is what we currently do

This doesn't work for the querier. There's no target level there. The querier has to deal w/ files from ALL levels at the SAME time.

**Comment by NGA-TRAN** [comment]
Let us have zoom chat. I am not aware of the context in Querier.

**Comment by NGA-TRAN** [comment]
Here is the summary @Marco and I chatted about:

### Problem

Ingester, Compactor and Querier need to order the chunks/files for data deduplication. When Kafkaless Ingester available,  we order the chunk as follows:

- Ingester has a internal mechanism for doing so
- Compactor uses `created_at` field for L0 files, and 0 for L1 and L2 files (See code link above for reason)
- Querier uses `created_at`  field for all files (L0, L1, L2)

This leads to the problem that `created_at` of L1 and L2 files can be very recent but  include data ingested long ago and the Querier cannot relies solely on it to order the chunks/files  (see example above)

### Proposal

We will use the unused field `max_sequence_number` to simulate the order as we did before kafkaless available.

- Ingester:
      -  will write current clock on to it. This mean L0 files will have the same value of `max_sequence_number` and `created_at`
      - Unchanged in chunk order
- Compactor:
    - will create L1 and L2 files with `create_at`  = now and `max_sequence_number` = max_of_all_input_files(`max_sequence_number`)
    - Unchanged in chunk order
- Querier will use `max_sequence_number` to order the chunk

**Comment by pauldix** [comment]
This looks good to me. Makes sense and makes it easier for the querier to order everything by a single value.
