### ISSUE TITLE
Garbage Collector retention interval does not guarantee catalog backups 

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#6683]
Internal context: https://influxdata.slack.com/archives/CRK9M8L5Q/p1674572266169589?thread_ts=1674501201.787439&cid=CRK9M8L5Q

# Problem description

The strategy of taking database backups as a recovery mechanism has a problem, as pointed out by @mkmik , which is that there are cases when even though  `INFLUXDB_IOX_GC_OBJECTSTORE_CUTOFF`  is set longer than the backup period, the garbage collector may still delete files referred to by the backups

# Ticket goals
Design a system for backups that ensures the garbage collector will not delete files referred to by the backups.

# Example scenario

Let's say we have a namespace with 30d retention policy influxdb_iox namespace retention `--retention-hours 720 my_namespace`. 

This means that any parquet file that is older than 30d will be marked for deletion. Let's say that the `INFLUXDB_IOX_GC_PARQUETFILE_CUTOFF` is 1d; that means next day the file will be removed from the parquet_files table. The GC will later notice that there is a file on objstore that is not present in the catalog. According to the file metadata the file is 31d old, so it's below the 100d `INFLUXDB_IOX_GC_OBJECTSTORE_CUTOFF` and it won't touch it.  After 70 days, the GC will happily delete the file though. Now, at day 75 we decide to restore the catalog from backup and go back 7d to day 68. The state of the catalog at that time points to a file that no longer exists

**Comment by alamb** [comment]
FWIW I think this is likely an OK problem because parquet files are created very soon after the data is written written and thus the period of time between when they will be deleted due to the retention interval but might still be in a backup is relatively short

**Comment by Neyzoter** [comment]
You said 'restore the catalog from backup'. How can I operate?

**Comment by philjb** [comment]
> This means that any parquet file that is older than 30d will be marked for deletion. Let's say that the INFLUXDB_IOX_GC_PARQUETFILE_CUTOFF is 1d; that means next day the file will be removed from the parquet_files table. The GC will later notice that there is a file on objstore that is not present in the catalog. According to the file metadata the file is 31d old, so it's below the 100d INFLUXDB_IOX_GC_OBJECTSTORE_CUTOFF and it won't touch it. After 70 days, the GC will happily delete the file though. Now, at day 75 we decide to restore the catalog from backup and go back 7d to day 68. The state of the catalog at that time points to a file that no longer exists

I'm missing something about this scenario. The file is removed from the catalog on day 1 (day zero is when retention is applied to the file). The file is not in the catalog. The catalog backup for day 68 likewise doesn't have the parquet file in question. So it doesn't mater that it was removed from S3 after the day 68 catalog backup was made.


In any case, I've analyzed the catalog and parquet file backups/snapshots for what we do today which is different than the scenario above. No file is removed from the catalog until its "to delete" marker is 100 days old. And no file is removed from s3 until it has no record in the catalog (so a file could be removed from s3 immediately after it is removed from the catalog). So all the parquet files for any catalog backup (called snapshot) in the last 100 days still exist in s3. In practice that means it might be hard to restore to 100th-day backup but usually we just need to go back a few days. This policy also means a file is kept for 100 days after retention says it can be deleted.

**Comment by philjb** [comment]
@Neyzoter - we don't offer support if you're running iox yourself. If you're using influxdb iox serverless, contact support or ask in [our community slack ](influxcommunity.slack.com) with some more details. I'm not sure what you want to do.
