### ISSUE TITLE
Limit how stale entries can be in the querier cache

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#6684]
__Use case:__
Internal slack context: https://influxdata.slack.com/archives/CRK9M8L5Q/p1674570542893529?thread_ts=1674501201.787439&cid=CRK9M8L5Q

For tables that don't receive any traffic anymore, the querier currently NEVER refreshes the catalog `parquet_file` cache. This means that until the cache is refreshed via restart, the querier may try to read files that were previously deleted by the garbage collector. 

It would be better to have an explicit upper bound on "how stale" objects can be in the querier cache so we can ensure the garbage collector doesn't delete files that are referenced in the cache.

I don't think it likely to be hit frequently because we deploy multiple times a day during the week which forces a cache refresh and we are going to have the hard object store delete wait for a significant time period after the parquet file was deleted.

__Proposal:__
Add a background refresher to the cache that pulls the data after some set period of time (e.g. at least every 10h)

__Alternatives considered:__
Describe other solutions or features you considered.

**Comment by philjb** [comment]
I believe @crepererum 's PR below addressed this!

* https://github.com/influxdata/influxdb_iox/pull/7975

It adds a TTL.

I won't close this in case there is an additional desire.

**Comment by crepererum** [comment]
I agree that this can be closed.
