### ISSUE TITLE
Buckets with implicit schema and "never" retention policy, are hitting error in iox.

### ISSUE THREAD

**Issue by wiedld** [influxdata/influxdb_iox#6758]
The UI has various fixtures (in ui e2es, and in a remocal pre-created task) which generate test data for consumption. This test data:
1. creates a bucket, with a "never" retention policy and implicit schema.
2. Writes data to the bucket, which creates the measurement/table on write.

As of today, we are now hitting this error:

<img width="1550" alt="Screen Shot 2023-01-30 at 11 02 05 AM" src="https://user-images.githubusercontent.com/10232835/215570296-5d5b2a81-19c3-465c-8af3-6d244f8d14f8.png">

Which is coming [from here](https://github.com/influxdata/influxdb_iox/blob/49a9565240c3cb5fe19bf22d56f678e77130ad34/router/src/dml_handlers/retention_validator.rs#L23-L25) in iox.

## Steps to reproduce:
1. deploy a new remocal instance
2. go to tasks
3. run the `Fetch Sample Data Runs`
4. see error

remocal is on k8s-idpe [commit eb02bc1cb18788204b3a066006d4673c1d1e9f73](https://github.com/influxdata/k8s-idpe/commit/eb02bc1cb18788204b3a066006d4673c1d1e9f73)

## Scoping down:
* does not occur in new tools, upon new creation of bucket. on `Version (9130648)`

**Comment by jacobmarble** [comment]
> creates a bucket, with a "never" retention policy and implicit schema

What does the API call look like? I wonder if IOx's CreateNamespace is being called with a default retention period (like zero or never) and not explicitly? In that case, we should explicitly set the retention policy in the CreateNamespace call, whether the IDPE bucket API has received "default" or not.

**Comment by jacobmarble** [comment]
Because this is inside a remocal environment, I need some help to access the environment, to inspect a bucket/namespace that shows this behavior. Is that possible?

**Comment by wiedld** [comment]
https://twodotoh-dev-denisewiedl20220405130506.remocal.influxdev.co  @jacobmarble

**Comment by wiedld** [comment]
Flux query to write data (via csv) returned 200.
Query out => no table.

<img width="1069" alt="Screen Shot 2023-01-30 at 11 41 58 AM" src="https://user-images.githubusercontent.com/10232835/215579494-31ffabe5-1a98-43de-9a4f-58f705a064f2.png">

**Comment by jacobmarble** [comment]
> To be clear, I'm not sure if it's a remocal-only issue. Or because my remocal was just pulled this morning, and in advance of new tools (where I don't see this problem).

That's fine, I just want to observe the problem in the wild, rather than try to recreate it.

**Comment by jacobmarble** [comment]
> Flux query to write data (via csv) returned 200.
> Query out => no table.

This describes a different bug, doesn't it? This bug is about a retention policy error, when no retention policy was set, right?

**Comment by wiedld** [comment]
> > Flux query to write data (via csv) returned 200.
> > Query out => no table.
> 
> This describes a different bug, doesn't it? This bug is about a retention policy error, when no retention policy was set, right?

True. But both errors emerged at the same time (in terms of new remocal instance, prior pull was last week thursday). Unclear if related.

**Comment by jacobmarble** [comment]
Not likely related. I looked for an existing issue, but couldn't find one. Please open a second issue for the inability to query data recently written to a new table.

**Comment by appletreeisyellow** [comment]
> I wonder if IOx's CreateNamespace is being called with a default retention period (like zero or never) and not explicitly? In that case, we should explicitly set the retention policy in the CreateNamespace call, whether the IDPE bucket API has received "default" or not.

Yeah, currently in IDPE bucket API, if a bucket has a default "Forever" retention period, a retention period with value `0` is sent to IOx's CreateNamespace. 

Since the retention period value type is `int64` in [Namespace Service proto file](https://github.com/influxdata/influxdb_iox/blob/49a9565240c3cb5fe19bf22d56f678e77130ad34/generated_types/protos/influxdata/iox/namespace/v1/service.proto#L28), any other value other than `0` should the IDPE bucket API send to IOx? Or IO's namespace service will take care of this `0` value situation?
