### ISSUE TITLE
Transaction is not actually a transaction

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#6759]
Incident  https://influxdata.slack.com/archives/C04LZJYH614 tells us we delete files even if they are not compacted.

Tell me if the previous step filter out all files and not compacted, we still commit and leads to delete files
https://github.com/influxdata/influxdb_iox/blob/5b14caa780b77c6607c84ad38578ed4d28f15e86/compactor2/src/driver.rs#L188

**Comment by NGA-TRAN** [comment]
CC @crepererum 
I am trying to reproducing it locally

**Comment by NGA-TRAN** [comment]
I did not think much when I hit `incident 1` because I focused on fixing the FK constraint. The incident 2 makes me think about it

**Comment by NGA-TRAN** [comment]
Or the issue is we delete the files even if OS failed to persist the files. We need to check only commit if the file is persisted
https://github.com/influxdata/influxdb_iox/blob/5b14caa780b77c6607c84ad38578ed4d28f15e86/compactor2/src/driver.rs#L188

**Comment by pauldix** [comment]
Seems like if `delete_ids.len() > 0` then `create.len() > 0` must be true. Otherwise there's a problem and we shouldn't commit.

**Comment by NGA-TRAN** [comment]
I am trying to repdoduce empty `create`

**Comment by NGA-TRAN** [comment]
@pauldix : yes, that is a quick fix in https://github.com/influxdata/influxdb_iox/pull/6761

**Comment by crepererum** [comment]
I think this can be closed?
