### ISSUE TITLE
Allow underscores in database names to be replaced with another character

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb_iox#677]
IOx does not accept the `_` character in database names and returns an error if an attempt is made to create a database with an `_` in the name.

However, it is not always simple to get a client to use a valid name. A common example of this is when mapping existing InfluxData org and buckets (where underscores are valid) to IOx database names.

IOx should have a configuration option that allows an operator to specify an alternative valid character to replace the `_` characters in database names, rather than returning an error.

Further, this replacement strategy should be used on the read path so that a client can continue to refer to an invalid database name, e.g., `my_fun_database`, and IOx will always (when configured) convert the database name to, e.g., `my-fun-database`.

**Comment by alamb** [comment]
@e-dard  I think we should just allow IOx to use `_` in database names -- we currently use it to encode something related to a legacy API I think -- I think having IOx hande it as an internal detail would be best

**Comment by e-dard** [comment]
I also just realised that the replacement character approach doesn't help with clashes if the input components also contain the replacement character 😂

**Comment by pauldix** [comment]
Any valid utf8 character should be allowed, but should be percent encoded for the name it uses in object store. The `_` was a separator that was between org and bucket which were just translated over. So if we can come up with something else for encoding the separation. But org and bucket should only be used in the InfluxDB 2.0 write API and gRPC. Everywhere else should be using database name, which should accept those characters.

**Comment by alamb** [comment]
Upon additional discussion with @pauldix 👍 

>Yeah, there’s no valid reason I can think of to have a newline in a db name. Or a tab for that matter.

So therefore I propose restricting the database names to:
Valid UTF-8 that do not have ASCII control characters (codes between 0x0 and 0x1F, inclusive) which will cover newlines and tabs among other nonsense like nulls
