### ISSUE TITLE
Support `DESCRIBE` queries.

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#6816]
Issue the following SQL statement:

```sql
DESCRIBE my_table;
```

This should describe the table. Instead, this now returns:

```text
Error while planning query: Internal error: Unsupported logical plan: DescribeTable must be root of the plan. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

**Comment by alamb** [comment]
@mkmik  hit this recently; https://influxdata.slack.com/archives/C04K1QRSDFG/p1685023508713789?thread_ts=1685023473.300109&cid=C04K1QRSDFG

**Comment by alamb** [comment]
Filed https://github.com/apache/arrow-datafusion/issues/7440 upstream
