### ISSUE TITLE
compactor2 --compaction-process-once doesn't do what I expect

### ISSUE THREAD

**Issue by carols10cents** [influxdata/influxdb_iox#6876]
I was looking into porting the command `influxdb_iox compactor run-once` to compactor2, and I found the compactor2 option `--compaction-process-once`, so I tried to use that as a replacement.

## What I expected

I expected `run compactor2 --compaction-process-once` to do what `compactor run-once` did, which may be a fundamental mistake on my part. What that command did was one iteration of what the compactor server compaction loop did normally and then exit, rather than continuing.

## What happened instead

I don't think I actually have anything locally that needs to be compacted.

My `.env` file contains:

```
INFLUXDB_IOX_OBJECT_STORE=file
INFLUXDB_IOX_DB_DIR=/Users/carolnichols/.influxdb_iox/obj/
INFLUXDB_IOX_CATALOG_DSN=postgres://postgres@localhost/iox_shared
```

When I run 

```
INFLUXDB_IOX_RPC_MODE=2 cargo run -- run compactor2 --compaction-process-once
```

the compactor appears to be running in a loop. Every 5 seconds, it prints `No partition found`:

```
2023-02-06T19:32:20.133409Z  WARN compactor2::components::partitions_source::logging: No partition found
2023-02-06T19:32:25.141594Z  WARN compactor2::components::partitions_source::logging: No partition found
2023-02-06T19:32:30.149893Z  WARN compactor2::components::partitions_source::logging: No partition found
2023-02-06T19:32:35.159519Z  WARN compactor2::components::partitions_source::logging: No partition found
2023-02-06T19:32:40.164661Z  WARN compactor2::components::partitions_source::logging: No partition found
```

which, that's fine, I'd expect it to try to find partitions once and then exit.

Am I misunderstanding what this option is supposed to do?

I also understand this is likely not a high priority right now :)

**Comment by crepererum** [comment]
Ah yes, the "not empty" filter is a problem in that case. That's an easy fix. However this still won't exit after the it is completed due to the way the daemon is wired up. And it won't compact all partitions, only the active ones (see #6648 as well).
