### ISSUE TITLE
Discussion: all in one mode defaults (to file based)

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#6885]
__Use case:__
It is possible to run influxdb_iox as a single process for development and other non production usecases. I use it all the time for testing out various query / sql behavior and I think @stuartcarnie  does the same

You run it like

```shell
influxdb_iox <arguments>
```

```shell
influxdb_iox run all-in-one <arguments>
```

You can read about its various modes here:
* https://github.com/influxdata/influxdb_iox/blob/main/README.md#ephemeral-mode
* https://github.com/influxdata/influxdb_iox/blob/main/README.md#local-persistence-mode

Previously the "ephemeral" mode was the default because we didn't have a file based persistent catalog (for catalog persistence, we needed postgres), so it was the only option for "single process, no config local iox"

After https://github.com/influxdata/influxdb_iox/pull/6851 from @stuartcarnie has landed, we have access to the catalog

__Proposal:__
I propose changing the default behavior like this

```shell
# run in all in one mode, file backed, default data dir is `$HOME/.influxdb_iox`
influxdb_iox
```
Running in this mode,
1. The wal would be at `$DATA_DIR/wal`
2. The catalog would be a local sqllite file in `$DATA_DIR/catalog/catalog.sqlite`
3. The object store would be local files in `$DATA_DIR/store`

Examples
```shell
# run in all in one mode, file backed, default data dir is `$HOME/.influxdb_iox`
influxdb_iox
```

```shell
# run in all in one mode, file backed, wal, object store, catalog data in /tmp/data (
influxdb_iox --data-dir=/tmp/data
```

```shell
# Run with posgres backed catalog, wal and object store in `/tmp/my_data`
influxdb_iox run all-in-one --catalog-dsn postgres:///iox_shared --data-dir=/tmp/my_data
```

```shell
# Run with sqlite catalog in tmp/cat.sqlite, wal and object store in `/tmp/my_data`
influxdb_iox run all-in-one --catalog-dsn "sqllite:///tmp/cat.sqlite" --data-dir=/tmp/my_data
```

__Current behaviour:__
see above

__Desired behaviour:__
1. Remove the `--catalog` command line argument and instead pick the catalog type based on the format of the dsn
2. Remove the mention of "ephemeral mode" from the docs
3. 

__Alternatives considered:__
Describe other solutions or features you considered.

**Comment by alamb** [comment]
(assigning to myself so I don't lose this in the sea of tickets)

**Comment by stuartcarnie** [comment]
This is great, @alamb – sane defaults and flexible customisation. Also agree that the `--catalog` can go with the prefix in the `dsn`.

**Comment by crepererum** [comment]
`$HOME/.influxdb_iox` is a bad default. No sane program should ever write to `$HOME` directly. On every OS there is a folder structure that should be followed. Please use something like [`dirs`](https://crates.io/crates/dirs) and find an appropriate place for the data (likely [`data_dir`](https://docs.rs/dirs/4.0.0/dirs/fn.data_dir.html)).

**Comment by alamb** [comment]
> No sane program should ever write to $HOME directly. 

I am not necessarily disagreeing, but there is precident:

https://docs.influxdata.com/influxdb/v1.8/concepts/file-system-layout/#macos-default-directories

I think https://docs.rs/dirs/4.0.0/dirs/fn.data_dir.html sounds like a great idea to me

**Comment by NGA-TRAN** [comment]
One thing I want to add is, if possible, all the needed settings (e.g. default shard_index=1234 in the catalog) is created when we start `influxdb_iox`. This means we need to wipe the catalog if we reuse one but I think if it is possible, create (or replace) new catalog. Hopefully, it is @alamb's idea of "sqllite:///tmp/cat.sqlite".

If we do not wipe or create a new catalog, I suggest we add clear instructions on what to add in that catalog.  Some instructions like below will help

https://github.com/influxdata/influxdb_iox/tree/main/ingester2

mkdir -p /tmp/iox/{wal,obj}
createdb iox_shared
./target/debug/influxdb_iox catalog setup --catalog-dsn postgres:///iox_shared

**Comment by alamb** [comment]
@NGA-TRAN  can you explain your usecase (what do you want to happen / not happen)? I don't fully understand it

**Comment by NGA-TRAN** [comment]
@alamb : What I mean is if there are extra things users have to do, we want to document clear instructions. Something like "your catalog has to be empty" or your catalog needs to have this record and what it is or what to run to insert that record. I remembered I ran all-in-one before and no error at all but nothing works. I guess my catalog has something conflict with the expectation (shard, topic,...)

**Comment by alamb** [comment]
> @alamb : What I mean is if there are extra things users have to do, we want to document clear instructions. Something like "your catalog has to be empty" or your catalog needs to have this record and what it is or what to run to insert that record. I remembered I ran all-in-one before and no error at all but nothing works. I guess my catalog has something conflict with the expectation (shard, topic,...)


I guess what I was thinking here is that after we switch the default mode to be based on sqlite in a known location, it should always be consistent (and thus won't have the 'your catalog must be empty' problems) that the current version does when you start it up and point it at a pre-existing catalog

But I may still be misunderstanding

**Comment by NGA-TRAN** [comment]
@alamb I think that is it. I can't wait to try when it is ready

**Comment by alamb** [comment]
I had some time on the plane today so I whipped up a proposal for this feature: https://github.com/influxdata/influxdb_iox/pull/7027
