### ISSUE TITLE
InfluxQL-IOx: Tag key existence or absence predicate in `WHERE` clause

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb_iox#6901]
Teach the InfluxQL planner how to generate a DataFusion LogicalPlan and Expr that supports testing the existence and absence of tag keys / values.

# Background

Given InfluxDB's schema-less architecture, it is possible to construct predicates which test the presence or absence of tag keys. These are constructed using the equals (`=`) and not equals (`!=`) operators, tested against an empty string literal. 

<details><summary>Expand to see the line protocol used by these examples</summary><p>

```
# INFLUXDB EXPORT: 1677-09-21T10:17:35+10:04 - 2262-04-12T09:47:16+10:00
# DDL
CREATE DATABASE aaa WITH NAME autogen
# DML
# CONTEXT-DATABASE:aaa
# CONTEXT-RETENTION-POLICY:autogen
# writing tsm data
m0,tag0=val00 f64=10.1,i64=101i,str="hi" 1667181600000000000
m0,tag0=val00 f64=21.2,i64=211i,str="hi" 1667181610000000000
m0,tag0=val00 f64=11.2,i64=191i,str="lo" 1667181620000000000
m0,tag0=val00 f64=19.2,i64=392i,str="lo" 1667181630000000000
m0,tag0=val01 f64=11.3,i64=211i,str="lo" 1667181600000000000
m0,tag0=val02 f64=10.4,i64=101i,str="lo" 1667181600000000000
m0,tag0=val00,tag1=val10 f64=18.9,i64=211i,str="lo" 1667181610000000000
m1,tag0=val00 f64=100.5,i64=1001i,str="hi" 1667181600000000000
m1,tag0=val00 f64=200.6,i64=2001i,str="lo" 1667181610000000000
m1,tag0=val01 f64=101.7,i64=1011i,str="lo" 1667181600000000000
# writing wal data
```
</p></details>

For example, to return all rows that have a tag key named `tag1` with any value:

```sql
select * from m0 where tag1 != ''
```
```text
name: m0
time                f64  i64 str tag0  tag1
----                ---  --- --- ----  ----
1667181610000000000 18.9 211 lo  val00 val10
```

Conversely, to return all rows that do not have the tag key `tag1`:

```sql
select * from m0 where tag1 = ''
```
```text
name: m0
time                f64  i64 str tag0  tag1
----                ---  --- --- ----  ----
1667181600000000000 10.1 101 hi  val00
1667181600000000000 10.4 101 lo  val02
1667181600000000000 11.3 211 lo  val01
1667181610000000000 21.2 211 hi  val00
```

### Requirements

There are two cases that must be handled in IOx, as outlined in the following sections.

#### Case 1: Column exists in table

If the column exists and the Influx type is `tag`, the logical plan must rewrite the predicate `tag0 != ''` to `tag0 IS NOT NULL` to test for the presence of values. The predicate `tag0 = ''` must be rewritten to `tag0 IS NULL` to test for the absence of values in the `tag0` column.

#### Case 2: Column does not exist or is not type `tag`

When the predicate is `tag0 = ''`, meaning to find rows that do not have a value for `tag0`, the logical plan is generated to include the table. It does not require a filter condition given the column doesn't, and therefore the tag is absent from all rows. 

When the predicate is `tag0 != ''`, meaning to find rows that have a value for `tag0`, the logical plan is generated to exclude the table.

#### Edge case: Rewriting regular expressions

InfluxQL rewrites fully anchored regular expression to use the `=` and `!=` operator. That means that a predicate such as `tag1 =~ /^$/` is equivalent to `tag = ''`, which is interpreted as a _tag exists_ test:

```sql
select * from m0 where tag1 =~ /^$/
```
```text
name: m0
time                f64  i64 str tag0  tag1
----                ---  --- --- ----  ----
1667181600000000000 10.1 101 hi  val00
1667181600000000000 10.4 101 lo  val02
1667181600000000000 11.3 211 lo  val01
1667181610000000000 21.2 211 hi  val00
```

Similarly, `tag1 !~ /^$/` is equivalent to `tag != ''`, or a _tag not exists_ test:

```sql
select * from m0 where tag1 !~ /^$/
```
```text
name: m0
time                f64  i64 str tag0  tag1
----                ---  --- --- ----  ----
1667181610000000000 18.9 211 lo  val00 val10
```

See #6902 for further information on tag existence.

**Comment by wolffcm** [comment]
@stuartcarnie In looking over what we do for the IOx implementation of Influx RPC, we make [this transformation](https://github.com/influxdata/influxdb_iox/blob/3ec40ca5c74029e8ca761a5c5f69abcf8bb75d45/service_grpc_influxrpc/src/expr.rs#L532C1-L560):
```sql
some_tag = ''
```
becomes
```sql
CASE some_tag
WHEN some_tag IS NULL
THEN ''
ELSE some_tag
END = ''
```
Do you have any thoughts on this? I can think of reasons to do it the way you've described in this issue, or in the Influx RPC way:
- converting to CASE/WHEN will get the right answer even when the RHS of a predicate is something that we don't know will evaluate to the empty string at plan time. E.g., `tag0 = substring('f00', 1, 0)` or something. I'm having a hard time coming up with a better example.
- converting to `some_tag IS [NOT] NULL` is more likely to be pushed down and more performant in general. It's also more intuitive to read in EXPLAIN PLAN.

Maybe you wrote this issue with a nuanced understanding of what OG actually does, and your proposal here will be more faithful to OG, but I wanted to check, since there's another option to get similar behavior.

**Comment by stuartcarnie** [comment]
Presumably you are only referring to **Case 1**, as **Case 2** is necessary to ensure that InfluxQL succeeds when the column does not exist.

I arrived at the `IS [NOT] NULL` version for the same reasons you stated, that it will likely be much more performant and can probably be pushed down. I imagine `IS [NOT] NULL` checks will use the null bitsets in Arrow to quickly include / exclude rows.

InfluxQL does simplify the expressions, so that `tag = '' + ''` will still perform the existence check. Similarly, if we were to add support for string functions, your `substirng` example would also work. Given that, would you prefer to simplify the InfluxQL `Expr` or add a new DataFusion rewrite rule that replaced `tag = ''` with `tag IS NULL`?

For reference, here is the logic for `tag_key = ''`:

https://github.com/influxdata/influxdb/blob/926020e331f7b3be79627ccd160858e630659689/tsdb/index.go#L2586-L2600

and conversely for `tag_key != ''`:

https://github.com/influxdata/influxdb/blob/f365bb7e3a9c5e227dbf66d84adf674d3d127176/tsdb/index.go#L2621-L2622

**Comment by wolffcm** [comment]
> Presumably you are only referring to Case 1, as Case 2 is necessary to ensure that InfluxQL succeeds when the column does not exist.

Yes, that's right.

> InfluxQL does simplify the expressions, so that tag = '' + '' will still perform the existence check. Similarly, if we were to add support for string functions, your substirng example would also work. Given that, would you prefer to simplify the InfluxQL Expr or add a new DataFusion rewrite rule that replaced tag = '' with tag IS NULL?

Thinking this over some more, I think it makes sense to use the existing techniques from IOx's implementation of Influx RPC and the DF expression simplifier. Here's some more background I discovered today.

Interestingly, the Influx RPC front end does not just use CASE/WHEN but also pushes the equality predicate into the CASE statement as @alamb informed me: https://github.com/influxdata/influxdb_iox/blob/607bc7243dc517aef4afe721fa98ca3633ee2001/predicate/src/rpc_predicate/rewrite.rs#L18C2-L34

And I can see that with expression simplification, the plans that get executed for `read-filter` are reasonable:

| case | read-filter predicate | optimized physical plan predicate |
| ---- | ------- | -------- |
| 0 | `host = 'foo'` | `host@1 = 'foo'` |
| 1 | `host != 'foo'` | `host@1 IS NULL OR host@1 != 'foo'` |
| 2 | `host = ''` | `host@1 IS NULL OR host@1 = ''` |
| 3 | `host != ''` | `host@1 != ''` |

[^1]

So I think it makes sense to use the same approach as was taken for Influx RPC. As we add more functionality to InfluxQL I think this approach will be more robust and get right answers.

[^1]: Is it possible to insert a zero-length tag value using line protocol? I'm sure that TSM would ignore such a tag value, but I'm not sure about IOx. If IOx behaves the same we might consider further rewriting predicates we get for case 2 to just `host@1 IS NULL`.

**Comment by wolffcm** [comment]
Further looking over the code in https://github.com/influxdata/influxdb_iox/blob/main/predicate/src/rpc_predicate/rewrite.rs, almost all of it is relevant to the work of this issue, and much of the code is re-usable for InfluxQL. It solves the exact problems described in this issue for both cases 1 and 2 above.

One challenge I have encountered is that we need the IOx schema (including the annotations that tell us which columns are tags) in order to make use of these transformations (which we would need to know whether we re-used Influx RPC code path or not), so that is my current area of inquiry.

**Comment by stuartcarnie** [comment]
Great that we can reuse that code ❤️
