### ISSUE TITLE
Consider parking lot instead or RwLock

### ISSUE THREAD

**Issue by e-dard** [influxdata/influxdb_iox#711]
From #710 

 	
> @shepmaster shepmaster 1 hour ago Member
>
> Since we aren't caring to handle the poisoning case, we might want to take a look at parking_lot. Their mutex implementation skips that, so you don't have to unwrap.

**Comment by tustvold** [comment]
An additional benefit is the MutexGuard can be [mapped](https://docs.rs/lock_api/0.4.2/lock_api/struct.MutexGuard.html#method.map) which is useful when wanting to return a reference to something protected by a lock.

This is possible with std::sync using the owning_ref crate, but nicer imo to have "first-party" support
