### ISSUE TITLE
InfluxQL-IOx: `GROUP BY TIME` precision limited to milliseconds

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb_iox#7204]
InfluxQL relies on the `DATE_BIN` function when producing an aggregate query that specifies a combination of `GROUP BY TIME` and `FILL(none)`. The `stride` parameter of the `DATE_BIN` function is limited to a maximum precision of milliseconds.

The `date_bin_gapfill` function will need to be amended to support `MonthDayNano` for the stride argument:

https://github.com/influxdata/influxdb_iox/blob/30fea67701d0f6c93d847a8bd3ab4dd2796af734/query_functions/src/gapfill.rs#L24

See:

https://github.com/apache/arrow-datafusion/blob/146a949218ec970784974137277cde3b4e547d0a/datafusion/expr/src/function.rs#L453

Depends on:

- https://github.com/apache/arrow-datafusion/issues/5697
- https://github.com/apache/arrow-datafusion/pull/5698

**Comment by stuartcarnie** [comment]
@wolffcm heads up that we can support microsecond and nanosecond precision for `date_bin` and `interval` expressions, so we can update the `date_bin_gapfill` function too.

**Comment by alamb** [comment]
Note the upstream issue has been fixed: https://github.com/apache/arrow-datafusion/pull/5698

I am working to ensure this fix is available in IOx
