### ISSUE TITLE
Implement API Reflection

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#721]
UPDATE: Our api is not gRPC based; gRPC services are defined with a protobuf schema; gRPC supports a reflection API that allows other tools to consume the schema implemented by a server and generate various things, from dyanamic clients to API playgrounds or documentation generators.

Old goal was:

An HTTP GET to `/` should return a description of the API endpoints available. The debug output from the Router in HTTP routes should probably suffice as it's fairly descriptive and, I believe, JSON.

**Comment by tustvold** [comment]
In the light of the migration to the gRPC interface I think the best re-intepretation of this ticket is adding support for gRPC reflection - which has recently been added to [upstream tonic](https://github.com/hyperium/tonic/issues/165)

**Comment by LucioFranco** [comment]
https://docs.rs/tonic-reflection/0.1.0/tonic_reflection/ should work for yall, lmk if you have any issues 😄
