### ISSUE TITLE
Add list databases API

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#722]
An HTTP GET to `/iox/api/v1/databases` should return a list of the databases the `server` knows about. This is the list of names that is in the `ConfigState` struct. The response should be a json object:

```
{
  "names": ["pauldb", "telegraf"]
}
```

Also add this to the `influxdb_iox_client` crate

**Comment by alamb** [comment]
I think this was closed in https://github.com/influxdata/influxdb_iox/pull/741 so closing issue

**Comment by mkmik** [comment]
> Also add this to the influxdb_iox_client crate

I _think_ I didn't do this part ^^^

**Comment by alamb** [comment]
@mkmik  -- good call -- added https://github.com/influxdata/influxdb_iox/issues/767 to track adding to the client
