### ISSUE TITLE
Add communication state API

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#723]
For an IOx server, it should track when it last successfully communicated with other IOx servers. If it makes a replication request, a subscription request or a query request. The endpoint:

```
GET /iox/api/v1/servers
```

Response:

```
{
  "servers" : [
    {"writer_id" : 23, "connection_string" : "...", "last_request_at" : "2021-02-02T12:00:00Z", last_response_code: 200}
  ]
}
```

Conductor can use this to build a view of which servers have been able to communicate with which other servers. This can also be used for Conductor or any other system to build discovery of a collection of IOx servers from a single one.

Also add this to the `influxdb_iox_client` crate

**Comment by jacobmarble** [comment]
@domodwyer has this been implemented, or, is the issue still useful?

**Comment by domodwyer** [comment]
It has not as far as I know - I'm not sure we're yet talking from router->query nodes so they wouldn't have this information yet.

I think this was from a prior design where IOx would have a mode to act as a write buffer (instead of kafka), but this can still be useful.
