### ISSUE TITLE
Add API to replay WAL

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#725]
We'll want to be able to replay the WAL from a given segment number. The code should be structured so that we can later have a Rust client be able to replay WALs directly from object storage as well, but this issue is for the HTTP based API.

```
GET /iox/api/v1/databases/:name/wal/data
```

Parameters:
* `writer_id` and `sequence_number` if one of these is provided, both must be provided. Read back in the WAL until you find this specific writer ID and sequence number and send out the data in order from that point. If we don't find it, read back until the limit is hit. We can either have the response header indicate if that write was found, or we could just include that write as the first in the stream.
* `limit` - number of individual writes to return. Default to 100
* `segment_limit` - limit to reading back to n segments, default to 100
* `no_older_than` - don't return data from segments created before this date. Optional

This data should actually be the Flatbuffer structures, so it won't be JSON. We'll have to use something else here. Maybe just an HTTP stream of bytes that sends out the individual ReplciatedWrite FB bytes, with type and length values (1 byte and 4 bytes) and then the actual FB bytes?

**Comment by tustvold** [comment]
Just thinking about this in the context of #747 and #748 which we've decided to use gRPC for largely to avoid having to handle the complexity of streaming binary data, and wonder if it might make sense to use gRPC for this.

This does raise the question of using gRPC as the primary API for IOx, with the HTTP API preserved for backwards-compatibility where IOx has to impersonate other systems. I'm not sure if this has been raised before, but thought it worth raising before significant effort is put into fleshing out this HTTP API as part of #769 among others.

There would be some other benefits from this change. It would avoid a non-trivial amount of work to produce an HTTP-API description system (#721), and the gRPC IDL has good cross-language support which would potentially help with #766.

The major downside I can foresee is it can complicate integration testing, but I imagine we will need a python (or similar) test harness for integration testing anyway and having the API in a standard language-agnostic format may actually end up helping with this.

**Comment by alamb** [comment]
@tustvold, I think @e-dard  and I kind of talked @pauldix  out of gRPC a while ago, I think with the basic argument that the tools for handling REST-ful APIs were the most mature, widely available, and language agnostic. 

The question is definitely worth revisiting,  and in my personal selfish opinion, the only thing I would be really sad about would be losing the ability to interact with IOx from the command line (e.g. `curl` / Postman /  something similar) without having to compile something,. 

Maybe  grpc_cli? https://chromium.googlesource.com/external/github.com/grpc/grpc/+/refs/heads/chromium-deps/2016-08-17/doc/command_line_tool.md

I tried `grpc_cli` against a locally running IOx server and got an error (though I don't really know what i am doing)

```
alamb@ip-10-0-0-49 ~ % grpc_cli ls localhost:8082
Received an error when querying services endpoint.
Reflection request not implemented; is the ServerReflection service enabled?
alamb@ip-10-0-0-49 ~ % 
```

**Comment by alamb** [comment]
To make it clear, I don't have a strong API opinion for the IOx management API. If the rest of the team wants to use gRPC i think that is a fine choice and I will figure out a way to deal.

**Comment by tustvold** [comment]
grpc-cli likely needs the reflection service running to get the proto definitions from the server, however, Tonic doesn't currently support this (https://github.com/hyperium/tonic/issues/165). That being said [grpcurl](https://github.com/fullstorydev/grpcurl) and [grpcui](https://github.com/fullstorydev/grpcui) both support being pointed at proto definition files and so should work.

> REST-ful APIs were the most mature, widely available, and language agnostic.

This statement really depends on what you mean by REST-ful APIs. If you mean swagger/OpenAPI APIs, then yes of the two OpenAPI generally has broader ecosystem support, although when it comes to Rust support I'd wager tonic is more mature than paperclip.

But, what is being proposed for IOx is in my opinion a different beast. It's an HTTP API with ad-hoc and/or custom documentation, potentially custom chunking logic and manual codegen. Discussions around gRPCs differing, and I'd argue better, protocol abstraction aside, I think I'd favor gRPC for precisely the reasons given for favouring a JSON+HTTP API :sweat_smile:

**Comment by pauldix** [comment]
It's true, my original plan was that the entire API would be gRPC 😄 .

I do like the ability to just curl or point a web browser at the API and get a result. But if we can figure out tooling to do something similar through grpcurl and grpui then I think that negates it.

I completely agree with the advantages you state for gRPC. Declarative API syntax and all that other stuff. The only real concern for me is what it would look like using it in other languages. The gRPC support is broad, but the generated code in those other languages is frequently a dumpster fire.

**Comment by tustvold** [comment]
> The gRPC support is broad, but the generated code in those other languages is frequently a dumpster fire.

My only experience of gRPC is python, C++ (CMake) and Rust (limited), and I don't recall there being any major issues. In general I found the generated code to be inoffensive, certainly compared to the likes of some of the OpenAPI generators. Was there a particular language you remember being bad?

> Also, what does it look like accessing the IOx API from the browser if everything is gRPC?

The short answer is you don't. The more complex answer is [grpc-web](https://grpc.io/blog/grpc-web-ga/) which relies on a translating proxy - further info [here](https://grpc.io/blog/state-of-grpc-web/).

**Comment by pauldix** [comment]
Right, `grpc-web` was the thing I saw last time I tried to deal with it. I suppose we can not worry about that for now, but at some point we'll have to at least make all the metadata APIs available from the browser. Let's discuss in our daily in a bit.

**Comment by tustvold** [comment]
Following internal discussion it has been agreed to explore using gRPC for all configuration APIs in addition to the data movement APIs, such as the one on this ticket. 

Assuming no major issues are found, only the following HTTP endpoints will continue to be exposed by IOx:

* Submit line protocol
* Submit JSON data
* SQL query returning JSON
* (Metrics and Health reporting)

In addition there will be the following gRPC Services exposed on the gRPC endpoint:

* Arrow Flight
* Influx Storage
* Replication and subscriptions between IOx instances
* Management API - database creation, metadata read/write, server configuration, etc...

For usability reasons it is important that the basic management functionality needed to bootstrap and manage a single IOx instance is exposed via the IOx CLI, which will handle communicating over the gRPC management API with the IOx instance.

**Comment by alamb** [comment]
Thank you @tustvold  -- I think this captures the outcome of the discussion nicely

**Comment by tustvold** [comment]
Summary of some further internal discussion:

* The server API will return errors following the conventions outlined [here](https://cloud.google.com/apis/design/errors), including returning the standard error details payloads for standard error codes
* The rust client will surface errors as semantically relevant errors (e.g. Database not found instead of resource not found)
* The rust client will only parse the error details field where it is necessary to provide the above guarantees
* The rust client will only depend on the generated_types crate not the data_types crate

**Comment by tustvold** [comment]
Closing in favour of #1073
