### ISSUE TITLE
Update read API

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#726]
The read API should be moved to

```
GET /iox/api/v1/databases/:name/query
```

Parameters:
* `q` which would be the SQL query string.
* `format` to specify the return format in `json|csv|pretty`. Should also be able to specify this via an Accepts request header.

Thoughts or preferences on the JSON return format?

**Comment by alamb** [comment]
@pauldix  👍 

BTW there is an open PR to arrow at the moment to produce JSON formatted output;

https://github.com/apache/arrow/pull/9256 (thanks @houqp!)

So I vote the JSON format should be the format produced by that writer 

I can take this one -- maybe later this week or early next

**Comment by mkmik** [comment]
this is still going to stay a REST API along with the gRPC management API right?

**Comment by alamb** [comment]
@mkmik  I believe that is correct

**Comment by alamb** [comment]
@jacobmarble  says he would appreciate this API sooner rather than later so I am going to try and whip something up later today or tomorrow
