### ISSUE TITLE
Replication MVP

### ISSUE THREAD

**Issue by domodwyer** [influxdata/influxdb_iox#7266]
A tracking issue to implement a MVP of write replication.

[Design doc](https://docs.google.com/document/d/105ZvPEHpEipIpTBQF9u3xjUxDORjP4mcoWxbdfh7i3A/edit?usp=sharing)

**Comment by jacobmarble** [comment]
Waiting for performance double-check from Deployments Team

**Comment by jacobmarble** [comment]
Still waiting for performance tests from Deployments.

Next development work: add concurrency to the implementation.
