### ISSUE TITLE
FlightSQL `GetFlightInfo` Schema does not include metadata for `CommandStatementQuery`

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#7282]
# Background
To run a FlightSQL query the interaction looks like:

Step 1: Call GetFlightInfo
```
client --> GetFlightInfo(CommandStatementQuery) --> server
          <----------------- (FlightInfo)  --------
```

Step 2: Call DoGet with a `Ticket` that was in the `FlightInfo` returned from step 1
```
client ----------> DoGet(Ticket) --------------> server
          <--------- (Stream of Data)  --------
```

In addition to a `Ticket` the `FlightInfo` returned in step 1 also returns a `Schema` which should match the schema of the stream of data returned in step 2.

# Bug Description
After https://github.com/influxdata/influxdb_iox/issues/7279 the types are the same 🎉 

However, the metadata is still different. Specifically the schema reported from  `GetFlightInfo` doesn't match the actual plan as the metadata is not included. 

# Reproducer:
See `flightsql_schema_matches` introduced in https://github.com/influxdata/influxdb_iox/pull/7283

If we uncomment `strip_metadata` we can see the difference in 
[batch.txt](https://github.com/influxdata/influxdb_iox/files/11028766/batch.txt)
[flight_info.txt](https://github.com/influxdata/influxdb_iox/files/11028767/flight_info.txt)

```diff
--- /tmp/batch.txt	2023-03-21 09:26:09
+++ /tmp/flight_info.txt	2023-03-21 09:26:14
@@ -1,4 +1,4 @@
-batch_schema:
+flight_info_schema:
 Schema {
     fields: [
         Field {
@@ -7,9 +7,7 @@
             nullable: true,
             dict_id: 0,
             dict_is_ordered: false,
-            metadata: {
-                "iox::column::type": "iox::column_type::tag",
-            },
+            metadata: {},
         },
         Field {
             name: "tag2",
@@ -17,9 +15,7 @@
             nullable: true,
             dict_id: 0,
             dict_is_ordered: false,
-            metadata: {
-                "iox::column::type": "iox::column_type::tag",
-            },
+            metadata: {},
         },
         Field {
             name: "time",
@@ -30,9 +26,7 @@
             nullable: false,
             dict_id: 0,
             dict_is_ordered: false,
-            metadata: {
-                "iox::column::type": "iox::column_type::timestamp",
-            },
+            metadata: {},
         },
         Field {
             name: "val",
@@ -40,9 +34,7 @@
             nullable: true,
             dict_id: 0,
             dict_is_ordered: false,
-            metadata: {
-                "iox::column::type": "iox::column_type::field::integer",
-            },
+            metadata: {},
         },
     ],
     metadata: {},
(base) (arrow_dev) alamb@MacBook-Pro-8 influxdb_iox % 
```

**Comment by crepererum** [comment]
I think this is DataFusion loosing field metadata in some cases. I have found that at least the logical projection node does that and I'm working on a patch.
