### ISSUE TITLE
Allow running end to end tests with `sqllite` catalog

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#7285]
# Problem statement
1. As a developer not familiar with the IOx codebase
2. I run `cargo test --test end_to_end -- flightsql_schema` and the tests pass 🎉 
3. Then I run the tests on CI and they fail 😢 (because unless `TEST_INTEGRATION` environment is set they are just return)

By way of example, here is the output of running a test. It is not possible to tell if this actually ran or was skipped (it depends on the environment)?

```shell
$ cargo test --test end_to_end -- flightsql_schema
   Compiling influxdb_iox v0.1.0 (/Users/alamb/Software/influxdb_iox/influxdb_iox)
    Finished test [unoptimized + debuginfo] target(s) in 6.90s
     Running tests/end_to_end.rs (/Users/alamb/Software/target-iox/debug/deps/end_to_end-0cc71e1d1fd67233)

running 1 test
test end_to_end_cases::flightsql::flightsql_schema_matches ... ok(B
```

You **can** use `--nocpature` which tells you `skipping end-to-end integration tests - set TEST_INTEGRATION and TEST_INFLUXDB_IOX_CATALOG_DSN to run
`

```shell
$ cargo test --test end_to_end -- flightsql_schema --nocapture
    Finished test [unoptimized + debuginfo] target(s) in 0.72s
     Running tests/end_to_end.rs (/Users/alamb/Software/target-iox/debug/deps/end_to_end-0cc71e1d1fd67233)

running 1 test
skipping end-to-end integration tests - set TEST_INTEGRATION and TEST_INFLUXDB_IOX_CATALOG_DSN to run
test end_to_end_cases::flightsql::flightsql_schema_matches ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 251 filtered out; finished in 0.00s
```

# Proposal
Now that we have #6169 (thanks @stuartcarnie 👋 ) I propose changing the behavior so:
1. If `TEST_INFLUXDB_IOX_CATALOG_DSN` is not set, end to end tests default to sqlite / file backed catalog (improve the dev experience)
2. If `TEST_INFLUXDB_IOX_CATALOG_DSN` is set, run using the postgres catalog
3. Ensure CI tests continue to run with `TEST_INFLUXDB_IOX_CATALOG_DSN` set to posgres (to ensure they are covering the production codepath)
4. (possibly) Add CI test to run end to end tests using the sqlite file catalog

# Background

Here is code that implement the check
https://github.com/influxdata/influxdb_iox/blob/a385bb2ab23e3d3ac94d23f2a0b97b5127a47213/test_helpers_end_to_end/src/lib.rs#L111-L149

This is described in https://github.com/influxdata/influxdb_iox/blob/main/docs/testing.md#running (though it needs to be updated to drop kafka references -- which @carols10cents  has actually done in [this WIP PR](https://github.com/influxdata/influxdb_iox/pull/7049/files?file-filters%5B%5D=.md&show-deleted-files=true&show-viewed-files=true#diff-c22885d97fa21ad974a3f5f982d92b6f45edc251fd34bc14223492ebd7391245))

**Comment by domodwyer** [comment]
This sounds like a good idea to me :+1:

**Comment by alamb** [comment]
Here is PR 1: https://github.com/influxdata/influxdb_iox/pull/7658

**Comment by alamb** [comment]
Update here is that I have a PR that can run the tests using a single sqlite catalog: https://github.com/influxdata/influxdb_iox/pull/7657 🎉 

However, it has uncovered race conditions with using the file based catalog that causes intermittent test failures; I am still working through what to do about this

**Comment by alamb** [comment]
Update here: 
1. https://github.com/influxdata/influxdb_iox/pull/7708 makes it possible to run the end to end tests with sqlite
2. https://github.com/influxdata/influxdb_iox/issues/7709 tracks work to get the tests to run using sqlite by default and in CI

**Comment by alamb** [comment]
Code was reverted in https://github.com/influxdata/influxdb_iox/pull/7714 so reopening this ticket
