### ISSUE TITLE
FlightSQL: Add test that tests decoded schema from `include_schema`

### ISSUE THREAD

**Issue by appletreeisyellow** [influxdata/influxdb_iox#7328]
As discussed in https://github.com/influxdata/influxdb_iox/pull/7307/files#r1147395314, we should 

> have a test that actually decodes the data in the `table_schema` column back to a `Schema` (to verify there is actual data in there)

Here is an example for a new test https://github.com/influxdata/influxdb_iox/pull/7307/files#r1145993112

**Comment by alamb** [comment]
I plan to pick this up this week

**Comment by alamb** [comment]
WIP https://github.com/influxdata/influxdb_iox/compare/chunchun/test-decoded-schema?expand=1

**Comment by alamb** [comment]
https://github.com/influxdata/influxdb_iox/pull/7385
