### ISSUE TITLE
feat: Implement table statistics for data fusion table provider

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#733]
Follow on from #730 

__Use case:__
DataFusion is used to plan IOx queries. It currently has a rudimentary cost based optimizer (used to pick join orders / inner / outer relations) but we expect the optimizer to become more sophisticated over time. 

This is likely not be important in the near term because there aren't many decisions DataFusion makes with these statistics but will be important longer term

__Proposal:__
Implement statistics for TableProvider (let DataFusion planner know abou cardinalities, etc). 

Aka implement this:
https://github.com/influxdata/influxdb_iox/pull/730/files#diff-e02d4dfd33c9ea99b3b34d4be7da3b133cca551d23f64f89bcf7b29b6cc33d80R173-R175

__Current behaviour:__
Default statistics (no knowledge) is returned

__Desired behaviour:__
Describe what you want.

__Alternatives considered:__
Describe other solutions or features you considered.

**Comment by jacobmarble** [comment]
@alamb please update the status of this issue.

**Comment by alamb** [comment]
This is done

**Comment by alamb** [comment]
Done in https://github.com/influxdata/influxdb_iox/pull/2038
