### ISSUE TITLE
[WRITE TEAM] Change customer facing references of "namespace" to "database"

### ISSUE THREAD

**Issue by garylfowler** [influxdata/influxdb_iox#7432]
The decision has been made to use the word "database" instead of "namespace" for all IOx offerings.  As such, we need to cosmetically change any references in APIs or CLIs that use the word namespace to "database".

This ticket is for Write team.  There are other tickets for the Query and AIM teams for their applicable code areas.  They roll up to this EPIC:  https://github.com/influxdata/idpe/issues/17396

**Comment by alamb** [comment]
cc @pauldix
