### ISSUE TITLE
InfluxQL-IOx: Add a `PlannerError` type to ensure consistent error messages

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb_iox#7462]
Simplify error handling in the InfluxQL planner, with the ability to distinguish exceptional / internal errors from query errors.

## Background

Currently, errors returned in the InfluxQL planner use the `DataFusion::Internal` variant for representing exceptional or unexpected situations, such as the following:

https://github.com/influxdata/influxdb_iox/blob/9f5fec42b840e86534efeac76c721a82de825eb2/iox_query_influxql/src/plan/planner.rs#L563

The `DataFusion::Internal` error is reserved for DataFusion-specific errors, and encourages the user to raise an issue against the DataFusion repository. InfluxQL internal errors are an IOx issue.

It is still useful for the planner to identify its own inconsistency errors and encourage the user to raise an IOx issue instead. 

One approach is to add a `PlannerError` enumeration with similar intent to the `DataFusionError` type. For example, a template might look like: 

```rust
enum PlannerError {
    Internal(String),
    // etc
}

impl Debug for PlannerError {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        todo!()
    }
}

impl Display for PlannerError {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Internal(msg) => // write a message with the msg and encourage the user to log an IOx issue
        }
    }
}

impl Error for PlannerError {}

impl PlannerError {
    /// An error that was the result of an invalid query.
    fn user(s: &str) -> DataFusionError {
        DataFusionError::Plan(s.to_owned())
    }

    /// An unexpected error whilst planning that represents a bug in IOx.
    fn internal(s: &str) -> DataFusionError {
        DataFusionError::External(Box::new(Self::Internal(s.to_owned())))
    }
}
```

**Comment by crepererum** [comment]
I suggest we don't introduce yet another error type but directly map to the right DF error type. See https://github.com/influxdata/influxdb_iox/pull/7519

And here's the mapping:

https://github.com/influxdata/influxdb_iox/blob/b9a49907fe869d9e4c82a1eb27b317c23eb982b5/service_common/src/error.rs#L4-L73
