### ISSUE TITLE
InfluxQL-IOx: Refactor `LIMIT` and `OFFSET` behaviour so it can be reused

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb_iox#7463]
Refactor the implementation of `LIMIT` and `OFFSET`, so it may be reused for other InfluxQL statements, such as `SHOW FIELD KEYS`:

https://github.com/influxdata/influxdb_iox/pull/7405#discussion_r1159150804

**Comment by wolffcm** [comment]
I think this is done? I can see `limit` being used for `SHOW TAG KEYS` here.
https://github.com/influxdata/influxdb_iox/blob/6969d94cdab17c4aae5958659719324976103239/iox_query_influxql/src/plan/planner.rs#L1503

**Comment by stuartcarnie** [comment]
It is being reused for the `SHOW` statements as mentioned by @wolffcm. Thanks for the reminder!
