### ISSUE TITLE
Implement the RemoteServer replicated write

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#747]
The `RemoteServer` trait in the server crate doesn't have a real underlying implementation. We should have the `influxdb_iox_client` create implement an interface to replicate a write.

On the other side of this, the server will need to implement an API to handle this. This should be in the gRPC API and should live at the endpoint `/iox/api/v1/databases/:name/replicate_write`

**Comment by jacobmarble** [comment]
@pauldix can this be closed?
