### ISSUE TITLE
Tracing Visibility during query: Propagate tracing spans over querier -> ingester RPC boundary

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#7477]
Similarly to https://github.com/influxdata/influxdb_iox/issues/6177

usecase: while analyzing query performance (see https://github.com/influxdata/idpe/issues/17252) the querier <----> ingester communication takes a significant portion of query execution time. I want to know where the time is  spent in more detail:

![Screenshot 2023-04-06 at 1 30 18 PM](https://user-images.githubusercontent.com/490673/230453255-6d44d18d-d2d1-4293-b8af-f523cc586c0f.png)
 

The current querier -> ingester RPC does not propagate the span information,  meaning information from the ingester is not linked  linked with the processing ine querier

* We should propagate the trace spans via RPC metadata from the querier, to the ingester.
* The absence of this tracing information should not cause an error in the ingester.

**Comment by alamb** [comment]
cc @crepererum

**Comment by domodwyer** [comment]
I just double checked - the spans are in-place in the ingester already, so likely just querier-side that needs to push them: https://github.com/influxdata/influxdb_iox/blob/8b25a3a64cdf372d4583aa2119a57022346ae165/ingester2/src/query/tracing.rs#L46-L63

**Comment by crepererum** [comment]
I'm pretty sure that worked at one point. @carols10cents (IIRC) implemented this and showed in a local jaeger instance that the traces are correct. Maybe some refactor broke it. Let me quickly check locally....

**Comment by crepererum** [comment]
I'm working on a PR to improve the trace hierarchy on the client (querier) side a bit to better visualize the connect+request+stream phases.

**Comment by alamb** [comment]
I am working on a PR to improve the display

**Comment by alamb** [comment]
Here is a PR that fixes it: https://github.com/influxdata/influxdb_iox/pull/7507
