### ISSUE TITLE
Implement subscriptions CRUD

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#750]
The HTTP API needs methods to list, add and remove subscriptions without having to update the entire `DatabaseRules` struct.

Add `name` field to the `Subscription` struct in `DatabaseRules`. 

The `Subscription` struct in `DatabaseRules` has a `host_group_id`, which should be updated to just have a `writer_id`. So it should go to a single other IOx server.

API:

```
# list all subscriptions for a database
GET /iox/api/v1/databases/:name/subscriptions
# create a database subscription, should error out if one of the same name already exists
POST /iox/api/v1/databases/:name/subscriptions
# update/replace an existing subscription
PUT /iox/api/v1/databases/:database_name/subscriptions/:subscription_name
DELETE /iox/api/v1/databases/:database_name/subscriptions/:subscription_name
``` 

This should likely come before #746 and #748 as they'll need this stuff.

**Comment by jacobmarble** [comment]
@pauldix can this be closed?

**Comment by pauldix** [comment]
This can be closed. Subscriptions are still on the roadmap, but I'll need to open up an issue with some higher level requirements on it. This was about the subscriptions that used to be in DatabaseRules.
