### ISSUE TITLE
Teach selector functions how to project additional fields

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb_iox#7533]
Teach the selector functions, such as `selector_first`, how to project additional fields for the matching row. An example invocation might be

```sql
SELECT selector_first(usage_idle, time, usage_system, usage_user) FROM cpu
```

and the expected output include a nested `fields` struct with the values of the additional fields for the matching timestamp:

```text
+----------------------------------------------------------------------------------------------------+
| selector_first(t.usage_idle,t.time,t.usage_system,t.usage_user)                                    |
+----------------------------------------------------------------------------------------------------+
| {value: 0.97, time: 1970-01-01T00:00:00.000001, fields: { usage_user: 0.02, usage_system: 0.01 } } |
+----------------------------------------------------------------------------------------------------+
```

> **Note**
>
> The additional field arguments must be column references and not arbitrary expressions.

```[tasklist]
- [x] Teach IOx `selector_` functions how to project additional fields
- [ ] Teach InfluxQL how to use updated IOx `selector_` functions
```

# Rationale

InfluxQL queries which project a single selector function, such as `first`, will produce a matching result and timestamp, such as the following example:

```SQL
SELECT first(usage_idle) FROM cpu
```

```
name: cpu
time                 first
----                 -----
2020-06-11T16:52:00Z 99.8015873015873
```

> **Note**
>
>  The `time` column reflects the timestamp for the `first` value of `usage_idle`, at `2020-06-11T16:52:00Z`

When projecting a single selector, it is possible to include additional fields for the matching timestamp:

```SQL
SELECT first(usage_idle), usage_system, usage_user FROM cpu
```

```
name: cpu
time                 first            usage_system       usage_user
----                 -----            ------------       ----------
2020-06-11T16:52:00Z 99.8015873015873 0.0992063492063492 0.0992063492063492
```

In this case, the columns `usage_system` and `usage_user` project the values of the `first` point at `2020-06-11T16:52:00Z`

**Comment by alamb** [comment]
The implementation of the selector functions is https://github.com/influxdata/influxdb_iox/blob/main/query_functions/src/selectors.rs
