### ISSUE TITLE
Additively merge namespace schema updates in the Router's NamespaceCache

### ISSUE THREAD

**Issue by savage-engineer** [influxdata/influxdb_iox#7575]
When schema validation for incoming writes occurs on the router, any changes to the schema from the write result in the `NamespaceCache` [being updated](https://github.com/influxdata/influxdb_iox/blob/a6ccb05caf2bb7d971f34782b4227ac36faa1b59/router/src/dml_handlers/schema_validation.rs#L295). The cache's `put_schema()` currently unconditionally overwrites the previous entry. 

This means a pair of parallel writes adding separate, new columns or tables to a namespace can knock the in-memory cache out of sync with the catalog. This will result in future write requests querying the catalog to get the most up-to-date schema. This de-synchronisation can be avoided by additively merging the cached set of tables and their columns with the new cache entry and spare unnecessary network calls.

**Comment by domodwyer** [comment]
> This de-synchronisation can be avoided by additively merging the current cached column schema with the new cache entry

Minor correction (probably I typo, but just to be sure):

This de-synchronisation can be avoided by additively merging the cached set of tables and their columns with the new cache entry
