### ISSUE TITLE
InfluxQL-IOx: InfluxQL internal errors should be more distinct

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb_iox#7606]
Update the `Display` implementation of the InfluxQL `Planner::Internal` error to be more consistent with DataFusion and allow a client to distinguish an InfluxQL internal error. The current prefix is `internal: `, which is not very useful for determining the source of the error. The recommended change is:

```
        #[error("InfluxQL internal error: {0}")]
        Internal(String),
```

## Background

Certain DataFusion errors which propagate over gRPC are returned as `INVALID_ARGUMENT` per:

https://github.com/influxdata/influxdb_iox/blob/ce273b6006b06c99610daa69861686d8bb628ff3/service_common/src/error.rs#L42-L54

This is problematic, as it is not clear to the client how to determine whether the error was the result of an invalid query, an internal IOx error or an internal DataFusion error.

The only stand out solution that does not require significant changes to DataFusion is to use the existing strings present in the various error kinds.

### Interesting errors

A `DataFusion::Plan` error indicates a problem with the SQL or InfluxQL query submitted by the user and contains `Error during planning: ` per:

https://github.com/apache/arrow-datafusion/blob/9798fbcab1e04123f05e7692475e104310e0473a/datafusion/common/src/error.rs#L320-L322

A `DataFusion::Internal` error indicates a bug with DataFusion, and contains `Internal error: ` per:

https://github.com/apache/arrow-datafusion/blob/9798fbcab1e04123f05e7692475e104310e0473a/datafusion/common/src/error.rs#L316-L319

Another form of internal error may originate during InfluxQL planning and indicates a bug with the IOx InfluxQL planner. This will contain `InfluxQL internal error: `

**Comment by alamb** [comment]
There are several places that DataFusion probably generates an internal error rather than a planning error -- if we run into these they should be fixed. I filed https://github.com/apache/arrow-datafusion/issues/6108 to track this

**Comment by stuartcarnie** [comment]
Great, thanks @alamb. 

I have done the same with the InfluxQL planner, so it no longer generates `DataFusion::Internal` errors. We don't have any other mechanism for propagating error codes, so for the time being, this will make it easier for a client to identify InfluxQL internal errors programmatically.
