### ISSUE TITLE
InfluxQL-IOx: Time range semantics should match InfluxQL OG

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb_iox#7610]
The time range predicate must be applied to the entire query such that

```sql
SELECT cpu, usage_idle FROM cpu 
WHERE cpu = 'cpu0' OR cpu = 'cpu1' AND time > '2020-06-11T16:53:30Z'
```

is the equivalent of

```sql
SELECT cpu, usage_idle FROM cpu 
WHERE (cpu = 'cpu0' OR cpu = 'cpu1') AND time > '2020-06-11T16:53:30Z'
```

and they must be rewritten using conjunction (`OR`) operators, regardless of how they appear in the original expression.

## Background

The InfluxQL query engine always promotes the time range expression to filter all results. It is misleading that time ranges are written in the `WHERE` clause, as the `WHERE` predicate is not evaluated in its entirety for each row. Rather, InfluxQL extracts the time range to form a time bound for the entire query and removes any time range expressions from the filter predicate. The time range is determined using the `>` and `≥` operators to form the lower bound and the `<` and `≤` operators to form the upper bound. When multiple instances of the lower or upper bound operators are found, the time bounds will form the intersection. For example

```sql
WHERE time >= 1000 AND time >= 2000 AND time < 10000 and time < 9000
```

is equivalent to

```sql
WHERE time >= 2000 AND time < 9000
```

Further, InfluxQL only allows a single `time = <value>` binary expression. Multiple occurrences result in an empty result set.

### Examples

Lets illustrate how InfluxQL applies predicates with a typical example, using the `metrics.lp` data in the IOx repository:

```sql
SELECT cpu, usage_idle FROM cpu 
WHERE 
  time > '2020-06-11T16:53:30Z' AND time < '2020-06-11T16:55:00Z' AND cpu = 'cpu0'
```

InfluxQL first filters rows based on the time range: 

```
'2020-06-11T16:53:30Z' < time <  '2020-06-11T16:55:00Z'
```

and then applies the predicate to the individual rows:

```
cpu = 'cpu0'
```

Producing the following result:

```text
name: cpu
time                 cpu  usage_idle
----                 ---  ----------
2020-06-11T16:53:40Z cpu0 90.29029029029029
2020-06-11T16:53:50Z cpu0 89.8
2020-06-11T16:54:00Z cpu0 90.09009009009009
2020-06-11T16:54:10Z cpu0 88.82235528942115
```

The following example is a little more complicated, but shows again how InfluxQL separates the time ranges from the predicate:

```sql
SELECT cpu, usage_idle FROM cpu 
WHERE 
  time > '2020-06-11T16:53:30Z' AND time < '2020-06-11T16:55:00Z' AND cpu = 'cpu0' OR cpu = 'cpu1'
```

InfluxQL first filters rows based on the time range: 

```
'2020-06-11T16:53:30Z' < time <  '2020-06-11T16:55:00Z'
```

and then applies the predicate to the individual rows:

```
cpu = 'cpu0' OR cpu = 'cpu1'
```

This is certainly quite different to SQL, which would evaluate the predicate as:

```sql
SELECT cpu, usage_idle FROM cpu 
WHERE 
  (time > '2020-06-11T16:53:30Z' AND time < '2020-06-11T16:55:00Z' AND cpu = 'cpu0') OR cpu = 'cpu1'
```

#### Time ranges are not normal

Finally, we demonstrate how the operators combining time ranges do not matter. Lets take the original query:

```sql
SELECT cpu, usage_idle FROM cpu 
WHERE 
  time > '2020-06-11T16:53:30Z' AND time < '2020-06-11T16:55:00Z' AND cpu = 'cpu0'
```

and rewrite it with `OR` operators

```sql
SELECT cpu, usage_idle FROM cpu 
WHERE 
  time > '2020-06-11T16:53:30Z' OR time < '2020-06-11T16:55:00Z' OR cpu = 'cpu0'
```

This should return all rows, but yet it returns the same result 🤯:

```text
name: cpu
time                 cpu  usage_idle
----                 ---  ----------
2020-06-11T16:53:40Z cpu0 90.29029029029029
2020-06-11T16:53:50Z cpu0 89.8
2020-06-11T16:54:00Z cpu0 90.09009009009009
2020-06-11T16:54:10Z cpu0 88.82235528942115
```

It becomes clearer, if we again review at how InfluxQL OG evaluates the `WHERE` predicate, InfluxQL first filters rows based on the time range, which uses the rules previously defined by finding `>` and `≥` to determine the lower bound and `<` and `≤`: 

```
'2020-06-11T16:53:30Z' < time <  '2020-06-11T16:55:00Z'
```

and then applies the predicate to the individual rows:

```
cpu = 'cpu0'
```

### How to think of it intuitively

Imagine a slight variation of InfluxQL has a separate _time bounds clause_. It could have two forms, first as a `BETWEEN`

```sql
SELECT cpu, usage_idle FROM cpu 
WITH TIME BETWEEN '2020-06-11T16:53:30Z' AND '2020-06-11T16:55:00Z'
WHERE 
  cpu = 'cpu0'
```

or as an `IN` to select multiple points

```sql
SELECT cpu, usage_idle FROM cpu 
WITH TIME IN ('2004-04-09T12:00:00Z', '2004-04-09T12:00:10Z', ...)
WHERE 
  cpu = 'cpu0'
```

## Problem

Currently InfluxQL on IOx is passing the entire filter predicate to DataFusion, meaning the following query:

```sql
select cpu, usage_idle from cpu where cpu = 'cpu0' or cpu = 'cpu1' and time > '2020-06-11T16:53:30Z'
```

is equivalent to:

```sql
select cpu, usage_idle from cpu where cpu = 'cpu0' or (cpu = 'cpu1' and time > '2020-06-11T16:53:30Z')
```

and therefore returning incorrect results with respect to InfluxQL OG. We can validate this by wrapping the `OR` condition in parenthesis to produce the same results as InfluxQL OSS:

```sql
select cpu, usage_idle from cpu where (cpu = 'cpu0' or cpu = 'cpu1') and time > '2020-06-11T16:53:30Z'
```

## Steps

Using `metrics.lp` in the IOx repository, execute

1. Execute

    ```sql
    select cpu, usage_idle from cpu where cpu = 'cpu0' or cpu = 'cpu1' and time > '2020-06-11T16:53:30Z'
    ```

## Expected results

time > '2020-06-11T16:53:30Z' is applied to entire result set producing:

```text
name: cpu
time                 cpu  usage_idle
----                 ---  ----------
2020-06-11T16:53:40Z cpu0 90.29029029029029
2020-06-11T16:53:40Z cpu1 99.89989989989989
2020-06-11T16:53:50Z cpu0 89.8
2020-06-11T16:53:50Z cpu1 99.8001998001998
2020-06-11T16:54:00Z cpu0 90.09009009009009
2020-06-11T16:54:00Z cpu1 99.8997995991984
2020-06-11T16:54:10Z cpu0 88.82235528942115
2020-06-11T16:54:10Z cpu1 99.8001998001998
```

## Actual results

```text
name: cpu
time                 cpu  usage_idle
----                 ---  ----------
2020-06-11T16:52:00Z cpu0 89.56262425447316
2020-06-11T16:52:10Z cpu0 88.6113886113886
2020-06-11T16:52:20Z cpu0 88.6
2020-06-11T16:52:30Z cpu0 83.41708542713567
2020-06-11T16:52:40Z cpu0 87.76119402985074
2020-06-11T16:52:50Z cpu0 88.78878878878879
2020-06-11T16:53:00Z cpu0 86.91308691308691
2020-06-11T16:53:10Z cpu0 89.88988988988989
2020-06-11T16:53:20Z cpu0 89.01098901098901
2020-06-11T16:53:30Z cpu0 90.4
2020-06-11T16:53:40Z cpu0 90.29029029029029
2020-06-11T16:53:40Z cpu1 99.89989989989989
2020-06-11T16:53:50Z cpu0 89.8
2020-06-11T16:53:50Z cpu1 99.8001998001998
2020-06-11T16:54:00Z cpu0 90.09009009009009
2020-06-11T16:54:00Z cpu1 99.8997995991984
2020-06-11T16:54:10Z cpu0 88.82235528942115
2020-06-11T16:54:10Z cpu1 99.8001998001998
```

**Comment by pauldix** [comment]
Another way to think of this is to look at it in the context of the InfluxDB 1.x architecture. In the WHERE clause you can have tags, fields and the time show up. InfluxDB will use the tags that show up to do lookups in the inverted index to match which time series will need to be scanned. It applies whatever time appeared in the WHERE clause to all cursors that matched the other filtering.

It's kind of insane, but I'm pretty sure we did this because queries that didn't filter on time always made for a bad user experience (i.e. they took forever on any real dataset) and the user almost always meant to filter whatever selection of data they had by the same time range.

But the language semantics are obviously completely inconsistent 😬
