### ISSUE TITLE
Implement list_with_delimiter for Azure object storage

### ISSUE THREAD

**Issue by carols10cents** [influxdata/influxdb_iox#765]
We [left this as `unimplemented`](https://github.com/influxdata/influxdb_iox/blob/8399c565870eab61cee149f7e59ecfc9230f0502/object_store/src/azure.rs#L187-L189).

**Comment by shepmaster** [comment]
Started in [jg/azure-list-with-delimiter](https://github.com/influxdata/influxdb_iox/tree/jg/azure-list-with-delimiter), but the azure crate doesn't seem to provide a way to get the `common_prefixes` data yet.
