### ISSUE TITLE
Can't alias columns with 'interpolate' or 'locf' operations

### ISSUE THREAD

**Issue by sanderson** [influxdata/influxdb_iox#7684]
In the process of testing `date_bin_gapfill`  with `interpolate` and `locf`, I found that you cannot alias columns when using `interpolate` or `locf`.

```sql
SELECT
  date_bin_gapfill(INTERVAL '30 minutes', time) as _time,
  room,
  interpolate(avg(temp)) as temp_interpolated,
  locf(avg(temp)) as temp_locf
FROM home
WHERE
    time >= '2022-01-01T08:00:00Z'
    AND time <= '2022-01-01T10:00:00Z'
GROUP BY _time, room
```

Returns this error:

> executing query: failed to create Flight record reader: arrow/flight: could not create flight reader: arrow/ipc: could not read schema from stream: arrow/ipc: could not read message schema: rpc error: code = Internal desc = Error while planning query: handle_gap_fill
caused by
Internal error: Optimizer rule 'handle_gap_fill' failed due to unexpected error: Error during planning: interpolate may only be used in the SELECT list of a gap-filling query. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker

Also note that if I use the same aggregate function with both `interpolate` and `locf`, in the results, the column is duplicated with results from only one of the gap filling functions:

| _time                | room        | AVG(home.temp) | AVG(home.temp) |
| :------------------- | :---------- | -------------: | -------------: |
| 2022-01-01T08:00:00Z | Kitchen     |             21 |             21 |
| 2022-01-01T08:30:00Z | Kitchen     |             21 |             21 |
| 2022-01-01T09:00:00Z | Kitchen     |             23 |             23 |
| 2022-01-01T09:30:00Z | Kitchen     |             23 |             23 |
| 2022-01-01T10:00:00Z | Kitchen     |           22.7 |           22.7 |
| 2022-01-01T08:00:00Z | Living Room |           21.1 |           21.1 |
| 2022-01-01T08:30:00Z | Living Room |           21.1 |           21.1 |
| 2022-01-01T09:00:00Z | Living Room |           21.4 |           21.4 |
| 2022-01-01T09:30:00Z | Living Room |           21.4 |           21.4 |
| 2022-01-01T10:00:00Z | Living Room |           21.8 |           21.8 |

I think this is because without the ability to alias, the output columns inherit the name of the aggregate function and end up named the same.

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Write the [data provided in the getting started documentation](https://docs.influxdata.com/influxdb/cloud-serverless/get-started/write/).
2. Run the following query above against that data (adjust the time range as needed).

__Expected behaviour:__
Results with aliased columns.

__Actual behaviour:__
Returns an error.

**Comment by wolffcm** [comment]
I think it's fair to close this bug as fixed by #7725.

As for this part of the issue:
> Also note that if I use the same aggregate function with both `interpolate` and `locf`, in the results, the column is duplicated with results from only one of the gap filling functions

Now it will return an error `multiple fill strategies for the same column` for that case.

I filed https://github.com/influxdata/influxdb_iox/issues/7760 to do the work to make that work correctly. It would be a bit of effort and it's unclear to me how important it is.
