### ISSUE TITLE
Debug Tool: Load Parquet files directly into an IOx catalog

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#7744]
__Use case:__
As a developer I want to debug problems / reproduce issues locally in my development environment (not production) so I can examine the system more and test out possible fixes. 

We have good debug tools to fetch parquet files from production systems (`remote store get`) but there is no good way to use those parquet files locally as the corresponding catalog metadata is not available and most parts of IOx like the querier and compactor expect the metadata to be present 

This has come up in:
1. https://github.com/influxdata/influxdb_iox/issues/7687 (trying to reproduce compactor plans)
2. https://github.com/influxdata/idpe/issues/17556 (trying to reproduce a specific plan seen in production)

A more sophisticated version of this functionality (e.g. importing pre-existing files into a catalog) is described in [IOx Bulk Ingest / TSM Migration](https://docs.google.com/document/d/1Ofdd0XEaREjxxLq8w8BRXKD4HAVPvrUOWmqH-VgVgZI/edit). The debug tool may be able to provide an initial implementation of code that could be used in the bulk ingest path.

__Proposal:__

What I want to do
1. Download the relevant parquet files from production (using `remote store get-table` or some other means)
2. Run a command that inserts those files into a local catalog and object store as though they had been created directly

Here is a proposed session:
```shell
# Get parquet for a particular partition from the `incoming_lines`
# table into the `incoming_lines.count` directory
influxdb_iox remote store get-table --partition-id 13180488  4ffa1256cf09608b_2b62db476a21c690 'incoming_lines'

# Copy the parquet files from incoming_lines.count into the iox catalog
# stored in /tmp/catalog.sqlite and objectstore /tmp/object_store
# in namespace `new_namespace`
influxdb_iox --catalog-dsn=file:///tmp/catalog.sqlite --data-dir=/tmp/object_store debug import_parquet new_namespace 'incoming_lines'

# startup IOx
influxdb_iox --catalog-dsn=file:///tmp/catalog.sqlite --data-dir=/tmp/object_store  run &

# Query the data and expect it will be present
influxdb_iox query new_namespace 'select * from incoming_lines'
```

__Alternatives considered:__

A nice follow on to this project would be to make the parquet import function a service 

The recently removed `remote store pull` was a partial attempt to satisfy this usecase (but it copied files and metadata directly from one catalog/object_store to another): https://github.com/influxdata/influxdb_iox/pull/7688 but it seemed to have bitrotted

__SubTasks__
- [x] https://github.com/influxdata/influxdb_iox/pull/7688
- [x] https://github.com/influxdata/influxdb_iox/pull/7779
- [ ] https://github.com/influxdata/influxdb_iox/issues/7803

**Comment by crepererum** [comment]
> Download the relevant parquet files from production (using `remote store get-table` or some other means)

These files will likely NOT contain all the necessary metadata. So I would phrase this as: "download files AND all relevant metadata".

**Comment by NGA-TRAN** [comment]
Great proposal @alamb . A few more details:

- Down loading files for a partition is great use case. The other smaller use case that happen to us maybe more often is only certain files we need the queries to run or the compactor to compact. We currently have a way to download one file only:

```
# get a parquet file using its uuid
influxdb_iox remote store get <remote_file_uuid>  <your_local_path_to_store_the_file>
```

If we happen to need 10 files which are a lot t to put in the command line but we do not want to download full partition which may have hundreds or even thousands of files. Maybe we want to command like 

```
# get a parquet files of uuids in a file
influxdb_iox remote store get <file_that_stores_many_remote_uuids>  <your_local_path_to_store_the_files>
```

2. Like Marco pointed out that the file meta da is not enough for needed meta data to run queries/compact plans. However, the files do include `namespace_id, table_id, partition_id`. We may use that info to go to the remote DB to get the needed meta data and recreate them in the local catalog.

3. The downloaded parquet files may have changed to `to_delete`. So depending what we need but in the 2 use cases you listed, we want this `to_delete` field empty for compactor and querier to pull them.

**Comment by NGA-TRAN** [comment]
> The remote store get-table command currently ignores entries with to_delete IS NOT NULL -- which I think makes sense for my use cases.

Yes, this is one use case.
But for the use cases where we do want those specific files (by specifying their UUID), we do want to download them no matter what `to_delete` value is but when we add them into local `parquet_file` catalog, we make `to_delete` field empty/null. This is the use case when we run query in remote DB, `to_delete` is null but after a while the compactor compacts it and `to_delete` becomes not null. We still want those files but make them force them not deleted in our local environment

**Comment by alamb** [comment]
> But for the use cases where we do want those specific files (by specifying their UUID),
> We still want those files but make them force them not deleted in our local environment

I think perhaps when we need this usecase we can figure out how to handle it correctly.

**Comment by alamb** [comment]
Internal showme demo: https://influxdata.slack.com/archives/CG8NACC8M/p1683319922221869

**Comment by alamb** [comment]
Per @NGA-TRAN 's comment on  https://github.com/influxdata/influxdb_iox/issues/7744#issuecomment-1535250798, I filed https://github.com/influxdata/influxdb_iox/issues/7803

**Comment by alamb** [comment]
I plan to work on this when I have time, but I don't know when that might be

**Comment by alamb** [comment]
Internal slack showme: https://influxdata.slack.com/archives/CG8NACC8M/p1688758923144309?thread_ts=1683319922.221869&cid=CG8NACC8M
