### ISSUE TITLE
Change methods in the `schema` crate that take `&str` parameters to take `impl Into<String>` when possible

### ISSUE THREAD

**Issue by carols10cents** [influxdata/influxdb_iox#7764]
[See this comment for context](https://github.com/influxdata/influxdb_iox/pull/7692#discussion_r1187396809).

Methods like [`schema::SchemaBuilder::influx_column`](https://github.com/influxdata/influxdb_iox/blob/dc1a9e9ed6ff45c099e828c5e083d85cc2e70c09/schema/src/builder.rs#L61) currently take `&str` arguments, then pass those (eventually) to [`arrow::datatypes::Field::new`](https://docs.rs/arrow/latest/arrow/datatypes/struct.Field.html#method.new), which takes `impl Into<String>`. 

Change our methods from `&str` to `impl Into<String>` to match the arrow methods, which would let callers decide whether they want to borrow or give up ownership.

**Comment by kayagokalp** [comment]
I have been looking into the repo for some time now, this looks like a good starting point to lend a hand. I will open a PR if no one beats me to it.

To clarify by 

> Methods like [schema::SchemaBuilder::influx_column](https://github.com/influxdata/influxdb_iox/blob/dc1a9e9ed6ff45c099e828c5e083d85cc2e70c09/schema/src/builder.rs#L61) 

do you mean the methods implemented for `SchemeBuilder`? Like:

1.  https://github.com/influxdata/influxdb_iox/blob/dc1a9e9ed6ff45c099e828c5e083d85cc2e70c09/schema/src/builder.rs#L38
2. https://github.com/influxdata/influxdb_iox/blob/dc1a9e9ed6ff45c099e828c5e083d85cc2e70c09/schema/src/builder.rs#L46
3. https://github.com/influxdata/influxdb_iox/blob/dc1a9e9ed6ff45c099e828c5e083d85cc2e70c09/schema/src/builder.rs#L61
4. https://github.com/influxdata/influxdb_iox/blob/dc1a9e9ed6ff45c099e828c5e083d85cc2e70c09/schema/src/builder.rs#L72
