### ISSUE TITLE
GC should batch get_by_object_store_id() lookups

### ISSUE THREAD

**Issue by domodwyer** [influxdata/influxdb_iox#7784]
In a cluster where we're clearing a backlog of orphaned files in object storage (via the garbage collector) it's causing a relatively high query workload against the catalog:

![plot](https://github.com/influxdata/influxdb_iox/assets/9275968/c20a9012-60d0-4efb-bcfd-ae3fd89adf0d)

The `parquet.get_by_object_store_id()` calls are only made by GC, and are responsible for **~70% of the catalog load** for the last few days in a cluster processing several thousand writes/s:

https://github.com/influxdata/influxdb_iox/blob/36c1d23e19d3dd258bdc7dd350082355bbc3ed82/garbage_collector/src/objectstore/checker.rs#L92

Instead of performing one query per ID, we should batch the ID lookups (for example, look up 500 IDs at once). This will significantly reduce the catalog load!

**Comment by philjb** [comment]
much success in one cluster.

![Screenshot 2023-06-15 at 11 35 41 AM](https://github.com/influxdata/influxdb_iox/assets/13472206/550051b3-17b3-
4861-9d23-348f6dd59273)
