### ISSUE TITLE
InfluxQL-IOx: Inconsistent time-bounds behaviour

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb_iox#7829]
Ensure time-bounds behaviour is consistent with InfluxQL OG for gap-filling and subqueries.

- [x] InfluxQL-IOx: Ensure gap filling uses minimum bounds for time range
    - #7889
- [x] InfluxQL-IOx: Identify lower and upper bounds for time range
    - #7913
- [ ] InfluxQL-IOx: Ensure time ranges for subqueries are narrowed by outer query(s)

# Background

InfluxQL OG resolves the issues described previously using the following solutions:

* Simplify time ranges to a single lower and upper bound
* Propagate outer query time ranges to subqueries when specified and the outer range is narrower.

As a result of simplifying time ranges and propagating the time range expressions from parent to child, it should address the issue with gap filling, as described:

https://github.com/influxdata/influxdb_iox/blob/e88d8befdbeedc346e785105db777feebe4fedf5/iox_query_influxql/src/plan/planner.rs#L2027-L2031

## Issue: Gap filling

Currently, InfluxQL gap filling uses the `find_time_range` API to determine the lower and upper bounds:

https://github.com/influxdata/influxdb_iox/blob/e88d8befdbeedc346e785105db777feebe4fedf5/iox_query_influxql/src/plan/planner.rs#L2035

The issue is that multiple time expressions can confuse the `find_time_range` function. For example, running the following query using the `issue_6112` end-to-end test:

```sql
SELECT COUNT(usage_idle) FROM cpu WHERE time >= '2022-10-31T02:00:00Z' AND time <= '2022-10-31T02:00:05Z' AND time <= '2022-10-31T02:00:10Z' GROUP BY TIME(10s) FILL(0)
```

Produces the following output:

```
name: cpu
+---------------------+-------+
| time                | count |
+---------------------+-------+
| 2022-10-31T02:00:00 | 3     |
| 2022-10-31T02:00:10 | 0     |
+---------------------+-------+
```

These results are incorrect and inconsistent with InfluxQL OG, due `find_time_range` using the last observed `time` predicate, `time <= '2022-10-31T02:00:10Z'`.

The expected output is:

```
name: cpu
+---------------------+-------+
| time                | count |
+---------------------+-------+
| 2022-10-31T02:00:00 | 3     |
+---------------------+-------+
```

The query is incorrect as for the interval `2022-10-31T02:00:10`, the count is `0`, when in fact there are 3 results:

```
name: cpu
+---------------------+------------+
| time                | usage_idle |
+---------------------+------------+
| 2022-10-31T02:00:00 | 2.98       |
| 2022-10-31T02:00:00 | 0.98       |
| 2022-10-31T02:00:00 | 1.98       |
| 2022-10-31T02:00:10 | 2.99       |
| 2022-10-31T02:00:10 | 0.99       |
| 2022-10-31T02:00:10 | 1.99       |
+---------------------+------------+
```

InfluxQL OG addresses this issue, as it evaluates and extracts time ranges using the `ConditionExpr` function:

https://github.com/influxdata/influxql/blob/802555d6b3a35cd464a6d8afa2a6511002cf3c2c/ast.go#L5700-L5704

which includes substituting `now()` with the query execution time, allowing time ranges expressions to be simplified completely.

## Other reading

Time ranges are special in InfluxQL, and whilst they appear in the `WHERE` clause, they are not evaluated as part of the whole expression. For an explanation of time range behaviour, see:

- #7610

Secondly, time bounds should be propagated as described in

- #6897

**Comment by wolffcm** [comment]
> These results are incorrect and inconsistent with InfluxQL OG, due find_time_range using the last observed time predicate, time <= '2022-10-31T02:00:10Z'.

This seems like `find_time_range` needs to be fixed? It should be looking at the existing accumulated bounds and only update them if the new predicate makes the range smaller.

**Comment by stuartcarnie** [comment]
> This seems like `find_time_range` needs to be fixed? It should be looking at the existing accumulated bounds and only update them if the new predicate makes the range smaller.

Agreed, as it will be important for SQL. The behaviour of this function was not the core issue for InfluxQL, as my problem stemmed from the fact that the logical planner processes the tree bottom-up. However, to match InfluxQL OG, we must push the time-range expressions top-down when processing subqueries, and therefore we needed an API to resolve these from the InfluxQL expressions. This top-down approach will also mean the correct time bounds are generated for gap-filling node during the bottom-up pass.
