### ISSUE TITLE
Return partition template protobuf in Namespace and Tables

### ISSUE THREAD

**Issue by carols10cents** [influxdata/influxdb_iox#7867]
See https://github.com/influxdata/influxdb_iox/pull/7826#discussion_r1205513231 for some context. In that PR and in https://github.com/influxdata/influxdb_iox/pull/7790, we added gRPC APIs to set partition templates on namespaces and tables.

However, there's currently no gRPC API that reads those templates back _out_. 

So this ticket is for adding `partition_template` to [the Namespace message](https://github.com/influxdata/influxdb_iox/blob/cdd519424dd102cac5162899fcb0fde21103a1dc/generated_types/protos/influxdata/iox/namespace/v1/service.proto#L90) and the Table message added in https://github.com/influxdata/influxdb_iox/pull/7826 and populate those fields from the catalog wherever they're used.

Those `Namespace` and `Table` messages make sense to have that field because they're the messages returned from the `Create` requests-- should the `partition_template` also be added to [the `NamespaceSchema` and `TableSchema` messages in the schema service](https://github.com/influxdata/influxdb_iox/blob/cdd519424dd102cac5162899fcb0fde21103a1dc/generated_types/protos/influxdata/iox/schema/v1/service.proto#L19-L41)?

**Comment by domodwyer** [comment]
I think just the types (`Namespace` and `Table`) you mention will be good! The schema types don't contain other metadata (they have just the schema) so I think they should be left as-is :+1:

**Comment by savage-engineer** [comment]
Oops, looks like I duplicated this somewhat with #8576.
