### ISSUE TITLE
Race condition theoretically possible with table partition templates and non-tag columns

### ISSUE THREAD

**Issue by carols10cents** [influxdata/influxdb_iox#7871]
[Currently, custom partition templates may only use tag columns](https://github.com/influxdata/influxdb_iox/blob/d68a399a7bd1f54df8fa2d04d55a338508cfafc5/mutable_batch/src/payload/partition.rs#L85-L94) (and format the time column).  

This restriction is enforced by, on table creation, going through the tag value columns used in the partition template and creating them as tag columns in the table's schema so that future writes will get an error if they try to send non-tag data in that column.

The table creation catalog request and the column creation catalog requests are not currently happening within a transaction, so there's a small chance that a user who is particularly unlucky and also trying to do something unsupported could have this happen:

> T1: create() table -> OK
> T2: write hits schema validator (runs before partitioner in the router)
> T2: schema upserts my_tag as u64
> T1: attempts to set tag type: columns().create_or_get("my_tag", id, TAG); -> error
> T1: returns error to user
> T2: request hits partitioner, partitioner refuses write, returning an error because the template uses my_tag as a tag column to partition, and it is not a tag.

The fix is making a new catalog function that does both the table creation and column creation in a transaction.

[More context in this comment](https://github.com/influxdata/influxdb_iox/pull/7826#discussion_r1205545031).

**Comment by domodwyer** [comment]
Actually - I forgot that attempting to partition using non-tag columns is not an error - it's a panic!

https://github.com/influxdata/influxdb_iox/blob/0b9b775fbd5a47a8e8c918fab5d704af3f576b5e/mutable_batch/src/payload/partition.rs#L89-L92

This changes the risk profile a little - it's now a potential DoS vector - we should cover this off.

The `table.create()` method is given the partition key, so we can use that to do the loop below _within the catalog method_, where we can run it as part of a transaction:

https://github.com/influxdata/influxdb_iox/blob/0b9b775fbd5a47a8e8c918fab5d704af3f576b5e/service_grpc_table/src/lib.rs#L116-L137

This will eliminate the race, and it'll not require adding another catalog method!
