### ISSUE TITLE
Disk Full Protection

### ISSUE THREAD

**Issue by domodwyer** [influxdata/influxdb_iox#7899]
The ingester writes WAL entries to a local disk, if this disk becomes full, the ingester will be unable to make progress.

We should:

* Emit "free space" metrics for the WAL disk
* Stop ingesting when we're down to ~10% disk free

Lets discuss this to produce a detailed design before starting.
```[tasklist]
### Tasks
- [x] Emit "free space" metrics for the WAL disk
- [ ] Stop ingesting when we're down to ~10% disk free
```

**Comment by crepererum** [comment]
Another backup measure that I've seen on top of the "stop when there're only 10% left": create a file that occupies around 10% disk space that you could delete if you really wanna make some more space for emergency measures and that can buy you some time.

**Comment by aierui** [comment]
In a large-scale distributed environment, we often encounter various types of hardware failures, such as machine crashes, disk read-only, etc.

We can add service state to the Ingester instance, the specific state machine diagram is roughly as follows.

```
                       ┌────────────────┐              
                    ┌──│     Stable     │◀─┐           
                    │  └───▲─────────┬──┘  │           
                    │      │         │     │           
                    │      │   Set   │     │           
                    │      │         │     │           
                    │  ┌───┴─────────▼──┐  │           
                    │  │    Readonly    │  │           
   Instance Failure │  └────────┬───────┘  │ Recovery  
                    │           │          │           
                    │   Instance Failure   │           
                    │           │          │           
                    │           │          │           
                    │  ┌────────▼───────┐  │           
                    └─▶│     Broken     │──┘           
                       └────────────────┘              
```

- When the disk space is almost full or when the disk is read-only, can trigger a status flow to Readonly

**Comment by domodwyer** [comment]
Hey @aierui!

What you describe is a great way of preserving availability in the presence of faults - we already have the capability to switch the ingester to a read-only state for some cases!

For each write, the first thing the ingester does is check an atomic flag variable:

https://github.com/influxdata/influxdb_iox/blob/cff6783241edeaed2bce9ec502374fb0316128b3/ingester/src/server/grpc/rpc_write.rs#L134-L152

When this flag is set, we reject the write, but continue servicing queries and trying to persist to object storage - this turns the ingester into a read only system as you describe :tada:

We currently use this primitive to gracefully stop the ingester (rejecting writes as we flush buffered data and shutdown), and also when we detect that the number of persist jobs has exceeded the configured limit (suggesting the ingester is receiving more writes than it can flush out through persistence - a common problem when the object store is unavailable).

I want to expand this to include disk utilisation (this ticket) but I also have an idea for tracking the overall RAM utilisation too. I'm sure we'll add more!

Dom

**Comment by aierui** [comment]
Looks great. Also the router instance contains a probe, which looks good enough for a production environment.
