### ISSUE TITLE
HTTP /api/v2/query

### ISSUE THREAD

**Issue by lmangani** [influxdata/influxdb_iox#7929]
## Describe Development Experience Issue:

The `/api/v2/query` API is mentioned in docs and used in several tests/examples, but does not seem to be included in this repository and only write APIs appear to be implemented. Is there a way to enable it as a feature at build time, or is this to be considered a cloud only feature at this time?

Thanks!

### Steps to reproduce:

1. build iox and start all-in-one
2. curl `localhost:8080/api/v2/query`
3. `404`

## Build Environment:

I'm building IOx using [Github Actions](https://github.com/metrico/iox-community/blob/main/.github/workflows/build-musl.yml)

**Comment by philjb** [comment]
Iox in this repo uses a arrow flight client for queries in sql or influxql. You can find an example using the iox binary in the readme. https://github.com/influxdata/influxdb_iox/blob/main/README.md#write-and-read-data

HTTP `api/v2/query` is the influxdb endpoint in cloud iox and tsm-based influxdb.

**Comment by alamb** [comment]
> Are the api/v2/query handlers expected to become part of OSS IOx at some point, or will gRPC remain the only method for querying?

I think this is a question for @pauldix

cc @garylfowler  @rickspencer3

**Comment by lmangani** [comment]
Thanks, this already helps. To further clarify: we're super happy either way, just trying to plan an integration with iox _(both cloud and oss)_ and wanted to understand if this part should be considered out of scope for the moment.

**Comment by pauldix** [comment]
IOx itself won't support the v2 query API. Its preferred query interfaces are FlightSQL and InfluxQL over Flight. We need to update the readme to indicate that it won't be supporting the v2 API outside of the write endpoint. This is of course different in our Cloud Serverless environment.

**Comment by zekena2** [comment]
If IOx support InfluxQL then maybe supporting an http endpoint like v1 influxdb would be easy and convenient for something like Grafana to use. It would be hard to migrate dashboards from InfluxQL to FlightSQL and AFAIK Nothing actually support InfluxQL over FlightSQL.

**Comment by alamb** [comment]
> AFAIK Nothing actually support InfluxQL over FlightSQL.

Yes, that is accurate. We have discussed the possibility internally, but given how tightly coupled FlightSQL is to SQL (date model, tables, etc) it is not clear that it will ever be possible.

Note Paul said "FlightSQL and InfluxQL over Flight" as IOx has a native API built on Flight (**In Addtion** to FlightSQL, **NOT** the same)

**Comment by zekena2** [comment]
Does that entail that the open source and the enterprise version 3.0 won't support flux or influxql http endpoint? Or it will be supported somehow via a compatibility layer?

**Comment by pauldix** [comment]
Open source and commercial versions will also support the v1 query API with InfluxQL. We've implemented InfluxQL natively and in our cloud product we've implemented a v1 API bridge. We'll be bringing something like that over to open source in the future.

**Comment by gpinkos** [comment]
Will the forthcoming open source version support Flux?
