### ISSUE TITLE
Hook up tokio metrics

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#7982]
# What
Hook up tokio runtime metrics into our metrics system.

# Why
Get insights into tokio internals.

# How
Use [`RuntimeMetrics`](https://docs.rs/tokio/1.28.2/tokio/runtime/struct.RuntimeMetrics.html) and hook that into our [`metric](https://github.com/influxdata/influxdb_iox/blob/af92463848001ed98acccca64eb02d751209261b/metric/src/lib.rs) module.

Note the following details:

- **multi-runtime:** We have at least two tokio runtimes in IOx -- the [main one](https://github.com/influxdata/influxdb_iox/blob/af92463848001ed98acccca64eb02d751209261b/influxdb_iox/src/main.rs#L419-L423) and the [DataFusion execution](https://github.com/influxdata/influxdb_iox/blob/af92463848001ed98acccca64eb02d751209261b/executor/src/lib.rs#L215-L227). The metrics should therefore be labeled with `runtime=main|executor`
- **all metrics:** All metrics exposed by [`RuntimeMetrics`](https://docs.rs/tokio/1.28.2/tokio/runtime/struct.RuntimeMetrics.html) should be mapped.
- **naming:** The names should be `tokio_<method>` where `<method>` stands for the method name used by [`RuntimeMetrics`](https://docs.rs/tokio/1.28.2/tokio/runtime/struct.RuntimeMetrics.html)
- **docs:** The docs from [`RuntimeMetrics`](https://docs.rs/tokio/1.28.2/tokio/runtime/struct.RuntimeMetrics.html) should be used. For this, mostly copy the first sentence and replace `Returns ` w/ `Tokio metric for `.
- **type:** Use "counter" or "gauge" depending on the right semantics.
- **multi-worker:** Some metrics are per-worker. These should get an additional `worker=x` label.

**Comment by domodwyer** [comment]
The necessary bits are already active if you want to try the tokio-console - it should be a case of port forwarding and pointing it at a IOx pod :+1:

**Comment by crepererum** [comment]
> The necessary bits are already active if you want to try the tokio-console - it should be a case of port forwarding and pointing it at a IOx pod +1

I know, but it might be nice to have this in our prod dashboards as well.

**Comment by domodwyer** [comment]
I agree!
