### ISSUE TITLE
Is anything/anyone using sqlite in a persistent manner?

### ISSUE THREAD

**Issue by carols10cents** [influxdata/influxdb_iox#8007]
I noticed in https://github.com/influxdata/influxdb_iox/pull/8001 that @savage-engineer hit the issue of sqlite not having `ALTER TABLE` that supports migrations we need to do, and I'm likely to run into that problem too with some of the deterministic partition hash ID work in the near future. For many changes to sqlite tables, you have to [copy data into a temporary table, delete the old table, recreate the new table in the way you want it to be different, then copy the data back over.](https://github.com/influxdata/influxdb_iox/pull/8001/files#diff-4842683eaaa8f345eda4d721a17faa1125abe4da4e1e54570f41020a8da2589fR6-R28)

What I'm wondering is, do we actually need to migrate data in sqlite? Or is everyone using sqlite in development scenarios only where deleting the database is acceptable and happens often anyway?

@alamb I believe you added the sqlite support, do you have thoughts?

Looking at that migration, it's not the worst thing in the world, but it does look error-prone and annoying to me, so while I think we have to write that SQL either way, I want to be clear about what sqlite catalogs guarantee and how much time we're spending testing migrations, etc.

**Comment by alamb** [comment]
> What I'm wondering is, do we actually need to migrate data in sqlite? Or is everyone using sqlite in development scenarios only where deleting the database is acceptable and happens often anyway?

As of today I do not think we need to sort out migrating sqlite data as there is no supported production use. (aka yes it is all for development / testing purposes0. 

I believe there are plans (cc @pauldix ) to create a version of our product where there are real users of sqlite (to be the file backed catalog) but that thing does not yet exist.
 
@stuartcarnie  added the support for sqlite so perhaps he has some thoughts.

**Comment by pauldix** [comment]
Yeah for now we don't need to do migrations. Its only purpose to exist right now is for testing

**Comment by carols10cents** [comment]
Ok, I don't think there's anything to do here then, I mostly just wanted this decision documented. The decision being "sqlite migrations are best-effort but don't spend much time on them as they should only be used in dev/test".
