### ISSUE TITLE
CLI to create databases or tables with partition templates

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#8038]
__Use case:__
In order to use custom partitioning (https://github.com/influxdata/idpe/issues/17266)  admins need to be able to set it and they often use `influxdb_iox` CLI rather than 

See internal slack: https://influxdata.slack.com/archives/C04QYLRFQE5/p1687366195005009

__Proposal:__

Add some way , via CLI, to specify the custom partitioning

Note @pauldix  says "customers use influxctl to create the DB"

__Current behaviour:__
So the gRPCs CreateNamespaceRequest [https://github.com/influxdata/influxdb_iox/blob/70ffedadc7380739dbc1a0ca64e4703464[…]enerated_types/protos/influxdata/iox/namespace/v1/service.proto](https://github.com/influxdata/influxdb_iox/blob/70ffedadc7380739dbc1a0ca64e47034643a7eb4/generated_types/protos/influxdata/iox/namespace/v1/service.proto#L32-L47) and CreateTableRequest  [https://github.com/influxdata/influxdb_iox/blob/70ffedadc7380739dbc1a0ca64e4703464[…]b4/generated_types/protos/influxdata/iox/table/v1/service.proto](https://github.com/influxdata/influxdb_iox/blob/70ffedadc7380739dbc1a0ca64e47034643a7eb4/generated_types/protos/influxdata/iox/table/v1/service.proto#L12-L25) optionally take a PartitionTemplate, defined here [https://github.com/influxdata/influxdb_iox/blob/70ffedadc7380739dbc1a0ca64e4703464[…]ypes/protos/influxdata/iox/partition_template/v1/template.proto](https://github.com/influxdata/influxdb_iox/blob/70ffedadc7380739dbc1a0ca64e47034643a7eb4/generated_types/protos/influxdata/iox/partition_template/v1/template.proto)

There are also some integration tests in the router that demonstrate both database/table creation, as well as their interaction, as well as checking the writes get partitioned correctly. These should be good examples https://github.com/influxdata/influxdb_iox/blob/70ffedadc7380739dbc1a0ca64e47034643a7eb4/router/tests/grpc.rs#L1035-L1235
[grpc.rs](https://github.com/influxdata/influxdb_iox/blob/70ffedadc7380739dbc1a0ca64e47034643a7eb4/router/tests/grpc.rs)
#[tokio::test]
async fn test_namespace_partition_template_explicit_table_creation_without_partition_template() {
    // Initialise a TestContext without a namespace autocreation policy.
    let ctx = TestContextBuilder::default().build().await;

Update: we will implement this in 2 tasks:

- [x] #8250
- [x] #8251
- [x] #8335

**Comment by dgnorton** [comment]
Is the intent to make this user facing functionality via `influxctl` (https://github.com/influxdata/influxctl)?

**Comment by barbaranelson** [comment]
Ideally, yes.  We don't want to have to be a go-between whenever a customer creates a database. We can live with being a go-between for now, but ultimately database creation, with or without custom partitioning, needs to be done by the customer.

**Comment by NGA-TRAN** [comment]
The create table CLI is needed as the part of feature User Defined Sort Orders https://github.com/influxdata/idpe/issues/17897 and we will implement it this week

**Comment by NGA-TRAN** [comment]
All tasks are done
