### ISSUE TITLE
Implement data lifecycle from MutableBuffer and/or ReadBuffer --> Parquet Files

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#808]
__Use case:__
IOx needs code to write data from the MutableBuffer and/or ReadBuffer to parquet files on object store. We need the basic plumbing of "write parquet chunks", "read parquet chunks", "list parquet chunks", etc

We currently have basic Create, Read, Write operations for chunks going between mutable buffer and read buffer. We need to extend the pattern for parquet files.

__Proposal:__

1. Implement relevant functions on `Db` (e.g. `load_chunk_to_object_store` and `list_object_store_chunks`)
2. Add tests (following pattern in db.rs) for scenarios such as
** Load data into the mutable buffer, write to parquet chunks
** Load data into read buffer, write to parquet chunks
etc

__Current behaviour:__

* Code that moves Chunks to mutable buffer from read buffer https://github.com/influxdata/influxdb_iox/blob/a316b16960b35c639353ee4f39f9925d433ca2a6/server/src/db.rs#L198. Possibly to model the code for sending data to parquet

Tests showing data movement from mutable buffer to read buffer:
https://github.com/influxdata/influxdb_iox/blob/a316b16960b35c639353ee4f39f9925d433ca2a6/server/src/db.rs#L446-L464

* Snapshot code that can write data to parquet files  https://github.com/influxdata/influxdb_iox/blob/a316b16960b35c639353ee4f39f9925d433ca2a6/server/src/snapshot.rs#L74

* The `ArrowWriter` struct in the parquet crate https://docs.rs/parquet/3.0.0/parquet/arrow/index.html can be used to write parquet files from record batches. It is used in the snapshot code.

**Comment by NGA-TRAN** [comment]
Since we have hooked writing Parquet FIles in the Life Cycle and seeing them in our daily test runs, I am going to close this. All remaining work will be kept track in the parent epic and all of its specific children.
