### ISSUE TITLE
Support string(UTF8) Field values in the read buffer

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#820]
__Use case:__
The influxdb data model allows storing fields that have string values. This is currently not supported by the read buffer

If you try and load data such as the following (note `field2=\"ss\"`)
```
 let data = "h2o,tag1=foo,tag2=bar field1=70.6,field3=2 100\n\
                   h2o,tag1=foo,tag2=bar field1=70.4,field2=\"ss\" 100\n\
                   h2o,tag1=foo,tag2=bar field1=70.5,field2=\"ss\" 100\n\
                   h2o,tag1=foo,tag2=bar field1=70.6,field4=true 1000";
```
into the read buffer, it will panic in the following way:
```
 thread 'query_tests::influxrpc::field_columns::test_field_name_plan' panicked
        // at 'not implemented: data type Utf8 currently not supported for field
        // columns', read_buffer/src/row_group.rs:1014:31 note: run with
        // `RUST_BACKTRACE=1` environment variable to display a backtrace
```
__Proposal:__
Implement support to load/store/query utf8 / string fields in the ReadBuffer

__Current behaviour:__
`panic!`

__Desired behaviour:__
sweet, sweet results

**Comment by e-dard** [comment]
I shall investigate and remind myself what's left to do here

**Comment by alamb** [comment]
This isn't blocking anything, just FYI -- I stumbled across it while porting tests from mutable buffer
