### ISSUE TITLE
InfluxQL: `count` aggregates return incorrect value when using `FILL(null)`

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/influxdb_iox#8232]
__Steps to reproduce:__

Using the `issue_6112` dataset in IOx, execute the following:

```sl
SELECT COUNT(usage_idle) FROM cpu WHERE time >= '2022-10-31T02:00:00Z' AND time < '2022-10-31T02:02:00Z' GROUP BY TIME(30s) FILL(null)
```

> **Note**
>
> The `FILL(null)` clause can be omitted, as it is the default behaviour.

__Expected behaviour:__

The gaps without data should return `0` to be consistent with InfluxQL:

```text
name: cpu
time                count
----                -----
1667181600000000000 6
1667181630000000000 0
1667181660000000000 0
1667181690000000000 0
```

> **Note**
>
> See ce6b354ded5a799ab554e5acc98f1e9e6a44a889 with updated test expectations

__Actual behaviour:__

Gaps are filled with `NULL`

```text
name: cpu
time                count
----                -----
1667181600000000000 6
1667181630000000000
1667181660000000000
1667181690000000000
```

### Influx OG

The specialisation of `COUNT` aggregates can be found in the `new<Data Type>FillIterator` implementations, such as for [`Float`](https://github.com/influxdata/influxdb/blob/e484c4d87193a475466c0285c018d16f168139e6/query/iterator.gen.go#L724-L729):

```go
if opt.Fill == influxql.NullFill {
	if expr, ok := expr.(*influxql.Call); ok && expr.Name == "count" {
		opt.Fill = influxql.NumberFill
		opt.FillValue = float64(0)
	}
}
```

**Comment by alamb** [comment]
COUNT also has special semantics in SQL as well (namely that it is never null, even if it has seen no values)

**Comment by stuartcarnie** [comment]
I wonder if we need to make it behave the same for SQL + gap filling?
