### ISSUE TITLE
Graceful Shutdown / Termination

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#827]
As far as I can tell IOx currently does not perform graceful termination. 

It currently blocks the main thread waiting on completion of the joined future of the gRPC and HTTP servers, but it never hooks up anything to trigger this shutdown. _On a somewhat related note, blocking on this joined future will prevent surfacing errors if only one crashes_

IOx should listen for OS signals, most likely using tokio::signal, and use this to trigger graceful shutdown of these servers. Ideally this shutdown procedure would also hook into any background tasks, and ensure they have run to completion before exiting - the TrackerRegistry could fairly easily be extended to provide this functionality.

**Comment by alamb** [comment]
I am guessing the IOx should respond to `SIGTERM` by starting a graceful shutdown (which makes sense to me). Any other signal handling you have in mind?

What do you think about also adding a management API to initiate the process as well?

**Comment by tustvold** [comment]
> I am guessing the IOx should respond to SIGTERM by starting a graceful shutdown (which makes sense to me). Any other signal handling you have in mind?

SIGTERM was all I was thinking of for now

> What do you think about also adding a management API to initiate the process as well?

I'm not really sure what the use-case for this would be?

**Comment by alamb** [comment]
>I'm not really sure what the use-case for this would be?

I was thinking conductor triggers a pre-emptive shutdown prior to moving nodes out of the cluster? I am also fine with adding such a command if/when we have an actual use for it

**Comment by tustvold** [comment]
> I was thinking conductor triggers a pre-emptive shutdown prior to moving nodes out of the cluster? I am also fine with adding such a command if/when we have an actual use for it

I'm not sure what the semantics for this would be, as the workload isn't in a position to acknowledge its own shutdown :sweat_smile: . I'd imagine conductor to go via the orchestration layer (kubernetes) for this sort of lifecycle management.

**Comment by domodwyer** [comment]
Yeah Conductor will move things away from the IOx instance and then have it killed through Kubernetes, which will SIGTERM it for us and follow it up with a SIGKILL if it doesn't stop fairly promptly (configurable) 👍
