### ISSUE TITLE
DataFusion Panic in InfluxQL planner when using  bitwise AND operator

### ISSUE THREAD

**Issue by wolffcm** [influxdata/influxdb_iox#8291]
This is a little tricky to reproduce so I am hesitant to file an upstream issue in DataFusion until we've done more investigation on our end.

I have an experimental branch that makes use of `SortPreservingRepartionExec` to do parallelized deduplication. Currently it's not possible to get physical plans that have `SortPreservingRepartionExec` nodes with bounded query contexts like IOx. So I had to make my experimental IOx branch pin to a local branch of DataFusion.

With this set up in place, some of the queries from the InfluxQL end-to-end test `issue_6112` will fail, e.g., this one:
https://github.com/influxdata/influxdb_iox/blob/732ae81f0b5496bb0e70e4463f57c350adfbe52a/influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql#L70

The panic looks like this:
```
thread 'IOx Query 2' panicked at 'internal error: entered unreachable code', /Users/cwolff/workspace/github.com/apache/arrow-datafusion/datafusion/physical-expr/src/intervals/cp_solver.rs:211:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:117:5
   3: datafusion_physical_expr::intervals::cp_solver::get_inverse_op
             at /Users/cwolff/workspace/github.com/apache/arrow-datafusion/datafusion/physical-expr/src/intervals/cp_solver.rs:211:14
   4: datafusion_physical_expr::intervals::cp_solver::propagate_arithmetic
             at /Users/cwolff/workspace/github.com/apache/arrow-datafusion/datafusion/physical-expr/src/intervals/cp_solver.rs:233:22
   5: <datafusion_physical_expr::expressions::binary::BinaryExpr as datafusion_physical_expr::physical_expr::PhysicalExpr>::propagate_constraints
             at /Users/cwolff/workspace/github.com/apache/arrow-datafusion/datafusion/physical-expr/src/expressions/binary.rs:794:13
   6: datafusion_physical_expr::intervals::cp_solver::ExprIntervalGraph::propagate_constraints
             at /Users/cwolff/workspace/github.com/apache/arrow-datafusion/datafusion/physical-expr/src/intervals/cp_solver.rs:505:40
   7: datafusion_physical_expr::intervals::cp_solver::ExprIntervalGraph::update_ranges
             at /Users/cwolff/workspace/github.com/apache/arrow-datafusion/datafusion/physical-expr/src/intervals/cp_solver.rs:531:26
   8: datafusion_physical_expr::physical_expr::analyze
             at /Users/cwolff/workspace/github.com/apache/arrow-datafusion/datafusion/physical-expr/src/physical_expr.rs:179:11
   9: <datafusion::physical_plan::filter::FilterExec as datafusion::physical_plan::ExecutionPlan>::statistics
             at /Users/cwolff/workspace/github.com/apache/arrow-datafusion/datafusion/core/src/physical_plan/filter.rs:210:34
  10: datafusion::physical_optimizer::repartition::optimize_partitions
             at /Users/cwolff/workspace/github.com/apache/arrow-datafusion/datafusion/core/src/physical_optimizer/repartition.rs:228:17
  11: datafusion::physical_optimizer::repartition::optimize_partitions::{{closure}}
             at /Users/cwolff/workspace/github.com/apache/arrow-datafusion/datafusion/core/src/physical_optimizer/repartition.rs:200:17
```

The culprit seems to be hitting the `unreachable!` arm of this `match`:
https://github.com/apache/arrow-datafusion/blob/5907c21f20448fe75b101ebd6a5d9746383386e1/datafusion/physical-expr/src/intervals/cp_solver.rs#L206-L213

My guess is that this code does some analysis related to repartitioning and filter predicates, and probably is not considering that an expression may contain a bitwise operator.

We'll need to address this somehow as part of [the improve deduplication epic](https://github.com/influxdata/influxdb_iox/issues/7706).

**Comment by alamb** [comment]
I believe this is due to  https://github.com/apache/arrow-datafusion/issues/7125

The fix should get into IOx as part of https://github.com/influxdata/influxdb_iox/pull/8355

**Comment by wolffcm** [comment]
> The fix should get into IOx as part of https://github.com/influxdata/influxdb_iox/pull/8355

Wonderful, I will try to reproduce and close it if it's fixed.

**Comment by alamb** [comment]
https://github.com/influxdata/influxdb_iox/pull/8355 is merged

**Comment by wolffcm** [comment]
Verified this as fixed upstream
