### ISSUE TITLE
Suboptimal parallel deduplication when unioning unsorted `RecordBatchesExec` with `ParquetExec`

### ISSUE THREAD

**Issue by wolffcm** [influxdata/influxdb_iox#8292]
For additional context see https://github.com/influxdata/influxdb_iox/pull/8293

When making experimental use of parallel deduplication, plans that need to union unsorted ingester data with presorted persisted parquet files produce a sub-optimal plan (from `influxdb_iox/tests/query_tests/cases/in/dedup_and_predicates_parquet_ingester.sql.expected`):

```diff
 -- SQL: EXPLAIN SELECT * FROM "table" ORDER BY tag;
 -- Results After Normalizing UUIDs
 ----------
 | plan_type    | plan    |
 ----------
 | logical_plan    | Sort: table.tag ASC NULLS LAST    |
 |    |   TableScan: table projection=[bar, foo, tag, time]    |
-| physical_plan    | SortExec: expr=[tag@2 ASC NULLS LAST]    |
-|    |   ProjectionExec: expr=[bar@1 as bar, foo@2 as foo, tag@3 as tag, time@4 as time]    |
-|    |     DeduplicateExec: [tag@3 ASC,time@4 ASC]    |
-|    |       SortPreservingMergeExec: [tag@3 ASC,time@4 ASC,__chunk_order@0 ASC]    |
-|    |         UnionExec    |
-|    |           SortExec: expr=[tag@3 ASC,time@4 ASC,__chunk_order@0 ASC]    |
-|    |             RecordBatchesExec: batches_groups=1 batches=1 total_rows=2    |
-|    |           ParquetExec: file_groups={1 group: [[1/1/1/00000000-0000-0000-0000-000000000000.parquet]]}, projection=[__chunk_order, bar, foo, tag, time], output_ordering=[tag@3 ASC, time@4 ASC, __chunk_order@0 ASC]    |
+| physical_plan    | SortPreservingMergeExec: [tag@2 ASC NULLS LAST]    |
+|    |   SortExec: expr=[tag@2 ASC NULLS LAST]    |
+|    |     ProjectionExec: expr=[bar@1 as bar, foo@2 as foo, tag@3 as tag, time@4 as time]    |
+|    |       DeduplicateExec: [tag@3 ASC,time@4 ASC]    |
+|    |         SortExec: expr=[tag@3 ASC,time@4 ASC,__chunk_order@0 ASC]    |
+|    |           CoalesceBatchesExec: target_batch_size=8192    |
+|    |             RepartitionExec: partitioning=Hash([tag@3, time@4], 4), input_partitions=4    |
+|    |               RepartitionExec: partitioning=RoundRobinBatch(4), input_partitions=2    |
+|    |                 UnionExec    |
+|    |                   RecordBatchesExec: batches_groups=1 batches=1 total_rows=2    |
+|    |                   ParquetExec: file_groups={1 group: [[1/1/1/00000000-0000-0000-0000-000000000000.parquet]]}, projection=[__chunk_order, bar, foo, tag, time], output_ordering=[tag@3 ASC, time@4 ASC, __chunk_order@0 ASC]    |
 |    |    |
```

We should understand why DF does not produce `SortPreservingRepartitionExec` nodes for this, instead of unioning and then sorting all of the data. It could be that the relevant planner rule is getting a pattern that it does not recognize.

**Comment by alamb** [comment]
I wonder if this could be related to the fact that the repartition is only added in "unbounded output" cases - https://github.com/apache/arrow-datafusion/pull/6921#discussion_r1261511368

**Comment by wolffcm** [comment]
> I wonder if this could be related to the fact that the repartition is only added in "unbounded output" cases

It's definitely not, I had DF pinned to a local branch that removes the unbounded requirement. Things are definitely working right if we only need to dedupe parquet files.

**Comment by wolffcm** [comment]
DataFusion does not optimize this case because it won't push a `SortExec` node beneath a `RepartitionExec` node, because it could result in less parallelism for the sort. #8423 adds an optimizer that will handle this case.
