### ISSUE TITLE
Ingester->Querier v2: Record batch serde

### ISSUE THREAD

**Issue by crepererum** [influxdata/influxdb_iox#8347]
Design+implement the serialization and deserialization of record batches for #8169.

Note that this split the handling of the schema and the handling of the payload data that should NOT repeat the schema. Schemas are sent ONCE for the whole table and every batch just is a projection of that.

This should not invent a new protocol, but should basically use Flight IPC.

This should be its own crate that can be shared.

**Comment by alamb** [comment]
Would this involve fixing https://github.com/apache/arrow-rs/issues/1206 ? Aka should the upstream team prioritize implementing that feature?

**Comment by crepererum** [comment]
I think the ingester has a single dict-batch pair for each chunk it tries to serialize, so we probably not going to reuse dictionaries at all. Since we are also not using plain flight but serialize a batch at a time (ref #8346), we're not going to run into the panic mentioned in the upstream ticket.
