### ISSUE TITLE
Internal error with string functions like 'upper' on tags - `The "upper" function can only accept strings.`

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#8356]
When running a query and trying to use string functions IOx generates an internal error, which is very poor UX

@sanderson  reported this a while ago, and there is an upstream ticket https://github.com/apache/arrow-datafusion/issues/5471 but I also wanted an IOx one to track our behavior

__Steps to reproduce:__
Run IOx locally:

```shell
influxdb_iox
```

Then in another terminal, load [metrics.lp](https://github.com/influxdata/influxdb_iox/blob/main/test_fixtures/lineproto/metrics.lp) (from example file in this repo):

```shell
$ influxdb_iox write my_namespace test_fixtures/lineproto/metrics.lp
227391 Bytes OK in 37.559148ms. 5.86 MB/sec
```

Then run this query `select upper(cpu) from cpu`:

```shell
influxdb_iox query my_namespace 'select upper(cpu) from cpu';
Error querying: Tonic(Status { code: Internal, message: "Error while planning query: Internal error: The \"upper\" function can only accept strings.. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker", metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Thu, 27 Jul 2023 17:44:34 GMT", "content-length": "0"} }, source: None })
```

__Expected behaviour:__
Should return results with the `cpu` column all upper cased

Here is what the data looks like without lower case:

```shell
(arrow_dev) alamb@MacBook-Pro-8:~/Software/influxdb_iox2$ influxdb_iox query my_namespace 'select cpu from cpu';
+-----------+
| cpu       |
+-----------+
| cpu-total |
| cpu-total |
| cpu-total |
| cpu-total |
| cpu-total |
...
```

There is a workaround to explicitly cast the column to varchar (via `::varchar`)

```shell
$ influxdb_iox query my_namespace 'select upper(cpu::varchar) from cpu';
+----------------+
| upper(cpu.cpu) |
+----------------+
| CPU-TOTAL      |
| CPU-TOTAL      |
| CPU-TOTAL      |
| CPU-TOTAL      |
| CPU-TOTAL      |
``

**Comment by appletreeisyellow** [comment]
A fix PR https://github.com/apache/arrow-datafusion/pull/7262
