### ISSUE TITLE
Switch to hashbrown instead of std::collections

### ISSUE THREAD

**Issue by carols10cents** [influxdata/influxdb_iox#836]
This will get us things like `raw_entry` without needing a nightly feature flag.

**Comment by jacobmarble** [comment]
@carols10cents I see mentions of both hashbrown and `std::collections::HashMap` in the code today. Anything left?

**Comment by carols10cents** [comment]
There may still be places that could benefit from being switched from `std::collections::HashMap` to `hashbrown`, but if they're important, I would expect them to show up in profiling. So yeah, I think we can close this for now.
