### ISSUE TITLE
Change query testing to use a data driven harness

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#843]
__Use case:__

User Story

As a developer working on the IOx query engine
* I want to run queries to known input scenarios and compare the results stored in files
* So that I am more productive:
** I don’t spend time waiting for compile/relink when adding / changing tests
** I can easily script update / diff comparison of test changes	

__Proposal:__
https://docs.google.com/document/d/1T_WoZfutTopzNAs5DA2F8npTVI_ZkvKmDAcHHqk3Z1E/edit#

**Comment by tustvold** [comment]
Is this still tracking anything?

**Comment by alamb** [comment]
I have part of `query_tests` implemented as a data driven harness, so this ticket could in theory be tracking the remaining conversion. Let's leave it open for a little bit longer (likely for sentimental reasons)

**Comment by jacobmarble** [comment]
@alamb is this still a valid issue? We have perf.py and @pauldix is working on a fancy data generator, etc.

**Comment by alamb** [comment]
I think we have enough of this in `query_tests` for now. Not tracking anything more worthwhile
