### ISSUE TITLE
Write script to fill the null values of `sort_key_ids` with corresponding values from `sort_key`

### ISSUE THREAD

**Issue by NGA-TRAN** [influxdata/influxdb_iox#8467]

**Comment by NGA-TRAN** [comment]
There were mismatches after the migration and here is the semi manual work to update all mismatches
https://github.com/influxdata/influxdb_iox/issues/8570

**Comment by crepererum** [comment]
Then we need to do this again. Manual work is not a fix for this.

**Comment by NGA-TRAN** [comment]
I am going to verify how data was migrated in all CST clusters https://github.com/influxdata/influxdb_iox/issues/8616

**Comment by NGA-TRAN** [comment]
@crepererum Summary of CST clusters:

Out of 16 CST clusters, only one cluster `InfluxData_PerformanceB` has mismatches. The other 15 cluster have their sort_key_ids filled well.
Looking more details into PerformanceB, all the mismatches had sort_key_ids NULL before 2023-08-24. After that both sort_key and sort_key_ids have the right values. This tells me the migration (aka filling sort_key_ids) seems not yet run on this CST cluster.

See this https://github.com/influxdata/influxdb_iox/issues/8616#issuecomment-1699602899 for more details

**Comment by NGA-TRAN** [comment]
The migration assertion https://github.com/influxdata/influxdb_iox/pull/8623 has been deployed successfully, I close this per discussion with Marco
