### ISSUE TITLE
don't break build if both VERISON_HASH and git repo are missing

### ISSUE THREAD

**Issue by memetb** [influxdata/influxdb_iox#8502]
When building on a custom CI, (or possibly locally in a test env), we may want to build the repo without any git hash information present (the most common reason is that we'd not be building directly from within a git repo). For reference, CI's like concourse-ci do not fetch the `.git` repo into the build directory.

I don't see a good motivation for outright breaking a build if no git hash is available.

The [`get_git_hash`](https://github.com/influxdata/influxdb_iox/blob/1cc0926a7f52c7138be991df6dd60d11c6549df6/influxdb_iox/build.rs#L15C6-L30) function can be made to fail gracefully with a warning and set a hash like `UNKNOWN-dirty` to the build instead of breaking it outright.

```rust
let out = match std::env::var("VERSION_HASH") {
        Ok(v) => v,
        Err(_) => {
            let output = Command::new("git")
                .args(["describe", "--always", "--dirty", "--abbrev=64"])
                .output()
                .expect("failed to execute git rev-parse to read the current git hash");

            String::from_utf8(output.stdout).expect("non-utf8 found in git hash")
        }
    };
```

The solution would be to replace `.expect()` with `.unrawp_or("UNKNOWN-dirty")`.

At present, we are simply running our builds with `VERSION_HASH=DIRTY cargo build` which seems to me an unnecessary complication.

**Comment by domodwyer** [comment]
> I don't see a good motivation for outright breaking a build if no git hash is available.

We did this so that if the hash wasn't specified, our builds would fail - this prevents us deploying images that we can't easily identify. Silent failures are destined to happen!

To build without requiring git, explicitly set `VERSION_HASH=unknown"`in the build env :+1:

**Comment by memetb** [comment]
Most likely, the error can be more human friendly then. 

> "failed to execute git rev-parse to read the current git hash"

can be replaced with

> "unknown git revision: please either specify a VERSION_HASH or build from within a git repo"

Although, I realize that this project is becoming increasingly hostile to outside developers, the desired effect my simply be to increase resistance.
