### ISSUE TITLE
Add ClickBench results

### ISSUE THREAD

**Issue by alexey-milovidov** [influxdata/influxdb_iox#8552]
__Use case:__

I've heard that InfluxDB could pretend to be an analytical database.

__Proposal:__

It makes sense to add it to ClickBench: https://github.com/ClickHouse/ClickBench/

__Current behaviour:__

It does not exist there.

__Desired behaviour:__

Let it be present in the benchmark.

__Alternatives considered:__

If you don't do it, maybe I will, and you will be found regretting*.

\* tongue-in-cheek.

**Comment by pauldix** [comment]
For the time being, we'll let the DataFusion project be the focus for ClickBench. IOx is currently a moving target and this would be a distraction for the moment.
