### ISSUE TITLE
feat: Connect ReadBuffer::column_values to gRPC storage column_values

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#857]
__Use case:__
The read buffer will (shortly) have a fast path for reading all distinct string values in a column (used for tag_values gRPC storage call).

__Proposal:__
Connect `server::db::Chunk::column_values`,
 (in server/src/db/chunk.rs) to the (to be written) new ReadBuffer API

__Current behaviour:__
At the moment `InfluxRPCPlaner::tag_values` ( introduced in https://github.com/influxdata/influxdb_iox/pull/859) runs a full on plan which scans values via `read_filter` rather than answering the queries via a metadata faster path. 

The code is here: https://github.com/influxdata/influxdb_iox/blob/fb4018355957f50c5cd54ab52a5269653e97802b/server/src/db/chunk.rs#L378

__Desired behaviour:__
`server::db::Chunk::column_values` for MutableBuffer chunks should call the ReadBuffer fast path

__Alternatives considered:__
Describe other solutions or features you considered.

**Comment by alamb** [comment]
@e-dard  is there a ticket that tracks the faster read buffer API?

**Comment by e-dard** [comment]
No but I can make one if it's helpful.

**Comment by e-dard** [comment]
https://github.com/influxdata/influxdb_iox/issues/868

**Comment by e-dard** [comment]
This is done I think right?

**Comment by alamb** [comment]
@e-dard  I think there is still work to do to make the server chunk call the read buffer `column_values`: https://github.com/influxdata/influxdb_iox/blob/94bd200e60a7dd950f9879890a5d32ae24362b02/server/src/db/chunk.rs#L413-L418
