### ISSUE TITLE
feat: Optimize the InfluxRPCPlanner for field_names

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#861]
__Use case:__
The `InfluxRPCPlanner::field_names`, introduced in https://github.com/influxdata/influxdb_iox/pull/819, currently runs fairly heavy weight plans to figure out what fields have data in them. The PR description has more background

However, with the exception of the `timestamp` field in the gRPC `MeasurementFieldsResponse ` response https://github.com/influxdata/influxdb_iox/blob/8cb8276819ba8d07ff6f4034f99a1ead7a228940/generated_types/storage_common.proto#L233-L237 this query could (very often) be answered only with metadata. THis metadata only approach is implemented in the `InfluxRPCPlanner::tag_keys` request

Thankfully,  @e-dard  has done some research / ferreting around and confirmed we do not need to return the timestamp associated with the field key results. 

> The reason why there is a Timestamp field is for influxql to deduplicate results across distributed nodes, which is not going to be something that we need to worry about

> You can just set that to 0.

__Proposal:__
Set  `MessageField::timestamp` to zero, and add special case metadata handling for the `MutableBuffer` and `ReadBuffer` for field_names. Ideally we could use the same implementation for `tag_keys`

__Current behaviour:__
A full plan is run to test for non null field values

__Desired behaviour:__
Only use metadata, rather than running a plan, if possible

__Alternatives considered:__
Describe other solutions or features you considered.

**Comment by jacobmarble** [comment]
@alamb is this still valid?

**Comment by alamb** [comment]
as of https://github.com/influxdata/influxdb_iox/blob/d2c214327790641d8a539c6439ffe7a50a53bd50/query/src/frontend/influxrpc.rs#L482-L530 the `tag_values` planner does use metadata for some of its plans, so I would say that this ticket is not tracking anything useful anymore
