### ISSUE TITLE
Automatically recover from an incomplete WAL write

### ISSUE THREAD

**Issue by domodwyer** [influxdata/influxdb_iox#8613]
The ingester batches up incoming writes, and writes them to the WAL in a big chunk, and then ACKs to the user.

Sometimes the ingester hard-crashes while it's in the middle of writing this big chunk to disk, and this leaves a partial chunk on disk. When the ingester starts up, it sees the chunk should have 42 entires, but the file ends before it sees all 42, because writing it was never finished.

The recovery playbook is to (effectively) replay the good bits in the WAL, and ignore the bad bit at the end. [This is fine] because those writes wouldn't have been ACK'd to the user anyway, because the writes to the WAL have to complete before we send an ACK, so the user isn't expecting that data to turn up anyway.

[This is fine]:https://img2.rtve.es/i/?w=1600&i=1614352808020.jpg

Doing this manually means it's slow (time to notice the problem, time to run the slow playbook, interrupting normal workl) and error prone (many WAL files, lots of confusingly similar IDs, lots of hosts, dodgy network connections) and risky (possible to replay writes for namespace X into Y, leaking data :fire:).

Instead we should automate this, and just replay the good bits and drop the bad bit at the end (specifically: only treat early EOF as an ignorable error). We should also raise an alert for investigation when this happens.

## Potential Data Loss

There's a caveat though (and the reason it's not automated today) - the WAL file is effectively a length-prefixed series of records, it looks like this (massively oversimplified):

```
       ┌───────┬─────────────────────────────────┬───────┬──────────
       │len: 42│     42 writes in one chunk      │len: 24│   ...
       └───────┴─────────────────────────────────┴───────┴──────────
```

The problem is that if the length field on disk becomes corrupt, it could end up like this:

```
       ┌───────────────┬─────────────────────────────────┬───────┬──────────
       │len: 4242424242│     42 writes in one chunk      │len: 24│   ...
       └───────────────┴─────────────────────────────────┴───────┴──────────
```

In this case, the WAL reader is going to look at the length field, and try to read loads of bytes thinking it is reading one bit chunk until it hits the end and returns an early EOF error. This looks like the first problem, but isn't.

**In this case, we lose previously ACK'd data**. The risk of this is low though - I don't think we've ever seen disk/file corruption, and most filesystems are fairly good at detecting it and raising it as a read error instead of returning back junk data.

My conjecture is this corruption is very unlikely, and the the benefits of automating this recovery vastly outweigh the risk.

## Best of Both

Realistically we need to change the on-disk WAL format to allow us to detect this sort of problem (fixed headers, incremental checksumming, forward-scanning on error to look for more records) but that's a much longer-term project that'll take much longer, and gain us protection from relatively rare problems that perhaps will never happen. Diminishing returns!

(we should change it anyway - for lots of reasons!)

**Comment by jacobmarble** [comment]
Sounds good to me.
