### ISSUE TITLE
How this project is 

### ISSUE THREAD

**Issue by tetofonta** [influxdata/influxdb_iox#8628]
__Use case:__
Why is this important (helps with prioritizing requests)?

__Proposal:__
Short summary of the feature.

__Current behaviour:__
Describe what currently happens.

__Desired behaviour:__
Describe what you want.

__Alternatives considered:__
Describe other solutions or features you considered.

**Comment by crepererum** [comment]
Please fill out the template when filing a feature request or bug report.

**Comment by tetofonta** [comment]
whoops, wrong button :|
