### ISSUE TITLE
Implement object storage wrapper library

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#87]
We need to support multiple object stores for the durability layer. At the very least:
* S3
* Google Cloud Storage (objects)
* Azure Blob Storage

And later we'll want to be able to support Minio and Ceph, but I assume those will be fine by just using the S3 API.

We'll need to support operations for `put`, `get`, `delete` and we'll need to be able to traverse the directory tree of object storage to see all the file listings given some prefix.

**Comment by alamb** [comment]
I would say this is basically implemented -- shall we close it @carols10cents ?

**Comment by carols10cents** [comment]
Yup! https://github.com/influxdata/influxdb_iox/blob/e9e92ece32bf1fc0b4c76aca622774bccb1bba17/object_store/src/lib.rs
