### ISSUE TITLE
Improved end-to-end testing

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#890]
The current end-to-end testing performed by `tests/end-to-end.rs` is not ideal.

In particular:

* The log output is quite hard to parse
* It isn't possible to run specific tests individually
* All tests are reported as a single success/failure

I'm not entirely sure what the best approach here is, and we probably want to wait until we have a more comprehensive set of such tests, but creating an issue to track.

There is unstable support for [custom test frameworks](https://doc.rust-lang.org/unstable-book/language-features/custom-test-frameworks.html), but it may be necessary to implement something truly custom - it's unclear to me at this stage.

**Comment by alamb** [comment]
Something I have been thinking about is breaking up end-to-end.rs into multiple `#[tokio::test]`s ` (and use a global fixture of some type to initialize / manage the server)

**Comment by alamb** [comment]
I plan to take a crack at this later this week
