### ISSUE TITLE
Improved CLI Output

### ISSUE THREAD

**Issue by tustvold** [influxdata/influxdb_iox#908]
In order to facilitate scripting of the CLI (and testing), it should be possible to request JSON-formatted output, enable/disable ANSI escape codes, etc... 

There should also be stability guarantees associated with the structure of this output. Depending on when JSON support lands in prost, it might be possible to build on this - see [here](https://github.com/danburkert/prost/issues/75).

Creating this issue largely as a placeholder that will need further fleshing out as part of an implementation effort.

**Comment by alamb** [comment]
There was some additional discussion here: https://github.com/influxdata/influxdb_iox/pull/939#discussion_r589411347

about the use of `println!` vs `eprintln!` and possibly not printing anything on success at all

**Comment by tustvold** [comment]
Much of the CLI is now making use of pbsjon to provide stable output
