### ISSUE TITLE
docker build fails on main branch

### ISSUE THREAD

**Issue by aelse** [influxdata/influxdb_iox#909]
__Steps to reproduce:__

1. Get fresh clone of repository
2. Run `docker build .` per the instructions in readme

__Expected behaviour:__

Docker image successfully built, docker exits with status code 0

__Actual behaviour:__

Docker exits with status code 1. I see the error output as pasted below.

__Environment info:__

* Please provide the command you used to build the project, including any `RUSTFLAGS`.

I ran `docker build .`

* System info: Run `uname -srm` or similar and copy the output here (we want to know your OS, architecture etc).

Darwin 18.7.0 x86_64

* If you're running IOx in a containerised environment then details about that would be helpful.

Docker/engine version 20.10.2

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__

Output from docker

```
Step 5/14 : RUN   --mount=type=cache,id=influxdb_iox_registry,sharing=locked,target=/usr/local/cargo/registry   --mount=type=cache,id=influxdb_iox_git,sharing=locked,target=/usr/local/cargo/git   --mount=type=cache,id=influxdb_iox_target,sharing=locked,target=/influxdb_iox/target   du -cshx /usr/local/cargo/registry /usr/local/cargo/git /influxdb_iox/target &&   cargo build --target-dir /influxdb_iox/target --release &&   cp /influxdb_iox/target/release/influxdb_iox /root/influxdb_iox &&   du -cshx /usr/local/cargo/registry /usr/local/cargo/git /influxdb_iox/target
 ---> Running in 93189d762263
du: cannot access '/usr/local/cargo/registry': No such file or directory
du: cannot access '/usr/local/cargo/git': No such file or directory
du: cannot access '/influxdb_iox/target': No such file or directory
0	total
The command '/bin/sh -c du -cshx /usr/local/cargo/registry /usr/local/cargo/git /influxdb_iox/target &&   cargo build --target-dir /influxdb_iox/target --release &&   cp /influxdb_iox/target/release/influxdb_iox /root/influxdb_iox &&   du -cshx /usr/local/cargo/registry /usr/local/cargo/git /influxdb_iox/target' returned a non-zero code: 1
```

**Comment by alamb** [comment]
FYI @jacobmarble

**Comment by jacobmarble** [comment]
@aelse I believe I reproduced your error by setting env var `DOCKER_BUILDKIT=0` before `docker build .`.

Please try `DOCKER_BUILDKIT=1 docker build .` and let me know what errors you get.

For context, my environment is "Darwin 20.3.0 x86_64" and Docker engine 20.10.2.

**Comment by aelse** [comment]
@jacobmarble `DOCKER_BUILDKIT=1 docker build .` works.
