### ISSUE TITLE
feat: API and CLI to add remote IOx servers to known remotes

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#917]
An IOx server should maintain a list of other IOx servers it is aware of. It should have the writer ID of the server and a connection string. This is part of the effort to deliver #916.

This should be added to the gRPC management API and exposed via the CLI for users to issue commands to add servers.

Add server - takes a writer ID and connection string with an optional flag to test the connection or not before adding it
Update - update the connection string for a given writer ID
Delete - delete the writer ID from the list of known hosts. This should perform a check across all database rules to determine if this writer ID shows up and fail if so with information about where the writer is still being used.

**Potential client commands**
```
# add a server with the given id and connect string to the list of servers the target knows about
./influxdb_iox server add 23 http://10.1.1.123:8080

# add a server with the given id and connect string to the list of servers the target knows about
# and attempt to make a connection to the server, returning an error if unable to connect. Timeout 
# is optional in seconds.
./influxdb_iox server add 42 http://10.1.1.89:8080 -verify -timeout=10

# show the list of servers that the target knows about
./influxdb_iox server list
[{id: 23, connection_string: "http://10.1.1.123:8080}]

# remove the server from the list of known servers. fails with error if that server is 
# referenced in any of the database rules. If error, it should at least return the names 
# of databases that have references.
./influxdb_iox server remove 42

# checks the server is able to connect to a specific server with response. timeout is
# optional in seconds.
./influxdb_iox server check 42 -timeout=2
{id: 42, response_code: 500, message: "blah blah"}

# checks the server is able to connect to all servers and returns responses
./influxdb_iox server check
[{id: 23, response_code: 200, message: "ok"}, {id:42, response_code: 408, message: "timeout"}]
```

`add` and `remove` could be changed to `create` and `delete`. The former felt a little bit more correct to me because we're not actually creating those servers, we're just adding references to them. But from a strictly HTTP CRUD perspective the latter would probably be a bit more "pure".

**Comment by alamb** [comment]
@pauldix  what is an example connection string? Is it like `http://myhost.example.com:8080` type thing? Is that the address of the management api on the remote server?

**Comment by pauldix** [comment]
@alamb yes, that's what I was thinking. Flight, gRPC Storage Legacy, and gRPC IOx all run on the same port, yes? The management API is actually going to expand to handle the replication, subscriptions, etc so maybe just gRPC IOx?

**Comment by alamb** [comment]
GRPC management API makes a lot of sense to me (using that API the other servers can always ask for any other information they need)

**Comment by mkmik** [comment]
```command
$ influxdb_iox server remote add 23 http://10.1.1.23:8080
$ influxdb_iox server remote add 24 http://10.1.1.24:8080
$ influxdb_iox server remote add 23 http://10.1.1.25:8080
remote 23 already exists
$ influxdb_iox server remote remove 23
$ influxdb_iox server remote add 23 http://10.1.1.25:8080
```

(I swear is just a case of convergent evolution with `git remote ...` :-) )

Or we can just have one command that sets and overwrites:

```command
$ influxdb_iox server remote set 23 http://10.1.1.23:8080
$ influxdb_iox server remote set 24 http://10.1.1.24:8080
$ influxdb_iox server remote set 23 http://10.1.1.25:8080
$ influxdb_iox server remote remove 23
```

wdyt?

**Comment by mkmik** [comment]
How does this relate to the existing concept of _host groups_:

```rust
pub type HostGroupId = String;

struct ConfigState {
  ...
  host_groups: BTreeMap<HostGroupId, Arc<HostGroup>>,
```

```rust
pub struct HostGroup {
    pub id: HostGroupId,
    /// `hosts` is a vector of connection strings for remote hosts.
    pub hosts: Vec<String>,
}
```

**Comment by mkmik** [comment]
> How does this relate to the existing concept of _host groups_:

ok, these are gone now (#935)
