### ISSUE TITLE
add routing rules to database rules

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#918]
This is part of the effort to deliver #916. Database rules should have rules for routing write and read requests. This gives users the ability to horizontally distribute their write workloads. For queries, they can proxy to other query servers, which may have data locality, or just to process the query elsewhere.

When routing writes, the line protocol should still be parsed and separated out into the different batch requests that will go out.

Each database has its own routing rules (i.e. a routing rule belongs to a database).

There are two different kinds of routing rules. The first is for a specific match:
* table name (optional)
* predicate (optional)
* target IOx node (writer ID)

There can be any number of specific match routing rules. They are in a list and their order matters as they are evaluated in order. Specific match routing rules aren't required.

A default routing rule will take a hash of:
* table name
* list of column values (what columns to include)

And then match that hash against a location in a collection of IOx writers.

These rules should be organized in an outer struct called route, which should have a name. A database can have multiple routes. If so, the data will be copied to each matching route (i.e. replicated). Maybe this should have a different name?

Read based routing rules should be separate and have the same options.

**Comment by mkmik** [comment]
Done in  #972
