### ISSUE TITLE
feat: implement routing writes to remote IOx server

### ISSUE THREAD

**Issue by pauldix** [influxdata/influxdb_iox#920]
This is part of delivering #916. With routing rules in place, the server should now route writes to the routes specified for a given database. A client writing data should not receive a response until these route requests complete. If one of them errors, the client should receive the error from the failed route request.

Note that this could split the incoming write into multiple requests (one per shard), but it could also create a copy of the data and split it in another way.

**Comment by mkmik** [comment]
an optional fire&forget mode is welcome

**Comment by carols10cents** [comment]
Blocked on @pauldix putting up a PR for data structures

**Comment by pauldix** [comment]
On the Write Buffer side of things, #1157 will need to be implemented before it can actually receive the write.
