### ISSUE TITLE
feat: admin_query interface

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#946]
__Use case:__
As IOx moves to production, it will be important to have various administrative reporting  via API. For example, view lists of what chunks are available, their stats, how large they are, etc.

The primary interface for this data will likely be the management API defined via gRPC.

However, It would also be nice to have the following
1. get the data back in various formats (e.g. csv), as
2. Support filtering such as restricting to chunks with a certain property
3. Grouping / summarization (e.g. sumarize how much memory is currently used by a table across chunks)

Other databases (e.g. postgres) provide access to their administrative functions via SQL but we are concerned about going all in on SQL for IOx for reasons which include:
* How we would document these APIs,
* How would people discover them
* how we would avoid breaking them
* How would we implement streaming - i.e. notify me of any changes to this database

Which all have good answers in the gRPC management API

We also would like to see the management APIs to be "complete" - i.e. conductor or something similar shouldn't need to run a mix of gRPC and SQL to do its job.

We see no issue with SQL being an additional window into that information, but there is some concerned about it being the only one?

__Proposal:__
We propose to add a special `admin_query` interface in addition to the query interface added in https://github.com/influxdata/influxdb_iox/pull/943. The admin_query would be able to run normal data queries as normal, but would also have access to special "virtual system" tables.

These tables would be "virtual" in that would provide a view on to the underlying IOx system objects (e.g. chunks, WAL, etc).

Like the query interface, the admin_query interface would within the context of a single database so any cross database commands (e.g. creation of database, setting writer ids, etc) would contninue to have its own specific management API

Thus, so rather than an api such as thisL

```
# Now the chunk is loaded into the read buffer
./influxdb_iox chunks list mydatabase “20201-03-2”
[
  {partition_key: "20201-03-2", location: “mutable_buffer”, id: 2, open: true},
  {partition_key: "20201-03-2", location: “mutable_buffer”, id: 1, open: false},
  {partition_key: "20201-03-2", location: “read_buffer”, id: 1, open: false},
  {partition_key: "20201-03-2", location: “read_buffer”, id: 0, open: false}
]
```

we would have something like

```
./influxdb_iox database admin_query mydatabase "select * from chunks"
+---------------+----------+----------+-------+
| partition_key | chunk_id | location |  open |
+---------------+----------+----------+-------+
|  20201-03-2   |   2      |   mb     | true  |
|  20201-03-2   |   1      |   mb     | false |
|  20201-03-2   |   1      |   rb     | false |
|  20201-03-2   |   0      |   rb     | false |
+---------------+----------+----------+-------+
```

And filter by chunk_id for example

```
./influxdb_iox database admin_query mydatabase "select * from chunks where chunk_id = 1"
+---------------+----------+----------+-------+
| partition_key | chunk_id | location |  open |
+---------------+----------+----------+-------+
|  20201-03-2   |   1      |   mb     | false |
|  20201-03-2   |   1      |   rb     | false |
+---------------+----------+----------+-------+
```

__Implementation details__
* Datafusion already allows us to register table providers so we would simply implement one

__Alternatives considered:__
The alternate is to only have specific management APIs  and corresponding CLIs for each function needed.

Upsides:
* We would have clearly documented (via protobuf) / structured responses;

Downsides:
* Adding any new interface would require adding code in both the management api (protobuf definition and implementation) as well as a CLI
* Adding filtering or summarization features will require query patterns to be hard coded in an ad hoc manner in to the apis
** Any additional output format (e.g. csv) would need additional work

**Comment by NGA-TRAN** [comment]
I like this SQL proposal because it provide flexibility in getting different report summary easily. I guess you will define specific needs such as measurement of memory and  CPU, size of Mutable Buffer vs Read Buffer, actual size of uncompressed  vs compressed ones, etc... in different issue tickets. 

Regarding providing other APIs, I think we may want to see what our monitoring UI tools and Cloud 2 need first. Then whether those APIs are a must for those needs or the output of SQL can be directed to them by some channel/mechanism.
