### ISSUE TITLE
chore: Add test for unsigned types to query tests

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#950]
__Use case:__
We added support for unsigned line protocol parsing in https://github.com/influxdata/influxdb_iox/pull/906 along with support in the mutable buffer

We should add some end to end query tests (that include moving such unsigned datatypes into the read buffer and querying them via SQL) 

__Proposal:__
Add a test in `server/src/query_tests/...` that loads line protocol data with unsigned data and then queries it. The scenarios should cover mutable buffer and read buffer

**Comment by e-dard** [comment]
FYI the read buffer already supports unsigned so whoever takes this please let me know if something fails on the e2e tests and it's in the read buffer.

**Comment by NGA-TRAN** [comment]
I will work on this next Monday and will let you know @e-dard
