### ISSUE TITLE
Add Basic CLI commands to manage chunks 

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#979]
__Use case:__
There needs to be some way to do basic chunk manipulation on 

__Proposal:__
Keep the pattern of `“<type of object> <action> <arguments>”` for the CLI resulting with the following commands:

```
# puts open chunk into closing state, creates new chunk
./influxdb_iox database partition new-chunk <db_name> <partition_key>

# puts chunk into closed state and starts migration to REB / object store
./influxdb_iox database partition close-chunk <db_name> <partition_key> <chunk_id> 

# drop chunk from MB. Don't need to do this after close since it'll do 
# that when it completes. This is for completeness to just drop it out
./influxdb_iox database partition drop-mb-chunk <db_name> <partition_key> <chunk_id> 

# drop chunk from RB
./influxdb_iox database partition drop-rb-chunk <db_name> <partition_key> <chunk_id> 
```

@tustvold  mentions that `-` is the the default for clap 

__Current behaviour:__
No way to access this functionality

__Desired behaviour:__
Describe what you want.

__Alternatives considered:__
Describe other solutions or features you considered.

**Comment by alamb** [comment]
I think with the completion of #1002, close-chunk (which moves a chunk to read buffer and drops from the mutable buffer) CLI / API I am rethinking the wisdom of adding drop-chunk it seems like giving the user such a command is just giving  the user a :foot: :gun:

The only thing drop-chunk could do now is to (effectively) lose data - https://github.com/influxdata/influxdb_iox/issues/979

Thus I am thinking I may close this ticket once #1002 is closed.

**Comment by NGA-TRAN** [comment]
># drop chunk from MB. Don't need to do this after close since it'll do 
># that when it completes. This is for completeness to just drop it out
>./influxdb_iox database partition drop-mb-chunk <db_name> <partition_key> <chunk_id> 

I do not think we need this. Instead, users should run other command to see which chunks available and know those chunks are dropped

**Comment by NGA-TRAN** [comment]
> # drop chunk from RB
> ./influxdb_iox database partition drop-rb-chunk <db_name> <partition_key> <chunk_id> 

Why we need this command? In case of bugs?

**Comment by alamb** [comment]
Thanks @NGA-TRAN  -- I agree. I don't know why I thought we needed these commands (I think I was trying to simply expose the low level calls on `Db` which is not a good idea in retrospect). 

Ok, so with that I am claiming this ticket is done so closing it down. ✅
