### ISSUE TITLE
support scientific notation in line protocol parser

### ISSUE THREAD

**Issue by jacobmarble** [influxdata/influxdb_iox#997]
__Steps to reproduce:__
1. write a line of LP such as `myMeasurement fieldKey=-1.234456e+06 1615869152385000000`
2. watch logs fail with something like this:
```
 Mar 16 04:32:32.289 ERROR influxdb_iox::influxdb_ioxd::http: Error while handling request error=ParsingLineProtocol { source: CannotParseEntireLine { trailing_content: "e+06 1615869152385000000" } } error_message="Error parsing line protocol: Could not parse entire line. Found trailing content: \'e+06 1615869152385000000\'"
```

__Expected behaviour:__
Field value with scientific notation treated as float.
See https://docs.influxdata.com/influxdb/v2.0/reference/syntax/line-protocol/#float

__Actual behaviour:__
Write rejected.

__Environment info:__
Docker image jacobmarble/influxdb_iox:2021-03-16, hosted on a Mac

**Comment by NGA-TRAN** [comment]
@jacobmarble Unless someone wants to work on this, I will do it after adding some e2e tests for mutable and read buffers

**Comment by NGA-TRAN** [comment]
Yes, reproduce it. Put down step to reproduce it in CLI:

```
cargo build
cargo run -- server
```

Go to different terminal
```
cd /Users/nga/git/influxdb_iox
./target/debug/influxdb_iox writer set 42
./target/debug/influxdb_iox database create my_db -m 100
./target/debug/influxdb_iox database write my_db /Users/nga/git/ngaPlaying/commands/IOx/997.lp
```
The 997.lp inlucdes only one line of "myMeasurement fieldKey=-1.234456e+06 1615869152385000000"
I got the following error message:
"Error writing: Unexpected server error: Client specified an invalid argument: Violation for field "lp_data": Invalid Line Protocol: Could not parse entire line. Found trailing content: 'e+06 1615869152385000000'"

**Comment by NGA-TRAN** [comment]
I know where this happens but need to consult Jake and Carol for the solution.

Currently, the value -1.234456e+06 1615869152385000000 is mapped to the right float F64 data of FieldSet  type inside influxdb_line_protocol::src::lib.rs::parse_line. However, the __map__ function did not move string data after map. I will create a PR to ask question to Jake and Carol
